"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { useAuth } from "@/app/components/AuthProvider";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";
type PortalSession = { enrollmentId: string; sessionId: string; state: string; acknowledged: boolean; environmentReady: boolean; released: boolean; entryUrl: string; package: null | { generatedAt: string; ready: boolean; requirements: string[]; privacy: string[]; blockers: string[]; receiptChecksum: string }; certification: null | { ready: boolean; checks: Array<{ key: string; passed: boolean; detail: string }>; blockers: string[]; receiptChecksum: string; observedAt: string } };
const button = "rounded-lg border border-white/20 bg-white px-3 py-2 font-black text-black";
export default function TimelineDawBetaTesterPortal() {
  const { user, loading } = useAuth(), [sessions, setSessions] = useState<PortalSession[]>([]), [error, setError] = useState("");
  const load = useCallback(async () => { const token = (await requireProjectSupabase().auth.getSession()).data.session?.access_token ?? "", response = await fetch("/api/timeline/daw-beta-tester-portal", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }), result = await response.json(); if (!response.ok) throw Error(result.error); setSessions(result.sessions); }, []);
  useEffect(() => { if (user) queueMicrotask(() => void load().catch(cause => setError(cause.message))); }, [user, load]);
  if (loading) return <main className="p-8 text-white">Checking membership…</main>;
  if (!user) return <main className="p-8 text-white"><h1 className="text-3xl font-black">Musician Beta Portal</h1><Link className={`${button} mt-4 inline-block`} href="/members">Members Sign In</Link></main>;
  return <main className="mx-auto max-w-4xl space-y-5 p-6 text-white"><p className="text-xs font-black uppercase tracking-[.22em] text-sky-200">Private musician portal</p><h1 className="text-4xl font-black">My DAW Beta Sessions</h1><p className="text-white/60">Only your enrollments, readiness, owner instructions, and permitted entry links appear here. Other testers and owner-only evidence are never returned.</p>{sessions.map(session => <section className="rounded-2xl border border-white/15 p-5" key={session.enrollmentId}><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black">Session {session.sessionId}</h2><p>{session.state} · acknowledgement {session.acknowledged ? "saved" : "needed"} · environment {session.environmentReady ? "ready" : "held"} · release {session.released ? "passed" : "held"}</p></div>{session.state === "active" && session.released ? <Link className={button} href={session.entryUrl}>Open permitted session</Link> : <span className="rounded-lg border border-amber-300/30 px-3 py-2 text-amber-200">Entry locked</span>}</div>{session.package ? <div className="mt-4 rounded-xl border border-sky-300/20 p-3"><b>Owner handoff · {session.package.ready ? "ready" : "held"}</b><h3 className="mt-2 font-black">Before testing</h3>{session.package.requirements.map(item => <p key={item}>• {item}</p>)}<h3 className="mt-2 font-black">Privacy boundary</h3>{session.package.privacy.map(item => <p key={item}>• {item}</p>)}{session.package.blockers.map(item => <p className="text-amber-200" key={item}>Hold · {item}</p>)}</div> : <p className="mt-3 text-amber-200">The owner has not generated your handoff package yet.</p>}{session.certification ? <div className="mt-3 border-t border-white/10 pt-3"><b className={session.certification.ready ? "text-emerald-200" : "text-amber-200"}>{session.certification.ready ? "Externally beta certified" : "Certification held"}</b>{session.certification.checks.map(check => <p key={check.key} className={check.passed ? "text-emerald-200" : "text-amber-200"}>{check.passed ? "PASS" : "HOLD"} · {check.detail}</p>)}<p className="mt-2 break-all font-mono text-xs text-white/45">{session.certification.receiptChecksum}</p></div> : null}</section>)}{!sessions.length && !error ? <p>No beta invitations have been redeemed by this account.</p> : null}{error ? <p role="alert" className="text-red-200">{error}</p> : null}</main>;
}
