import type {
  MultiTrackKeeperBankAsset,
  MultiTrackKeeperBankCollection,
  MultiTrackKeeperBankWorkspaceState,
} from "./MultiTrackKeeperBankEngineTypes";

export const multiTrackKeeperBankAssetsSeed: MultiTrackKeeperBankAsset[] = [
  {
    id: "keeper-bank-asset-main-hook-a",
    title: "Main Hook Keeper A",
    lane: "hook-bank",
    assetKind: "hook",
    sourceCandidateId: "survivor-candidate-main-hook-a",
    sourceVersionIds: ["suno-version-01", "suno-version-04", "suno-version-07"],
    sectionLabel: "Hook",
    startBar: 17,
    endBar: 25,
    emotionalScore: 96,
    reuseScore: 94,
    arrangementScore: 91,
    confidence: 92,
    decision: "accept",
    readiness: "ready",
    qualityFlags: ["emotionally-strong", "repeatable", "arrangement-ready"],
    evidence: [
      {
        id: "keeper-evidence-main-hook-survivor",
        label: "Promoted survivor",
        detail: "This hook was promoted from the survivor engine as the strongest hook candidate.",
        sourceKind: "survivor-promotion",
        strength: 96,
        confidence: 92,
      },
      {
        id: "keeper-evidence-main-hook-repeat",
        label: "Repeatable hook",
        detail: "The hook can be reused as the emotional center of the arrangement.",
        sourceKind: "phrase-match",
        strength: 94,
        confidence: 91,
      },
    ],
    notes: [
      "Store as the main hook keeper.",
      "Later wiring can send this into arrangement candidates.",
    ],
  },
  {
    id: "keeper-bank-asset-verse-riff-b",
    title: "Verse Riff Keeper B",
    lane: "riff-bank",
    assetKind: "verse-riff",
    sourceCandidateId: "survivor-candidate-verse-riff-b",
    sourceVersionIds: ["suno-version-02", "suno-version-05"],
    sectionLabel: "Verse",
    startBar: 5,
    endBar: 13,
    emotionalScore: 78,
    reuseScore: 82,
    arrangementScore: 76,
    confidence: 74,
    decision: "review",
    readiness: "needs-review",
    qualityFlags: ["needs-ear-check", "possible-duplicate"],
    evidence: [
      {
        id: "keeper-evidence-verse-riff-color",
        label: "Useful riff color",
        detail: "The riff has a stable color but needs a human ear check before acceptance.",
        sourceKind: "riff-color",
        strength: 82,
        confidence: 74,
      },
    ],
    notes: [
      "Keep in pending bank.",
      "Do not accept until listening confirms it does not fight the main hook.",
    ],
  },
  {
    id: "keeper-bank-asset-bridge-lift-c",
    title: "Bridge Lift Keeper C",
    lane: "bridge-bank",
    assetKind: "bridge-lift",
    sourceCandidateId: "survivor-candidate-bridge-lift-c",
    sourceVersionIds: ["suno-version-03", "suno-version-08", "suno-version-10"],
    sectionLabel: "Bridge",
    startBar: 33,
    endBar: 41,
    emotionalScore: 86,
    reuseScore: 79,
    arrangementScore: 88,
    confidence: 83,
    decision: "hold",
    readiness: "needs-review",
    qualityFlags: ["arrangement-ready", "needs-trim"],
    evidence: [
      {
        id: "keeper-evidence-bridge-arrangement",
        label: "Arrangement lift",
        detail: "The bridge lift may help ramp energy into the final hook.",
        sourceKind: "idea-cluster",
        strength: 88,
        confidence: 83,
      },
    ],
    notes: [
      "Hold for arrangement testing.",
      "Could become a bridge, pre-hook, or final chorus lift.",
    ],
  },
];

export const multiTrackKeeperBankCollectionsSeed: MultiTrackKeeperBankCollection[] = [
  {
    id: "keeper-bank-collection-hooks",
    title: "Hook Keeper Bank",
    description: "Accepted and pending hook ideas that can become the emotional center of a song.",
    lane: "hook-bank",
    acceptedAssetIds: ["keeper-bank-asset-main-hook-a"],
    pendingAssetIds: [],
    rejectedAssetIds: [],
    readiness: "ready",
  },
  {
    id: "keeper-bank-collection-riffs",
    title: "Riff Keeper Bank",
    description: "Verse riffs, instrumental responses, and repeatable musical shapes.",
    lane: "riff-bank",
    acceptedAssetIds: [],
    pendingAssetIds: ["keeper-bank-asset-verse-riff-b"],
    rejectedAssetIds: [],
    readiness: "needs-review",
  },
  {
    id: "keeper-bank-collection-bridges",
    title: "Bridge Keeper Bank",
    description: "Bridge lifts and transition ideas that may help build arrangement energy.",
    lane: "bridge-bank",
    acceptedAssetIds: [],
    pendingAssetIds: ["keeper-bank-asset-bridge-lift-c"],
    rejectedAssetIds: [],
    readiness: "needs-review",
  },
];

export const multiTrackKeeperBankWorkspaceSeed: MultiTrackKeeperBankWorkspaceState = {
  engineId: "multi-track-keeper-bank-engine",
  engineTitle: "Multi-Track Keeper Bank Engine",
  enginePurpose:
    "Store promoted survivor ideas into organized keeper banks so hooks, riffs, grooves, bridge lifts, and arrangement moments can be reused later.",
  readiness: "ready",
  assets: multiTrackKeeperBankAssetsSeed,
  collections: multiTrackKeeperBankCollectionsSeed,
  nextActions: [
    "Keep this engine preserved only.",
    "Do not wire into the page yet.",
    "Later connect accepted survivor promotion outputs.",
    "Later send accepted keepers into arrangement candidate building.",
  ],
};