
import type {
  MultiTrackArrangementBlueprintStep,
  MultiTrackArrangementLane,
  MultiTrackArrangementRenderPrepItem,
  MultiTrackArrangementSection,
  MultiTrackArrangementWorkspaceState,
} from "./MultiTrackArrangementEngineTypes";

export const multiTrackArrangementEngineSections: MultiTrackArrangementSection[] = [
  {
    id: "arrangement-section-intro-original",
    title: "Original idea intro setup",
    sourceId: "keeper-extraction-v03-main-hook",
    sourceKind: "keeper-extraction",
    sectionKind: "intro",
    readinessStatus: "ready",
    priority: "high",
    startBar: 1,
    endBar: 8,
    targetOrder: 1,
    repeatCount: 1,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 62,
    hookScore: 78,
    transitionScore: 84,
    arrangementScore: 82,
    actions: ["place", "trim", "review"],
    risks: ["needs-human-review", "seed-placeholder"],
    detail:
      "Seed-safe intro using the keeper hook as a recognizable setup before the main section lands.",
    notes: [
      "Good opening anchor.",
      "Later this can reference real extracted audio.",
    ],
  },
  {
    id: "arrangement-section-verse-pocket",
    title: "Verse groove pocket",
    sourceId: "keeper-extraction-v03-riff-repeat",
    sourceKind: "keeper-extraction",
    sectionKind: "verse",
    readinessStatus: "ready",
    priority: "high",
    startBar: 9,
    endBar: 24,
    targetOrder: 2,
    repeatCount: 2,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 74,
    hookScore: 72,
    transitionScore: 80,
    arrangementScore: 84,
    actions: ["place", "loop", "duplicate"],
    risks: ["rough-transition", "seed-placeholder"],
    detail:
      "Loopable riff pocket that can support the verse before the stronger hook section arrives.",
    notes: [
      "Good duplicate-lane candidate.",
      "Needs real timing confirmation later.",
    ],
  },
  {
    id: "arrangement-section-main-hook",
    title: "Main hook keeper chorus",
    sourceId: "keeper-promotion-v03-main-hook",
    sourceKind: "keeper-promotion",
    sectionKind: "chorus",
    readinessStatus: "ready",
    priority: "critical",
    startBar: 25,
    endBar: 40,
    targetOrder: 3,
    repeatCount: 2,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 94,
    hookScore: 97,
    transitionScore: 88,
    arrangementScore: 96,
    actions: ["place", "duplicate", "prepare-render"],
    risks: ["seed-placeholder"],
    detail:
      "Primary keeper hook section. This is the strongest arrangement anchor and should lead the blueprint.",
    notes: [
      "Main keeper section.",
      "Best render-prep candidate in this isolated layer.",
    ],
  },
  {
    id: "arrangement-section-bridge-mutation",
    title: "Bridge mutation lift",
    sourceId: "keeper-promotion-v07-bridge-review",
    sourceKind: "keeper-promotion",
    sectionKind: "bridge",
    readinessStatus: "needs-review",
    priority: "medium",
    startBar: 41,
    endBar: 56,
    targetOrder: 4,
    repeatCount: 1,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 81,
    hookScore: 68,
    transitionScore: 76,
    arrangementScore: 78,
    actions: ["review", "place", "swap"],
    risks: ["needs-human-review", "rough-transition", "seed-placeholder"],
    detail:
      "Useful bridge mutation that can lift the arrangement, but it needs human review before final placement.",
    notes: [
      "Do not auto-lock this section.",
      "Good bridge option.",
    ],
  },
  {
    id: "arrangement-section-final-hook-repeat",
    title: "Final hook repeat",
    sourceId: "keeper-promotion-v03-main-hook",
    sourceKind: "keeper-promotion",
    sectionKind: "hook",
    readinessStatus: "ready",
    priority: "critical",
    startBar: 57,
    endBar: 72,
    targetOrder: 5,
    repeatCount: 2,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 96,
    hookScore: 98,
    transitionScore: 86,
    arrangementScore: 95,
    actions: ["duplicate", "place", "prepare-render"],
    risks: ["seed-placeholder"],
    detail:
      "Final repeat of the strongest hook for the future keeper arrangement blueprint.",
    notes: [
      "Strong closing keeper.",
      "Future render queue candidate.",
    ],
  },
  {
    id: "arrangement-section-outro-release",
    title: "Outro release",
    sourceId: "keeper-extraction-v10-polish-chorus",
    sourceKind: "keeper-extraction",
    sectionKind: "outro",
    readinessStatus: "future",
    priority: "low",
    startBar: 73,
    endBar: 80,
    targetOrder: 6,
    repeatCount: 1,
    bpm: 120,
    keyLabel: "C#m",
    energyScore: 58,
    hookScore: 52,
    transitionScore: 70,
    arrangementScore: 64,
    actions: ["review", "prepare-render"],
    risks: ["missing-audio", "seed-placeholder"],
    detail:
      "Future outro reference from the polished render pass. Useful later, not required now.",
    notes: [
      "Future-only outro.",
      "No render queue import.",
    ],
  },
];

export const multiTrackArrangementEngineLanes: MultiTrackArrangementLane[] = [
  {
    id: "arrangement-lane-intro",
    title: "Intro Lane",
    sectionKind: "intro",
    readinessStatus: "ready",
    sectionIds: ["arrangement-section-intro-original"],
    description: "Opening setup sections that introduce the keeper idea.",
  },
  {
    id: "arrangement-lane-verse",
    title: "Verse Lane",
    sectionKind: "verse",
    readinessStatus: "ready",
    sectionIds: ["arrangement-section-verse-pocket"],
    description: "Groove and pocket sections for verse structure.",
  },
  {
    id: "arrangement-lane-hook",
    title: "Hook Lane",
    sectionKind: "hook",
    readinessStatus: "ready",
    sectionIds: ["arrangement-section-main-hook", "arrangement-section-final-hook-repeat"],
    description: "Strong keeper hook placements and duplicate hook sections.",
  },
  {
    id: "arrangement-lane-bridge",
    title: "Bridge Lane",
    sectionKind: "bridge",
    readinessStatus: "needs-review",
    sectionIds: ["arrangement-section-bridge-mutation"],
    description: "Mutation sections that may become the bridge or lift.",
  },
  {
    id: "arrangement-lane-outro",
    title: "Outro Lane",
    sectionKind: "outro",
    readinessStatus: "future",
    sectionIds: ["arrangement-section-outro-release"],
    description: "Future ending and release sections.",
  },
];

export const multiTrackArrangementEngineBlueprintSteps: MultiTrackArrangementBlueprintStep[] = [
  {
    id: "arrangement-blueprint-step-intro",
    sectionId: "arrangement-section-intro-original",
    order: 1,
    label: "Place intro setup",
    action: "place",
    readinessStatus: "ready",
    detail: "Open with a recognizable piece of the keeper idea.",
  },
  {
    id: "arrangement-blueprint-step-verse",
    sectionId: "arrangement-section-verse-pocket",
    order: 2,
    label: "Build verse pocket",
    action: "loop",
    readinessStatus: "ready",
    detail: "Use the riff pocket as a repeatable verse groove.",
  },
  {
    id: "arrangement-blueprint-step-main-hook",
    sectionId: "arrangement-section-main-hook",
    order: 3,
    label: "Drop main keeper hook",
    action: "place",
    readinessStatus: "ready",
    detail: "Place the strongest keeper as the main chorus/hook section.",
  },
  {
    id: "arrangement-blueprint-step-bridge",
    sectionId: "arrangement-section-bridge-mutation",
    order: 4,
    label: "Review bridge mutation",
    action: "review",
    readinessStatus: "needs-review",
    detail: "Human review before locking the bridge mutation into the arrangement.",
  },
  {
    id: "arrangement-blueprint-step-final-hook",
    sectionId: "arrangement-section-final-hook-repeat",
    order: 5,
    label: "Duplicate final hook",
    action: "duplicate",
    readinessStatus: "ready",
    detail: "Repeat the strongest hook as the final keeper section.",
  },
  {
    id: "arrangement-blueprint-step-outro",
    sectionId: "arrangement-section-outro-release",
    order: 6,
    label: "Hold outro reference",
    action: "review",
    readinessStatus: "future",
    detail: "Future outro reference, not required for current keeper lock.",
  },
];

export const multiTrackArrangementEngineRenderPrepItems: MultiTrackArrangementRenderPrepItem[] = [
  {
    id: "arrangement-render-main-hook",
    sectionId: "arrangement-section-main-hook",
    label: "Prepare main hook for render",
    readinessStatus: "ready",
    renderPriority: "critical",
    detail: "Primary keeper section should be first future render-prep target.",
  },
  {
    id: "arrangement-render-final-hook",
    sectionId: "arrangement-section-final-hook-repeat",
    label: "Prepare final hook repeat",
    readinessStatus: "ready",
    renderPriority: "critical",
    detail: "Final hook duplicate should be included in the future render plan.",
  },
  {
    id: "arrangement-render-verse-pocket",
    sectionId: "arrangement-section-verse-pocket",
    label: "Prepare verse pocket",
    readinessStatus: "ready",
    renderPriority: "high",
    detail: "Verse groove should be prepared after the main hook.",
  },
  {
    id: "arrangement-render-bridge-review",
    sectionId: "arrangement-section-bridge-mutation",
    label: "Review bridge before render",
    readinessStatus: "needs-review",
    renderPriority: "medium",
    detail: "Bridge mutation needs human approval before render prep.",
  },
];

export const multiTrackArrangementEngineWorkspaceState: MultiTrackArrangementWorkspaceState = {
  id: "multi-track-arrangement-engine-workspace",
  title: "Arrangement Engine",
  description:
    "Seed-safe arrangement foundation for placing keeper hooks, riff pockets, bridge mutations, duplicated sections, and future render prep into a song blueprint.",
  readinessStatus: "ready",
  sections: multiTrackArrangementEngineSections,
  lanes: multiTrackArrangementEngineLanes,
  blueprintSteps: multiTrackArrangementEngineBlueprintSteps,
  renderPrepItems: multiTrackArrangementEngineRenderPrepItems,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No imports outside this 4-file arrangement set.",
    "No real audio rendering.",
    "Designed to follow keeper extraction later without importing it now.",
  ],
};