
import type {
  MultiTrackRiffGroupingEngineSource,
  MultiTrackRiffGroupingEngineWorkspace,
} from "./MultiTrackRiffGroupingEngineTypes";

export const multiTrackRiffGroupingEngineSources: MultiTrackRiffGroupingEngineSource[] = [
  {
    sourceId: "riff-group-track-a",
    title: "Track A original riff regions",
    sourceKind: "track-a",
    fileLabel: "Original ad-lib / musician source",
    readiness: "needs-review",
    similarityReady: true,
    transientReady: true,
    groupingReady: true,
    segments: [
      {
        segmentId: "track-a-riff-main-hook",
        sourceId: "riff-group-track-a",
        title: "Original main hook riff",
        startMs: 16000,
        endMs: 26000,
        role: "main-hook",
        energyScore: 0.58,
        transientScore: 0.81,
        similarityScore: 0.76,
        timingDriftMs: 0,
        confidence: 0.78,
        status: "estimated",
        risk: "low",
      },
      {
        segmentId: "track-a-riff-variation",
        sourceId: "riff-group-track-a",
        title: "Original variation riff",
        startMs: 42000,
        endMs: 77000,
        role: "variation",
        energyScore: 0.48,
        transientScore: 0.58,
        similarityScore: 0.56,
        timingDriftMs: 0,
        confidence: 0.55,
        status: "seeded",
        risk: "medium",
      },
      {
        segmentId: "track-a-riff-intro",
        sourceId: "riff-group-track-a",
        title: "Original intro idea",
        startMs: 0,
        endMs: 16000,
        role: "intro-idea",
        energyScore: 0.34,
        transientScore: 0.49,
        similarityScore: 0.45,
        timingDriftMs: 0,
        confidence: 0.43,
        status: "seeded",
        risk: "medium",
      },
    ],
    notes: [
      "Track A segments are treated as the original reference family.",
      "Main hook should seed the first riff group.",
      "Weak intro and variation regions stay available but should not outrank the hook.",
    ],
  },
  {
    sourceId: "riff-group-suno-v7",
    title: "Suno V7 riff regions",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render with strong chorus",
    readiness: "needs-review",
    similarityReady: true,
    transientReady: true,
    groupingReady: true,
    segments: [
      {
        segmentId: "suno-v7-riff-chorus",
        sourceId: "riff-group-suno-v7",
        title: "Suno V7 chorus riff",
        startMs: 48000,
        endMs: 61000,
        role: "main-hook",
        energyScore: 0.72,
        transientScore: 0.88,
        similarityScore: 0.78,
        timingDriftMs: 420,
        confidence: 0.82,
        status: "estimated",
        risk: "medium",
      },
      {
        segmentId: "suno-v7-riff-final-hook",
        sourceId: "riff-group-suno-v7",
        title: "Suno V7 final hook riff",
        startMs: 182400,
        endMs: 194000,
        role: "supporting-riff",
        energyScore: 0.7,
        transientScore: 0.79,
        similarityScore: 0.69,
        timingDriftMs: 280,
        confidence: 0.72,
        status: "seeded",
        risk: "medium",
      },
      {
        segmentId: "suno-v7-riff-bridge",
        sourceId: "riff-group-suno-v7",
        title: "Suno V7 bridge lift",
        startMs: 124000,
        endMs: 132000,
        role: "bridge-lift",
        energyScore: 0.66,
        transientScore: 0.78,
        similarityScore: 0.54,
        timingDriftMs: 680,
        confidence: 0.61,
        status: "seeded",
        risk: "high",
      },
    ],
    notes: [
      "Suno V7 chorus is a strong grouped candidate but still has timing drift.",
      "Final hook may be a mutation, not a duplicate.",
      "Bridge lift stays secondary until mutation mapping verifies it.",
    ],
  },
  {
    sourceId: "riff-group-suno-v4",
    title: "Suno V4 alternate riff regions",
    sourceKind: "suno-version",
    fileLabel: "Alternate Suno render with rougher groove",
    readiness: "future",
    similarityReady: true,
    transientReady: true,
    groupingReady: false,
    segments: [
      {
        segmentId: "suno-v4-riff-hook",
        sourceId: "riff-group-suno-v4",
        title: "Suno V4 hook sketch",
        startMs: 44000,
        endMs: 57000,
        role: "main-hook",
        energyScore: 0.61,
        transientScore: 0.67,
        similarityScore: 0.63,
        timingDriftMs: 540,
        confidence: 0.62,
        status: "seeded",
        risk: "medium",
      },
      {
        segmentId: "suno-v4-riff-turnaround",
        sourceId: "riff-group-suno-v4",
        title: "Suno V4 turnaround",
        startMs: 91000,
        endMs: 98000,
        role: "turnaround",
        energyScore: 0.52,
        transientScore: 0.59,
        similarityScore: 0.46,
        timingDriftMs: 740,
        confidence: 0.48,
        status: "seeded",
        risk: "high",
      },
    ],
    notes: [
      "V4 is kept as a weaker alternate branch.",
      "May contain useful groove mutations even if it loses the main keeper race.",
      "Needs stronger grouping evidence before extraction.",
    ],
  },
];

export const multiTrackRiffGroupingEngineWorkspace: MultiTrackRiffGroupingEngineWorkspace = {
  workspaceId: "multi-track-riff-grouping-engine",
  title: "Riff Grouping Engine Foundation",
  summary:
    "Fifth real engine layer. Groups related riff segments across Track A and Suno versions so mutation mapping and survivor analysis can compare families instead of isolated hits.",
  readiness: "needs-review",
  readinessLabel: "Seeded riff groups are ready. Real similarity and transient input comes next.",
  engineGoal:
    "Group matching hook, riff, bridge, and variation regions into families before survivor decisions.",
  engineBoundary:
    "This layer creates riff families. It does not decide the final keeper or render the hybrid.",
  sources: multiTrackRiffGroupingEngineSources,
  groups: [
    {
      groupId: "riff-family-main-hook",
      title: "Main hook family",
      role: "main-hook",
      segmentIds: ["track-a-riff-main-hook", "suno-v7-riff-chorus", "suno-v4-riff-hook"],
      sourceIds: ["riff-group-track-a", "riff-group-suno-v7", "riff-group-suno-v4"],
      groupStrength: "keeper-candidate",
      averageSimilarity: 0.72,
      averageConfidence: 0.74,
      driftSpreadMs: 540,
      survivorPotential: 0.81,
      detail:
        "Main hook appears in the original source and multiple Suno versions with strong enough similarity to become a survivor candidate.",
      recommendation:
        "Send this group to mutation mapping and survivor analysis as the top family.",
      status: "estimated",
      risk: "medium",
    },
    {
      groupId: "riff-family-variation",
      title: "Variation family",
      role: "variation",
      segmentIds: ["track-a-riff-variation", "suno-v7-riff-final-hook"],
      sourceIds: ["riff-group-track-a", "riff-group-suno-v7"],
      groupStrength: "moderate",
      averageSimilarity: 0.63,
      averageConfidence: 0.64,
      driftSpreadMs: 280,
      survivorPotential: 0.59,
      detail:
        "Variation and final hook may share a transformed idea, but evidence is not strong enough yet.",
      recommendation:
        "Keep as a secondary mutation candidate, not a keeper winner.",
      status: "seeded",
      risk: "medium",
    },
    {
      groupId: "riff-family-bridge-lift",
      title: "Bridge lift family",
      role: "bridge-lift",
      segmentIds: ["suno-v7-riff-bridge", "suno-v4-riff-turnaround"],
      sourceIds: ["riff-group-suno-v7", "riff-group-suno-v4"],
      groupStrength: "weak",
      averageSimilarity: 0.5,
      averageConfidence: 0.55,
      driftSpreadMs: 740,
      survivorPotential: 0.41,
      detail:
        "Bridge lift has useful energy but weak evidence against the original source.",
      recommendation:
        "Do not send to extraction until mutation engine finds stronger support.",
      status: "seeded",
      risk: "high",
    },
  ],
  findings: [
    {
      findingId: "riff-group-finding-main-hook",
      title: "Main hook family is the first real keeper lane",
      detail:
        "It has the strongest average confidence and appears across the original source plus Suno versions.",
      action: "Promote this family into mutation mapping and survivor scoring.",
      status: "estimated",
      risk: "medium",
    },
    {
      findingId: "riff-group-finding-drift",
      title: "Timing drift still needs correction",
      detail:
        "The strongest group has a drift spread that could affect extraction boundaries.",
      action: "Carry drift spread into mutation and extraction engines.",
      status: "estimated",
      risk: "medium",
    },
    {
      findingId: "riff-group-finding-bridge",
      title: "Bridge family is not ready",
      detail:
        "Bridge lift lacks enough relationship to Track A.",
      action: "Keep bridge family visible but blocked from keeper selection.",
      status: "seeded",
      risk: "high",
    },
  ],
  engineRules: [
    "Do not create a riff family from one isolated hit.",
    "A keeper candidate should include original-source evidence when possible.",
    "Timing drift must stay attached to every riff group.",
    "Weak families can remain visible but should not drive extraction.",
    "Riff grouping feeds mutation and survivor engines; it does not replace them.",
  ],
  nextSteps: [
    "Connect grouped segments to real similarity matches.",
    "Add automatic segment grouping by role, score, and timing drift.",
    "Send riff families to mutation mapping engine.",
    "Send top families to survivor scoring.",
    "Carry drift and risk into extraction planning.",
  ],
};