import type {
  MultiTrackHybridAssetCandidate,
  MultiTrackHybridBuilderOwnershipItem,
  MultiTrackHybridCompatibilitySignal,
  MultiTrackHybridMergePlan,
  MultiTrackHybridUserConfirmationRule,
  MultiTrackHybridWorkspaceState,
} from "./MultiTrackHybridIntelligenceTypes";

export const multiTrackHybridCompatibilitySignals: MultiTrackHybridCompatibilitySignal[] = [
  {
    id: "tempo-window",
    label: "Tempo Window",
    status: "needs-review",
    confidence: "manual-required",
    detail: "Track A and Track B need an approved BPM relationship before hybrid building.",
    userRule: "Do not assume tempo compatibility without user confirmation.",
  },
  {
    id: "key-center",
    label: "Key Center",
    status: "needs-review",
    confidence: "manual-required",
    detail: "The workspace should mark whether the two tracks can share a key, pivot key, or contrast key.",
    userRule: "User must confirm the intended key relationship.",
  },
  {
    id: "section-boundaries",
    label: "Section Boundaries",
    status: "future",
    confidence: "low",
    detail: "Future analysis can identify verse, hook, bridge, intro, outro, and transition zones.",
    userRule: "Until analysis is wired, sections stay planning-only.",
  },
  {
    id: "stem-identity",
    label: "Stem Identity",
    status: "needs-review",
    confidence: "manual-required",
    detail: "Useful stems must be labeled before they can be trusted for hybrid assembly.",
    userRule: "Never merge unlabeled stems automatically.",
  },
  {
    id: "hook-ownership",
    label: "Hook Ownership",
    status: "needs-review",
    confidence: "manual-required",
    detail: "The user decides which hook, riff, melody, or vocal idea owns the hybrid direction.",
    userRule: "Hook ownership must remain user-confirmed.",
  },
];

export const multiTrackHybridAssetCandidates: MultiTrackHybridAssetCandidate[] = [
  {
    id: "track-a-main-hook",
    sourceId: "track-a",
    assetType: "hook",
    label: "Track A Main Hook",
    usableFor: ["hybrid identity", "riff comparison", "melody anchor"],
    status: "needs-review",
    confidence: "manual-required",
    reason: "Track A may contain the original usable idea or reference phrase.",
    requiredConfirmation: "Confirm that Track A hook should lead the hybrid.",
  },
  {
    id: "track-b-main-hook",
    sourceId: "track-b",
    assetType: "hook",
    label: "Track B Main Hook",
    usableFor: ["replacement hook", "call response", "chorus lift"],
    status: "needs-review",
    confidence: "manual-required",
    reason: "Track B may contain the Suno/result hook or stronger finished phrase.",
    requiredConfirmation: "Confirm that Track B hook should replace or answer Track A.",
  },
  {
    id: "track-a-rhythm-bed",
    sourceId: "track-a",
    assetType: "drums",
    label: "Track A Rhythm Bed",
    usableFor: ["groove foundation", "tempo anchor", "section support"],
    status: "future",
    confidence: "low",
    reason: "Future stem analysis can determine whether Track A groove should carry the hybrid.",
    requiredConfirmation: "Confirm the rhythm bed before merge planning.",
  },
  {
    id: "track-b-bass-support",
    sourceId: "track-b",
    assetType: "bass",
    label: "Track B Bass Support",
    usableFor: ["low-end support", "chorus power", "arrangement lift"],
    status: "future",
    confidence: "low",
    reason: "Future stem analysis can determine whether Track B bass supports Track A material.",
    requiredConfirmation: "Confirm bass compatibility before builder ownership.",
  },
  {
    id: "track-a-vocal-phrase",
    sourceId: "track-a",
    assetType: "vocal",
    label: "Track A Vocal Phrase",
    usableFor: ["ad-lib recovery", "lyric rhythm", "original melody proof"],
    status: "needs-review",
    confidence: "manual-required",
    reason: "Original phone/ad-lib ideas may be the proof source for hybrid direction.",
    requiredConfirmation: "Confirm which vocal phrases are keepers.",
  },
  {
    id: "track-b-chorus-lift",
    sourceId: "track-b",
    assetType: "chorus",
    label: "Track B Chorus Lift",
    usableFor: ["big section swap", "finished chorus", "commercial lift"],
    status: "needs-review",
    confidence: "manual-required",
    reason: "Track B may provide the finished chorus section for a hybrid version.",
    requiredConfirmation: "Confirm chorus swap before any future builder action.",
  },
];

export const multiTrackHybridMergePlans: MultiTrackHybridMergePlan[] = [
  {
    id: "stem-merge-plan",
    lane: "stem-merge",
    title: "Stem Merge Planning",
    status: "future",
    confidence: "low",
    trackAPurpose: "Provide original groove, riff, melody, or raw idea.",
    trackBPurpose: "Provide finished stem, stronger support, or alternate layer.",
    plannedOutcome: "A future builder can propose safe stem combinations.",
    blockedUntil: "Stem labels, source ownership, and user confirmation exist.",
  },
  {
    id: "hook-merge-plan",
    lane: "hook-merge",
    title: "Hook Merge Planning",
    status: "needs-review",
    confidence: "manual-required",
    trackAPurpose: "Original hook source or call phrase.",
    trackBPurpose: "Finished hook source or response phrase.",
    plannedOutcome: "A call-and-response or replacement hook map.",
    blockedUntil: "User confirms which hook owns the hybrid.",
  },
  {
    id: "section-swap-plan",
    lane: "section-swap",
    title: "Section Swap Planning",
    status: "future",
    confidence: "low",
    trackAPurpose: "Supply verse, intro, bridge, or raw structure.",
    trackBPurpose: "Supply chorus, outro, lift, or alternate arrangement.",
    plannedOutcome: "A future section swap map with no audio mutation yet.",
    blockedUntil: "Section boundaries are detected or manually marked.",
  },
  {
    id: "tempo-key-plan",
    lane: "tempo-key",
    title: "Tempo / Key Compatibility",
    status: "needs-review",
    confidence: "manual-required",
    trackAPurpose: "Baseline BPM/key or original reference.",
    trackBPurpose: "Target BPM/key or produced reference.",
    plannedOutcome: "A compatibility decision before merge planning.",
    blockedUntil: "User approves tempo/key relationship.",
  },
  {
    id: "builder-ownership-plan",
    lane: "builder-ownership",
    title: "Future Hybrid Builder Ownership",
    status: "future",
    confidence: "low",
    trackAPurpose: "Source material only.",
    trackBPurpose: "Source material only.",
    plannedOutcome: "Future builder receives approved plans, not raw assumptions.",
    blockedUntil: "Confirmation rules and confidence gates are satisfied.",
  },
];

export const multiTrackHybridConfirmationRules: MultiTrackHybridUserConfirmationRule[] = [
  {
    id: "confirm-source-ownership",
    label: "Confirm Source Ownership",
    owner: "user",
    requiredBefore: "Any hybrid plan becomes active.",
    rule: "The user must confirm which track owns the main idea.",
  },
  {
    id: "confirm-hook-direction",
    label: "Confirm Hook Direction",
    owner: "user",
    requiredBefore: "Hook merge planning.",
    rule: "The user must choose replace, blend, call-response, or keep separate.",
  },
  {
    id: "confirm-tempo-key",
    label: "Confirm Tempo / Key",
    owner: "user",
    requiredBefore: "Stem or section merge planning.",
    rule: "The user must approve whether tracks should match, contrast, or pivot.",
  },
  {
    id: "confirm-builder-action",
    label: "Confirm Builder Action",
    owner: "future-builder",
    requiredBefore: "Future hybrid builder execution.",
    rule: "The builder can only act on confirmed read-only plans.",
  },
];

export const multiTrackHybridBuilderOwnership: MultiTrackHybridBuilderOwnershipItem[] = [
  {
    id: "read-only-workspace",
    owner: "manual-review",
    label: "Read-Only Workspace",
    currentScope: "Display planning, readiness, and confidence gates.",
    futureScope: "Feed approved plans to a future hybrid builder.",
    status: "ready",
  },
  {
    id: "no-audio-processing",
    owner: "manual-review",
    label: "No Audio Processing",
    currentScope: "No DSP, no rendering, no save, no Supabase writes.",
    futureScope: "Builder can later request processing through approved engine layers.",
    status: "ready",
  },
  {
    id: "confidence-gates",
    owner: "user",
    label: "Confidence Gates",
    currentScope: "Require manual confirmation where analysis is not wired.",
    futureScope: "AI can suggest, but user confirms final hybrid direction.",
    status: "needs-review",
  },
  {
    id: "future-builder-contract",
    owner: "future-builder",
    label: "Future Builder Contract",
    currentScope: "Define what the future builder will own later.",
    futureScope: "Create hybrid arrangement instructions after confirmation.",
    status: "future",
  },
];

export const multiTrackHybridWorkspaceState: MultiTrackHybridWorkspaceState = {
  title: "Hybrid Intelligence Workspace",
  description:
    "Read-only planning layer for hybrid song-building readiness across Track A, Track B, stems, hooks, sections, tempo, key, confidence, and future builder ownership.",
  compatibilitySignals: multiTrackHybridCompatibilitySignals,
  assetCandidates: multiTrackHybridAssetCandidates,
  mergePlans: multiTrackHybridMergePlans,
  confirmationRules: multiTrackHybridConfirmationRules,
  builderOwnership: multiTrackHybridBuilderOwnership,
};