import type { MultiTrackExtractionPlanWorkspaceState } from "./MultiTrackExtractionPlanTypes";

export const multiTrackExtractionPlanSeed: MultiTrackExtractionPlanWorkspaceState = {
  id: "multi-track-extraction-plan-workspace",
  title: "Extraction Plan",
  description:
    "Seed-safe bridge for turning detected musical ideas into color-coded markers, trim windows, edit instructions, duplicate plans, and future render targets.",
  readinessStatus: "ready",
  activeTargetId: "target-main-hook-extract",
  guardrailNotes: [
    "No page wiring yet.",
    "No audio files are modified by this layer.",
    "No render engine is called here.",
    "Extraction plans are reviewable before any destructive edit exists.",
    "All timing windows are placeholders until real waveform analysis is connected.",
  ],
  sourceClips: [
    {
      id: "clip-hook-v01",
      versionId: "version-01",
      title: "Hook Clip V01",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Baseline hook window",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "clip-hook-v02",
      versionId: "version-02",
      title: "Hook Clip V02",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook window",
      },
      readinessStatus: "ready",
    },
    {
      id: "clip-hook-v03",
      versionId: "version-03",
      title: "Hook Clip V03",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Review hook window",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "clip-riff-v04",
      versionId: "version-04",
      title: "Riff Clip V04",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 21,
        endSeconds: 29,
        label: "Riff pocket",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "clip-bass-v05",
      versionId: "version-05",
      title: "Bass Groove V05",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass groove",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "clip-vocal-v07",
      versionId: "version-07",
      title: "Vocal Phrase V07",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      readinessStatus: "needs-review",
    },
  ],
  risks: [
    {
      id: "risk-extraction-missing-waveform",
      riskKind: "missing-waveform",
      label: "Missing waveform evidence",
      detail:
        "Extraction timing is seed-only until real waveform markers are connected.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-extraction-tail-cut",
      riskKind: "tail-cut-risk",
      label: "Tail cut risk",
      detail:
        "Hook and vocal clips may need tail padding so notes do not cut off.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-extraction-stem-bleed",
      riskKind: "stem-bleed",
      label: "Stem bleed risk",
      detail:
        "Stem-safe extraction needs separation checks later.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-extraction-future-render",
      riskKind: "future-render-engine",
      label: "Future render engine required",
      detail:
        "WAV/MP3/stem output cannot run until render engine wiring exists.",
      severity: "high",
      isBlocking: false,
    },
  ],
  markers: [
    {
      id: "marker-hook-v01",
      sourceClipId: "clip-hook-v01",
      label: "Hook marker V01",
      detail: "Blue marker for baseline hook candidate.",
      color: "blue",
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Baseline hook",
      },
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "marker-hook-v02",
      sourceClipId: "clip-hook-v02",
      label: "Hook marker V02",
      detail: "Blue marker for strongest hook candidate.",
      color: "blue",
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook",
      },
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "marker-hook-v03",
      sourceClipId: "clip-hook-v03",
      label: "Hook marker V03",
      detail: "Blue marker for review hook candidate.",
      color: "blue",
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Review hook",
      },
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "marker-riff-v04",
      sourceClipId: "clip-riff-v04",
      label: "Riff marker V04",
      detail: "Orange marker for riff pocket.",
      color: "orange",
      timeRange: {
        startSeconds: 21,
        endSeconds: 29,
        label: "Riff pocket",
      },
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "marker-bass-v05",
      sourceClipId: "clip-bass-v05",
      label: "Bass marker V05",
      detail: "Green marker for bass groove.",
      color: "green",
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass groove",
      },
      confidenceBucket: "strong",
      readinessStatus: "needs-review",
    },
    {
      id: "marker-vocal-v07",
      sourceClipId: "clip-vocal-v07",
      label: "Vocal marker V07",
      detail: "Purple marker for vocal phrase.",
      color: "purple",
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
  ],
  steps: [
    {
      id: "step-hook-mark",
      stepNumber: 1,
      actionKind: "mark",
      label: "Mark hook candidates",
      detail: "Place review-safe markers on all hook windows.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "ready",
    },
    {
      id: "step-hook-color",
      stepNumber: 2,
      actionKind: "color-code",
      label: "Color-code hook blue",
      detail: "Apply the same blue planning identity to all hook matches.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "ready",
    },
    {
      id: "step-hook-trim",
      stepNumber: 3,
      actionKind: "trim",
      label: "Trim strongest hook",
      detail: "Future trim window around Hook Clip V02.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "future",
    },
    {
      id: "step-hook-extract",
      stepNumber: 4,
      actionKind: "extract",
      label: "Extract strongest hook",
      detail: "Future extraction into editable clip lane.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "future",
    },
    {
      id: "step-hook-duplicate",
      stepNumber: 5,
      actionKind: "duplicate",
      label: "Duplicate strongest hook",
      detail: "Future duplication into arrangement testing lane.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "future",
    },
    {
      id: "step-hook-render",
      stepNumber: 6,
      actionKind: "render",
      label: "Render hook WAV",
      detail: "Future render output after extraction is safe.",
      targetClipId: "clip-hook-v02",
      markerId: "marker-hook-v02",
      readinessStatus: "future",
    },
    {
      id: "step-bass-mark",
      stepNumber: 1,
      actionKind: "mark",
      label: "Mark bass groove",
      detail: "Place green planning marker on bass groove.",
      targetClipId: "clip-bass-v05",
      markerId: "marker-bass-v05",
      readinessStatus: "needs-review",
    },
    {
      id: "step-vocal-hold",
      stepNumber: 1,
      actionKind: "hold",
      label: "Hold vocal phrase",
      detail: "Wait for phonetic/lyric confidence before extraction.",
      targetClipId: "clip-vocal-v07",
      markerId: "marker-vocal-v07",
      readinessStatus: "needs-review",
    },
  ],
  editInstructions: [
    {
      id: "edit-hook-v02",
      sourceClipId: "clip-hook-v02",
      label: "Edit Hook V02",
      detail: "Future edit instruction for strongest hook candidate.",
      trimStartSeconds: 44,
      trimEndSeconds: 53,
      fadeInMs: 12,
      fadeOutMs: 80,
      duplicateCount: 2,
      targetLaneLabel: "Hook Edit Lane",
      readinessStatus: "future",
    },
    {
      id: "edit-bass-v05",
      sourceClipId: "clip-bass-v05",
      label: "Edit Bass V05",
      detail: "Future bass groove trim and duplicate plan.",
      trimStartSeconds: 16,
      trimEndSeconds: 25,
      fadeInMs: 8,
      fadeOutMs: 60,
      duplicateCount: 4,
      targetLaneLabel: "Groove Edit Lane",
      readinessStatus: "future",
    },
    {
      id: "edit-riff-v04",
      sourceClipId: "clip-riff-v04",
      label: "Edit Riff V04",
      detail: "Future riff loop candidate after review.",
      trimStartSeconds: 21,
      trimEndSeconds: 29,
      fadeInMs: 10,
      fadeOutMs: 70,
      duplicateCount: 3,
      targetLaneLabel: "Riff Edit Lane",
      readinessStatus: "future",
    },
  ],
  renderInstructions: [
    {
      id: "render-hook-v02-wav",
      sourceClipId: "clip-hook-v02",
      label: "Render Hook V02 WAV",
      detail: "Future WAV output for strongest hook.",
      outputKind: "wav-render",
      includeTail: true,
      normalizeOutput: true,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
    {
      id: "render-hook-v02-stems",
      sourceClipId: "clip-hook-v02",
      label: "Render Hook V02 Stems",
      detail: "Future stem-pack output after separation exists.",
      outputKind: "stem-pack",
      includeTail: true,
      normalizeOutput: false,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
    {
      id: "render-bass-v05-loop",
      sourceClipId: "clip-bass-v05",
      label: "Render Bass V05 Loop",
      detail: "Future loop output for bass groove testing.",
      outputKind: "loop",
      includeTail: false,
      normalizeOutput: true,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
  ],
  targets: [
    {
      id: "target-main-hook-extract",
      title: "Main Hook Extraction",
      targetKind: "hook",
      color: "blue",
      summary:
        "Primary extraction plan for the strongest repeated hook across Suno versions.",
      sourceClipIds: ["clip-hook-v01", "clip-hook-v02", "clip-hook-v03"],
      markerIds: ["marker-hook-v01", "marker-hook-v02", "marker-hook-v03"],
      stepIds: [
        "step-hook-mark",
        "step-hook-color",
        "step-hook-trim",
        "step-hook-extract",
        "step-hook-duplicate",
        "step-hook-render",
      ],
      editInstructionIds: ["edit-hook-v02"],
      renderInstructionIds: ["render-hook-v02-wav", "render-hook-v02-stems"],
      riskIds: [
        "risk-extraction-missing-waveform",
        "risk-extraction-tail-cut",
        "risk-extraction-future-render",
      ],
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "target-bass-groove-extract",
      title: "Bass Groove Extraction",
      targetKind: "bass-groove",
      color: "green",
      summary: "Future extraction plan for bass/groove material.",
      sourceClipIds: ["clip-bass-v05"],
      markerIds: ["marker-bass-v05"],
      stepIds: ["step-bass-mark"],
      editInstructionIds: ["edit-bass-v05"],
      renderInstructionIds: ["render-bass-v05-loop"],
      riskIds: ["risk-extraction-stem-bleed", "risk-extraction-future-render"],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "target-riff-extract",
      title: "Riff Extraction",
      targetKind: "riff",
      color: "orange",
      summary: "Future extraction plan for riff loop candidates.",
      sourceClipIds: ["clip-riff-v04"],
      markerIds: ["marker-riff-v04"],
      stepIds: [],
      editInstructionIds: ["edit-riff-v04"],
      renderInstructionIds: [],
      riskIds: ["risk-extraction-missing-waveform"],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "target-vocal-hold",
      title: "Vocal Phrase Hold",
      targetKind: "vocal-phrase",
      color: "purple",
      summary:
        "Hold vocal phrase until lyric/phonetic matching confirms it belongs.",
      sourceClipIds: ["clip-vocal-v07"],
      markerIds: ["marker-vocal-v07"],
      stepIds: ["step-vocal-hold"],
      editInstructionIds: [],
      renderInstructionIds: [],
      riskIds: ["risk-extraction-tail-cut"],
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "lane-extract-hooks",
      label: "Hook Extraction",
      detail: "Blue hook targets ready for future clip extraction.",
      color: "blue",
      targetIds: ["target-main-hook-extract"],
      readinessStatus: "ready",
    },
    {
      id: "lane-extract-groove",
      label: "Groove Extraction",
      detail: "Green groove targets waiting for stem-safe review.",
      color: "green",
      targetIds: ["target-bass-groove-extract"],
      readinessStatus: "needs-review",
    },
    {
      id: "lane-extract-review",
      label: "Review Queue",
      detail: "Orange and purple ideas that need more confidence.",
      color: "yellow",
      targetIds: ["target-riff-extract", "target-vocal-hold"],
      readinessStatus: "needs-review",
    },
  ],
};