import type {
  MultiTrackTransientEngineSource,
  MultiTrackTransientEngineWorkspace,
} from "./MultiTrackTransientEngineTypes";

export const multiTrackTransientEngineSources: MultiTrackTransientEngineSource[] = [
  {
    sourceId: "transient-track-a",
    title: "Track A transient pass",
    sourceKind: "track-a",
    fileLabel: "Original ad-lib or musician reference track",
    durationMs: 224000,
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientsReady: true,
    transientCount: 9,
    anchorCount: 3,
    hits: [
      {
        transientId: "track-a-hit-001",
        label: "Phrase start",
        timeMs: 0,
        strength: "anchor",
        role: "riff-start",
        peak: 0.62,
        rmsJump: 0.21,
        confidence: 0.82,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-002",
        label: "Kick emphasis",
        timeMs: 830,
        strength: "strong",
        role: "kick",
        peak: 0.68,
        rmsJump: 0.18,
        confidence: 0.76,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-003",
        label: "Hook attack",
        timeMs: 16200,
        strength: "anchor",
        role: "riff-start",
        peak: 0.79,
        rmsJump: 0.29,
        confidence: 0.9,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-004",
        label: "Vocal push",
        timeMs: 18480,
        strength: "medium",
        role: "vocal-attack",
        peak: 0.58,
        rmsJump: 0.14,
        confidence: 0.66,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-005",
        label: "Guitar bite",
        timeMs: 21140,
        strength: "strong",
        role: "guitar-attack",
        peak: 0.71,
        rmsJump: 0.22,
        confidence: 0.81,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-006",
        label: "Hook repeat",
        timeMs: 24600,
        strength: "anchor",
        role: "riff-start",
        peak: 0.74,
        rmsJump: 0.27,
        confidence: 0.87,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-007",
        label: "Soft response",
        timeMs: 42800,
        strength: "weak",
        role: "unknown",
        peak: 0.42,
        rmsJump: 0.08,
        confidence: 0.44,
        status: "seeded",
      },
      {
        transientId: "track-a-hit-008",
        label: "Variation hit",
        timeMs: 49200,
        strength: "medium",
        role: "section-hit",
        peak: 0.61,
        rmsJump: 0.16,
        confidence: 0.69,
        status: "estimated",
      },
      {
        transientId: "track-a-hit-009",
        label: "Phrase close",
        timeMs: 76000,
        strength: "medium",
        role: "section-hit",
        peak: 0.56,
        rmsJump: 0.13,
        confidence: 0.62,
        status: "estimated",
      },
    ],
    clusters: [
      {
        clusterId: "track-a-cluster-hook",
        title: "Main hook transient group",
        startMs: 16000,
        endMs: 26000,
        transientIds: ["track-a-hit-003", "track-a-hit-004", "track-a-hit-005", "track-a-hit-006"],
        dominantRole: "riff-start",
        averageConfidence: 0.81,
        densityLabel: "Dense hook activity",
        status: "estimated",
        risk: "low",
      },
      {
        clusterId: "track-a-cluster-variation",
        title: "Variation phrase group",
        startMs: 42000,
        endMs: 77000,
        transientIds: ["track-a-hit-007", "track-a-hit-008", "track-a-hit-009"],
        dominantRole: "section-hit",
        averageConfidence: 0.58,
        densityLabel: "Loose variation activity",
        status: "seeded",
        risk: "medium",
      },
    ],
    findings: [
      {
        findingId: "track-a-finding-hook-anchor",
        title: "Hook anchors are clear enough to track",
        detail: "Three strong anchor hits exist in the seeded Track A pass.",
        action: "Send anchor hits to riff grouping and similarity scoring.",
        status: "estimated",
        risk: "low",
      },
      {
        findingId: "track-a-finding-soft-variation",
        title: "Variation region is weaker",
        detail: "Variation region has lower confidence and should not outrank the hook yet.",
        action: "Keep variation as secondary candidate until real decode verifies it.",
        status: "seeded",
        risk: "medium",
      },
    ],
    notes: [
      "Transient engine should consume waveform and statistics summaries.",
      "Anchor hits become the first reliable riff boundary clues.",
      "Weak hits should not create survivor winners by themselves.",
    ],
  },
  {
    sourceId: "transient-suno-v7",
    title: "Suno Version 7 transient pass",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render with strong chorus",
    durationMs: 238000,
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientsReady: true,
    transientCount: 11,
    anchorCount: 4,
    hits: [
      {
        transientId: "suno-v7-hit-001",
        label: "Intro lift",
        timeMs: 0,
        strength: "strong",
        role: "downbeat",
        peak: 0.72,
        rmsJump: 0.2,
        confidence: 0.78,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-002",
        label: "Pre-hook hit",
        timeMs: 46000,
        strength: "medium",
        role: "section-hit",
        peak: 0.67,
        rmsJump: 0.17,
        confidence: 0.71,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-003",
        label: "Chorus downbeat",
        timeMs: 48000,
        strength: "anchor",
        role: "downbeat",
        peak: 0.91,
        rmsJump: 0.34,
        confidence: 0.94,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-004",
        label: "Chorus riff start",
        timeMs: 50120,
        strength: "anchor",
        role: "riff-start",
        peak: 0.88,
        rmsJump: 0.31,
        confidence: 0.92,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-005",
        label: "Snare snap",
        timeMs: 52040,
        strength: "strong",
        role: "snare",
        peak: 0.83,
        rmsJump: 0.24,
        confidence: 0.84,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-006",
        label: "Hook repeat",
        timeMs: 56200,
        strength: "anchor",
        role: "riff-start",
        peak: 0.86,
        rmsJump: 0.3,
        confidence: 0.91,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-007",
        label: "Chorus response",
        timeMs: 60400,
        strength: "strong",
        role: "vocal-attack",
        peak: 0.79,
        rmsJump: 0.22,
        confidence: 0.8,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-008",
        label: "Bridge downbeat",
        timeMs: 124000,
        strength: "anchor",
        role: "downbeat",
        peak: 0.86,
        rmsJump: 0.28,
        confidence: 0.88,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-009",
        label: "Bridge lift",
        timeMs: 130200,
        strength: "medium",
        role: "section-hit",
        peak: 0.7,
        rmsJump: 0.16,
        confidence: 0.67,
        status: "seeded",
      },
      {
        transientId: "suno-v7-hit-010",
        label: "Final hook entry",
        timeMs: 182400,
        strength: "strong",
        role: "riff-start",
        peak: 0.82,
        rmsJump: 0.25,
        confidence: 0.79,
        status: "estimated",
      },
      {
        transientId: "suno-v7-hit-011",
        label: "Outro hit",
        timeMs: 224000,
        strength: "medium",
        role: "section-hit",
        peak: 0.61,
        rmsJump: 0.12,
        confidence: 0.58,
        status: "seeded",
      },
    ],
    clusters: [
      {
        clusterId: "suno-v7-cluster-chorus",
        title: "Chorus transient group",
        startMs: 48000,
        endMs: 61000,
        transientIds: [
          "suno-v7-hit-003",
          "suno-v7-hit-004",
          "suno-v7-hit-005",
          "suno-v7-hit-006",
          "suno-v7-hit-007",
        ],
        dominantRole: "riff-start",
        averageConfidence: 0.88,
        densityLabel: "Strong chorus activity",
        status: "estimated",
        risk: "low",
      },
      {
        clusterId: "suno-v7-cluster-bridge",
        title: "Bridge transient group",
        startMs: 124000,
        endMs: 132000,
        transientIds: ["suno-v7-hit-008", "suno-v7-hit-009"],
        dominantRole: "downbeat",
        averageConfidence: 0.78,
        densityLabel: "Bridge lift activity",
        status: "estimated",
        risk: "medium",
      },
    ],
    findings: [
      {
        findingId: "suno-v7-finding-chorus-anchor",
        title: "Chorus has strongest transient anchor set",
        detail: "The chorus cluster has the strongest confidence and density in the seeded pass.",
        action: "Send chorus cluster to survivor and riff group engines.",
        status: "estimated",
        risk: "low",
      },
      {
        findingId: "suno-v7-finding-loudness-risk",
        title: "Loudness may inflate transient confidence",
        detail: "Statistics layer already flagged this version as louder and more compressed.",
        action: "Normalize confidence before comparing to Track A.",
        status: "estimated",
        risk: "medium",
      },
    ],
    notes: [
      "Transient confidence must be normalized against waveform statistics.",
      "Chorus anchor set is a strong survivor candidate but not final proof.",
      "Timing drift must be checked before calling this the same riff as Track A.",
    ],
  },
];

export const multiTrackTransientEngineWorkspace: MultiTrackTransientEngineWorkspace = {
  workspaceId: "multi-track-transient-engine",
  title: "Transient Engine Foundation",
  summary:
    "Third real engine layer. Finds attack points, anchor hits, riff starts, downbeats, and dense transient groups that can feed similarity, riff grouping, survivor analysis, and extraction planning.",
  readiness: "needs-review",
  readinessLabel: "Seeded transient pass is ready. Real waveform/statistics input comes next.",
  engineGoal:
    "Turn waveform energy movement into reliable timing anchors before any riff or survivor decision is made.",
  engineBoundary:
    "This layer finds timing events. It does not decide whether a hook is musically better.",
  sources: multiTrackTransientEngineSources,
  comparisons: [
    {
      comparisonId: "transient-track-a-vs-suno-v7",
      title: "Track A hook anchors vs Suno V7 chorus anchors",
      leftSourceId: "transient-track-a",
      rightSourceId: "transient-suno-v7",
      sharedAnchorCount: 3,
      timingDriftMs: 420,
      densityDifference: 0.19,
      detail:
        "Both sources have strong riff-start anchors, but Suno V7 is denser and may require drift correction before comparison.",
      status: "estimated",
      risk: "medium",
    },
  ],
  engineRules: [
    "Do not compare riffs until transient anchors are normalized.",
    "Do not let loudness alone create stronger transient confidence.",
    "Anchor hits should feed riff grouping, not replace it.",
    "Weak hits can support a phrase but should not create a survivor winner.",
    "Timing drift must be tracked before claiming two hooks are the same idea.",
  ],
  nextSteps: [
    "Connect transient engine to waveform statistics windows.",
    "Calculate real RMS jumps from decoded frames.",
    "Add downbeat estimation from repeated anchor spacing.",
    "Send transient clusters to riff grouping engine.",
    "Send timing drift to similarity and survivor engines.",
  ],
};