import type {
  MultiTrackMutationEngineMutation,
  MultiTrackMutationEngineVersion,
  MultiTrackMutationEngineWorkspace,
} from "./MultiTrackMutationEngineTypes";

export const multiTrackMutationEngineVersions: MultiTrackMutationEngineVersion[] = [
  {
    versionId: "mutation-original-track-a",
    title: "Original Track A hook",
    sourceKind: "original",
    fileLabel: "Original ad-lib / musician source",
    order: 1,
    riffFamilyId: "riff-family-main-hook",
    startMs: 16000,
    endMs: 26000,
    similarityScore: 1,
    confidence: 0.78,
    driftMs: 0,
    energyScore: 0.58,
    transientScore: 0.81,
    survivalState: "survived",
    status: "estimated",
    risk: "low",
  },
  {
    versionId: "mutation-suno-v4-hook",
    title: "Suno V4 hook sketch",
    sourceKind: "suno-version",
    fileLabel: "Alternate Suno render with rougher groove",
    order: 2,
    riffFamilyId: "riff-family-main-hook",
    startMs: 44000,
    endMs: 57000,
    similarityScore: 0.63,
    confidence: 0.62,
    driftMs: 540,
    energyScore: 0.61,
    transientScore: 0.67,
    survivalState: "mutated",
    status: "seeded",
    risk: "medium",
  },
  {
    versionId: "mutation-suno-v7-chorus",
    title: "Suno V7 chorus hook",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render with strong chorus",
    order: 3,
    riffFamilyId: "riff-family-main-hook",
    startMs: 48000,
    endMs: 61000,
    similarityScore: 0.78,
    confidence: 0.82,
    driftMs: 420,
    energyScore: 0.72,
    transientScore: 0.88,
    survivalState: "survived",
    status: "estimated",
    risk: "medium",
  },
  {
    versionId: "mutation-suno-v7-final-hook",
    title: "Suno V7 final hook repeat",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render final hook entry",
    order: 4,
    riffFamilyId: "riff-family-main-hook",
    startMs: 182400,
    endMs: 194000,
    similarityScore: 0.69,
    confidence: 0.72,
    driftMs: 280,
    energyScore: 0.7,
    transientScore: 0.79,
    survivalState: "mutated",
    status: "seeded",
    risk: "medium",
  },
  {
    versionId: "mutation-suno-v9-lost",
    title: "Suno V9 missing hook lane",
    sourceKind: "suno-version",
    fileLabel: "Later Suno render where hook shape weakens",
    order: 5,
    riffFamilyId: "riff-family-main-hook",
    startMs: 52000,
    endMs: 65000,
    similarityScore: 0.34,
    confidence: 0.38,
    driftMs: 900,
    energyScore: 0.49,
    transientScore: 0.41,
    survivalState: "weakened",
    status: "seeded",
    risk: "high",
  },
];

export const multiTrackMutationEngineMutations: MultiTrackMutationEngineMutation[] = [
  {
    mutationId: "mutation-original-to-v4-timing",
    title: "Original to V4 timing shift",
    fromVersionId: "mutation-original-track-a",
    toVersionId: "mutation-suno-v4-hook",
    mutationKind: "timing-shift",
    amount: 0.54,
    amountLabel: "540ms drift",
    detail:
      "V4 preserves part of the hook but shifts the entry enough to require alignment before extraction.",
    impact: "Moderate timing drift. Keep candidate but do not use as final cut anchor.",
    status: "seeded",
    risk: "medium",
  },
  {
    mutationId: "mutation-v4-to-v7-energy",
    title: "V4 to V7 energy lift",
    fromVersionId: "mutation-suno-v4-hook",
    toVersionId: "mutation-suno-v7-chorus",
    mutationKind: "energy-lift",
    amount: 0.11,
    amountLabel: "+0.11 energy",
    detail:
      "V7 chorus keeps the rough hook family but increases energy and transient confidence.",
    impact: "Positive mutation. V7 becomes stronger survivor candidate.",
    status: "estimated",
    risk: "low",
  },
  {
    mutationId: "mutation-v7-chorus-to-final-density",
    title: "Chorus to final hook density change",
    fromVersionId: "mutation-suno-v7-chorus",
    toVersionId: "mutation-suno-v7-final-hook",
    mutationKind: "density-change",
    amount: 0.1,
    amountLabel: "-0.10 transient density",
    detail:
      "Final hook keeps the family but loses some transient density compared with first chorus.",
    impact: "Useful repeat, but first chorus remains stronger keeper lane.",
    status: "seeded",
    risk: "medium",
  },
  {
    mutationId: "mutation-v7-to-v9-weakening",
    title: "V7 to V9 hook weakening",
    fromVersionId: "mutation-suno-v7-chorus",
    toVersionId: "mutation-suno-v9-lost",
    mutationKind: "rhythm-change",
    amount: 0.44,
    amountLabel: "-0.44 similarity drop",
    detail:
      "Later version weakens the original hook identity and should not be treated as a survivor.",
    impact: "Negative mutation. Keep visible but block from keeper selection.",
    status: "seeded",
    risk: "high",
  },
];

export const multiTrackMutationEngineWorkspace: MultiTrackMutationEngineWorkspace = {
  workspaceId: "multi-track-mutation-engine",
  title: "Mutation Engine Foundation",
  summary:
    "Sixth real engine layer. Tracks how riff families change across original and Suno versions so survivor scoring can tell the difference between a strong evolution and a lost idea.",
  readiness: "needs-review",
  readinessLabel: "Seeded mutation map is ready. Real riff group input comes next.",
  engineGoal:
    "Follow a hook or riff through versions and identify where it survives, mutates, weakens, or disappears.",
  engineBoundary:
    "This layer maps change. It does not pick the final keeper or create the extraction plan.",
  versions: multiTrackMutationEngineVersions,
  mutations: multiTrackMutationEngineMutations,
  families: [
    {
      familyId: "mutation-family-main-hook",
      title: "Main hook mutation family",
      riffFamilyId: "riff-family-main-hook",
      sourceSegmentIds: [
        "track-a-riff-main-hook",
        "suno-v4-riff-hook",
        "suno-v7-riff-chorus",
        "suno-v7-riff-final-hook",
      ],
      versionIds: [
        "mutation-original-track-a",
        "mutation-suno-v4-hook",
        "mutation-suno-v7-chorus",
        "mutation-suno-v7-final-hook",
        "mutation-suno-v9-lost",
      ],
      mutationIds: [
        "mutation-original-to-v4-timing",
        "mutation-v4-to-v7-energy",
        "mutation-v7-chorus-to-final-density",
        "mutation-v7-to-v9-weakening",
      ],
      survivalScore: 0.74,
      mutationScore: 0.68,
      keeperPotential: 0.8,
      detail:
        "The main hook survives into V7 strongly, mutates into final hook, and weakens in later V9 lane.",
      recommendation:
        "Promote V7 chorus as the strongest survivor candidate while keeping V7 final hook as a supporting repeat.",
      status: "estimated",
      risk: "medium",
    },
    {
      familyId: "mutation-family-bridge-lift",
      title: "Bridge lift mutation family",
      riffFamilyId: "riff-family-bridge-lift",
      sourceSegmentIds: ["suno-v7-riff-bridge", "suno-v4-riff-turnaround"],
      versionIds: ["mutation-suno-v4-hook", "mutation-suno-v7-chorus"],
      mutationIds: ["mutation-v4-to-v7-energy"],
      survivalScore: 0.41,
      mutationScore: 0.48,
      keeperPotential: 0.33,
      detail:
        "Bridge lift has energy but weak relationship to the original hook family.",
      recommendation:
        "Do not promote bridge lift into survivor scoring until stronger original-source evidence exists.",
      status: "seeded",
      risk: "high",
    },
  ],
  findings: [
    {
      findingId: "mutation-finding-v7-wins",
      title: "V7 chorus is the strongest evolved hook",
      detail:
        "It has the best combination of survival, energy lift, transient confidence, and manageable drift.",
      action: "Send V7 chorus into survivor engine as the top candidate.",
      status: "estimated",
      risk: "medium",
    },
    {
      findingId: "mutation-finding-final-repeat",
      title: "Final hook is a useful repeat, not the main winner",
      detail:
        "The final hook keeps the idea but loses density compared with the first chorus.",
      action: "Mark as supporting extraction lane, not primary keeper lane.",
      status: "seeded",
      risk: "medium",
    },
    {
      findingId: "mutation-finding-v9-lost",
      title: "V9 weakens the original idea",
      detail:
        "Similarity and transient evidence drop too far to call it a survivor.",
      action: "Block V9 from keeper selection unless later evidence changes.",
      status: "seeded",
      risk: "high",
    },
  ],
  engineRules: [
    "Mutation is not automatically improvement.",
    "A louder version can still be a weaker mutation.",
    "Keeper scoring should reward survival plus useful evolution.",
    "Lost ideas should stay visible but blocked from extraction.",
    "Mutation map must carry timing drift into extraction planning.",
  ],
  nextSteps: [
    "Connect mutation versions to real riff grouping output.",
    "Calculate mutation amount from similarity, drift, and energy deltas.",
    "Add mutation trend scoring across all 10 Suno versions.",
    "Send top evolved candidates to survivor engine.",
    "Send blocked mutations to review instead of extraction.",
  ],
};