import type { MultiTrackSurvivorAnalysisWorkspaceState } from "./MultiTrackSurvivorAnalysisTypes";

export const multiTrackSurvivorAnalysisSeed: MultiTrackSurvivorAnalysisWorkspaceState = {
  id: "multi-track-survivor-analysis-workspace",
  title: "Survivor Analysis",
  description:
    "Seed-safe winner picker for finding the strongest surviving musical idea across Suno versions before extraction, edit, duplicate, or render wiring.",
  readinessStatus: "ready",
  activeGroupId: "group-hook-survivors",
  activeCandidateId: "survivor-hook-v02",
  guardrailNotes: [
    "No page wiring yet.",
    "No audio analyzer is called here.",
    "No candidate is rendered here.",
    "Winner picks remain reviewable until real waveform evidence exists.",
  ],
  candidates: [
    {
      id: "survivor-original-hook",
      title: "Original Hook",
      versionId: "original",
      candidateKind: "hook",
      color: "blue",
      timeRange: { startSeconds: 0, endSeconds: 8, label: "Original idea" },
      summary: "User-origin hook used as the reference.",
      identityScore: 100,
      editScore: 70,
      renderScore: 60,
      keeperScore: 95,
      outcome: "support",
      confidenceBucket: "verified",
      readinessStatus: "ready",
    },
    {
      id: "survivor-hook-v01",
      title: "Hook V01",
      versionId: "version-01",
      candidateKind: "hook",
      color: "blue",
      timeRange: { startSeconds: 42, endSeconds: 50, label: "Hook V01" },
      summary: "Good preserved hook candidate.",
      identityScore: 84,
      editScore: 76,
      renderScore: 72,
      keeperScore: 82,
      outcome: "runner-up",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "survivor-hook-v02",
      title: "Hook V02 Winner",
      versionId: "version-02",
      candidateKind: "hook",
      color: "blue",
      timeRange: { startSeconds: 44, endSeconds: 53, label: "Hook V02" },
      summary: "Strongest current hook survivor and best render candidate.",
      identityScore: 92,
      editScore: 88,
      renderScore: 84,
      keeperScore: 94,
      outcome: "winner",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "survivor-hook-v03",
      title: "Hook V03 Review",
      versionId: "version-03",
      candidateKind: "hook",
      color: "blue",
      timeRange: { startSeconds: 39, endSeconds: 48, label: "Hook V03" },
      summary: "Related hook but weaker rhythm confidence.",
      identityScore: 72,
      editScore: 68,
      renderScore: 62,
      keeperScore: 71,
      outcome: "review",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "survivor-bass-v05",
      title: "Bass Groove V05",
      versionId: "version-05",
      candidateKind: "bass-motion",
      color: "green",
      timeRange: { startSeconds: 16, endSeconds: 25, label: "Bass groove" },
      summary: "Strong support idea, not the main hook winner.",
      identityScore: 63,
      editScore: 78,
      renderScore: 74,
      keeperScore: 76,
      outcome: "support",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "survivor-vocal-v07",
      title: "Vocal Phrase V07",
      versionId: "version-07",
      candidateKind: "vocal-phrase",
      color: "purple",
      timeRange: { startSeconds: 58, endSeconds: 67, label: "Vocal phrase" },
      summary: "Possible phrase memory held for future lyric/phonetic analyzer.",
      identityScore: 54,
      editScore: 52,
      renderScore: 50,
      keeperScore: 59,
      outcome: "hold",
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  reasons: [
    {
      id: "reason-v02-identity",
      candidateId: "survivor-hook-v02",
      label: "Best identity match",
      detail: "V02 keeps the hook identity while making it stronger.",
      weight: 92,
      confidenceBucket: "strong",
    },
    {
      id: "reason-v02-edit",
      candidateId: "survivor-hook-v02",
      label: "Best edit window",
      detail: "V02 has the strongest seed edit window.",
      weight: 88,
      confidenceBucket: "strong",
    },
    {
      id: "reason-v02-render",
      candidateId: "survivor-hook-v02",
      label: "Best render target",
      detail: "V02 should become the first future WAV render target.",
      weight: 84,
      confidenceBucket: "strong",
    },
    {
      id: "reason-v01-preserve",
      candidateId: "survivor-hook-v01",
      label: "Preserved baseline",
      detail: "V01 remains useful as a comparison reference.",
      weight: 80,
      confidenceBucket: "strong",
    },
    {
      id: "reason-v03-review",
      candidateId: "survivor-hook-v03",
      label: "Needs rhythm review",
      detail: "V03 may still belong, but rhythm shift lowers confidence.",
      weight: 68,
      confidenceBucket: "moderate",
    },
    {
      id: "reason-bass-support",
      candidateId: "survivor-bass-v05",
      label: "Support groove",
      detail: "Bass V05 may support the winning hook in arrangement.",
      weight: 74,
      confidenceBucket: "moderate",
    },
  ],
  risks: [
    {
      id: "risk-survivor-waveform",
      riskKind: "missing-waveform",
      label: "Missing waveform evidence",
      detail: "Winner selection needs waveform and contour evidence later.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-survivor-conflict",
      riskKind: "conflicting-winner",
      label: "Conflicting winner",
      detail: "A future analyzer may promote a different version.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-survivor-review",
      riskKind: "manual-review",
      label: "Manual review",
      detail: "User ears should approve winner before extraction/render.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-survivor-future",
      riskKind: "future-analyzer",
      label: "Future analyzer required",
      detail: "Final winner confidence requires real DSP/analysis wiring.",
      severity: "high",
      isBlocking: false,
    },
  ],
  groups: [
    {
      id: "group-hook-survivors",
      title: "Hook Survivors",
      detail: "Main hook candidates ranked by identity, editability, render readiness, and keeper strength.",
      candidateIds: [
        "survivor-original-hook",
        "survivor-hook-v01",
        "survivor-hook-v02",
        "survivor-hook-v03",
      ],
      winnerCandidateId: "survivor-hook-v02",
      runnerUpCandidateId: "survivor-hook-v01",
      riskIds: ["risk-survivor-waveform", "risk-survivor-future"],
      color: "blue",
      readinessStatus: "ready",
    },
    {
      id: "group-support-survivors",
      title: "Support Survivors",
      detail: "Bass, groove, and arrangement support candidates.",
      candidateIds: ["survivor-bass-v05"],
      winnerCandidateId: "survivor-bass-v05",
      runnerUpCandidateId: null,
      riskIds: ["risk-survivor-review"],
      color: "green",
      readinessStatus: "needs-review",
    },
    {
      id: "group-vocal-survivors",
      title: "Vocal Survivors",
      detail: "Vocal phrase candidates held for future phonetic analyzer.",
      candidateIds: ["survivor-vocal-v07"],
      winnerCandidateId: null,
      runnerUpCandidateId: null,
      riskIds: ["risk-survivor-review", "risk-survivor-future"],
      color: "purple",
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "lane-survivor-winners",
      label: "Winners",
      detail: "Strongest candidates ready for future extraction.",
      color: "blue",
      candidateIds: ["survivor-hook-v02"],
      readinessStatus: "ready",
    },
    {
      id: "lane-survivor-runners",
      label: "Runner Ups",
      detail: "Useful comparison candidates.",
      color: "yellow",
      candidateIds: ["survivor-hook-v01"],
      readinessStatus: "ready",
    },
    {
      id: "lane-survivor-support",
      label: "Support",
      detail: "Ideas that support the winning hook.",
      color: "green",
      candidateIds: ["survivor-bass-v05"],
      readinessStatus: "needs-review",
    },
    {
      id: "lane-survivor-review",
      label: "Review",
      detail: "Candidates not ready for promotion.",
      color: "purple",
      candidateIds: ["survivor-hook-v03", "survivor-vocal-v07"],
      readinessStatus: "needs-review",
    },
  ],
};