import type {
  MultiTrackExtractionEngineCutWindow,
  MultiTrackExtractionEngineWorkspace,
} from "./MultiTrackExtractionEngineTypes";

export const multiTrackExtractionEngineCutWindows: MultiTrackExtractionEngineCutWindow[] = [
  {
    cutWindowId: "extract-v7-chorus-primary",
    title: "Extract V7 chorus hook",
    sourceCandidateId: "survivor-v7-chorus-hook",
    sourceKind: "survivor-candidate",
    role: "primary-hook",
    originalStartMs: 48000,
    originalEndMs: 61000,
    correctedStartMs: 47580,
    correctedEndMs: 61500,
    preRollMs: 420,
    postRollMs: 500,
    driftCorrectionMs: -420,
    confidence: 0.84,
    decision: "extract",
    status: "estimated",
    risk: "medium",
    boundaries: [
      {
        boundaryId: "v7-primary-start-anchor",
        kind: "drift-corrected",
        label: "Corrected hook start",
        timeMs: 47580,
        confidence: 0.82,
        detail:
          "Start moved earlier to compensate for known similarity/transient drift from the survivor lane.",
        status: "estimated",
        risk: "medium",
      },
      {
        boundaryId: "v7-primary-entry-transient",
        kind: "transient-anchor",
        label: "Main transient entry",
        timeMs: 48000,
        confidence: 0.92,
        detail:
          "Strong downbeat/transient cluster from the V7 chorus candidate.",
        status: "estimated",
        risk: "low",
      },
      {
        boundaryId: "v7-primary-end-tail",
        kind: "manual-safe-margin",
        label: "Safe tail boundary",
        timeMs: 61500,
        confidence: 0.74,
        detail:
          "Tail includes a small safety margin so the phrase does not clip early.",
        status: "seeded",
        risk: "medium",
      },
    ],
    notes: [
      "Primary extraction target from survivor engine.",
      "Needs listening review because drift correction is still estimated.",
      "Should feed keeper selection before render preparation.",
    ],
  },
  {
    cutWindowId: "extract-v7-final-repeat",
    title: "Extract V7 final hook repeat",
    sourceCandidateId: "survivor-v7-final-hook",
    sourceKind: "survivor-candidate",
    role: "supporting-repeat",
    originalStartMs: 182400,
    originalEndMs: 194000,
    correctedStartMs: 182120,
    correctedEndMs: 194450,
    preRollMs: 280,
    postRollMs: 450,
    driftCorrectionMs: -280,
    confidence: 0.69,
    decision: "hold",
    status: "seeded",
    risk: "medium",
    boundaries: [
      {
        boundaryId: "v7-repeat-start",
        kind: "drift-corrected",
        label: "Corrected repeat start",
        timeMs: 182120,
        confidence: 0.7,
        detail:
          "Start adjusted for smaller drift than the main chorus hook.",
        status: "seeded",
        risk: "medium",
      },
      {
        boundaryId: "v7-repeat-end",
        kind: "manual-safe-margin",
        label: "Repeat safe tail",
        timeMs: 194450,
        confidence: 0.66,
        detail:
          "Tail margin preserves the final hook decay for later arrangement review.",
        status: "seeded",
        risk: "medium",
      },
    ],
    notes: [
      "Supporting extraction lane.",
      "Hold until primary hook is confirmed.",
      "Can become arrangement repeat or alternate keeper material.",
    ],
  },
  {
    cutWindowId: "extract-v4-rough-reference",
    title: "Review V4 rough hook sketch",
    sourceCandidateId: "survivor-v4-hook-sketch",
    sourceKind: "survivor-candidate",
    role: "review-only",
    originalStartMs: 44000,
    originalEndMs: 57000,
    correctedStartMs: 43460,
    correctedEndMs: 57400,
    preRollMs: 540,
    postRollMs: 400,
    driftCorrectionMs: -540,
    confidence: 0.55,
    decision: "review",
    status: "seeded",
    risk: "medium",
    boundaries: [
      {
        boundaryId: "v4-review-start",
        kind: "drift-corrected",
        label: "Rough hook start",
        timeMs: 43460,
        confidence: 0.58,
        detail:
          "Large drift correction makes this a review lane rather than immediate extraction.",
        status: "seeded",
        risk: "medium",
      },
      {
        boundaryId: "v4-review-end",
        kind: "manual-safe-margin",
        label: "Rough hook tail",
        timeMs: 57400,
        confidence: 0.52,
        detail:
          "Tail is intentionally loose for manual review.",
        status: "seeded",
        risk: "medium",
      },
    ],
    notes: [
      "Use only as mutation history or reference material.",
      "Do not send directly to render preparation.",
      "Could help prompt generation later.",
    ],
  },
  {
    cutWindowId: "extract-v9-rejected-lane",
    title: "Block V9 weakened hook",
    sourceCandidateId: "survivor-v9-weakened-hook",
    sourceKind: "survivor-candidate",
    role: "review-only",
    originalStartMs: 52000,
    originalEndMs: 65000,
    correctedStartMs: 0,
    correctedEndMs: 0,
    preRollMs: 0,
    postRollMs: 0,
    driftCorrectionMs: 0,
    confidence: 0.29,
    decision: "reject",
    status: "seeded",
    risk: "high",
    boundaries: [
      {
        boundaryId: "v9-reject-boundary",
        kind: "unknown",
        label: "No safe extraction boundary",
        timeMs: 0,
        confidence: 0.18,
        detail:
          "Survivor engine rejected this lane. Extraction should not create cut points.",
        status: "seeded",
        risk: "high",
      },
    ],
    notes: [
      "Rejected from extraction.",
      "Useful only as negative training evidence.",
      "Do not allow into keeper selection.",
    ],
  },
];

export const multiTrackExtractionEngineWorkspace: MultiTrackExtractionEngineWorkspace = {
  workspaceId: "multi-track-extraction-engine",
  title: "Extraction Engine Foundation",
  summary:
    "Eighth real engine layer. Converts survivor winners into drift-corrected cut windows with safe margins, review gates, and extraction plans.",
  readiness: "needs-review",
  readinessLabel: "Seeded extraction plans are ready. Real survivor input and listening review come next.",
  engineGoal:
    "Turn promoted survivor candidates into safe extraction windows without cutting the hook too early or dragging weak lanes into render.",
  engineBoundary:
    "This layer plans cut windows. It does not pick the final keeper, build hybrids, or render audio.",
  cutWindows: multiTrackExtractionEngineCutWindows,
  plans: [
    {
      planId: "extract-plan-primary-hook",
      title: "Primary hook extraction plan",
      cutWindowIds: ["extract-v7-chorus-primary"],
      primaryCutWindowId: "extract-v7-chorus-primary",
      decision: "extract",
      extractionScore: 0.84,
      timingSafetyScore: 0.73,
      reviewScore: 0.78,
      detail:
        "The V7 chorus hook is the strongest extraction target but still needs drift-aware listening review.",
      recommendation:
        "Extract V7 chorus hook first, then send to keeper selection for approval.",
      status: "estimated",
      risk: "medium",
    },
    {
      planId: "extract-plan-support-repeat",
      title: "Supporting repeat extraction plan",
      cutWindowIds: ["extract-v7-final-repeat"],
      primaryCutWindowId: "extract-v7-final-repeat",
      decision: "hold",
      extractionScore: 0.66,
      timingSafetyScore: 0.69,
      reviewScore: 0.64,
      detail:
        "The final hook repeat can support arrangement but should not be first extraction.",
      recommendation:
        "Hold until primary hook is confirmed by keeper selection.",
      status: "seeded",
      risk: "medium",
    },
    {
      planId: "extract-plan-review-reference",
      title: "Review-only rough reference plan",
      cutWindowIds: ["extract-v4-rough-reference"],
      primaryCutWindowId: "extract-v4-rough-reference",
      decision: "review",
      extractionScore: 0.52,
      timingSafetyScore: 0.46,
      reviewScore: 0.57,
      detail:
        "V4 can be useful as a comparison lane but is not ready for clean extraction.",
      recommendation:
        "Keep in review only and block from render preparation.",
      status: "seeded",
      risk: "medium",
    },
  ],
  reviewGates: [
    {
      gateId: "gate-primary-survivor",
      title: "Primary survivor exists",
      detail:
        "At least one candidate must be promoted by survivor engine before extraction can continue.",
      pass: true,
      action: "Continue with promoted V7 chorus hook.",
      status: "estimated",
      risk: "low",
    },
    {
      gateId: "gate-drift-correction",
      title: "Drift correction available",
      detail:
        "Primary extraction window must carry a drift correction value from similarity and mutation analysis.",
      pass: true,
      action: "Apply drift correction before final boundaries are reviewed.",
      status: "estimated",
      risk: "medium",
    },
    {
      gateId: "gate-reject-weak-lanes",
      title: "Weak lanes blocked",
      detail:
        "Rejected survivor lanes must not generate extraction plans.",
      pass: true,
      action: "Keep V9 blocked from extraction and render preparation.",
      status: "seeded",
      risk: "low",
    },
    {
      gateId: "gate-listening-review",
      title: "Listening review still needed",
      detail:
        "Seeded boundaries are not final until real playback review confirms cut safety.",
      pass: false,
      action: "Require manual or future automated listening review before render.",
      status: "future",
      risk: "medium",
    },
  ],
  findings: [
    {
      findingId: "extraction-finding-primary-ready",
      title: "Primary hook is extraction-ready with review",
      detail:
        "The V7 chorus hook has a usable drift-corrected window and clear survivor promotion.",
      action: "Send primary hook plan to keeper selection after listening review.",
      status: "estimated",
      risk: "medium",
    },
    {
      findingId: "extraction-finding-support-held",
      title: "Supporting repeat should stay held",
      detail:
        "The final hook repeat has value but should not replace the primary extraction.",
      action: "Hold repeat plan until keeper selection asks for supporting material.",
      status: "seeded",
      risk: "medium",
    },
    {
      findingId: "extraction-finding-weak-blocked",
      title: "Rejected lanes are blocked from extraction",
      detail:
        "V9 weakened hook does not create real cut points.",
      action: "Send weak lanes to training evidence only.",
      status: "seeded",
      risk: "high",
    },
  ],
  engineRules: [
    "Do not extract a lane that survivor engine rejected.",
    "Always carry drift correction into the cut window.",
    "Add pre-roll and post-roll safety before final review.",
    "Extraction plans are not keeper approvals.",
    "Listening review must happen before render execution.",
  ],
  nextSteps: [
    "Connect extraction windows to real survivor engine output.",
    "Add boundary builder from transient anchors and drift values.",
    "Add listening review status to each cut window.",
    "Send approved extraction plans to keeper selection engine.",
    "Block rejected lanes from render preparation.",
  ],
};
