import type { MultiTrackRenderQueueWorkspaceState } from "./MultiTrackRenderQueueTypes";

export const multiTrackRenderQueueSeed: MultiTrackRenderQueueWorkspaceState = {
  id: "multi-track-render-queue-workspace",
  title: "Render Queue",
  description:
    "Seed-safe queue for future WAV, MP3, clip-pack, stem-pack, and session output after musical ideas are identified and extraction plans are approved.",
  readinessStatus: "ready",
  activeJobId: "render-job-hook-v02-wav",
  guardrailNotes: [
    "No page wiring yet.",
    "No file writer is called here.",
    "No browser download is triggered here.",
    "No DSP render is executed here.",
    "Jobs are planning records only until the render engine is explicitly wired.",
  ],
  sources: [
    {
      id: "render-source-hook-v02",
      versionId: "version-02",
      title: "Hook Clip V02",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook window",
      },
      readinessStatus: "ready",
    },
    {
      id: "render-source-hook-v01",
      versionId: "version-01",
      title: "Hook Clip V01",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Baseline hook window",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "render-source-hook-v03",
      versionId: "version-03",
      title: "Hook Clip V03",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Review hook window",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "render-source-bass-v05",
      versionId: "version-05",
      title: "Bass Groove V05",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass groove",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "render-source-riff-v04",
      versionId: "version-04",
      title: "Riff Clip V04",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 21,
        endSeconds: 29,
        label: "Riff pocket",
      },
      readinessStatus: "needs-review",
    },
    {
      id: "render-source-vocal-v07",
      versionId: "version-07",
      title: "Vocal Phrase V07",
      fileLabel: "Waiting for extracted clip",
      bpm: null,
      keyLabel: null,
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      readinessStatus: "needs-review",
    },
  ],
  risks: [
    {
      id: "render-risk-no-engine",
      riskKind: "future-render-engine",
      label: "Future render engine required",
      detail: "Render queue cannot output files until real render wiring exists.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "render-risk-missing-extraction",
      riskKind: "missing-extraction",
      label: "Missing extraction",
      detail: "Source clips must be extracted before render jobs become real.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "render-risk-bad-tail",
      riskKind: "bad-tail",
      label: "Tail review",
      detail: "Hook and vocal clips need tail padding review before final output.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "render-risk-stem-bleed",
      riskKind: "stem-bleed",
      label: "Stem bleed risk",
      detail: "Stem-pack output needs separation confidence later.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "render-risk-manual-review",
      riskKind: "manual-review",
      label: "Manual review",
      detail: "User should approve final render candidates before export.",
      severity: "medium",
      isBlocking: false,
    },
  ],
  settings: [
    {
      id: "render-setting-wav-main",
      label: "Main WAV Render",
      detail: "Preferred musician-safe WAV output setting.",
      outputFormat: "wav",
      includeTail: true,
      tailMs: 250,
      normalizeOutput: true,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
    {
      id: "render-setting-mp3-preview",
      label: "MP3 Preview Render",
      detail: "Small preview render for quick listening later.",
      outputFormat: "mp3",
      includeTail: true,
      tailMs: 180,
      normalizeOutput: true,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
    {
      id: "render-setting-stem-pack",
      label: "Stem Pack Render",
      detail: "Future separated stem pack output.",
      outputFormat: "stem-pack",
      includeTail: true,
      tailMs: 300,
      normalizeOutput: false,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
    {
      id: "render-setting-clip-pack",
      label: "Clip Pack Render",
      detail: "Future batch of selected clips for arrangement testing.",
      outputFormat: "clip-pack",
      includeTail: true,
      tailMs: 220,
      normalizeOutput: true,
      preserveOriginalPitch: true,
      preserveOriginalTempo: true,
      readinessStatus: "future",
    },
  ],
  jobs: [
    {
      id: "render-job-hook-v02-wav",
      title: "Render Hook V02 WAV",
      jobKind: "hook-render",
      color: "blue",
      priority: "high",
      sourceIds: ["render-source-hook-v02"],
      settingId: "render-setting-wav-main",
      riskIds: [
        "render-risk-no-engine",
        "render-risk-missing-extraction",
        "render-risk-bad-tail",
      ],
      outputName: "hook-v02-main.wav",
      destinationLabel: "Future Hook Renders",
      confidenceBucket: "strong",
      readinessStatus: "future",
    },
    {
      id: "render-job-hook-v02-mp3",
      title: "Render Hook V02 MP3 Preview",
      jobKind: "hook-render",
      color: "blue",
      priority: "normal",
      sourceIds: ["render-source-hook-v02"],
      settingId: "render-setting-mp3-preview",
      riskIds: ["render-risk-no-engine", "render-risk-missing-extraction"],
      outputName: "hook-v02-preview.mp3",
      destinationLabel: "Future Preview Renders",
      confidenceBucket: "strong",
      readinessStatus: "future",
    },
    {
      id: "render-job-hook-pack",
      title: "Render Hook Comparison Pack",
      jobKind: "comparison-export",
      color: "blue",
      priority: "normal",
      sourceIds: [
        "render-source-hook-v01",
        "render-source-hook-v02",
        "render-source-hook-v03",
      ],
      settingId: "render-setting-clip-pack",
      riskIds: ["render-risk-no-engine", "render-risk-missing-extraction"],
      outputName: "hook-comparison-pack.zip",
      destinationLabel: "Future Comparison Packs",
      confidenceBucket: "moderate",
      readinessStatus: "future",
    },
    {
      id: "render-job-bass-v05-loop",
      title: "Render Bass V05 Loop",
      jobKind: "bass-loop-render",
      color: "green",
      priority: "normal",
      sourceIds: ["render-source-bass-v05"],
      settingId: "render-setting-wav-main",
      riskIds: [
        "render-risk-no-engine",
        "render-risk-missing-extraction",
        "render-risk-stem-bleed",
      ],
      outputName: "bass-v05-loop.wav",
      destinationLabel: "Future Groove Renders",
      confidenceBucket: "moderate",
      readinessStatus: "future",
    },
    {
      id: "render-job-riff-v04-loop",
      title: "Render Riff V04 Loop",
      jobKind: "riff-render",
      color: "orange",
      priority: "low",
      sourceIds: ["render-source-riff-v04"],
      settingId: "render-setting-wav-main",
      riskIds: ["render-risk-no-engine", "render-risk-manual-review"],
      outputName: "riff-v04-loop.wav",
      destinationLabel: "Future Riff Renders",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "render-job-vocal-v07-hold",
      title: "Hold Vocal V07 Render",
      jobKind: "vocal-phrase-render",
      color: "purple",
      priority: "hold",
      sourceIds: ["render-source-vocal-v07"],
      settingId: "render-setting-wav-main",
      riskIds: [
        "render-risk-no-engine",
        "render-risk-bad-tail",
        "render-risk-manual-review",
      ],
      outputName: "vocal-v07-held.wav",
      destinationLabel: "Future Vocal Review",
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
    {
      id: "render-job-hook-stem-pack",
      title: "Render Hook Stem Pack",
      jobKind: "stem-export",
      color: "blue",
      priority: "normal",
      sourceIds: ["render-source-hook-v02"],
      settingId: "render-setting-stem-pack",
      riskIds: [
        "render-risk-no-engine",
        "render-risk-missing-extraction",
        "render-risk-stem-bleed",
      ],
      outputName: "hook-v02-stem-pack.zip",
      destinationLabel: "Future Stem Packs",
      confidenceBucket: "moderate",
      readinessStatus: "future",
    },
  ],
  batches: [
    {
      id: "render-batch-hook-main",
      title: "Main Hook Render Batch",
      detail: "WAV, MP3 preview, and stem-pack targets for selected hook.",
      jobIds: [
        "render-job-hook-v02-wav",
        "render-job-hook-v02-mp3",
        "render-job-hook-stem-pack",
      ],
      outputFormat: "wav",
      readinessStatus: "future",
    },
    {
      id: "render-batch-comparison",
      title: "Hook Comparison Batch",
      detail: "Pack of hook candidates across versions.",
      jobIds: ["render-job-hook-pack"],
      outputFormat: "clip-pack",
      readinessStatus: "future",
    },
    {
      id: "render-batch-review",
      title: "Review Render Batch",
      detail: "Riff, vocal, and groove candidates that need review.",
      jobIds: [
        "render-job-bass-v05-loop",
        "render-job-riff-v04-loop",
        "render-job-vocal-v07-hold",
      ],
      outputFormat: "wav",
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "render-lane-hook",
      label: "Hook Renders",
      detail: "Primary hook output jobs.",
      color: "blue",
      jobIds: [
        "render-job-hook-v02-wav",
        "render-job-hook-v02-mp3",
        "render-job-hook-stem-pack",
      ],
      readinessStatus: "future",
    },
    {
      id: "render-lane-comparison",
      label: "Comparison Packs",
      detail: "Export packs for listening and picking winners.",
      color: "yellow",
      jobIds: ["render-job-hook-pack"],
      readinessStatus: "future",
    },
    {
      id: "render-lane-groove",
      label: "Groove Renders",
      detail: "Bass and riff loop output jobs.",
      color: "green",
      jobIds: ["render-job-bass-v05-loop", "render-job-riff-v04-loop"],
      readinessStatus: "needs-review",
    },
    {
      id: "render-lane-vocal",
      label: "Vocal Review",
      detail: "Vocal phrase output stays held until confidence improves.",
      color: "purple",
      jobIds: ["render-job-vocal-v07-hold"],
      readinessStatus: "needs-review",
    },
  ],
};