import type {
  MultiTrackSimilarityEngineSource,
  MultiTrackSimilarityEngineWorkspace,
} from "./MultiTrackSimilarityEngineTypes";

export const multiTrackSimilarityEngineSources: MultiTrackSimilarityEngineSource[] = [
  {
    sourceId: "similarity-track-a",
    title: "Track A original idea map",
    sourceKind: "track-a",
    fileLabel: "Original ad-lib / musician source",
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientsReady: true,
    similarityReady: true,
    regions: [
      {
        regionId: "track-a-region-hook",
        title: "Original hook phrase",
        sourceId: "similarity-track-a",
        startMs: 16000,
        endMs: 26000,
        energyScore: 0.58,
        transientScore: 0.81,
        timingScore: 0.74,
        structureScore: 0.69,
        confidence: 0.76,
        status: "estimated",
      },
      {
        regionId: "track-a-region-variation",
        title: "Original variation phrase",
        sourceId: "similarity-track-a",
        startMs: 42000,
        endMs: 77000,
        energyScore: 0.48,
        transientScore: 0.58,
        timingScore: 0.61,
        structureScore: 0.55,
        confidence: 0.56,
        status: "seeded",
      },
      {
        regionId: "track-a-region-intro",
        title: "Original intro phrase",
        sourceId: "similarity-track-a",
        startMs: 0,
        endMs: 16000,
        energyScore: 0.34,
        transientScore: 0.49,
        timingScore: 0.52,
        structureScore: 0.47,
        confidence: 0.45,
        status: "seeded",
      },
    ],
    features: [
      {
        featureId: "track-a-feature-energy",
        kind: "energy-shape",
        label: "Hook energy contour",
        sourceLabel: "Track A",
        score: 0.58,
        detail: "Original hook has a medium energy lift that should survive loudness normalization.",
        status: "estimated",
        risk: "low",
      },
      {
        featureId: "track-a-feature-anchor",
        kind: "transient-anchor",
        label: "Three anchor hits",
        sourceLabel: "Track A",
        score: 0.81,
        detail: "Transient engine found three clear anchor hits inside the original hook phrase.",
        status: "estimated",
        risk: "low",
      },
      {
        featureId: "track-a-feature-riff-entry",
        kind: "riff-entry",
        label: "Riff starts at hook entry",
        sourceLabel: "Track A",
        score: 0.76,
        detail: "Hook entry has enough strength to become the original reference region.",
        status: "estimated",
        risk: "low",
      },
    ],
    notes: [
      "Track A should be the anchor source for similarity comparisons.",
      "Similarity should use normalized energy, not raw loudness.",
      "The original hook region is the first likely keeper reference.",
    ],
  },
  {
    sourceId: "similarity-suno-v7",
    title: "Suno Version 7 candidate map",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render with strong chorus",
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientsReady: true,
    similarityReady: true,
    regions: [
      {
        regionId: "suno-v7-region-chorus",
        title: "Suno V7 chorus hook",
        sourceId: "similarity-suno-v7",
        startMs: 48000,
        endMs: 61000,
        energyScore: 0.72,
        transientScore: 0.88,
        timingScore: 0.78,
        structureScore: 0.73,
        confidence: 0.82,
        status: "estimated",
      },
      {
        regionId: "suno-v7-region-bridge",
        title: "Suno V7 bridge lift",
        sourceId: "similarity-suno-v7",
        startMs: 124000,
        endMs: 132000,
        energyScore: 0.66,
        transientScore: 0.78,
        timingScore: 0.63,
        structureScore: 0.6,
        confidence: 0.67,
        status: "estimated",
      },
      {
        regionId: "suno-v7-region-final-hook",
        title: "Suno V7 final hook entry",
        sourceId: "similarity-suno-v7",
        startMs: 182400,
        endMs: 194000,
        energyScore: 0.7,
        transientScore: 0.79,
        timingScore: 0.7,
        structureScore: 0.68,
        confidence: 0.72,
        status: "seeded",
      },
    ],
    features: [
      {
        featureId: "suno-v7-feature-energy",
        kind: "energy-shape",
        label: "Dense chorus energy",
        sourceLabel: "Suno V7",
        score: 0.72,
        detail: "Chorus energy is stronger than Track A but must be normalized for loudness bias.",
        status: "estimated",
        risk: "medium",
      },
      {
        featureId: "suno-v7-feature-anchor",
        kind: "transient-anchor",
        label: "Four chorus anchors",
        sourceLabel: "Suno V7",
        score: 0.88,
        detail: "Chorus has strong transient anchors that may map to the original hook.",
        status: "estimated",
        risk: "low",
      },
      {
        featureId: "suno-v7-feature-drift",
        kind: "timing-drift",
        label: "Timing drift present",
        sourceLabel: "Suno V7",
        score: 0.58,
        detail: "Timing drift must be corrected before calling this the same riff.",
        status: "estimated",
        risk: "medium",
      },
    ],
    notes: [
      "Suno V7 has strong candidate regions but loudness bias is still present.",
      "Chorus and final hook both deserve survivor comparison.",
      "Bridge lift should remain a secondary candidate until riff grouping confirms it.",
    ],
  },
];

export const multiTrackSimilarityEngineWorkspace: MultiTrackSimilarityEngineWorkspace = {
  workspaceId: "multi-track-similarity-engine",
  title: "Similarity Engine Foundation",
  summary:
    "Fourth real engine layer. Compares original regions against Suno candidate regions using normalized energy, transient anchors, timing drift, and structure clues.",
  readiness: "needs-review",
  readinessLabel: "Seeded similarity pass is ready. Real transient/statistics input is next.",
  engineGoal:
    "Identify which Suno regions are actually related to the original hook or riff before survivor ranking.",
  engineBoundary:
    "This layer finds related regions. It does not pick the final keeper or build the extraction plan.",
  sources: multiTrackSimilarityEngineSources,
  matches: [
    {
      matchId: "match-track-a-hook-to-suno-v7-chorus",
      title: "Original hook vs Suno V7 chorus",
      originalRegionId: "track-a-region-hook",
      candidateRegionId: "suno-v7-region-chorus",
      overallScore: 0.78,
      matchStrength: "strong",
      timingDriftMs: 420,
      energyDifference: 0.14,
      transientOverlap: 0.74,
      detail:
        "Strong similarity candidate. Energy and anchor shape line up, but timing drift needs correction.",
      recommendation:
        "Send to riff grouping and survivor analysis as a strong candidate, not a final keeper yet.",
      status: "estimated",
      risk: "medium",
    },
    {
      matchId: "match-track-a-hook-to-suno-v7-final",
      title: "Original hook vs Suno V7 final hook",
      originalRegionId: "track-a-region-hook",
      candidateRegionId: "suno-v7-region-final-hook",
      overallScore: 0.69,
      matchStrength: "moderate",
      timingDriftMs: 280,
      energyDifference: 0.12,
      transientOverlap: 0.63,
      detail:
        "Moderate similarity. Final hook may be a later mutation of the original idea.",
      recommendation:
        "Keep as a secondary survivor candidate until mutation mapping runs.",
      status: "seeded",
      risk: "medium",
    },
    {
      matchId: "match-track-a-variation-to-suno-v7-bridge",
      title: "Original variation vs Suno V7 bridge",
      originalRegionId: "track-a-region-variation",
      candidateRegionId: "suno-v7-region-bridge",
      overallScore: 0.54,
      matchStrength: "weak",
      timingDriftMs: 680,
      energyDifference: 0.18,
      transientOverlap: 0.42,
      detail:
        "Weak relationship. Bridge may share energy behavior but not enough transient evidence.",
      recommendation:
        "Do not promote to survivor until pattern genome confirms stronger evidence.",
      status: "seeded",
      risk: "high",
    },
  ],
  findings: [
    {
      findingId: "similarity-finding-main-candidate",
      title: "Suno V7 chorus is the best current match",
      detail:
        "The chorus region has the strongest overall similarity score against the original hook region.",
      action: "Send this match to riff grouping, mutation map, and survivor analysis.",
      status: "estimated",
      risk: "medium",
    },
    {
      findingId: "similarity-finding-drift",
      title: "Timing drift must be corrected",
      detail:
        "The best match still has 420ms of timing drift, which can mislead extraction and render decisions.",
      action: "Carry timing drift forward into riff grouping and extraction plan.",
      status: "estimated",
      risk: "medium",
    },
  ],
  engineRules: [
    "Do not compare raw loudness without normalization.",
    "Do not call a region a keeper from similarity alone.",
    "Timing drift must travel with every match.",
    "Weak matches can stay in the tree but should not drive render decisions.",
    "Similarity feeds survivor analysis; it does not replace survivor analysis.",
  ],
  nextSteps: [
    "Connect similarity input to transient clusters.",
    "Normalize energy scores using statistics engine output.",
    "Add timing drift correction helpers.",
    "Send strong matches to riff grouping engine.",
    "Send match evidence to survivor analysis.",
  ],
};