import type { MultiTrackMutationMapWorkspaceState } from "./MultiTrackMutationMapTypes";

export const multiTrackMutationMapSeed: MultiTrackMutationMapWorkspaceState = {
  id: "multi-track-mutation-map-workspace",
  title: "Mutation Map",
  description:
    "Seed-safe mutation map for showing how one musical idea changes across Suno versions before extraction, edit, duplicate, or render wiring.",
  readinessStatus: "ready",
  activePathId: "path-main-hook-mutations",
  activePointId: "point-hook-v02-expanded",
  guardrailNotes: [
    "No page wiring yet.",
    "No waveform analyzer is called here.",
    "No mutation is final until real audio evidence confirms it.",
    "Keeper scores are seed planning values only.",
  ],
  points: [
    {
      id: "point-original-hook",
      title: "Original Hook",
      versionId: "original",
      ideaKind: "hook",
      mutationKind: "preserved",
      color: "blue",
      timeRange: { startSeconds: 0, endSeconds: 8, label: "Original idea" },
      summary: "User-origin hook idea before generation.",
      mutationStrength: 0,
      keeperScore: 95,
      parentPointId: null,
      confidenceBucket: "verified",
      readinessStatus: "ready",
    },
    {
      id: "point-hook-v01-preserved",
      title: "Hook V01 Preserved",
      versionId: "version-01",
      ideaKind: "hook",
      mutationKind: "preserved",
      color: "blue",
      timeRange: { startSeconds: 42, endSeconds: 50, label: "Hook V01" },
      summary: "Version 01 keeps the original hook shape.",
      mutationStrength: 18,
      keeperScore: 82,
      parentPointId: "point-original-hook",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "point-hook-v02-expanded",
      title: "Hook V02 Expanded",
      versionId: "version-02",
      ideaKind: "hook",
      mutationKind: "expanded",
      color: "blue",
      timeRange: { startSeconds: 44, endSeconds: 53, label: "Hook V02" },
      summary: "Version 02 expands the hook and becomes the strongest keeper.",
      mutationStrength: 34,
      keeperScore: 92,
      parentPointId: "point-original-hook",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "point-hook-v03-rhythm",
      title: "Hook V03 Rhythm Shift",
      versionId: "version-03",
      ideaKind: "hook",
      mutationKind: "rhythm-shifted",
      color: "blue",
      timeRange: { startSeconds: 39, endSeconds: 48, label: "Hook V03" },
      summary: "Version 03 keeps the hook family but shifts rhythm.",
      mutationStrength: 47,
      keeperScore: 71,
      parentPointId: "point-original-hook",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "point-hook-v08-key",
      title: "Hook V08 Key Shift",
      versionId: "version-08",
      ideaKind: "hook",
      mutationKind: "key-shifted",
      color: "blue",
      timeRange: { startSeconds: 47, endSeconds: 56, label: "Hook V08" },
      summary: "Version 08 may descend from V02 with a key shift.",
      mutationStrength: 55,
      keeperScore: 68,
      parentPointId: "point-hook-v02-expanded",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "point-bass-v05-instrument",
      title: "Bass V05 Instrument Shift",
      versionId: "version-05",
      ideaKind: "bass-motion",
      mutationKind: "instrument-shifted",
      color: "green",
      timeRange: { startSeconds: 16, endSeconds: 25, label: "Bass V05" },
      summary: "Hook identity may appear as supporting bass motion.",
      mutationStrength: 62,
      keeperScore: 74,
      parentPointId: "point-hook-v02-expanded",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "point-vocal-v07-lyric",
      title: "Vocal V07 Lyric Shift",
      versionId: "version-07",
      ideaKind: "vocal-phrase",
      mutationKind: "lyric-shifted",
      color: "purple",
      timeRange: { startSeconds: 58, endSeconds: 67, label: "Vocal V07" },
      summary: "Possible lyric or phonetic memory of the original idea.",
      mutationStrength: 70,
      keeperScore: 59,
      parentPointId: "point-original-hook",
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  signals: [
    {
      id: "signal-original-memory",
      pointId: "point-original-hook",
      label: "Original memory",
      detail: "Manual user source.",
      value: 100,
      confidenceBucket: "verified",
    },
    {
      id: "signal-v01-shape",
      pointId: "point-hook-v01-preserved",
      label: "Shape preserved",
      detail: "Hook contour remains close.",
      value: 84,
      confidenceBucket: "strong",
    },
    {
      id: "signal-v02-keeper",
      pointId: "point-hook-v02-expanded",
      label: "Keeper strength",
      detail: "Best balance of identity and expanded hook power.",
      value: 92,
      confidenceBucket: "strong",
    },
    {
      id: "signal-v03-rhythm",
      pointId: "point-hook-v03-rhythm",
      label: "Rhythm shift",
      detail: "Related hook with changed rhythmic shape.",
      value: 71,
      confidenceBucket: "moderate",
    },
    {
      id: "signal-v08-key",
      pointId: "point-hook-v08-key",
      label: "Key shift",
      detail: "Possible key-shifted descendant.",
      value: 67,
      confidenceBucket: "moderate",
    },
    {
      id: "signal-v05-support",
      pointId: "point-bass-v05-instrument",
      label: "Support mutation",
      detail: "Musical idea may have moved into bass support.",
      value: 64,
      confidenceBucket: "moderate",
    },
    {
      id: "signal-v07-phrase",
      pointId: "point-vocal-v07-lyric",
      label: "Phrase memory",
      detail: "Needs future phonetic analyzer.",
      value: 54,
      confidenceBucket: "weak",
    },
  ],
  risks: [
    {
      id: "risk-mutation-waveform",
      riskKind: "missing-waveform",
      label: "Missing waveform evidence",
      detail: "Mutation claims need waveform and contour evidence later.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-mutation-conflict",
      riskKind: "conflicting-mutation",
      label: "Conflicting mutation",
      detail: "A point may belong to multiple paths until scoring improves.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-mutation-analyzer",
      riskKind: "future-analyzer",
      label: "Future analyzer required",
      detail: "Real mutation labels need melody/rhythm/key analyzers.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-mutation-review",
      riskKind: "manual-review",
      label: "Manual review",
      detail: "User ears should approve keeper mutation path.",
      severity: "medium",
      isBlocking: false,
    },
  ],
  paths: [
    {
      id: "path-main-hook-mutations",
      title: "Main Hook Mutation Path",
      detail: "Original hook through preserved, expanded, rhythm-shifted, and key-shifted descendants.",
      pointIds: [
        "point-original-hook",
        "point-hook-v01-preserved",
        "point-hook-v02-expanded",
        "point-hook-v03-rhythm",
        "point-hook-v08-key",
      ],
      strongestPointId: "point-hook-v02-expanded",
      color: "blue",
      riskIds: ["risk-mutation-waveform", "risk-mutation-analyzer"],
      readinessStatus: "ready",
    },
    {
      id: "path-support-mutations",
      title: "Support Mutation Path",
      detail: "Ideas that moved into bass, groove, or support roles.",
      pointIds: ["point-bass-v05-instrument"],
      strongestPointId: "point-bass-v05-instrument",
      color: "green",
      riskIds: ["risk-mutation-review"],
      readinessStatus: "needs-review",
    },
    {
      id: "path-vocal-mutations",
      title: "Vocal Mutation Path",
      detail: "Lyric or phonetic descendants waiting for future analysis.",
      pointIds: ["point-vocal-v07-lyric"],
      strongestPointId: null,
      color: "purple",
      riskIds: ["risk-mutation-review", "risk-mutation-analyzer"],
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "lane-mutation-keepers",
      label: "Keeper Mutations",
      detail: "Mutation paths with a strong survivor.",
      color: "blue",
      pathIds: ["path-main-hook-mutations"],
      readinessStatus: "ready",
    },
    {
      id: "lane-mutation-support",
      label: "Support Mutations",
      detail: "Mutations that support the main idea.",
      color: "green",
      pathIds: ["path-support-mutations"],
      readinessStatus: "needs-review",
    },
    {
      id: "lane-mutation-review",
      label: "Review Mutations",
      detail: "Mutation paths that need more confidence.",
      color: "yellow",
      pathIds: ["path-vocal-mutations"],
      readinessStatus: "needs-review",
    },
  ],
};