import type { MultiTrackEditDecisionWorkspaceState } from "./MultiTrackEditDecisionTypes";

export const multiTrackEditDecisionSeed: MultiTrackEditDecisionWorkspaceState = {
  id: "multi-track-edit-decision-workspace",
  title: "Edit Decision",
  description:
    "Seed-safe decision layer for choosing which matched musical ideas should be kept, edited, duplicated, rendered, held, or rejected.",
  readinessStatus: "ready",
  activeDecisionId: "decision-hook-v02-keep",
  guardrailNotes: [
    "No page wiring yet.",
    "No audio is modified here.",
    "No render job is started here.",
    "Every decision remains reviewable before destructive editing.",
  ],
  candidates: [
    {
      id: "candidate-hook-v02",
      title: "Hook Candidate V02",
      versionId: "version-02",
      targetKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook window",
      },
      summary: "Strongest hook candidate for future edit and render.",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "candidate-hook-v03",
      title: "Hook Candidate V03",
      versionId: "version-03",
      targetKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Review hook window",
      },
      summary: "Related hook candidate that needs more review.",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-bass-v05",
      title: "Bass Groove V05",
      versionId: "version-05",
      targetKind: "bass-groove",
      color: "green",
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass groove",
      },
      summary: "Bass groove candidate for future loop testing.",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-riff-v04",
      title: "Riff Candidate V04",
      versionId: "version-04",
      targetKind: "riff",
      color: "orange",
      timeRange: {
        startSeconds: 21,
        endSeconds: 29,
        label: "Riff pocket",
      },
      summary: "Riff candidate for later arrangement tests.",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-vocal-v07",
      title: "Vocal Phrase V07",
      versionId: "version-07",
      targetKind: "vocal-phrase",
      color: "purple",
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      summary: "Vocal phrase held until phonetic matching exists.",
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  scores: [
    {
      id: "score-hook-v02-identity",
      candidateId: "candidate-hook-v02",
      label: "Identity match",
      detail: "Strongest match to the repeated hook idea.",
      value: 91,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v02-edit",
      candidateId: "candidate-hook-v02",
      label: "Editability",
      detail: "Cleanest seed window for trimming.",
      value: 84,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v03-identity",
      candidateId: "candidate-hook-v03",
      label: "Identity match",
      detail: "Related but weaker than V02.",
      value: 72,
      confidenceBucket: "moderate",
    },
    {
      id: "score-bass-v05-groove",
      candidateId: "candidate-bass-v05",
      label: "Groove strength",
      detail: "Good pocket candidate for future loop testing.",
      value: 78,
      confidenceBucket: "moderate",
    },
    {
      id: "score-riff-v04-rhythm",
      candidateId: "candidate-riff-v04",
      label: "Rhythm strength",
      detail: "Possible riff phrase for arrangement tests.",
      value: 70,
      confidenceBucket: "moderate",
    },
    {
      id: "score-vocal-v07-keeper",
      candidateId: "candidate-vocal-v07",
      label: "Keeper phrase",
      detail: "Manual keeper candidate until lyric analyzer exists.",
      value: 61,
      confidenceBucket: "weak",
    },
  ],
  risks: [
    {
      id: "risk-missing-extraction",
      riskKind: "missing-extraction",
      label: "Missing extraction",
      detail: "No real extracted clip exists yet.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-tail",
      riskKind: "tail-risk",
      label: "Tail risk",
      detail: "Clip tail may need padding before render.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-stem-bleed",
      riskKind: "stem-bleed",
      label: "Stem bleed",
      detail: "Stem-safe edit needs future separation confidence.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-manual-review",
      riskKind: "manual-review",
      label: "Manual review",
      detail: "Needs user confirmation before promotion.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-future-engine",
      riskKind: "future-engine",
      label: "Future engine",
      detail: "Editing, duplication, and rendering need future engine wiring.",
      severity: "high",
      isBlocking: false,
    },
  ],
  decisions: [
    {
      id: "decision-hook-v02-keep",
      candidateId: "candidate-hook-v02",
      choice: "keep",
      label: "Keep Hook V02",
      detail: "Promote Hook V02 as the strongest matched hook.",
      reason: "Best identity score and cleanest edit window.",
      riskIds: ["risk-missing-extraction", "risk-tail", "risk-future-engine"],
      readinessStatus: "ready",
    },
    {
      id: "decision-hook-v02-duplicate",
      candidateId: "candidate-hook-v02",
      choice: "duplicate",
      label: "Duplicate Hook V02",
      detail: "Future duplicate into an edit lane for arrangement testing.",
      reason: "Strong enough to become a repeated arrangement part.",
      riskIds: ["risk-missing-extraction", "risk-future-engine"],
      readinessStatus: "future",
    },
    {
      id: "decision-hook-v03-hold",
      candidateId: "candidate-hook-v03",
      choice: "hold",
      label: "Hold Hook V03",
      detail: "Keep in review queue until confidence improves.",
      reason: "Related hook, but weaker than V02.",
      riskIds: ["risk-manual-review"],
      readinessStatus: "needs-review",
    },
    {
      id: "decision-bass-v05-edit",
      candidateId: "candidate-bass-v05",
      choice: "edit",
      label: "Edit Bass V05",
      detail: "Future trim and duplicate bass groove for loop tests.",
      reason: "Good groove candidate, but stem-safe review is needed.",
      riskIds: ["risk-stem-bleed", "risk-future-engine"],
      readinessStatus: "future",
    },
    {
      id: "decision-riff-v04-hold",
      candidateId: "candidate-riff-v04",
      choice: "hold",
      label: "Hold Riff V04",
      detail: "Needs comparison against stronger riff candidates.",
      reason: "Moderate rhythm score only.",
      riskIds: ["risk-manual-review"],
      readinessStatus: "needs-review",
    },
    {
      id: "decision-vocal-v07-hold",
      candidateId: "candidate-vocal-v07",
      choice: "hold",
      label: "Hold Vocal V07",
      detail: "Wait for phonetic and lyric confidence before extraction.",
      reason: "Vocal phrase may be important, but confidence is weak.",
      riskIds: ["risk-manual-review", "risk-tail"],
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "lane-keep",
      label: "Keep",
      detail: "Decisions promoted as strongest material.",
      color: "blue",
      decisionIds: ["decision-hook-v02-keep"],
      readinessStatus: "ready",
    },
    {
      id: "lane-edit",
      label: "Edit / Duplicate",
      detail: "Future edit-lane decisions.",
      color: "green",
      decisionIds: ["decision-hook-v02-duplicate", "decision-bass-v05-edit"],
      readinessStatus: "future",
    },
    {
      id: "lane-review",
      label: "Review",
      detail: "Held decisions that need user or analyzer confirmation.",
      color: "yellow",
      decisionIds: [
        "decision-hook-v03-hold",
        "decision-riff-v04-hold",
        "decision-vocal-v07-hold",
      ],
      readinessStatus: "needs-review",
    },
  ],
};