import type {
  MultiTrackRiffExperimentPlan,
  MultiTrackRiffExtractPlan,
  MultiTrackRiffGroup,
  MultiTrackRiffGroupWorkspaceState,
  MultiTrackRiffEditPlan,
  MultiTrackRiffInstance,
  MultiTrackRiffSourceTrack,
} from "./MultiTrackRiffGroupTypes";

export const MULTI_TRACK_RIFF_GROUP_SOURCE_TRACKS: MultiTrackRiffSourceTrack[] = [
  {
    id: "suno-version-01",
    label: "Track 01",
    sunoVersionLabel: "Suno Version 01",
    sourceTrackNumber: 1,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: true,
  },
  {
    id: "suno-version-02",
    label: "Track 02",
    sunoVersionLabel: "Suno Version 02",
    sourceTrackNumber: 2,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 97,
    targetBpm: 96,
    normalized: true,
  },
  {
    id: "suno-version-03",
    label: "Track 03",
    sunoVersionLabel: "Suno Version 03",
    sourceTrackNumber: 3,
    originalKey: "D minor",
    targetKey: "C minor",
    originalBpm: 95,
    targetBpm: 96,
    normalized: false,
  },
  {
    id: "suno-version-04",
    label: "Track 04",
    sunoVersionLabel: "Suno Version 04",
    sourceTrackNumber: 4,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: true,
  },
  {
    id: "suno-version-05",
    label: "Track 05",
    sunoVersionLabel: "Suno Version 05",
    sourceTrackNumber: 5,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 98,
    targetBpm: 96,
    normalized: false,
  },
  {
    id: "suno-version-06",
    label: "Track 06",
    sunoVersionLabel: "Suno Version 06",
    sourceTrackNumber: 6,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: true,
  },
  {
    id: "suno-version-07",
    label: "Track 07",
    sunoVersionLabel: "Suno Version 07",
    sourceTrackNumber: 7,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 94,
    targetBpm: 96,
    normalized: false,
  },
  {
    id: "suno-version-08",
    label: "Track 08",
    sunoVersionLabel: "Suno Version 08",
    sourceTrackNumber: 8,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: true,
  },
  {
    id: "suno-version-09",
    label: "Track 09",
    sunoVersionLabel: "Suno Version 09",
    sourceTrackNumber: 9,
    originalKey: "B minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: false,
  },
  {
    id: "suno-version-10",
    label: "Track 10",
    sunoVersionLabel: "Suno Version 10",
    sourceTrackNumber: 10,
    originalKey: "C minor",
    targetKey: "C minor",
    originalBpm: 96,
    targetBpm: 96,
    normalized: true,
  },
];

function makeRiffInstance(
  id: string,
  riffGroupId: string,
  sourceTrackId: string,
  sourceTrackLabel: string,
  startSeconds: number,
  endSeconds: number,
  similarityPercent: number,
  noteMatchPercent: number,
  rhythmMatchPercent: number,
  timingDriftSeconds: number,
  notes: string,
): MultiTrackRiffInstance {
  return {
    id,
    riffGroupId,
    sourceTrackId,
    sourceTrackLabel,
    source: "user-marked",
    color: riffGroupId === "riff-group-blue-hook" ? "blue" : "purple",
    status: similarityPercent >= 90 ? "ready" : "needs-review",
    timeRange: {
      startSeconds,
      endSeconds,
      durationSeconds: Number((endSeconds - startSeconds).toFixed(2)),
      startLabel: `${startSeconds.toFixed(1)}s`,
      endLabel: `${endSeconds.toFixed(1)}s`,
    },
    similarityPercent,
    noteMatchPercent,
    rhythmMatchPercent,
    timingDriftSeconds,
    pitchDriftSemitones: 0,
    matchReasons: [
      "same-hook-memory",
      "same-melodic-shape",
      "same-rhythm-shape",
      "manual-family",
    ],
    risks:
      similarityPercent >= 90
        ? ["timing-drift", "needs-listening"]
        : ["note-difference", "timing-drift", "needs-listening"],
    notes,
  };
}

export const MULTI_TRACK_RIFF_GROUPS: MultiTrackRiffGroup[] = [
  {
    id: "riff-group-blue-hook",
    label: "Blue Hook Riff Family",
    color: "blue",
    status: "manual",
    source: "user-marked",
    targetKey: "C minor",
    targetBpm: 96,
    familyConfidencePercent: 92,
    minimumSimilarityPercent: 90,
    description:
      "Main repeated hook idea across the Suno versions. Timing can drift, and one note can change, but the musical memory belongs together.",
    instances: [
      makeRiffInstance(
        "blue-hook-track-01",
        "riff-group-blue-hook",
        "suno-version-01",
        "Track 01",
        42.1,
        46.8,
        94,
        92,
        91,
        0,
        "Reference version for the blue hook family.",
      ),
      makeRiffInstance(
        "blue-hook-track-02",
        "riff-group-blue-hook",
        "suno-version-02",
        "Track 02",
        42.4,
        47,
        91,
        90,
        88,
        0.3,
        "Same idea, slightly late and rhythm bends near the ending.",
      ),
      makeRiffInstance(
        "blue-hook-track-04",
        "riff-group-blue-hook",
        "suno-version-04",
        "Track 04",
        41.9,
        46.5,
        96,
        94,
        93,
        -0.2,
        "Strongest match and probably a keeper candidate.",
      ),
      makeRiffInstance(
        "blue-hook-track-07",
        "riff-group-blue-hook",
        "suno-version-07",
        "Track 07",
        43,
        47.4,
        89,
        86,
        90,
        0.9,
        "Borderline version: same memory, but notes need listening review.",
      ),
    ],
  },
  {
    id: "riff-group-purple-response",
    label: "Purple Response Riff Family",
    color: "purple",
    status: "manual",
    source: "user-marked",
    targetKey: "C minor",
    targetBpm: 96,
    familyConfidencePercent: 88,
    minimumSimilarityPercent: 90,
    description:
      "Answer phrase after the hook. Not all versions contain it, but it is useful for extraction and experiment lanes.",
    instances: [
      makeRiffInstance(
        "purple-response-track-03",
        "riff-group-purple-response",
        "suno-version-03",
        "Track 03",
        58.2,
        61.9,
        90,
        89,
        92,
        0,
        "Response phrase candidate from version 03.",
      ),
      makeRiffInstance(
        "purple-response-track-05",
        "riff-group-purple-response",
        "suno-version-05",
        "Track 05",
        58.7,
        62.5,
        87,
        84,
        90,
        0.5,
        "Close rhythm but note confidence needs review.",
      ),
      makeRiffInstance(
        "purple-response-track-10",
        "riff-group-purple-response",
        "suno-version-10",
        "Track 10",
        57.9,
        61.6,
        91,
        90,
        91,
        -0.3,
        "Clean response phrase and good extraction candidate.",
      ),
    ],
  },
];

export const MULTI_TRACK_RIFF_EXTRACT_PLANS: MultiTrackRiffExtractPlan[] = [
  {
    id: "extract-blue-hook-family",
    riffGroupId: "riff-group-blue-hook",
    label: "Extract Blue Hook To Lane",
    laneMode: "riff-family-lane",
    destinationLaneLabel: "Blue Hook Riff Lane",
    includeCount: 4,
    readyCount: 3,
    reviewCount: 1,
    detail:
      "Drop all blue hook clips from the 10 source tracks into one dedicated riff-family lane.",
  },
  {
    id: "extract-purple-response-family",
    riffGroupId: "riff-group-purple-response",
    label: "Extract Purple Response To Lane",
    laneMode: "riff-family-lane",
    destinationLaneLabel: "Purple Response Riff Lane",
    includeCount: 3,
    readyCount: 2,
    reviewCount: 1,
    detail:
      "Drop purple response clips into their own lane for edit and arrangement comparison.",
  },
];

export const MULTI_TRACK_RIFF_EDIT_PLANS: MultiTrackRiffEditPlan[] = [
  {
    id: "edit-blue-hook-group",
    riffGroupId: "riff-group-blue-hook",
    label: "Edit Blue Hook As Group",
    editMode: "group",
    selectedInstanceIds: [
      "blue-hook-track-01",
      "blue-hook-track-02",
      "blue-hook-track-04",
    ],
    editableFields: ["trim", "nudge", "gain", "pitch", "stretch", "mute"],
    microEditStepSeconds: 0.1,
    detail:
      "Group edit the strongest blue hook matches while leaving the borderline version in review.",
  },
  {
    id: "edit-purple-selected",
    riffGroupId: "riff-group-purple-response",
    label: "Edit Selected Purple Responses",
    editMode: "selected",
    selectedInstanceIds: ["purple-response-track-03", "purple-response-track-10"],
    editableFields: ["trim", "nudge", "gain", "stretch"],
    microEditStepSeconds: 0.1,
    detail:
      "Edit the two best purple response clips together for timing and level.",
  },
];

export const MULTI_TRACK_RIFF_EXPERIMENT_PLANS: MultiTrackRiffExperimentPlan[] = [
  {
    id: "experiment-blue-hook-track-04",
    riffGroupId: "riff-group-blue-hook",
    sourceInstanceId: "blue-hook-track-04",
    label: "Duplicate Best Blue Hook 10 Times",
    duplicateCount: 10,
    destinationLanePrefix: "Blue Hook Experiment",
    knobTargets: [
      "pitch",
      "timing",
      "gain",
      "stretch",
      "reverse-later",
      "filter-later",
      "texture-later",
    ],
    detail:
      "Take the strongest blue hook and create ten experiment lanes for knob turning and keeper selection.",
  },
];

export const DEFAULT_MULTI_TRACK_RIFF_GROUP_WORKSPACE_STATE: MultiTrackRiffGroupWorkspaceState = {
  id: "multi-track-riff-group-workspace",
  label: "Multi Track Riff Group Engine",
  summary:
    "Monster-engine foundation for 10 Suno versions, shared riff families, color groups, extraction lanes, micro edits, and duplicate experiment lanes.",
  targetTrackCount: 10,
  loadedTrackCount: 0,
  targetKey: "C minor",
  targetBpm: 96,
  microEditStepSeconds: 0.1,
  groups: MULTI_TRACK_RIFF_GROUPS,
  extractPlans: MULTI_TRACK_RIFF_EXTRACT_PLANS,
  editPlans: MULTI_TRACK_RIFF_EDIT_PLANS,
  experimentPlans: MULTI_TRACK_RIFF_EXPERIMENT_PLANS,
};