import type {
  MultiTrackAiPromptGuardrail,
  MultiTrackAiPromptInputRequirement,
  MultiTrackAiPromptOutputTarget,
  MultiTrackAiPromptTemplate,
  MultiTrackAiPromptWorkflowStep,
  MultiTrackAiPromptWorkspaceState,
} from "./MultiTrackAiPromptWorkspaceTypes";

export const multiTrackAiPromptTemplates: MultiTrackAiPromptTemplate[] = [
  {
    id: "prompt-describe-track-a",
    category: "song-description",
    actionType: "describe",
    label: "Describe Track A",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    purpose: "Turn user-approved Track A notes into a safe song description.",
    templateText:
      "Describe Track A using only user-confirmed notes. Focus on mood, groove, hook, melody, arrangement role, and any known source purpose. Do not invent BPM, key, stems, or lineage.",
    requiredInputs: ["track-a", "manual-user-note"],
    userRule: "User must confirm Track A meaning before prompt export.",
  },
  {
    id: "prompt-describe-track-b",
    category: "song-description",
    actionType: "describe",
    label: "Describe Track B",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    purpose: "Turn user-approved Track B notes into a safe song description.",
    templateText:
      "Describe Track B using only user-confirmed notes. Focus on produced feel, hook strength, arrangement lift, chorus energy, and any known result purpose. Do not invent BPM, key, stems, or lineage.",
    requiredInputs: ["track-b", "manual-user-note"],
    userRule: "User must confirm Track B meaning before prompt export.",
  },
  {
    id: "prompt-compare-tracks",
    category: "lineage-question",
    actionType: "compare",
    label: "Compare Track A and Track B",
    status: "needs-review",
    confidence: "manual-required",
    owner: "manual-review",
    purpose: "Build a safe comparison prompt without claiming lineage.",
    templateText:
      "Compare Track A and Track B as musical references. Ask whether the hook, melody, rhythm, structure, and energy feel related. Do not claim one came from the other unless the user confirmed the source relationship.",
    requiredInputs: ["track-a", "track-b", "comparison", "confidence"],
    userRule: "Comparison prompt must avoid automatic lineage claims.",
  },
  {
    id: "prompt-hybrid-direction",
    category: "hybrid-instruction",
    actionType: "recommend",
    label: "Hybrid Direction Prompt",
    status: "future",
    confidence: "low",
    owner: "future-hybrid-builder",
    purpose: "Prepare future AI to suggest a hybrid direction after confirmation gates.",
    templateText:
      "Suggest a hybrid direction using the confirmed strongest parts of Track A and Track B. Respect confirmed hook ownership, tempo/key strategy, section plan, and user-approved confidence gates.",
    requiredInputs: ["hybrid", "comparison", "confidence", "manual-user-note"],
    userRule: "Hybrid prompt cannot be used until user confirms merge direction.",
  },
  {
    id: "prompt-arrangement-instruction",
    category: "arrangement-instruction",
    actionType: "structure",
    label: "Arrangement Instruction Prompt",
    status: "future",
    confidence: "low",
    owner: "future-analyzer",
    purpose: "Create arrangement instructions after section mapping exists.",
    templateText:
      "Write an arrangement instruction based on confirmed section roles. Include intro, verse, hook, chorus, bridge, breakdown, lift, outro, and transition notes only when confirmed.",
    requiredInputs: ["future-analysis", "manual-user-note"],
    userRule: "Do not invent section boundaries.",
  },
  {
    id: "prompt-stem-instruction",
    category: "stem-instruction",
    actionType: "structure",
    label: "Stem Instruction Prompt",
    status: "future",
    confidence: "low",
    owner: "future-analyzer",
    purpose: "Prepare safe stem instructions for future separated tracks.",
    templateText:
      "Write stem instructions using only confirmed stem labels. Identify drums, bass, vocal, melody, harmony, texture, and transitions only when evidence exists.",
    requiredInputs: ["future-analysis", "confidence"],
    userRule: "No automatic stem identity claims.",
  },
  {
    id: "prompt-hook-instruction",
    category: "hook-instruction",
    actionType: "recommend",
    label: "Hook Instruction Prompt",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    purpose: "Help the user decide how hooks should be treated.",
    templateText:
      "Ask the user whether the strongest hook should be kept, replaced, blended, repeated, moved, or turned into call-and-response.",
    requiredInputs: ["track-a", "track-b", "manual-user-note"],
    userRule: "Hook ownership belongs to the user.",
  },
  {
    id: "prompt-training-feedback",
    category: "training-feedback",
    actionType: "ask",
    label: "Training Feedback Prompt",
    status: "future",
    confidence: "low",
    owner: "future-ai",
    purpose: "Ask for training feedback after the user makes a decision.",
    templateText:
      "Ask the user why this decision was correct. Capture what mattered: hook, groove, lyrics, emotional feel, key, arrangement, or source relationship.",
    requiredInputs: ["training", "manual-user-note"],
    userRule: "Training feedback cannot override future user choices.",
  },
  {
    id: "prompt-safety-warning",
    category: "safety-rule",
    actionType: "warn",
    label: "Safety Warning Prompt",
    status: "ready",
    confidence: "high",
    owner: "manual-review",
    purpose: "Warn before AI output gets treated as truth.",
    templateText:
      "This is a suggestion only. Confirm track roles, hooks, BPM, key, stems, and lineage before using it as a decision.",
    requiredInputs: ["confidence"],
    userRule: "Always show safety warning when confidence is manual or low.",
  },
  {
    id: "prompt-export-note",
    category: "export-note",
    actionType: "export",
    label: "Prompt Export Note",
    status: "future",
    confidence: "low",
    owner: "future-ai",
    purpose: "Prepare future prompt export for Suno, notes, or builder instructions.",
    templateText:
      "Export a clean prompt using only confirmed information. Separate known facts from creative suggestions and unanswered questions.",
    requiredInputs: ["manual-user-note", "confidence"],
    userRule: "Export must separate facts from suggestions.",
  },
];

export const multiTrackAiPromptInputRequirements: MultiTrackAiPromptInputRequirement[] = [
  {
    id: "input-track-a",
    inputSource: "track-a",
    label: "Track A Notes",
    status: "needs-review",
    confidence: "manual-required",
    detail: "Track A meaning must be confirmed by the user or future analysis.",
    missingBehavior: "Use a question instead of an assertion.",
  },
  {
    id: "input-track-b",
    inputSource: "track-b",
    label: "Track B Notes",
    status: "needs-review",
    confidence: "manual-required",
    detail: "Track B meaning must be confirmed by the user or future analysis.",
    missingBehavior: "Use a question instead of an assertion.",
  },
  {
    id: "input-comparison",
    inputSource: "comparison",
    label: "Comparison Context",
    status: "needs-review",
    confidence: "manual-required",
    detail: "Comparison must be grounded in confirmed track roles.",
    missingBehavior: "Avoid comparing beyond visible or user-confirmed details.",
  },
  {
    id: "input-confidence",
    inputSource: "confidence",
    label: "Confidence Gate",
    status: "ready",
    confidence: "high",
    detail: "Prompt output must respect confidence safety rules.",
    missingBehavior: "Default to manual review.",
  },
  {
    id: "input-hybrid",
    inputSource: "hybrid",
    label: "Hybrid Plan",
    status: "future",
    confidence: "low",
    detail: "Hybrid prompt requires confirmed merge direction.",
    missingBehavior: "Block hybrid execution language.",
  },
  {
    id: "input-training",
    inputSource: "training",
    label: "Training Feedback",
    status: "future",
    confidence: "low",
    detail: "Training feedback can improve future suggestions after user decisions.",
    missingBehavior: "Ask the user why a choice worked.",
  },
  {
    id: "input-manual-note",
    inputSource: "manual-user-note",
    label: "Manual User Note",
    status: "needs-review",
    confidence: "manual-required",
    detail: "User-written notes are the safest source for prompt wording.",
    missingBehavior: "Ask for confirmation instead of inventing details.",
  },
  {
    id: "input-future-analysis",
    inputSource: "future-analysis",
    label: "Future Analysis",
    status: "future",
    confidence: "low",
    detail: "Future analyzer data may support prompt generation later.",
    missingBehavior: "Do not use unavailable analysis.",
  },
];

export const multiTrackAiPromptOutputTargets: MultiTrackAiPromptOutputTarget[] = [
  {
    id: "output-suno-prompt",
    label: "Suno Prompt",
    category: "song-description",
    status: "future",
    owner: "future-ai",
    outputPurpose: "Create a clean music generation prompt from confirmed details.",
    safetyNote: "Must separate confirmed facts from creative suggestions.",
  },
  {
    id: "output-hybrid-builder-note",
    label: "Hybrid Builder Note",
    category: "hybrid-instruction",
    status: "future",
    owner: "future-hybrid-builder",
    outputPurpose: "Explain how a future builder should treat Track A and Track B.",
    safetyNote: "Cannot be used without confirmed hybrid direction.",
  },
  {
    id: "output-arrangement-note",
    label: "Arrangement Note",
    category: "arrangement-instruction",
    status: "future",
    owner: "future-analyzer",
    outputPurpose: "Describe section order, lift, drop, and transitions.",
    safetyNote: "Cannot invent section boundaries.",
  },
  {
    id: "output-comparison-question",
    label: "Comparison Question",
    category: "lineage-question",
    status: "needs-review",
    owner: "manual-review",
    outputPurpose: "Ask the user safe comparison questions.",
    safetyNote: "Must avoid automatic lineage claims.",
  },
  {
    id: "output-training-question",
    label: "Training Question",
    category: "training-feedback",
    status: "future",
    owner: "future-ai",
    outputPurpose: "Ask why a user-approved choice worked.",
    safetyNote: "Training learns from decisions but does not override the user.",
  },
  {
    id: "output-safety-warning",
    label: "Safety Warning",
    category: "safety-rule",
    status: "ready",
    owner: "manual-review",
    outputPurpose: "Warn when prompt output is suggestion-only.",
    safetyNote: "Must be shown for low, manual, or future-only confidence.",
  },
];

export const multiTrackAiPromptGuardrails: MultiTrackAiPromptGuardrail[] = [
  {
    id: "guard-no-invented-bpm",
    label: "No Invented BPM",
    status: "ready",
    owner: "manual-review",
    rule: "Prompts cannot invent BPM or tempo lock.",
  },
  {
    id: "guard-no-invented-key",
    label: "No Invented Key",
    status: "ready",
    owner: "manual-review",
    rule: "Prompts cannot invent key center or harmonic compatibility.",
  },
  {
    id: "guard-no-lineage-claim",
    label: "No Automatic Lineage Claim",
    status: "ready",
    owner: "user",
    rule: "Prompts cannot claim Track B came from Track A without confirmation.",
  },
  {
    id: "guard-no-stem-claim",
    label: "No Automatic Stem Claim",
    status: "ready",
    owner: "future-analyzer",
    rule: "Prompts cannot label stems without evidence.",
  },
  {
    id: "guard-no-builder-command",
    label: "No Builder Command",
    status: "ready",
    owner: "future-hybrid-builder",
    rule: "Prompts cannot command a future builder until confirmation gates pass.",
  },
  {
    id: "guard-user-owns-meaning",
    label: "User Owns Meaning",
    status: "ready",
    owner: "user",
    rule: "The user owns musical meaning, hook choice, hybrid direction, and final approval.",
  },
];

export const multiTrackAiPromptWorkflowSteps: MultiTrackAiPromptWorkflowStep[] = [
  {
    id: "step-collect-notes",
    label: "Collect User Notes",
    status: "needs-review",
    owner: "user",
    purpose: "Capture what the user says Track A and Track B mean.",
    blockedUntil: "User provides or confirms notes.",
  },
  {
    id: "step-check-confidence",
    label: "Check Confidence",
    status: "ready",
    owner: "manual-review",
    purpose: "Use confidence gates before writing prompt output.",
    blockedUntil: "Confidence workspace exists.",
  },
  {
    id: "step-build-safe-draft",
    label: "Build Safe Draft",
    status: "needs-review",
    owner: "manual-review",
    purpose: "Create prompt text using facts, suggestions, and questions separately.",
    blockedUntil: "Inputs are confirmed or marked missing.",
  },
  {
    id: "step-user-approval",
    label: "User Approval",
    status: "needs-review",
    owner: "user",
    purpose: "User approves the wording before export or future automation.",
    blockedUntil: "User reviews generated prompt.",
  },
  {
    id: "step-future-export",
    label: "Future Export",
    status: "future",
    owner: "future-ai",
    purpose: "Export prompts to future workflows after approval.",
    blockedUntil: "Export layer exists.",
  },
];

export const multiTrackAiPromptWorkspaceState: MultiTrackAiPromptWorkspaceState = {
  title: "AI Prompt Intelligence Workspace",
  description:
    "Read-only prompt planning layer for turning confirmed track notes, comparison context, confidence gates, hybrid plans, arrangement ideas, and training feedback into safe future AI prompts.",
  templates: multiTrackAiPromptTemplates,
  inputRequirements: multiTrackAiPromptInputRequirements,
  outputTargets: multiTrackAiPromptOutputTargets,
  guardrails: multiTrackAiPromptGuardrails,
  workflowSteps: multiTrackAiPromptWorkflowSteps,
};