
import type {
  MultiTrackConfidenceDashboardCard,
  MultiTrackConfidenceEvidence,
  MultiTrackConfidenceRisk,
  MultiTrackConfidenceSafetyRule,
  MultiTrackConfidenceSource,
  MultiTrackConfidenceWorkspaceState,
} from "./MultiTrackConfidenceIntelligenceTypes";

export const multiTrackConfidenceSources: MultiTrackConfidenceSource[] = [
  {
    id: "overall-confidence",
    lane: "overall",
    label: "Overall Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "user",
    score: 42,
    currentMeaning: "The system can show planning confidence, but final trust stays manual.",
    futureMeaning: "Future analyzers can combine tempo, key, hook, structure, stem, hybrid, and lineage signals.",
    userRule: "User overrides all confidence decisions.",
  },
  {
    id: "tempo-confidence",
    lane: "tempo",
    label: "Tempo Confidence",
    bucket: "unknown",
    status: "needs-review",
    owner: "manual-review",
    score: 35,
    currentMeaning: "Tempo confidence is not trusted until BPM is confirmed.",
    futureMeaning: "Future analyzer can compare BPM, drift, grid lock, downbeat stability, and section tempo.",
    userRule: "Do not auto-accept tempo without review.",
  },
  {
    id: "key-confidence",
    lane: "key",
    label: "Key Confidence",
    bucket: "unknown",
    status: "needs-review",
    owner: "manual-review",
    score: 35,
    currentMeaning: "Key confidence is planning-only until key center is confirmed.",
    futureMeaning: "Future analyzer can compare pitch center, chord fit, relative keys, and transpose strategy.",
    userRule: "Do not claim key compatibility without confirmation.",
  },
  {
    id: "structure-confidence",
    lane: "structure",
    label: "Structure Confidence",
    bucket: "weak",
    status: "future",
    owner: "future-analyzer",
    score: 20,
    currentMeaning: "Structure confidence waits for section boundaries or manual markers.",
    futureMeaning: "Future analyzer can compare intro, verse, hook, chorus, bridge, outro, and transitions.",
    userRule: "Structure claims stay future-only.",
  },
  {
    id: "hook-confidence",
    lane: "hook",
    label: "Hook Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "user",
    score: 45,
    currentMeaning: "Hook confidence depends on user confirmation of the keeper hook.",
    futureMeaning: "Future AI can compare contour, phrase repeat, rhythm, and placement.",
    userRule: "User chooses hook ownership.",
  },
  {
    id: "melody-confidence",
    lane: "melody",
    label: "Melody Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "user",
    score: 40,
    currentMeaning: "Melody confidence depends on user-confirmed source phrases.",
    futureMeaning: "Future AI can compare melody contour, intervals, phrase shape, and recurrence.",
    userRule: "Do not claim melody reuse without user review.",
  },
  {
    id: "rhythm-confidence",
    lane: "rhythm",
    label: "Rhythm Confidence",
    bucket: "weak",
    status: "future",
    owner: "future-analyzer",
    score: 22,
    currentMeaning: "Rhythm confidence waits for transient, beat-grid, and groove analysis.",
    futureMeaning: "Future analyzer can compare downbeats, accents, swing, syncopation, and density.",
    userRule: "Rhythm confidence stays low until analysis exists.",
  },
  {
    id: "stem-confidence",
    lane: "stem",
    label: "Stem Confidence",
    bucket: "weak",
    status: "future",
    owner: "future-dsp",
    score: 18,
    currentMeaning: "Stem confidence waits for stem labels or future separation.",
    futureMeaning: "Future DSP can identify drums, bass, vocals, instruments, harmony, and texture roles.",
    userRule: "No automatic stem claims.",
  },
  {
    id: "arrangement-confidence",
    lane: "arrangement",
    label: "Arrangement Confidence",
    bucket: "weak",
    status: "future",
    owner: "future-analyzer",
    score: 25,
    currentMeaning: "Arrangement confidence is only a planning concept right now.",
    futureMeaning: "Future analyzer can compare lift, breakdown, chorus strength, transitions, and section balance.",
    userRule: "Arrangement decisions require review.",
  },
  {
    id: "hybrid-confidence",
    lane: "hybrid",
    label: "Hybrid Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "future-hybrid-builder",
    score: 38,
    currentMeaning: "Hybrid confidence requires user-approved track roles, hooks, and compatibility.",
    futureMeaning: "Future builder can recommend safe merge plans after confidence gates pass.",
    userRule: "No hybrid builder action without user approval.",
  },
  {
    id: "lineage-confidence",
    lane: "lineage",
    label: "Lineage Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "user",
    score: 30,
    currentMeaning: "Lineage confidence cannot be claimed automatically.",
    futureMeaning: "Future AI can compare whether Track B appears derived from Track A.",
    userRule: "No automatic lineage claims.",
  },
  {
    id: "training-confidence",
    lane: "training",
    label: "Training Confidence",
    bucket: "weak",
    status: "future",
    owner: "future-ai",
    score: 15,
    currentMeaning: "Training confidence is seed-only until training workflows exist.",
    futureMeaning: "Future AI can learn user-approved decisions and improve suggestions.",
    userRule: "Training does not override user judgment.",
  },
  {
    id: "comparison-confidence",
    lane: "comparison",
    label: "Comparison Confidence",
    bucket: "manual-review",
    status: "needs-review",
    owner: "manual-review",
    score: 44,
    currentMeaning: "Comparison confidence depends on confirmed roles and evidence.",
    futureMeaning: "Future comparison analyzer can combine metrics into a stronger confidence map.",
    userRule: "Comparison meaning requires user confirmation.",
  },
];

export const multiTrackConfidenceEvidence: MultiTrackConfidenceEvidence[] = [
  {
    id: "evidence-overall-seed",
    sourceId: "overall-confidence",
    evidenceType: "seed-only",
    label: "Seed Confidence Foundation",
    detail: "The confidence system exists as a read-only planning branch.",
    status: "ready",
  },
  {
    id: "evidence-tempo-missing",
    sourceId: "tempo-confidence",
    evidenceType: "missing-evidence",
    label: "Missing BPM Confirmation",
    detail: "BPM needs user confirmation or future analyzer verification.",
    status: "needs-review",
  },
  {
    id: "evidence-key-missing",
    sourceId: "key-confidence",
    evidenceType: "missing-evidence",
    label: "Missing Key Confirmation",
    detail: "Key center needs user confirmation or future analyzer verification.",
    status: "needs-review",
  },
  {
    id: "evidence-hook-user",
    sourceId: "hook-confidence",
    evidenceType: "user-confirmed",
    label: "User Hook Review Required",
    detail: "The user must choose which hook, riff, or phrase matters.",
    status: "needs-review",
  },
  {
    id: "evidence-lineage-user",
    sourceId: "lineage-confidence",
    evidenceType: "user-confirmed",
    label: "User Lineage Review Required",
    detail: "The user must confirm original/result roles before lineage claims.",
    status: "needs-review",
  },
  {
    id: "evidence-structure-future",
    sourceId: "structure-confidence",
    evidenceType: "future-analyzer-confirmed",
    label: "Future Structure Analyzer",
    detail: "Future section detection can support structure confidence.",
    status: "future",
  },
  {
    id: "evidence-stem-future",
    sourceId: "stem-confidence",
    evidenceType: "future-dsp-confirmed",
    label: "Future Stem Evidence",
    detail: "Future DSP or stem labels can support stem confidence.",
    status: "future",
  },
  {
    id: "evidence-hybrid-future",
    sourceId: "hybrid-confidence",
    evidenceType: "future-ai-confirmed",
    label: "Future Hybrid Recommendation Evidence",
    detail: "Future builder can recommend only after user-approved gates.",
    status: "future",
  },
];

export const multiTrackConfidenceRisks: MultiTrackConfidenceRisk[] = [
  {
    id: "risk-missing-bpm",
    sourceId: "tempo-confidence",
    riskFactor: "missing-bpm",
    label: "Missing BPM",
    detail: "Tempo confidence cannot rise until BPM relationship is confirmed.",
    escalation: "review-required",
    status: "needs-review",
  },
  {
    id: "risk-missing-key",
    sourceId: "key-confidence",
    riskFactor: "missing-key",
    label: "Missing Key",
    detail: "Key confidence cannot rise until key center or strategy is confirmed.",
    escalation: "review-required",
    status: "needs-review",
  },
  {
    id: "risk-missing-structure",
    sourceId: "structure-confidence",
    riskFactor: "missing-structure",
    label: "Missing Structure",
    detail: "Arrangement and section claims are blocked until section boundaries exist.",
    escalation: "blocked",
    status: "future",
  },
  {
    id: "risk-missing-stems",
    sourceId: "stem-confidence",
    riskFactor: "missing-stem-labels",
    label: "Missing Stem Labels",
    detail: "Stem confidence stays low until stems are labeled or analyzed.",
    escalation: "blocked",
    status: "future",
  },
  {
    id: "risk-user-review",
    sourceId: "hook-confidence",
    riskFactor: "missing-user-review",
    label: "Missing User Review",
    detail: "Hook, melody, lineage, and hybrid direction must be user reviewed.",
    escalation: "manual-approval",
    status: "needs-review",
  },
  {
    id: "risk-unverified-ai",
    sourceId: "training-confidence",
    riskFactor: "unverified-ai-suggestion",
    label: "Unverified AI Suggestion",
    detail: "Future AI suggestions cannot become truth without confirmation.",
    escalation: "manual-approval",
    status: "future",
  },
];

export const multiTrackConfidenceDashboardCards: MultiTrackConfidenceDashboardCard[] = [
  {
    id: "dashboard-overall",
    lane: "overall",
    title: "Overall Confidence",
    bucket: "manual-review",
    score: 42,
    status: "needs-review",
    summary: "Foundation exists, but confidence cannot rise without confirmed evidence.",
    nextAction: "Review tempo, key, hook, lineage, and hybrid gates.",
  },
  {
    id: "dashboard-tempo",
    lane: "tempo",
    title: "Tempo Confidence",
    bucket: "unknown",
    score: 35,
    status: "needs-review",
    summary: "BPM relationship must be confirmed.",
    nextAction: "Confirm same BPM, target BPM, drift, or manual sync plan.",
  },
  {
    id: "dashboard-key",
    lane: "key",
    title: "Key Confidence",
    bucket: "unknown",
    score: 35,
    status: "needs-review",
    summary: "Key center and compatibility strategy must be confirmed.",
    nextAction: "Confirm same key, transpose, relative key, pivot, or contrast.",
  },
  {
    id: "dashboard-hook",
    lane: "hook",
    title: "Hook Confidence",
    bucket: "manual-review",
    score: 45,
    status: "needs-review",
    summary: "Hook confidence depends on user choice.",
    nextAction: "Choose Track A hook, Track B hook, blend, replace, or call-response.",
  },
  {
    id: "dashboard-structure",
    lane: "structure",
    title: "Structure Confidence",
    bucket: "weak",
    score: 20,
    status: "future",
    summary: "Section mapping is not wired yet.",
    nextAction: "Future section analyzer or manual section markers.",
  },
  {
    id: "dashboard-stem",
    lane: "stem",
    title: "Stem Confidence",
    bucket: "weak",
    score: 18,
    status: "future",
    summary: "Stem labels are missing.",
    nextAction: "Future stem labels or DSP separation evidence.",
  },
  {
    id: "dashboard-hybrid",
    lane: "hybrid",
    title: "Hybrid Confidence",
    bucket: "manual-review",
    score: 38,
    status: "needs-review",
    summary: "Hybrid readiness depends on source roles and confidence gates.",
    nextAction: "Confirm track roles, hooks, tempo/key, and merge direction.",
  },
  {
    id: "dashboard-lineage",
    lane: "lineage",
    title: "Lineage Confidence",
    bucket: "manual-review",
    score: 30,
    status: "needs-review",
    summary: "Lineage claims require user confirmation.",
    nextAction: "Confirm original/result relationship before any lineage claim.",
  },
];

export const multiTrackConfidenceSafetyRules: MultiTrackConfidenceSafetyRule[] = [
  {
    id: "safety-no-inflation",
    label: "No Confidence Inflation",
    rule: "Confidence cannot be upgraded without evidence.",
    owner: "manual-review",
    status: "ready",
  },
  {
    id: "safety-no-lineage-claim",
    label: "No Automatic Lineage Claims",
    rule: "Never claim one track came from another without user confirmation and future analysis.",
    owner: "user",
    status: "ready",
  },
  {
    id: "safety-no-ownership-claim",
    label: "No Automatic Ownership Claims",
    rule: "Do not claim hook, stem, or hybrid ownership without user review.",
    owner: "user",
    status: "ready",
  },
  {
    id: "safety-no-stem-claim",
    label: "No Automatic Stem Claims",
    rule: "Do not claim a stem identity until labels or future DSP evidence exist.",
    owner: "future-dsp",
    status: "ready",
  },
  {
    id: "safety-no-ai-approval",
    label: "No Automatic AI Approval",
    rule: "Future AI can suggest, but it cannot approve musical truth.",
    owner: "future-ai",
    status: "ready",
  },
  {
    id: "safety-user-overrides",
    label: "User Overrides Everything",
    rule: "The user can approve, reject, or override any confidence decision.",
    owner: "user",
    status: "ready",
  },
];

export const multiTrackConfidenceWorkspaceState: MultiTrackConfidenceWorkspaceState = {
  title: "Confidence Intelligence Workspace",
  description:
    "Read-only confidence layer for deciding how much trust exists across tempo, key, structure, hooks, melody, rhythm, stems, arrangement, hybrid planning, lineage, training, and comparison.",
  sources: multiTrackConfidenceSources,
  evidence: multiTrackConfidenceEvidence,
  risks: multiTrackConfidenceRisks,
  dashboardCards: multiTrackConfidenceDashboardCards,
  safetyRules: multiTrackConfidenceSafetyRules,
};