import type {
  MultiTrackKeeperPromotionDecision,
  MultiTrackKeeperPromotionItem,
  MultiTrackKeeperPromotionLane,
  MultiTrackKeeperPromotionWorkspaceState,
} from "./MultiTrackKeeperPromotionTypes";

export const multiTrackKeeperPromotionItems: MultiTrackKeeperPromotionItem[] = [
  {
    id: "keeper-promotion-v03-main-hook",
    title: "Promote Suno V03 main hook",
    versionLabel: "Suno V03",
    sourceCandidateId: "keeper-comparison-suno-v03",
    stage: "approved",
    target: "keeper-bank",
    priority: "critical",
    readinessStatus: "ready",
    reasons: [
      "best-survivor",
      "strong-hook",
      "closest-original",
      "arrangement-ready",
      "extraction-ready",
    ],
    promotionScore: 96,
    keeperPathColor: "gold-keeper",
    actionLabel: "Promote to Keeper Bank",
    detail:
      "Primary seed-safe keeper promotion item. This represents the strongest surviving hook across generated versions.",
    checks: [
      {
        id: "promotion-check-v03-lineage",
        kind: "lineage",
        label: "Lineage Confirmed",
        passed: true,
        score: 92,
        maxScore: 100,
        detail: "Seed comparison keeps V03 connected to the original phone riff.",
      },
      {
        id: "promotion-check-v03-hook",
        kind: "hook",
        label: "Hook Preserved",
        passed: true,
        score: 96,
        maxScore: 100,
        detail: "Strongest hook preservation in this promotion layer.",
      },
      {
        id: "promotion-check-v03-survivor",
        kind: "survivor",
        label: "Survivor Winner",
        passed: true,
        score: 95,
        maxScore: 100,
        detail: "Ranks as the strongest survivor candidate.",
      },
      {
        id: "promotion-check-v03-human",
        kind: "human-review",
        label: "Human Review Ready",
        passed: true,
        score: 88,
        maxScore: 100,
        detail: "Ready for future user approval workflow.",
      },
    ],
    notes: [
      "No real keeper bank wiring yet.",
      "This item is a buildable foundation for later promotion actions.",
    ],
  },
  {
    id: "keeper-promotion-v03-extract",
    title: "Prepare V03 hook extraction",
    versionLabel: "Suno V03",
    sourceCandidateId: "keeper-comparison-suno-v03",
    stage: "prepared",
    target: "extract-lane",
    priority: "high",
    readinessStatus: "ready",
    reasons: ["extraction-ready", "strong-hook", "best-survivor"],
    promotionScore: 91,
    keeperPathColor: "gold-extract",
    actionLabel: "Prepare Extract Lane",
    detail:
      "Creates the seed-safe foundation for pulling the best hook into a future extraction lane.",
    checks: [
      {
        id: "promotion-check-extract-hook",
        kind: "hook",
        label: "Hook Is Clear",
        passed: true,
        score: 94,
        maxScore: 100,
        detail: "Hook identity is strong enough to prepare extraction.",
      },
      {
        id: "promotion-check-extract-edit",
        kind: "extraction",
        label: "Extraction Ready",
        passed: true,
        score: 90,
        maxScore: 100,
        detail: "Seed placeholder says this can become an extraction lane later.",
      },
      {
        id: "promotion-check-extract-render",
        kind: "render",
        label: "Render Not Required",
        passed: true,
        score: 78,
        maxScore: 100,
        detail: "Extraction can be prepared before final render queue wiring.",
      },
    ],
    notes: [
      "Future extraction lane only.",
      "No waveform cutting yet.",
    ],
  },
  {
    id: "keeper-promotion-v07-bridge-review",
    title: "Review Suno V07 bridge mutation",
    versionLabel: "Suno V07",
    sourceCandidateId: "keeper-comparison-suno-v07",
    stage: "candidate",
    target: "arrangement-lane",
    priority: "medium",
    readinessStatus: "needs-review",
    reasons: ["useful-mutation", "arrangement-ready"],
    promotionScore: 78,
    keeperPathColor: "purple-review",
    actionLabel: "Review for Arrangement",
    detail:
      "Useful bridge mutation that should not be promoted automatically. It needs human review first.",
    checks: [
      {
        id: "promotion-check-v07-mutation",
        kind: "mutation",
        label: "Useful Mutation",
        passed: true,
        score: 82,
        maxScore: 100,
        detail: "The mutation is musically useful as a possible bridge section.",
      },
      {
        id: "promotion-check-v07-arrangement",
        kind: "arrangement",
        label: "Arrangement Candidate",
        passed: true,
        score: 88,
        maxScore: 100,
        detail: "Strong arrangement value, but not the primary keeper hook.",
      },
      {
        id: "promotion-check-v07-human",
        kind: "human-review",
        label: "Needs Human Review",
        passed: false,
        score: 58,
        maxScore: 100,
        detail: "Needs manual confirmation before promotion.",
      },
    ],
    notes: [
      "Good bridge candidate.",
      "Do not auto-promote.",
    ],
  },
  {
    id: "keeper-promotion-v10-render-reference",
    title: "Hold Suno V10 polished reference",
    versionLabel: "Suno V10",
    sourceCandidateId: "keeper-comparison-suno-v10",
    stage: "queued",
    target: "render-queue",
    priority: "low",
    readinessStatus: "future",
    reasons: ["render-ready", "arrangement-ready", "seed-placeholder"],
    promotionScore: 73,
    keeperPathColor: "green-render",
    actionLabel: "Hold for Render Queue",
    detail:
      "Polished future reference that can support render queue planning later without wiring anything now.",
    checks: [
      {
        id: "promotion-check-v10-render",
        kind: "render",
        label: "Render Reference",
        passed: true,
        score: 86,
        maxScore: 100,
        detail: "Useful future render reference.",
      },
      {
        id: "promotion-check-v10-lineage",
        kind: "lineage",
        label: "Lineage Weaker",
        passed: false,
        score: 68,
        maxScore: 100,
        detail: "Not as close to the original idea as V03.",
      },
      {
        id: "promotion-check-v10-future",
        kind: "arrangement",
        label: "Future Arrangement",
        passed: true,
        score: 84,
        maxScore: 100,
        detail: "Can support arrangement planning later.",
      },
    ],
    notes: [
      "Future-only render queue placeholder.",
      "No render system import.",
    ],
  },
  {
    id: "keeper-promotion-v02-archive",
    title: "Archive Suno V02 weak pass",
    versionLabel: "Suno V02",
    sourceCandidateId: "keeper-comparison-suno-v02",
    stage: "archived",
    target: "archive-bin",
    priority: "parking-lot",
    readinessStatus: "ready",
    reasons: ["archive-drift"],
    promotionScore: 28,
    keeperPathColor: "red-archive",
    actionLabel: "Archive Drifted Version",
    detail:
      "Weak pass that drifted too far from the original idea and should not move into keeper work.",
    checks: [
      {
        id: "promotion-check-v02-hook",
        kind: "hook",
        label: "Hook Lost",
        passed: false,
        score: 38,
        maxScore: 100,
        detail: "Hook preservation is too weak for promotion.",
      },
      {
        id: "promotion-check-v02-survivor",
        kind: "survivor",
        label: "Low Survivor",
        passed: false,
        score: 32,
        maxScore: 100,
        detail: "Low survivor value.",
      },
      {
        id: "promotion-check-v02-archive",
        kind: "human-review",
        label: "Archive Safe",
        passed: true,
        score: 80,
        maxScore: 100,
        detail: "Safe seed example for archive workflow.",
      },
    ],
    notes: [
      "Archive candidate.",
      "Useful negative example for future training logic.",
    ],
  },
];

export const multiTrackKeeperPromotionLanes: MultiTrackKeeperPromotionLane[] = [
  {
    id: "keeper-promotion-lane-bank",
    title: "Keeper Bank",
    target: "keeper-bank",
    readinessStatus: "ready",
    itemIds: ["keeper-promotion-v03-main-hook"],
    description: "Final keeper candidates approved for future extraction, duplication, and arrangement.",
  },
  {
    id: "keeper-promotion-lane-extract",
    title: "Extract Lane",
    target: "extract-lane",
    readinessStatus: "ready",
    itemIds: ["keeper-promotion-v03-extract"],
    description: "Items prepared for future hook or riff extraction.",
  },
  {
    id: "keeper-promotion-lane-arrangement",
    title: "Arrangement Lane",
    target: "arrangement-lane",
    readinessStatus: "needs-review",
    itemIds: ["keeper-promotion-v07-bridge-review"],
    description: "Mutations that may become bridge, breakdown, or alternate arrangement sections.",
  },
  {
    id: "keeper-promotion-lane-render",
    title: "Render Queue",
    target: "render-queue",
    readinessStatus: "future",
    itemIds: ["keeper-promotion-v10-render-reference"],
    description: "Future render-ready references and polished passes.",
  },
  {
    id: "keeper-promotion-lane-archive",
    title: "Archive Bin",
    target: "archive-bin",
    readinessStatus: "ready",
    itemIds: ["keeper-promotion-v02-archive"],
    description: "Versions that should stay available but should not drive keeper work.",
  },
];

export const multiTrackKeeperPromotionDecisions: MultiTrackKeeperPromotionDecision[] = [
  {
    id: "keeper-promotion-decision-v03-main",
    itemId: "keeper-promotion-v03-main-hook",
    label: "Approve V03 main hook",
    stage: "approved",
    approved: true,
    detail: "Approved as the main keeper candidate.",
  },
  {
    id: "keeper-promotion-decision-v03-extract",
    itemId: "keeper-promotion-v03-extract",
    label: "Prepare V03 extraction",
    stage: "prepared",
    approved: true,
    detail: "Prepared for future extraction lane.",
  },
  {
    id: "keeper-promotion-decision-v07-review",
    itemId: "keeper-promotion-v07-bridge-review",
    label: "Review V07 bridge",
    stage: "candidate",
    approved: false,
    detail: "Not approved until human review confirms the bridge mutation.",
  },
  {
    id: "keeper-promotion-decision-v02-archive",
    itemId: "keeper-promotion-v02-archive",
    label: "Archive V02",
    stage: "archived",
    approved: true,
    detail: "Archived as a weak drift example.",
  },
];

export const multiTrackKeeperPromotionWorkspaceState: MultiTrackKeeperPromotionWorkspaceState = {
  id: "multi-track-keeper-promotion-workspace",
  title: "Keeper Promotion",
  description:
    "Seed-safe promotion layer for moving the strongest survivor into keeper bank, extraction lane, edit lane, arrangement planning, render queue, or archive.",
  readinessStatus: "ready",
  items: multiTrackKeeperPromotionItems,
  lanes: multiTrackKeeperPromotionLanes,
  decisions: multiTrackKeeperPromotionDecisions,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No imports outside this 4-file promotion set.",
    "Designed to follow Keeper Comparison and Keeper Engine later without importing them now.",
  ],
};