import type {
  MultiTrackWaveformStatisticsEngineSource,
  MultiTrackWaveformStatisticsEngineWorkspace,
} from "./MultiTrackWaveformStatisticsEngineTypes";

export const multiTrackWaveformStatisticsEngineSources: MultiTrackWaveformStatisticsEngineSource[] = [
  {
    sourceId: "stats-track-a",
    title: "Track A statistics pass",
    sourceKind: "track-a",
    fileLabel: "Original ad-lib or reference track",
    durationMs: 224000,
    sampleRate: 44100,
    bitDepth: 24,
    channelCount: 2,
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientReady: false,
    measurements: [
      {
        measurementId: "track-a-peak",
        kind: "peak",
        label: "Peak ceiling",
        value: 0.79,
        valueLabel: "-2.0 dBFS est.",
        detail: "Seeded peak estimate. Real engine will calculate from decoded waveform frames.",
        status: "estimated",
        risk: "low",
      },
      {
        measurementId: "track-a-rms",
        kind: "rms",
        label: "Average RMS",
        value: 0.35,
        valueLabel: "-9.1 dB est.",
        detail: "Energy body estimate for matching against Suno versions.",
        status: "estimated",
        risk: "low",
      },
      {
        measurementId: "track-a-dynamic-range",
        kind: "dynamic-range",
        label: "Dynamic range",
        value: 0.44,
        valueLabel: "Medium",
        detail: "Enough movement to preserve riff shape for later survivor scoring.",
        status: "seeded",
        risk: "medium",
      },
      {
        measurementId: "track-a-silence",
        kind: "silence",
        label: "Silence amount",
        value: 0.12,
        valueLabel: "12%",
        detail: "Quiet space may help future downbeat and section detection.",
        status: "estimated",
        risk: "low",
      },
    ],
    windows: [
      {
        windowId: "track-a-window-1",
        label: "Intro phrase",
        startMs: 0,
        endMs: 16000,
        peak: 0.62,
        rms: 0.28,
        energy: 0.34,
        dynamicRange: 0.34,
        silencePercent: 0.16,
        clipRisk: "low",
        status: "estimated",
      },
      {
        windowId: "track-a-window-2",
        label: "Main hook idea",
        startMs: 16000,
        endMs: 42000,
        peak: 0.79,
        rms: 0.39,
        energy: 0.58,
        dynamicRange: 0.4,
        silencePercent: 0.06,
        clipRisk: "low",
        status: "estimated",
      },
      {
        windowId: "track-a-window-3",
        label: "Variation phrase",
        startMs: 42000,
        endMs: 76000,
        peak: 0.71,
        rms: 0.33,
        energy: 0.48,
        dynamicRange: 0.38,
        silencePercent: 0.1,
        clipRisk: "low",
        status: "estimated",
      },
    ],
    findings: [
      {
        findingId: "track-a-finding-hook-energy",
        title: "Hook area has strongest energy",
        detail: "The seeded hook window has the highest combined peak and RMS profile.",
        action: "Use this region as a future transient and riff-group candidate.",
        status: "estimated",
        risk: "low",
      },
      {
        findingId: "track-a-finding-no-clip",
        title: "No clipping risk in seed data",
        detail: "Peak estimate stays below the danger range.",
        action: "Safe to compare against louder Suno versions.",
        status: "estimated",
        risk: "low",
      },
    ],
    notes: [
      "Statistics engine should read waveform engine frames, not raw seed cards.",
      "This layer prepares facts for similarity and survivor ranking.",
      "Do not make musical decisions here. This layer only measures.",
    ],
  },
  {
    sourceId: "stats-suno-v7",
    title: "Suno version 7 statistics pass",
    sourceKind: "suno-version",
    fileLabel: "Candidate Suno render with strong chorus",
    durationMs: 238000,
    sampleRate: 48000,
    bitDepth: 24,
    channelCount: 2,
    readiness: "needs-review",
    waveformReady: true,
    statisticsReady: true,
    transientReady: false,
    measurements: [
      {
        measurementId: "suno-v7-peak",
        kind: "peak",
        label: "Peak ceiling",
        value: 0.91,
        valueLabel: "-0.8 dBFS est.",
        detail: "Suno render is louder and closer to ceiling than Track A.",
        status: "estimated",
        risk: "medium",
      },
      {
        measurementId: "suno-v7-rms",
        kind: "rms",
        label: "Average RMS",
        value: 0.44,
        valueLabel: "-7.1 dB est.",
        detail: "Higher loudness can make survivor hooks appear stronger unless normalized.",
        status: "estimated",
        risk: "medium",
      },
      {
        measurementId: "suno-v7-dynamic-range",
        kind: "dynamic-range",
        label: "Dynamic range",
        value: 0.31,
        valueLabel: "Compressed",
        detail: "Compression may hide phrase movement compared with the original idea.",
        status: "seeded",
        risk: "medium",
      },
      {
        measurementId: "suno-v7-stereo",
        kind: "stereo-width",
        label: "Stereo width",
        value: 0.68,
        valueLabel: "Wide",
        detail: "Wide render can affect similarity if mono references are not normalized.",
        status: "future",
        risk: "medium",
      },
    ],
    windows: [
      {
        windowId: "suno-v7-window-1",
        label: "Intro build",
        startMs: 0,
        endMs: 18000,
        peak: 0.72,
        rms: 0.34,
        energy: 0.44,
        dynamicRange: 0.38,
        silencePercent: 0.08,
        clipRisk: "low",
        status: "estimated",
      },
      {
        windowId: "suno-v7-window-2",
        label: "Chorus hook",
        startMs: 48000,
        endMs: 78000,
        peak: 0.91,
        rms: 0.51,
        energy: 0.72,
        dynamicRange: 0.29,
        silencePercent: 0.02,
        clipRisk: "medium",
        status: "estimated",
      },
      {
        windowId: "suno-v7-window-3",
        label: "Bridge lift",
        startMs: 124000,
        endMs: 152000,
        peak: 0.86,
        rms: 0.46,
        energy: 0.66,
        dynamicRange: 0.33,
        silencePercent: 0.04,
        clipRisk: "medium",
        status: "estimated",
      },
    ],
    findings: [
      {
        findingId: "suno-v7-finding-loudness-bias",
        title: "Normalize before survivor ranking",
        detail: "This version is louder than Track A and may win unfairly without normalization.",
        action: "Send normalized RMS profile to similarity and survivor engines.",
        status: "estimated",
        risk: "medium",
      },
      {
        findingId: "suno-v7-finding-chorus",
        title: "Chorus window is strongest candidate",
        detail: "The chorus hook window has the highest seeded energy score.",
        action: "Mark chorus hook for transient and riff extraction pass.",
        status: "estimated",
        risk: "low",
      },
    ],
    notes: [
      "Suno versions must be compared after loudness normalization.",
      "Peak/RMS windows become candidate regions for hook survival.",
      "Compression risk should be carried into survivor analysis.",
    ],
  },
];

export const multiTrackWaveformStatisticsEngineWorkspace: MultiTrackWaveformStatisticsEngineWorkspace = {
  workspaceId: "multi-track-waveform-statistics-engine",
  title: "Waveform Statistics Engine",
  summary:
    "Second real engine layer. Converts waveform frame shape into measurable peak, RMS, dynamic range, silence, energy, and risk facts for comparison and survivor analysis.",
  readiness: "needs-review",
  readinessLabel: "Seeded statistics are ready. Real waveform-frame input is next.",
  engineGoal:
    "Measure audio energy fairly before any hook, riff, similarity, or survivor decision is made.",
  sources: multiTrackWaveformStatisticsEngineSources,
  comparisons: [
    {
      comparisonId: "track-a-vs-suno-v7",
      title: "Track A vs Suno Version 7",
      leftSourceId: "stats-track-a",
      rightSourceId: "stats-suno-v7",
      peakDifference: 0.12,
      rmsDifference: 0.09,
      energyDifference: 0.14,
      detail:
        "Suno V7 is louder and denser. Future scoring should normalize energy before declaring it stronger.",
      status: "estimated",
      risk: "medium",
    },
  ],
  engineRules: [
    "Never rank survivor hooks using raw loudness only.",
    "Normalize before comparing Track A against Suno renders.",
    "Keep statistics separate from musical meaning.",
    "Send risk flags forward so later engines can avoid false winners.",
    "Do not treat seed values as final measured values.",
  ],
  nextSteps: [
    "Connect this engine to waveform engine frames.",
    "Calculate real peak and RMS per frame window.",
    "Add loudness normalization helper for fair version comparison.",
    "Send highest-energy windows to transient detection.",
    "Send normalized windows to similarity and survivor engines.",
  ],
};