import type {
  MultiTrackKeeperCandidate,
  MultiTrackKeeperEngineWorkspaceState,
  MultiTrackKeeperPath,
  MultiTrackKeeperQueueItem,
} from "./MultiTrackKeeperEngineTypes";

export const multiTrackKeeperEngineCandidates: MultiTrackKeeperCandidate[] = [
  {
    id: "keeper-candidate-original-phone-riff",
    title: "Original phone riff idea",
    sourceKind: "original-idea",
    versionLabel: "Original",
    ideaFamilyId: "idea-family-001",
    lineageId: "lineage-main-hook",
    mutationCount: 0,
    survivorRank: 2,
    strength: "strong",
    readinessStatus: "needs-review",
    color: "blue",
    reasonCodes: ["clear-lineage", "repeatable-riff", "needs-human-review"],
    promotionTargets: ["review", "extract", "edit-lane"],
    signals: [
      {
        id: "signal-original-memory",
        label: "Memory Anchor",
        value: 92,
        maxValue: 100,
        detail: "The starting idea is still recognizable across later Suno versions.",
      },
      {
        id: "signal-original-editability",
        label: "Editability",
        value: 76,
        maxValue: 100,
        detail: "Good candidate for manual extraction and comparison.",
      },
    ],
    notes: [
      "Seed-safe placeholder for the raw human idea.",
      "Later this can compare phone audio against generated versions.",
    ],
  },
  {
    id: "keeper-candidate-suno-v03-hook",
    title: "Suno version 03 hook lift",
    sourceKind: "suno-version",
    versionLabel: "Suno V03",
    ideaFamilyId: "idea-family-001",
    lineageId: "lineage-main-hook",
    mutationCount: 3,
    survivorRank: 1,
    strength: "keeper",
    readinessStatus: "ready",
    color: "gold",
    reasonCodes: ["strong-hook", "best-mutation", "arrangement-ready", "render-ready"],
    promotionTargets: ["extract", "duplicate", "arrangement", "render-queue"],
    signals: [
      {
        id: "signal-v03-hook",
        label: "Hook Strength",
        value: 96,
        maxValue: 100,
        detail: "Strongest seed keeper in this isolated workspace layer.",
      },
      {
        id: "signal-v03-survivor",
        label: "Survivor Score",
        value: 94,
        maxValue: 100,
        detail: "Ranks first for promotion into keeper path.",
      },
      {
        id: "signal-v03-render",
        label: "Render Readiness",
        value: 88,
        maxValue: 100,
        detail: "Ready to prepare for render queue once real audio wiring exists.",
      },
    ],
    notes: [
      "Primary keeper placeholder.",
      "Use this as the strongest survivor for future extraction workflow.",
    ],
  },
  {
    id: "keeper-candidate-suno-v07-bridge",
    title: "Suno version 07 bridge mutation",
    sourceKind: "variation-engine",
    versionLabel: "Suno V07",
    ideaFamilyId: "idea-family-001",
    lineageId: "lineage-bridge-mutation",
    mutationCount: 7,
    survivorRank: 3,
    strength: "maybe",
    readinessStatus: "needs-review",
    color: "purple",
    reasonCodes: ["best-mutation", "edit-ready", "needs-human-review"],
    promotionTargets: ["review", "edit-lane", "arrangement"],
    signals: [
      {
        id: "signal-v07-bridge",
        label: "Bridge Usefulness",
        value: 81,
        maxValue: 100,
        detail: "Could become a bridge or second arrangement section.",
      },
      {
        id: "signal-v07-risk",
        label: "Review Need",
        value: 63,
        maxValue: 100,
        detail: "Needs human confirmation before keeper promotion.",
      },
    ],
    notes: [
      "Useful mutation, not the main keeper yet.",
      "Good edit lane candidate.",
    ],
  },
  {
    id: "keeper-candidate-suno-v10-render-pass",
    title: "Suno version 10 render pass",
    sourceKind: "survivor-analysis",
    versionLabel: "Suno V10",
    ideaFamilyId: "idea-family-001",
    lineageId: "lineage-render-pass",
    mutationCount: 10,
    survivorRank: 4,
    strength: "strong",
    readinessStatus: "future",
    color: "green",
    reasonCodes: ["render-ready", "arrangement-ready", "seed-placeholder"],
    promotionTargets: ["render-queue", "archive"],
    signals: [
      {
        id: "signal-v10-polish",
        label: "Polish",
        value: 84,
        maxValue: 100,
        detail: "Potentially useful as a polished reference version.",
      },
      {
        id: "signal-v10-lineage",
        label: "Lineage Match",
        value: 72,
        maxValue: 100,
        detail: "Still related to the main idea but less direct than V03.",
      },
    ],
    notes: [
      "Future render queue placeholder.",
      "Should not be wired to real render systems yet.",
    ],
  },
];

export const multiTrackKeeperEnginePaths: MultiTrackKeeperPath[] = [
  {
    id: "keeper-path-main-hook",
    title: "Main hook keeper path",
    ideaFamilyId: "idea-family-001",
    color: "gold",
    summary: "Original phone idea moves through Suno versions and lands on V03 as the strongest keeper.",
    steps: [
      {
        id: "keeper-path-step-original",
        label: "Original idea",
        candidateId: "keeper-candidate-original-phone-riff",
        order: 1,
        color: "blue",
        detail: "Human starting point.",
      },
      {
        id: "keeper-path-step-v03",
        label: "Keeper lift",
        candidateId: "keeper-candidate-suno-v03-hook",
        order: 2,
        color: "gold",
        detail: "Strongest survivor candidate.",
      },
      {
        id: "keeper-path-step-v10",
        label: "Render pass",
        candidateId: "keeper-candidate-suno-v10-render-pass",
        order: 3,
        color: "green",
        detail: "Future render reference.",
      },
    ],
  },
];

export const multiTrackKeeperEnginePromotionQueue: MultiTrackKeeperQueueItem[] = [
  {
    id: "keeper-queue-extract-v03",
    candidateId: "keeper-candidate-suno-v03-hook",
    target: "extract",
    label: "Extract V03 hook",
    readinessStatus: "ready",
    detail: "Prepare the strongest hook for later extraction tooling.",
  },
  {
    id: "keeper-queue-duplicate-v03",
    candidateId: "keeper-candidate-suno-v03-hook",
    target: "duplicate",
    label: "Duplicate keeper into edit lane",
    readinessStatus: "ready",
    detail: "Seed-safe queue item for future duplication workflow.",
  },
  {
    id: "keeper-queue-review-v07",
    candidateId: "keeper-candidate-suno-v07-bridge",
    target: "review",
    label: "Review V07 bridge mutation",
    readinessStatus: "needs-review",
    detail: "Needs human confirmation before arrangement promotion.",
  },
];

export const multiTrackKeeperEngineWorkspaceState: MultiTrackKeeperEngineWorkspaceState = {
  id: "multi-track-keeper-engine-workspace",
  title: "Keeper Engine",
  description:
    "Seed-safe isolated engine foundation for finding the strongest musical idea across Suno versions, tracking keeper paths, and preparing future extraction/edit/render workflows.",
  readinessStatus: "ready",
  candidates: multiTrackKeeperEngineCandidates,
  keeperPaths: multiTrackKeeperEnginePaths,
  promotionQueue: multiTrackKeeperEnginePromotionQueue,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "All data is seed-safe and isolated to waveform folder.",
  ],
};