
import type {
  MultiTrackDuplicationClone,
  MultiTrackDuplicationLane,
  MultiTrackDuplicationPlanStep,
  MultiTrackDuplicationWorkspaceState,
} from "./MultiTrackDuplicationEngineTypes";

export const multiTrackDuplicationEngineClones: MultiTrackDuplicationClone[] = [
  {
    id: "duplication-clone-main-hook-final-repeat",
    title: "Duplicate main hook into final repeat",
    sourceId: "arrangement-section-main-hook",
    sourceKind: "arrangement-section",
    targetKind: "hook-repeat",
    readinessStatus: "ready",
    cloneStatus: "approved",
    priority: "critical",
    sourceStartBar: 25,
    sourceEndBar: 40,
    targetStartBar: 57,
    targetEndBar: 72,
    repeatCount: 2,
    offsetBeats: 0,
    bpm: 120,
    keyLabel: "C#m",
    cloneScore: 96,
    timingScore: 92,
    transitionScore: 88,
    renderScore: 94,
    actions: ["copy", "repeat", "place", "prepare-render"],
    checks: [
      {
        id: "duplication-check-main-hook-source",
        label: "Source hook approved",
        passed: true,
        score: 96,
        maxScore: 100,
        detail: "The main hook is the strongest keeper source.",
      },
      {
        id: "duplication-check-main-hook-target",
        label: "Target bars available",
        passed: true,
        score: 90,
        maxScore: 100,
        detail: "Final repeat slot is open in the seed arrangement.",
      },
      {
        id: "duplication-check-main-hook-render",
        label: "Render preparation safe",
        passed: true,
        score: 92,
        maxScore: 100,
        detail: "Good future render target after duplication.",
      },
    ],
    risks: ["seed-placeholder"],
    detail:
      "Primary duplication plan: copy the strongest main hook into the final hook repeat area.",
    notes: [
      "Highest-priority duplicate path.",
      "No audio copying is wired here.",
    ],
  },
  {
    id: "duplication-clone-riff-pocket-verse-loop",
    title: "Repeat riff pocket through verse groove",
    sourceId: "arrangement-section-verse-pocket",
    sourceKind: "riff-pocket",
    targetKind: "verse-copy",
    readinessStatus: "ready",
    cloneStatus: "prepared",
    priority: "high",
    sourceStartBar: 9,
    sourceEndBar: 16,
    targetStartBar: 17,
    targetEndBar: 24,
    repeatCount: 2,
    offsetBeats: 0,
    bpm: 120,
    keyLabel: "C#m",
    cloneScore: 88,
    timingScore: 84,
    transitionScore: 80,
    renderScore: 78,
    actions: ["copy", "loop", "place", "review"],
    checks: [
      {
        id: "duplication-check-riff-loop",
        label: "Loop pocket works",
        passed: true,
        score: 86,
        maxScore: 100,
        detail: "Seed riff pocket is useful as a repeated verse groove.",
      },
      {
        id: "duplication-check-riff-timing",
        label: "Timing needs later confirmation",
        passed: false,
        score: 68,
        maxScore: 100,
        detail: "Real waveform timing still needs review.",
      },
      {
        id: "duplication-check-riff-transition",
        label: "Transition acceptable",
        passed: true,
        score: 80,
        maxScore: 100,
        detail: "Can support the move into the main hook.",
      },
    ],
    risks: ["timing-drift", "seed-placeholder"],
    detail:
      "Copies a short riff pocket across the verse lane to create a stable repeated groove.",
    notes: [
      "Good edit-lane copy candidate.",
      "Review timing before real use.",
    ],
  },
  {
    id: "duplication-clone-hook-intro-tease",
    title: "Tease keeper hook in intro",
    sourceId: "keeper-extraction-v03-main-hook",
    sourceKind: "keeper-hook",
    targetKind: "intro-copy",
    readinessStatus: "needs-review",
    cloneStatus: "draft",
    priority: "medium",
    sourceStartBar: 25,
    sourceEndBar: 32,
    targetStartBar: 1,
    targetEndBar: 8,
    repeatCount: 1,
    offsetBeats: -2,
    bpm: 120,
    keyLabel: "C#m",
    cloneScore: 78,
    timingScore: 72,
    transitionScore: 82,
    renderScore: 70,
    actions: ["copy", "offset", "trim", "review"],
    checks: [
      {
        id: "duplication-check-intro-hook-value",
        label: "Intro tease has value",
        passed: true,
        score: 82,
        maxScore: 100,
        detail: "A light hook tease can make the intro recognizable.",
      },
      {
        id: "duplication-check-intro-offset",
        label: "Offset needs review",
        passed: false,
        score: 58,
        maxScore: 100,
        detail: "Offset timing should be confirmed by ear later.",
      },
      {
        id: "duplication-check-intro-density",
        label: "Arrangement density safe",
        passed: true,
        score: 76,
        maxScore: 100,
        detail: "Intro is not overcrowded in seed data.",
      },
    ],
    risks: ["timing-drift", "unreviewed-clone", "seed-placeholder"],
    detail:
      "Draft clone that teases the keeper hook in the intro with a small timing offset.",
    notes: [
      "Needs human review.",
      "Could make the intro feel connected to the main hook.",
    ],
  },
  {
    id: "duplication-clone-bridge-lift-copy",
    title: "Copy bridge mutation as lift",
    sourceId: "arrangement-section-bridge-mutation",
    sourceKind: "bridge-mutation",
    targetKind: "bridge-copy",
    readinessStatus: "needs-review",
    cloneStatus: "draft",
    priority: "medium",
    sourceStartBar: 41,
    sourceEndBar: 56,
    targetStartBar: 49,
    targetEndBar: 56,
    repeatCount: 1,
    offsetBeats: 0,
    bpm: 120,
    keyLabel: "C#m",
    cloneScore: 74,
    timingScore: 76,
    transitionScore: 68,
    renderScore: 66,
    actions: ["copy", "trim", "place", "review"],
    checks: [
      {
        id: "duplication-check-bridge-value",
        label: "Bridge lift has value",
        passed: true,
        score: 80,
        maxScore: 100,
        detail: "Bridge mutation may work as a lifted repeated section.",
      },
      {
        id: "duplication-check-bridge-review",
        label: "Human review required",
        passed: false,
        score: 52,
        maxScore: 100,
        detail: "Bridge clone should not be placed without review.",
      },
      {
        id: "duplication-check-bridge-transition",
        label: "Transition uncertain",
        passed: false,
        score: 60,
        maxScore: 100,
        detail: "Transition into final hook needs listening review.",
      },
    ],
    risks: ["weak-transition", "unreviewed-clone", "seed-placeholder"],
    detail:
      "Draft clone for repeating part of the bridge mutation as a lift before the final hook.",
    notes: [
      "Useful but not approved.",
      "Should stay review-gated.",
    ],
  },
  {
    id: "duplication-clone-render-copy-main-hook",
    title: "Prepare main hook render copy",
    sourceId: "render-queue-main-hook-preview",
    sourceKind: "keeper-hook",
    targetKind: "render-copy",
    readinessStatus: "future",
    cloneStatus: "prepared",
    priority: "low",
    sourceStartBar: 25,
    sourceEndBar: 40,
    targetStartBar: 25,
    targetEndBar: 40,
    repeatCount: 1,
    offsetBeats: 0,
    bpm: 120,
    keyLabel: "C#m",
    cloneScore: 82,
    timingScore: 86,
    transitionScore: 78,
    renderScore: 88,
    actions: ["copy", "prepare-render"],
    checks: [
      {
        id: "duplication-check-render-source",
        label: "Render source prepared",
        passed: true,
        score: 86,
        maxScore: 100,
        detail: "Seed render preview can provide a render-copy plan later.",
      },
      {
        id: "duplication-check-render-future",
        label: "Future render only",
        passed: false,
        score: 54,
        maxScore: 100,
        detail: "No real render system exists yet.",
      },
      {
        id: "duplication-check-render-safe",
        label: "Safe placeholder",
        passed: true,
        score: 84,
        maxScore: 100,
        detail: "Safe as a future-only clone.",
      },
    ],
    risks: ["render-risk", "seed-placeholder"],
    detail:
      "Future render copy placeholder for a main hook preview bounce.",
    notes: [
      "Future-only render copy.",
      "No render engine import.",
    ],
  },
];

export const multiTrackDuplicationEngineLanes: MultiTrackDuplicationLane[] = [
  {
    id: "duplication-lane-hook-repeat",
    title: "Hook Repeats",
    targetKind: "hook-repeat",
    readinessStatus: "ready",
    cloneIds: ["duplication-clone-main-hook-final-repeat"],
    description:
      "Approved hook repeats that keep the strongest keeper idea alive across the arrangement.",
  },
  {
    id: "duplication-lane-verse-copy",
    title: "Verse Copies",
    targetKind: "verse-copy",
    readinessStatus: "ready",
    cloneIds: ["duplication-clone-riff-pocket-verse-loop"],
    description:
      "Looped or repeated verse material built from keeper riff pockets.",
  },
  {
    id: "duplication-lane-intro-copy",
    title: "Intro Copies",
    targetKind: "intro-copy",
    readinessStatus: "needs-review",
    cloneIds: ["duplication-clone-hook-intro-tease"],
    description:
      "Intro teaser copies that need human review before placement.",
  },
  {
    id: "duplication-lane-bridge-copy",
    title: "Bridge Copies",
    targetKind: "bridge-copy",
    readinessStatus: "needs-review",
    cloneIds: ["duplication-clone-bridge-lift-copy"],
    description:
      "Bridge mutation copies that can create lift but should remain review-gated.",
  },
  {
    id: "duplication-lane-render-copy",
    title: "Render Copies",
    targetKind: "render-copy",
    readinessStatus: "future",
    cloneIds: ["duplication-clone-render-copy-main-hook"],
    description:
      "Future render-copy placeholders for preview and export workflows.",
  },
];

export const multiTrackDuplicationEnginePlanSteps: MultiTrackDuplicationPlanStep[] = [
  {
    id: "duplication-step-main-hook-copy",
    cloneId: "duplication-clone-main-hook-final-repeat",
    order: 1,
    label: "Copy main hook",
    action: "copy",
    readinessStatus: "ready",
    detail: "Copy the approved main hook into the final repeat position.",
  },
  {
    id: "duplication-step-main-hook-place",
    cloneId: "duplication-clone-main-hook-final-repeat",
    order: 2,
    label: "Place final hook repeat",
    action: "place",
    readinessStatus: "ready",
    detail: "Place the duplicate at the final hook target bars.",
  },
  {
    id: "duplication-step-riff-loop",
    cloneId: "duplication-clone-riff-pocket-verse-loop",
    order: 3,
    label: "Loop verse riff pocket",
    action: "loop",
    readinessStatus: "ready",
    detail: "Repeat the verse riff pocket to support the groove lane.",
  },
  {
    id: "duplication-step-intro-review",
    cloneId: "duplication-clone-hook-intro-tease",
    order: 4,
    label: "Review intro hook tease",
    action: "review",
    readinessStatus: "needs-review",
    detail: "Confirm whether the intro tease helps or overcrowds the intro.",
  },
  {
    id: "duplication-step-bridge-review",
    cloneId: "duplication-clone-bridge-lift-copy",
    order: 5,
    label: "Review bridge lift copy",
    action: "review",
    readinessStatus: "needs-review",
    detail: "Confirm the bridge copy before placing it into arrangement lanes.",
  },
  {
    id: "duplication-step-render-copy",
    cloneId: "duplication-clone-render-copy-main-hook",
    order: 6,
    label: "Hold render copy",
    action: "prepare-render",
    readinessStatus: "future",
    detail: "Future-only render copy placeholder.",
  },
];

export const multiTrackDuplicationEngineWorkspaceState: MultiTrackDuplicationWorkspaceState = {
  id: "multi-track-duplication-engine-workspace",
  title: "Duplication Engine",
  description:
    "Seed-safe duplication foundation for copying keeper hooks, repeating riff pockets, cloning bridge lifts, and preparing arrangement-safe duplicates.",
  readinessStatus: "ready",
  clones: multiTrackDuplicationEngineClones,
  lanes: multiTrackDuplicationEngineLanes,
  planSteps: multiTrackDuplicationEnginePlanSteps,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No real audio copying.",
    "No imports outside this 4-file duplication set.",
  ],
};