import type { MultiTrackVariationEngineWorkspaceState } from "./MultiTrackVariationEngineTypes";

export const multiTrackVariationEngineSeed: MultiTrackVariationEngineWorkspaceState = {
  id: "multi-track-variation-engine-workspace",
  title: "Variation Engine",
  description:
    "Future-safe workspace for ranking, choosing, editing, duplicating, extracting, and rendering the best musical idea variations across 10 Suno versions.",
  readinessStatus: "ready",
  activeClusterId: "cluster-main-hook",
  activeCandidateId: "candidate-hook-v02",
  guardrailNotes: [
    "No page wiring yet.",
    "No real render calls yet.",
    "No DSP extraction yet.",
    "All candidates are seed-safe until analyzer evidence is connected.",
    "Decisions should stay reviewable before any automatic edit or render.",
  ],
  sourceVersions: [
    {
      id: "variation-source-01",
      versionId: "version-01",
      title: "Suno Version 01",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-02",
      versionId: "version-02",
      title: "Suno Version 02",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-03",
      versionId: "version-03",
      title: "Suno Version 03",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-04",
      versionId: "version-04",
      title: "Suno Version 04",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-05",
      versionId: "version-05",
      title: "Suno Version 05",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-06",
      versionId: "version-06",
      title: "Suno Version 06",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-07",
      versionId: "version-07",
      title: "Suno Version 07",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-08",
      versionId: "version-08",
      title: "Suno Version 08",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-09",
      versionId: "version-09",
      title: "Suno Version 09",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
    {
      id: "variation-source-10",
      versionId: "version-10",
      title: "Suno Version 10",
      fileLabel: "Waiting for audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
    },
  ],
  scores: [
    {
      id: "score-hook-v01-identity",
      scoreKind: "identity-match",
      label: "Hook identity",
      detail: "Version 01 keeps the original hook shape but needs timing review.",
      value: 82,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v01-edit",
      scoreKind: "editability",
      label: "Hook edit window",
      detail: "Clean enough seed window for future extraction planning.",
      value: 76,
      confidenceBucket: "moderate",
    },
    {
      id: "score-hook-v02-identity",
      scoreKind: "identity-match",
      label: "Hook identity",
      detail: "Version 02 appears to preserve the strongest version of the hook.",
      value: 91,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v02-melody",
      scoreKind: "melody-strength",
      label: "Melody strength",
      detail: "Top-line shape is stronger and easier to recognize.",
      value: 88,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v02-render",
      scoreKind: "render-readiness",
      label: "Render readiness",
      detail: "Best seed candidate for future WAV hook render.",
      value: 79,
      confidenceBucket: "moderate",
    },
    {
      id: "score-hook-v03-identity",
      scoreKind: "identity-match",
      label: "Hook identity",
      detail: "Related hook, but less certain than version 02.",
      value: 72,
      confidenceBucket: "moderate",
    },
    {
      id: "score-riff-v04-rhythm",
      scoreKind: "rhythm-strength",
      label: "Riff rhythm",
      detail: "Useful rhythmic idea for riff matching.",
      value: 71,
      confidenceBucket: "moderate",
    },
    {
      id: "score-bass-v05-groove",
      scoreKind: "groove-strength",
      label: "Bass groove",
      detail: "Good groove pocket candidate for later stem-safe editing.",
      value: 83,
      confidenceBucket: "strong",
    },
    {
      id: "score-vocal-v07-user",
      scoreKind: "user-keeper",
      label: "User keeper",
      detail: "Manual keeper-style vocal phrase until phonetic analysis exists.",
      value: 69,
      confidenceBucket: "moderate",
    },
  ],
  risks: [
    {
      id: "risk-variation-no-audio",
      riskKind: "missing-audio",
      label: "No audio attached",
      detail: "Variation Engine is not allowed to claim real matches yet.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-variation-future-dsp",
      riskKind: "future-dsp",
      label: "Future DSP required",
      detail: "Extract, duplicate, and render actions require future DSP wiring.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-variation-manual-review",
      riskKind: "manual-review",
      label: "Manual review needed",
      detail: "User should approve best candidate before destructive editing.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-variation-render-not-ready",
      riskKind: "render-not-ready",
      label: "Render not ready",
      detail: "Render plan exists as target only; no audio writer is wired.",
      severity: "high",
      isBlocking: false,
    },
  ],
  decisions: [
    {
      id: "decision-hook-v01-compare",
      decisionKind: "compare",
      label: "Compare hook V01",
      detail: "Keep version 01 as a baseline comparison against stronger takes.",
      readinessStatus: "ready",
    },
    {
      id: "decision-hook-v02-keep",
      decisionKind: "keep",
      label: "Keep hook V02",
      detail: "Promote version 02 as the strongest seed hook candidate.",
      readinessStatus: "ready",
    },
    {
      id: "decision-hook-v02-extract",
      decisionKind: "extract",
      label: "Extract hook V02",
      detail: "Future action: cut this hook into an editable clip.",
      readinessStatus: "future",
    },
    {
      id: "decision-hook-v02-render",
      decisionKind: "render",
      label: "Render hook V02",
      detail: "Future action: render selected hook to WAV.",
      readinessStatus: "future",
    },
    {
      id: "decision-hook-v03-hold",
      decisionKind: "hold",
      label: "Hold hook V03",
      detail: "Keep under review until similarity is stronger.",
      readinessStatus: "needs-review",
    },
    {
      id: "decision-bass-v05-edit",
      decisionKind: "edit",
      label: "Edit bass groove",
      detail: "Future action: trim and test bass pocket.",
      readinessStatus: "future",
    },
    {
      id: "decision-vocal-v07-hold",
      decisionKind: "hold",
      label: "Hold vocal phrase",
      detail: "Needs lyric/phonetic analyzer before promotion.",
      readinessStatus: "needs-review",
    },
  ],
  candidates: [
    {
      id: "candidate-hook-v01",
      title: "Hook Candidate V01",
      versionId: "version-01",
      variationKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Hook window",
      },
      summary: "Baseline hook candidate from version 01.",
      scoreIds: ["score-hook-v01-identity", "score-hook-v01-edit"],
      riskIds: ["risk-variation-no-audio", "risk-variation-future-dsp"],
      decisionIds: ["decision-hook-v01-compare"],
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "candidate-hook-v02",
      title: "Hook Candidate V02",
      versionId: "version-02",
      variationKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook window",
      },
      summary: "Strongest seed hook candidate for future extract/render.",
      scoreIds: [
        "score-hook-v02-identity",
        "score-hook-v02-melody",
        "score-hook-v02-render",
      ],
      riskIds: [
        "risk-variation-no-audio",
        "risk-variation-future-dsp",
        "risk-variation-render-not-ready",
      ],
      decisionIds: [
        "decision-hook-v02-keep",
        "decision-hook-v02-extract",
        "decision-hook-v02-render",
      ],
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "candidate-hook-v03",
      title: "Hook Candidate V03",
      versionId: "version-03",
      variationKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Possible hook window",
      },
      summary: "Related hook candidate with weaker seed confidence.",
      scoreIds: ["score-hook-v03-identity"],
      riskIds: ["risk-variation-no-audio", "risk-variation-manual-review"],
      decisionIds: ["decision-hook-v03-hold"],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-riff-v04",
      title: "Riff Candidate V04",
      versionId: "version-04",
      variationKind: "riff",
      color: "orange",
      timeRange: {
        startSeconds: 21,
        endSeconds: 29,
        label: "Riff pocket",
      },
      summary: "Rhythmic riff idea that may become a repeatable arrangement part.",
      scoreIds: ["score-riff-v04-rhythm"],
      riskIds: ["risk-variation-no-audio"],
      decisionIds: [],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-bass-v05",
      title: "Bass Groove V05",
      versionId: "version-05",
      variationKind: "bass",
      color: "green",
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass groove",
      },
      summary: "Bass movement candidate for stem-safe edit testing later.",
      scoreIds: ["score-bass-v05-groove"],
      riskIds: ["risk-variation-no-audio", "risk-variation-future-dsp"],
      decisionIds: ["decision-bass-v05-edit"],
      confidenceBucket: "strong",
      readinessStatus: "needs-review",
    },
    {
      id: "candidate-vocal-v07",
      title: "Vocal Phrase V07",
      versionId: "version-07",
      variationKind: "vocal",
      color: "purple",
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      summary: "Possible user-original phrase memory for later phonetic matching.",
      scoreIds: ["score-vocal-v07-user"],
      riskIds: ["risk-variation-manual-review"],
      decisionIds: ["decision-vocal-v07-hold"],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
  ],
  clusters: [
    {
      id: "cluster-main-hook",
      title: "Main Hook Variations",
      detail: "Candidates that may be the same hook across Suno versions.",
      variationKind: "hook",
      color: "blue",
      candidateIds: [
        "candidate-hook-v01",
        "candidate-hook-v02",
        "candidate-hook-v03",
      ],
      winningCandidateId: "candidate-hook-v02",
      readinessStatus: "ready",
    },
    {
      id: "cluster-riff",
      title: "Riff Variations",
      detail: "Riff and short repeated phrase ideas.",
      variationKind: "riff",
      color: "orange",
      candidateIds: ["candidate-riff-v04"],
      winningCandidateId: null,
      readinessStatus: "needs-review",
    },
    {
      id: "cluster-groove",
      title: "Groove Variations",
      detail: "Bass, drums, and pocket ideas.",
      variationKind: "groove",
      color: "green",
      candidateIds: ["candidate-bass-v05"],
      winningCandidateId: "candidate-bass-v05",
      readinessStatus: "needs-review",
    },
    {
      id: "cluster-vocal",
      title: "Vocal Variations",
      detail: "Vocal phrase and lyric placement ideas.",
      variationKind: "vocal",
      color: "purple",
      candidateIds: ["candidate-vocal-v07"],
      winningCandidateId: null,
      readinessStatus: "needs-review",
    },
  ],
  comparisons: [
    {
      id: "variation-comparison-hook-v01-v02",
      clusterId: "cluster-main-hook",
      leftCandidateId: "candidate-hook-v01",
      rightCandidateId: "candidate-hook-v02",
      similarityPercent: 88,
      winnerCandidateId: "candidate-hook-v02",
      reason: "Version 02 has stronger identity and melody score.",
      confidenceBucket: "strong",
    },
    {
      id: "variation-comparison-hook-v02-v03",
      clusterId: "cluster-main-hook",
      leftCandidateId: "candidate-hook-v02",
      rightCandidateId: "candidate-hook-v03",
      similarityPercent: 74,
      winnerCandidateId: "candidate-hook-v02",
      reason: "Version 03 is related but weaker.",
      confidenceBucket: "moderate",
    },
  ],
  editPlans: [
    {
      id: "edit-plan-hook-v02",
      candidateId: "candidate-hook-v02",
      label: "Trim hook V02",
      detail: "Future editable hook clip from the strongest variation.",
      trimStartSeconds: 44,
      trimEndSeconds: 53,
      duplicateCount: 2,
      targetLaneLabel: "Hook Edit Lane",
      readinessStatus: "future",
    },
    {
      id: "edit-plan-bass-v05",
      candidateId: "candidate-bass-v05",
      label: "Trim bass groove V05",
      detail: "Future bass groove clip for arrangement testing.",
      trimStartSeconds: 16,
      trimEndSeconds: 25,
      duplicateCount: 4,
      targetLaneLabel: "Groove Edit Lane",
      readinessStatus: "future",
    },
  ],
  renderPlans: [
    {
      id: "render-plan-hook-v02-wav",
      candidateId: "candidate-hook-v02",
      label: "Render hook V02 WAV",
      detail: "Future WAV output for the selected hook variation.",
      outputFormat: "wav",
      includeTail: true,
      normalizeOutput: true,
      readinessStatus: "future",
    },
    {
      id: "render-plan-hook-v02-stems",
      candidateId: "candidate-hook-v02",
      label: "Render hook V02 stem pack",
      detail: "Future stem-safe output after separation/export exists.",
      outputFormat: "stem-pack",
      includeTail: true,
      normalizeOutput: false,
      readinessStatus: "future",
    },
  ],
  lanes: [
    {
      id: "variation-lane-hooks",
      label: "Hook Winners",
      detail: "Best hook choices after comparison.",
      color: "blue",
      candidateIds: ["candidate-hook-v02"],
      readinessStatus: "ready",
    },
    {
      id: "variation-lane-review",
      label: "Review Queue",
      detail: "Candidates that need ears or analyzer confirmation.",
      color: "yellow",
      candidateIds: [
        "candidate-hook-v03",
        "candidate-riff-v04",
        "candidate-vocal-v07",
      ],
      readinessStatus: "needs-review",
    },
    {
      id: "variation-lane-groove",
      label: "Groove Candidates",
      detail: "Bass and pocket options for future edit lanes.",
      color: "green",
      candidateIds: ["candidate-bass-v05"],
      readinessStatus: "needs-review",
    },
  ],
};