import type {
  MultiTrackRenderQueueJob,
  MultiTrackRenderQueueLane,
  MultiTrackRenderQueuePlanStep,
  MultiTrackRenderQueueWorkspaceState,
} from "./MultiTrackRenderQueueEngineTypes";

export const multiTrackRenderQueueEngineJobs: MultiTrackRenderQueueJob[] = [
  {
    id: "render-queue-main-hook-preview",
    title: "Main hook keeper preview",
    sourceArrangementId: "arrangement-section-main-hook",
    target: "keeper-preview",
    format: "wav",
    priority: "critical",
    status: "prepared",
    readinessStatus: "ready",
    estimatedLengthSeconds: 32,
    estimatedFileSizeMb: 11,
    renderScore: 96,
    qualityScore: 94,
    exportScore: 92,
    deliveryScore: 90,
    checks: [
      {
        id: "render-check-main-hook-arrangement",
        label: "Arrangement section selected",
        passed: true,
        score: 96,
        maxScore: 100,
        detail: "Main hook section is the strongest render candidate.",
      },
      {
        id: "render-check-main-hook-format",
        label: "WAV export preferred",
        passed: true,
        score: 95,
        maxScore: 100,
        detail: "WAV is the preferred musician-first format.",
      },
      {
        id: "render-check-main-hook-review",
        label: "Review ready",
        passed: true,
        score: 88,
        maxScore: 100,
        detail: "Seed-safe review gate is satisfied.",
      },
    ],
    risks: ["seed-placeholder"],
    detail:
      "Primary keeper preview render job. This prepares the strongest hook for a future WAV bounce.",
    notes: [
      "No real render engine is imported.",
      "This is a queue foundation only.",
    ],
  },
  {
    id: "render-queue-arrangement-demo",
    title: "Full arrangement demo",
    sourceArrangementId: "multi-track-arrangement-engine-workspace",
    target: "arrangement-demo",
    format: "wav",
    priority: "high",
    status: "queued",
    readinessStatus: "ready",
    estimatedLengthSeconds: 184,
    estimatedFileSizeMb: 64,
    renderScore: 88,
    qualityScore: 86,
    exportScore: 91,
    deliveryScore: 84,
    checks: [
      {
        id: "render-check-demo-blueprint",
        label: "Blueprint available",
        passed: true,
        score: 90,
        maxScore: 100,
        detail: "Arrangement blueprint exists as seed-safe data.",
      },
      {
        id: "render-check-demo-hooks",
        label: "Keeper hooks placed",
        passed: true,
        score: 92,
        maxScore: 100,
        detail: "Main and final hook placements are present.",
      },
      {
        id: "render-check-demo-bridge",
        label: "Bridge needs review",
        passed: false,
        score: 58,
        maxScore: 100,
        detail: "Bridge mutation still needs human review.",
      },
    ],
    risks: ["unreviewed-section", "seed-placeholder"],
    detail:
      "Future full arrangement demo render. Ready as a plan, but bridge review remains open.",
    notes: [
      "Good next render after hook preview.",
      "Bridge should be confirmed before final render.",
    ],
  },
  {
    id: "render-queue-verse-pocket-bounce",
    title: "Verse pocket edit-lane bounce",
    sourceArrangementId: "arrangement-section-verse-pocket",
    target: "edit-lane-bounce",
    format: "wav",
    priority: "medium",
    status: "draft",
    readinessStatus: "needs-review",
    estimatedLengthSeconds: 48,
    estimatedFileSizeMb: 17,
    renderScore: 78,
    qualityScore: 80,
    exportScore: 86,
    deliveryScore: 72,
    checks: [
      {
        id: "render-check-verse-loop",
        label: "Loopable pocket",
        passed: true,
        score: 84,
        maxScore: 100,
        detail: "Verse riff pocket is loopable in seed data.",
      },
      {
        id: "render-check-verse-transition",
        label: "Transition needs review",
        passed: false,
        score: 62,
        maxScore: 100,
        detail: "Transition into hook needs real listening review.",
      },
      {
        id: "render-check-verse-export",
        label: "Export candidate",
        passed: true,
        score: 82,
        maxScore: 100,
        detail: "Good candidate for edit-lane bounce later.",
      },
    ],
    risks: ["timing-risk", "unreviewed-section", "seed-placeholder"],
    detail:
      "Draft render job for a repeatable verse pocket that can later become edit-lane material.",
    notes: [
      "Do not render automatically.",
      "Needs real timing review later.",
    ],
  },
  {
    id: "render-queue-bridge-review-bounce",
    title: "Bridge mutation review bounce",
    sourceArrangementId: "arrangement-section-bridge-mutation",
    target: "edit-lane-bounce",
    format: "wav",
    priority: "medium",
    status: "draft",
    readinessStatus: "needs-review",
    estimatedLengthSeconds: 32,
    estimatedFileSizeMb: 11,
    renderScore: 72,
    qualityScore: 74,
    exportScore: 80,
    deliveryScore: 66,
    checks: [
      {
        id: "render-check-bridge-mutation",
        label: "Mutation has value",
        passed: true,
        score: 82,
        maxScore: 100,
        detail: "Bridge mutation may be useful as a lift section.",
      },
      {
        id: "render-check-bridge-human",
        label: "Human review required",
        passed: false,
        score: 50,
        maxScore: 100,
        detail: "Bridge is not approved for final render yet.",
      },
      {
        id: "render-check-bridge-transition",
        label: "Transition risk",
        passed: false,
        score: 58,
        maxScore: 100,
        detail: "Needs transition review into final hook.",
      },
    ],
    risks: ["unreviewed-section", "timing-risk", "seed-placeholder"],
    detail:
      "Bridge review bounce placeholder. Useful for review, not final render.",
    notes: [
      "Review-only bounce.",
      "Not a final keeper render.",
    ],
  },
  {
    id: "render-queue-final-song-future",
    title: "Final keeper song render",
    sourceArrangementId: "multi-track-arrangement-engine-workspace",
    target: "full-song-render",
    format: "wav",
    priority: "critical",
    status: "draft",
    readinessStatus: "future",
    estimatedLengthSeconds: 212,
    estimatedFileSizeMb: 74,
    renderScore: 82,
    qualityScore: 88,
    exportScore: 94,
    deliveryScore: 80,
    checks: [
      {
        id: "render-check-final-hooks",
        label: "Keeper hooks ready",
        passed: true,
        score: 94,
        maxScore: 100,
        detail: "Primary keeper sections are ready in the seed arrangement.",
      },
      {
        id: "render-check-final-sections",
        label: "All sections approved",
        passed: false,
        score: 62,
        maxScore: 100,
        detail: "Some sections remain future or review-only.",
      },
      {
        id: "render-check-final-audio",
        label: "Real audio missing",
        passed: false,
        score: 30,
        maxScore: 100,
        detail: "No real render engine or audio slicing is connected.",
      },
    ],
    risks: ["missing-audio", "missing-extraction", "seed-placeholder"],
    detail:
      "Future final render placeholder. This should stay draft until real audio and section approvals exist.",
    notes: [
      "Future-only final render.",
      "No real exporter.",
    ],
  },
];

export const multiTrackRenderQueueEngineLanes: MultiTrackRenderQueueLane[] = [
  {
    id: "render-lane-keeper-preview",
    title: "Keeper Preview",
    target: "keeper-preview",
    readinessStatus: "ready",
    jobIds: ["render-queue-main-hook-preview"],
    description: "Fast preview renders for the strongest keeper hooks.",
  },
  {
    id: "render-lane-arrangement-demo",
    title: "Arrangement Demo",
    target: "arrangement-demo",
    readinessStatus: "ready",
    jobIds: ["render-queue-arrangement-demo"],
    description: "Full blueprint demos prepared from the arrangement layer.",
  },
  {
    id: "render-lane-edit-bounce",
    title: "Edit Lane Bounce",
    target: "edit-lane-bounce",
    readinessStatus: "needs-review",
    jobIds: ["render-queue-verse-pocket-bounce", "render-queue-bridge-review-bounce"],
    description: "Partial section bounces for review, edit lanes, and future duplication.",
  },
  {
    id: "render-lane-final-song",
    title: "Final Song Render",
    target: "full-song-render",
    readinessStatus: "future",
    jobIds: ["render-queue-final-song-future"],
    description: "Future final full-song renders after audio, arrangement, and review gates pass.",
  },
];

export const multiTrackRenderQueueEnginePlanSteps: MultiTrackRenderQueuePlanStep[] = [
  {
    id: "render-plan-step-preview",
    jobId: "render-queue-main-hook-preview",
    order: 1,
    label: "Prepare keeper hook preview",
    status: "prepared",
    readinessStatus: "ready",
    detail: "First render target should be the strongest keeper hook preview.",
  },
  {
    id: "render-plan-step-demo",
    jobId: "render-queue-arrangement-demo",
    order: 2,
    label: "Queue arrangement demo",
    status: "queued",
    readinessStatus: "ready",
    detail: "Second target is the full seed arrangement demo.",
  },
  {
    id: "render-plan-step-verse",
    jobId: "render-queue-verse-pocket-bounce",
    order: 3,
    label: "Review verse pocket bounce",
    status: "draft",
    readinessStatus: "needs-review",
    detail: "Verse pocket bounce needs review before becoming edit-lane material.",
  },
  {
    id: "render-plan-step-bridge",
    jobId: "render-queue-bridge-review-bounce",
    order: 4,
    label: "Review bridge mutation bounce",
    status: "draft",
    readinessStatus: "needs-review",
    detail: "Bridge mutation needs human review before final arrangement render.",
  },
  {
    id: "render-plan-step-final",
    jobId: "render-queue-final-song-future",
    order: 5,
    label: "Hold final keeper song render",
    status: "draft",
    readinessStatus: "future",
    detail: "Final render remains future until real audio and render exporter exist.",
  },
];

export const multiTrackRenderQueueEngineWorkspaceState: MultiTrackRenderQueueWorkspaceState = {
  id: "multi-track-render-queue-engine-workspace",
  title: "Render Queue Engine",
  description:
    "Seed-safe render queue foundation for keeper previews, arrangement demos, edit-lane bounces, and future full-song WAV renders.",
  readinessStatus: "ready",
  jobs: multiTrackRenderQueueEngineJobs,
  lanes: multiTrackRenderQueueEngineLanes,
  planSteps: multiTrackRenderQueueEnginePlanSteps,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No real render/export code.",
    "No imports outside this 4-file render queue set.",
    "WAV is preferred for musician-first export planning.",
  ],
};