
import type {
  MultiTrackKeeperExtractionLane,
  MultiTrackKeeperExtractionPlanStep,
  MultiTrackKeeperExtractionRegion,
  MultiTrackKeeperExtractionWorkspaceState,
} from "./MultiTrackKeeperExtractionTypes";

export const multiTrackKeeperExtractionRegions: MultiTrackKeeperExtractionRegion[] = [
  {
    id: "keeper-extraction-v03-main-hook",
    title: "V03 main hook extraction",
    sourceVersionLabel: "Suno V03",
    sourceCandidateId: "keeper-promotion-v03-main-hook",
    regionKind: "hook",
    readinessStatus: "ready",
    confidence: "strong",
    startBeat: 17,
    endBeat: 33,
    startTimeSeconds: 8,
    endTimeSeconds: 16,
    bpm: 120,
    keyLabel: "C#m",
    strengthScore: 96,
    boundaryScore: 88,
    loopScore: 91,
    extractionScore: 94,
    actions: ["extract", "duplicate", "send-to-edit-lane", "send-to-arrangement"],
    risks: ["needs-human-confirmation", "seed-placeholder"],
    detail:
      "Primary seed-safe hook region. This is the strongest keeper extraction target for future waveform cutting.",
    notes: [
      "Use as first extraction target when real audio boundaries exist.",
      "No audio slicing is wired here.",
    ],
  },
  {
    id: "keeper-extraction-v03-riff-repeat",
    title: "V03 repeatable riff pocket",
    sourceVersionLabel: "Suno V03",
    sourceCandidateId: "keeper-promotion-v03-extract",
    regionKind: "riff",
    readinessStatus: "ready",
    confidence: "strong",
    startBeat: 33,
    endBeat: 41,
    startTimeSeconds: 16,
    endTimeSeconds: 20,
    bpm: 120,
    keyLabel: "C#m",
    strengthScore: 89,
    boundaryScore: 84,
    loopScore: 93,
    extractionScore: 88,
    actions: ["extract", "loop", "send-to-edit-lane"],
    risks: ["rough-boundary", "seed-placeholder"],
    detail:
      "Short riff pocket that can become a loopable edit-lane building block later.",
    notes: [
      "Good loop candidate.",
      "Needs real downbeat detection later.",
    ],
  },
  {
    id: "keeper-extraction-v07-bridge",
    title: "V07 bridge mutation section",
    sourceVersionLabel: "Suno V07",
    sourceCandidateId: "keeper-promotion-v07-bridge-review",
    regionKind: "bridge",
    readinessStatus: "needs-review",
    confidence: "medium",
    startBeat: 49,
    endBeat: 65,
    startTimeSeconds: 24,
    endTimeSeconds: 32,
    bpm: 120,
    keyLabel: "C#m",
    strengthScore: 81,
    boundaryScore: 72,
    loopScore: 69,
    extractionScore: 76,
    actions: ["review", "trim", "send-to-arrangement"],
    risks: ["rough-boundary", "needs-human-confirmation", "seed-placeholder"],
    detail:
      "Bridge mutation that may be extracted later, but it needs review before promotion.",
    notes: [
      "Useful alternate section.",
      "Should not auto-extract yet.",
    ],
  },
  {
    id: "keeper-extraction-v10-polish-chorus",
    title: "V10 polished chorus reference",
    sourceVersionLabel: "Suno V10",
    sourceCandidateId: "keeper-promotion-v10-render-reference",
    regionKind: "chorus",
    readinessStatus: "future",
    confidence: "medium",
    startBeat: 17,
    endBeat: 49,
    startTimeSeconds: 8,
    endTimeSeconds: 24,
    bpm: 120,
    keyLabel: "C#m",
    strengthScore: 78,
    boundaryScore: 70,
    loopScore: 62,
    extractionScore: 69,
    actions: ["review", "send-to-render-queue"],
    risks: ["missing-downbeat", "seed-placeholder"],
    detail:
      "Future polished chorus reference. Useful for render planning but not ready for extraction.",
    notes: [
      "Future render reference only.",
      "No render queue wiring.",
    ],
  },
];

export const multiTrackKeeperExtractionLanes: MultiTrackKeeperExtractionLane[] = [
  {
    id: "keeper-extraction-lane-hooks",
    title: "Hook Extractions",
    regionKind: "hook",
    readinessStatus: "ready",
    regionIds: ["keeper-extraction-v03-main-hook"],
    description: "Primary hook regions ready for future extraction and duplication.",
  },
  {
    id: "keeper-extraction-lane-riffs",
    title: "Riff Pockets",
    regionKind: "riff",
    readinessStatus: "ready",
    regionIds: ["keeper-extraction-v03-riff-repeat"],
    description: "Short repeatable regions that can become loopable edit-lane material.",
  },
  {
    id: "keeper-extraction-lane-bridges",
    title: "Bridge Mutations",
    regionKind: "bridge",
    readinessStatus: "needs-review",
    regionIds: ["keeper-extraction-v07-bridge"],
    description: "Alternate bridge sections that need human review before extraction.",
  },
  {
    id: "keeper-extraction-lane-render-reference",
    title: "Render References",
    regionKind: "chorus",
    readinessStatus: "future",
    regionIds: ["keeper-extraction-v10-polish-chorus"],
    description: "Future polished references that may guide render queue decisions later.",
  },
];

export const multiTrackKeeperExtractionPlanSteps: MultiTrackKeeperExtractionPlanStep[] = [
  {
    id: "keeper-extraction-step-review-hook",
    regionId: "keeper-extraction-v03-main-hook",
    order: 1,
    action: "review",
    label: "Confirm V03 hook boundaries",
    readinessStatus: "ready",
    detail: "Human confirms the seed boundary before real extraction exists.",
  },
  {
    id: "keeper-extraction-step-extract-hook",
    regionId: "keeper-extraction-v03-main-hook",
    order: 2,
    action: "extract",
    label: "Extract V03 main hook",
    readinessStatus: "ready",
    detail: "Future extraction action placeholder.",
  },
  {
    id: "keeper-extraction-step-duplicate-hook",
    regionId: "keeper-extraction-v03-main-hook",
    order: 3,
    action: "duplicate",
    label: "Duplicate hook into edit lane",
    readinessStatus: "ready",
    detail: "Future duplicate action placeholder.",
  },
  {
    id: "keeper-extraction-step-loop-riff",
    regionId: "keeper-extraction-v03-riff-repeat",
    order: 4,
    action: "loop",
    label: "Prepare riff loop",
    readinessStatus: "ready",
    detail: "Future loop preparation placeholder.",
  },
  {
    id: "keeper-extraction-step-review-bridge",
    regionId: "keeper-extraction-v07-bridge",
    order: 5,
    action: "review",
    label: "Review V07 bridge",
    readinessStatus: "needs-review",
    detail: "Manual approval before bridge extraction.",
  },
];

export const multiTrackKeeperExtractionWorkspaceState: MultiTrackKeeperExtractionWorkspaceState = {
  id: "multi-track-keeper-extraction-workspace",
  title: "Keeper Extraction",
  description:
    "Seed-safe extraction foundation for identifying hook, riff, bridge, and chorus regions that can later move into edit lanes, duplication, arrangement, or render queue workflows.",
  readinessStatus: "ready",
  regions: multiTrackKeeperExtractionRegions,
  lanes: multiTrackKeeperExtractionLanes,
  planSteps: multiTrackKeeperExtractionPlanSteps,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No real audio slicing.",
    "No imports outside this 4-file extraction set.",
  ],
};