import type {
  MultiTrackWaveformEngineSource,
  MultiTrackWaveformEngineWorkspace,
} from "./MultiTrackWaveformEngineTypes";

const trackAFrames = [
  { frameId: "track-a-frame-001", startMs: 0, endMs: 250, peak: 0.62, rms: 0.31, zeroCrossingRate: 0.08, status: "estimated" },
  { frameId: "track-a-frame-002", startMs: 250, endMs: 500, peak: 0.68, rms: 0.35, zeroCrossingRate: 0.09, status: "estimated" },
  { frameId: "track-a-frame-003", startMs: 500, endMs: 750, peak: 0.71, rms: 0.38, zeroCrossingRate: 0.11, status: "estimated" },
  { frameId: "track-a-frame-004", startMs: 750, endMs: 1000, peak: 0.56, rms: 0.28, zeroCrossingRate: 0.07, status: "estimated" },
  { frameId: "track-a-frame-005", startMs: 1000, endMs: 1250, peak: 0.74, rms: 0.41, zeroCrossingRate: 0.1, status: "estimated" },
  { frameId: "track-a-frame-006", startMs: 1250, endMs: 1500, peak: 0.79, rms: 0.45, zeroCrossingRate: 0.13, status: "estimated" },
  { frameId: "track-a-frame-007", startMs: 1500, endMs: 1750, peak: 0.66, rms: 0.33, zeroCrossingRate: 0.09, status: "estimated" },
  { frameId: "track-a-frame-008", startMs: 1750, endMs: 2000, peak: 0.51, rms: 0.25, zeroCrossingRate: 0.06, status: "estimated" },
] as const;

const sunoFrames = [
  { frameId: "suno-frame-001", startMs: 0, endMs: 250, peak: 0.54, rms: 0.22, zeroCrossingRate: 0.07, status: "estimated" },
  { frameId: "suno-frame-002", startMs: 250, endMs: 500, peak: 0.63, rms: 0.3, zeroCrossingRate: 0.08, status: "estimated" },
  { frameId: "suno-frame-003", startMs: 500, endMs: 750, peak: 0.81, rms: 0.47, zeroCrossingRate: 0.12, status: "estimated" },
  { frameId: "suno-frame-004", startMs: 750, endMs: 1000, peak: 0.86, rms: 0.49, zeroCrossingRate: 0.14, status: "estimated" },
  { frameId: "suno-frame-005", startMs: 1000, endMs: 1250, peak: 0.73, rms: 0.38, zeroCrossingRate: 0.1, status: "estimated" },
  { frameId: "suno-frame-006", startMs: 1250, endMs: 1500, peak: 0.58, rms: 0.27, zeroCrossingRate: 0.08, status: "estimated" },
  { frameId: "suno-frame-007", startMs: 1500, endMs: 1750, peak: 0.69, rms: 0.34, zeroCrossingRate: 0.09, status: "estimated" },
  { frameId: "suno-frame-008", startMs: 1750, endMs: 2000, peak: 0.77, rms: 0.42, zeroCrossingRate: 0.11, status: "estimated" },
] as const;

export const multiTrackWaveformEngineSources: MultiTrackWaveformEngineSource[] = [
  {
    sourceId: "engine-track-a",
    title: "Track A waveform engine pass",
    sourceKind: "track-a",
    fileLabel: "Waiting for loaded Track A audio",
    durationMs: 2000,
    sampleRate: 44100,
    bitDepth: 24,
    channelMode: "stereo",
    channelCount: 2,
    frameSizeMs: 250,
    waveformReady: true,
    statisticsReady: true,
    transientReady: false,
    readiness: "needs-review",
    frames: [...trackAFrames],
    channelSummaries: [
      {
        channelId: "track-a-left",
        label: "Left",
        peak: 0.79,
        rms: 0.35,
        averageRms: 0.35,
        minPeak: 0.51,
        maxPeak: 0.79,
        frameCount: 8,
        status: "estimated",
      },
      {
        channelId: "track-a-right",
        label: "Right",
        peak: 0.76,
        rms: 0.33,
        averageRms: 0.33,
        minPeak: 0.49,
        maxPeak: 0.76,
        frameCount: 8,
        status: "estimated",
      },
    ],
    decodeSteps: [
      {
        stepId: "track-a-load",
        kind: "load-file",
        label: "Load audio source",
        detail: "Track A file slot is the first target for real browser decode wiring.",
        status: "ready",
        owner: "Track Matcher deck",
      },
      {
        stepId: "track-a-decode",
        kind: "decode-audio",
        label: "Decode audio buffer",
        detail: "Future implementation will decode File or Blob into AudioBuffer.",
        status: "needs-decode",
        owner: "Waveform engine",
      },
      {
        stepId: "track-a-frame-analysis",
        kind: "frame-analysis",
        label: "Analyze frames",
        detail: "Engine will slice audio into frame windows for peak, RMS, and zero crossing.",
        status: "needs-analysis",
        owner: "Waveform engine",
      },
      {
        stepId: "track-a-summary",
        kind: "summary",
        label: "Build waveform summary",
        detail: "Summary feeds statistics, transient detection, similarity, and survivor analysis.",
        status: "future",
        owner: "Engine bridge",
      },
    ],
    metrics: [
      {
        metricId: "track-a-peak",
        label: "Peak ceiling",
        valueLabel: "0.79",
        detail: "Estimated placeholder peak from seeded frame data.",
        direction: "lower-is-better",
        status: "needs-review",
      },
      {
        metricId: "track-a-rms",
        label: "Average RMS",
        valueLabel: "0.35",
        detail: "Estimated loudness body for future comparison scoring.",
        direction: "informational",
        status: "needs-review",
      },
      {
        metricId: "track-a-zcr",
        label: "Zero crossing trend",
        valueLabel: "0.09 avg",
        detail: "Future use: rough brightness/noise/transient texture clue.",
        direction: "informational",
        status: "future",
      },
    ],
    notes: [
      "This pass does not replace playback. It prepares analysis data beside playback.",
      "Frame windows are intentionally small enough to feed future transient detection.",
      "Real decode will later read AudioBuffer channel data instead of seed frames.",
    ],
  },
  {
    sourceId: "engine-suno-version",
    title: "Suno version waveform engine pass",
    sourceKind: "suno-version",
    fileLabel: "Waiting for Suno version file",
    durationMs: 2000,
    sampleRate: 48000,
    bitDepth: 24,
    channelMode: "stereo",
    channelCount: 2,
    frameSizeMs: 250,
    waveformReady: true,
    statisticsReady: true,
    transientReady: false,
    readiness: "needs-review",
    frames: [...sunoFrames],
    channelSummaries: [
      {
        channelId: "suno-left",
        label: "Left",
        peak: 0.86,
        rms: 0.36,
        averageRms: 0.36,
        minPeak: 0.54,
        maxPeak: 0.86,
        frameCount: 8,
        status: "estimated",
      },
      {
        channelId: "suno-right",
        label: "Right",
        peak: 0.84,
        rms: 0.35,
        averageRms: 0.35,
        minPeak: 0.52,
        maxPeak: 0.84,
        frameCount: 8,
        status: "estimated",
      },
    ],
    decodeSteps: [
      {
        stepId: "suno-load",
        kind: "load-file",
        label: "Load Suno version",
        detail: "Future batch mode will repeat this pass across 10 Suno versions.",
        status: "ready",
        owner: "Finder / upload source",
      },
      {
        stepId: "suno-read-buffer",
        kind: "read-buffer",
        label: "Read raw buffer",
        detail: "Engine will read the file as ArrayBuffer before decoding.",
        status: "needs-decode",
        owner: "Waveform engine",
      },
      {
        stepId: "suno-peak-map",
        kind: "peak-map",
        label: "Create peak map",
        detail: "Peak map becomes the visual waveform and the first detection layer.",
        status: "needs-analysis",
        owner: "Waveform engine",
      },
      {
        stepId: "suno-rms-map",
        kind: "rms-map",
        label: "Create RMS map",
        detail: "RMS map gives energy shape for riff grouping and survivor ranking.",
        status: "future",
        owner: "Waveform engine",
      },
    ],
    metrics: [
      {
        metricId: "suno-peak",
        label: "Peak ceiling",
        valueLabel: "0.86",
        detail: "Estimated stronger peak profile than Track A seed.",
        direction: "lower-is-better",
        status: "needs-review",
      },
      {
        metricId: "suno-rms",
        label: "Average RMS",
        valueLabel: "0.36",
        detail: "Estimated energy level for future version comparison.",
        direction: "informational",
        status: "needs-review",
      },
      {
        metricId: "suno-zcr",
        label: "Zero crossing trend",
        valueLabel: "0.10 avg",
        detail: "Future use: compare texture against original ad-lib source.",
        direction: "informational",
        status: "future",
      },
    ],
    notes: [
      "This source models the future 10-version Suno analysis pass.",
      "Survivor analysis should not start until waveform and transient summaries exist.",
      "The same engine contract can analyze Track A, Track B, stems, and renders.",
    ],
  },
];

export const multiTrackWaveformEngineWorkspace: MultiTrackWaveformEngineWorkspace = {
  workspaceId: "multi-track-waveform-engine",
  title: "Waveform Engine Foundation",
  summary:
    "Real engine starting point for decoding audio, slicing waveform frames, calculating peak/RMS shape, and feeding transient, similarity, riff, survivor, and render systems.",
  readiness: "needs-review",
  readinessLabel: "Foundation ready. Real browser decode wiring is the next engine step.",
  engineGoal:
    "Turn loaded audio into stable analysis summaries that every later multi-track engine can trust.",
  engineBoundary:
    "This layer does not decide hooks, stems, or hybrids. It only produces waveform facts.",
  sources: multiTrackWaveformEngineSources,
  engineRules: [
    "Do not let visual waveform data replace playback state.",
    "Do not score survivor hooks until waveform and transient summaries exist.",
    "Keep engine summaries deterministic so reruns produce the same result.",
    "Keep seed data separate from future decoded AudioBuffer data.",
    "Treat missing audio as needs-audio, not as a failed engine result.",
  ],
  nextEngineSteps: [
    "Add a browser-safe AudioBuffer decode helper.",
    "Convert channel data into fixed-size waveform frames.",
    "Calculate peak, RMS, and zero-crossing values per frame.",
    "Feed waveform summaries into transient detection.",
    "Compare waveform energy maps across Suno versions.",
  ],
};