import type { MultiTrackIdeaLineageWorkspaceState } from "./MultiTrackIdeaLineageTypes";

export const multiTrackIdeaLineageSeed: MultiTrackIdeaLineageWorkspaceState = {
  id: "multi-track-idea-lineage-workspace",
  title: "Idea Lineage",
  description:
    "Seed-safe lineage layer for tracing one original musical idea through 10 Suno versions, including mutations, descendants, and strongest survivor choices.",
  readinessStatus: "ready",
  activeBranchId: "branch-main-hook-lineage",
  activeNodeId: "node-hook-v02",
  guardrailNotes: [
    "No page wiring yet.",
    "No analyzer claim is final until waveform evidence exists.",
    "Lineage is a planning map only.",
    "Survivor choices remain reviewable before extraction or rendering.",
  ],
  nodes: [
    {
      id: "node-original-hook",
      title: "Original Hook A",
      versionId: "original",
      ideaKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 0,
        endSeconds: 8,
        label: "Original phone idea",
      },
      summary: "User-origin hook idea before Suno generation.",
      parentNodeId: null,
      childNodeIds: ["node-hook-v01", "node-hook-v02", "node-hook-v03"],
      mutationKind: "preserved",
      confidenceBucket: "verified",
      readinessStatus: "ready",
    },
    {
      id: "node-hook-v01",
      title: "Hook V01 Descendant",
      versionId: "version-01",
      ideaKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Baseline hook",
      },
      summary: "First generated descendant of the original hook.",
      parentNodeId: "node-original-hook",
      childNodeIds: [],
      mutationKind: "preserved",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "node-hook-v02",
      title: "Hook V02 Survivor",
      versionId: "version-02",
      ideaKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 44,
        endSeconds: 53,
        label: "Strong hook",
      },
      summary: "Strongest current descendant and best survivor candidate.",
      parentNodeId: "node-original-hook",
      childNodeIds: ["node-hook-v08"],
      mutationKind: "expanded",
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "node-hook-v03",
      title: "Hook V03 Review",
      versionId: "version-03",
      ideaKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Review hook",
      },
      summary: "Related descendant with weaker certainty.",
      parentNodeId: "node-original-hook",
      childNodeIds: [],
      mutationKind: "rhythm-shifted",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "node-hook-v08",
      title: "Hook V08 Mutation",
      versionId: "version-08",
      ideaKind: "hook",
      color: "blue",
      timeRange: {
        startSeconds: 47,
        endSeconds: 56,
        label: "Late hook mutation",
      },
      summary: "Possible later mutation descended from V02.",
      parentNodeId: "node-hook-v02",
      childNodeIds: [],
      mutationKind: "key-shifted",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "node-bass-v05",
      title: "Bass Motion V05",
      versionId: "version-05",
      ideaKind: "bass-motion",
      color: "green",
      timeRange: {
        startSeconds: 16,
        endSeconds: 25,
        label: "Bass motion",
      },
      summary: "Bass motion may support the same hook lineage.",
      parentNodeId: null,
      childNodeIds: [],
      mutationKind: "instrument-shifted",
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "node-vocal-v07",
      title: "Vocal Phrase V07",
      versionId: "version-07",
      ideaKind: "vocal-phrase",
      color: "purple",
      timeRange: {
        startSeconds: 58,
        endSeconds: 67,
        label: "Vocal phrase",
      },
      summary: "Vocal phrase may carry lyric or phonetic memory.",
      parentNodeId: null,
      childNodeIds: [],
      mutationKind: "lyric-shifted",
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  scores: [
    {
      id: "score-original-hook",
      nodeId: "node-original-hook",
      label: "Origin confidence",
      detail: "Manual user-origin source.",
      value: 100,
      confidenceBucket: "verified",
    },
    {
      id: "score-hook-v01-lineage",
      nodeId: "node-hook-v01",
      label: "Lineage match",
      detail: "Preserves original hook identity.",
      value: 84,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v02-lineage",
      nodeId: "node-hook-v02",
      label: "Lineage match",
      detail: "Strongest hook survivor.",
      value: 92,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v02-edit",
      nodeId: "node-hook-v02",
      label: "Edit usefulness",
      detail: "Best candidate for extraction and render.",
      value: 87,
      confidenceBucket: "strong",
    },
    {
      id: "score-hook-v03-lineage",
      nodeId: "node-hook-v03",
      label: "Lineage match",
      detail: "Related but rhythm-shifted.",
      value: 72,
      confidenceBucket: "moderate",
    },
    {
      id: "score-hook-v08-lineage",
      nodeId: "node-hook-v08",
      label: "Lineage match",
      detail: "Possible mutation from V02.",
      value: 67,
      confidenceBucket: "moderate",
    },
    {
      id: "score-bass-v05-support",
      nodeId: "node-bass-v05",
      label: "Support role",
      detail: "May support hook lineage but is not the hook itself.",
      value: 63,
      confidenceBucket: "moderate",
    },
    {
      id: "score-vocal-v07-memory",
      nodeId: "node-vocal-v07",
      label: "Phrase memory",
      detail: "Needs phonetic analyzer later.",
      value: 54,
      confidenceBucket: "weak",
    },
  ],
  risks: [
    {
      id: "risk-lineage-missing-waveform",
      riskKind: "missing-waveform",
      label: "Missing waveform evidence",
      detail: "Lineage map is seed-safe until real analysis confirms matches.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-lineage-conflict",
      riskKind: "conflicting-lineage",
      label: "Conflicting lineage",
      detail: "Multiple versions may appear related until scoring improves.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-lineage-future-analyzer",
      riskKind: "future-analyzer",
      label: "Future analyzer required",
      detail: "Real lineage confidence needs melody/rhythm/structure analysis.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-lineage-manual-review",
      riskKind: "manual-review",
      label: "Manual review",
      detail: "User ears should approve survivor choices.",
      severity: "medium",
      isBlocking: false,
    },
  ],
  branches: [
    {
      id: "branch-main-hook-lineage",
      title: "Main Hook Lineage",
      detail: "Original hook traced through generated descendants.",
      rootNodeId: "node-original-hook",
      nodeIds: [
        "node-original-hook",
        "node-hook-v01",
        "node-hook-v02",
        "node-hook-v03",
        "node-hook-v08",
      ],
      survivorNodeId: "node-hook-v02",
      color: "blue",
      riskIds: [
        "risk-lineage-missing-waveform",
        "risk-lineage-future-analyzer",
      ],
      readinessStatus: "ready",
    },
    {
      id: "branch-groove-support-lineage",
      title: "Groove Support Lineage",
      detail: "Bass or groove material that may support the main idea.",
      rootNodeId: "node-bass-v05",
      nodeIds: ["node-bass-v05"],
      survivorNodeId: "node-bass-v05",
      color: "green",
      riskIds: ["risk-lineage-manual-review"],
      readinessStatus: "needs-review",
    },
    {
      id: "branch-vocal-memory-lineage",
      title: "Vocal Memory Lineage",
      detail: "Vocal or lyric phrase memory held for future phonetic review.",
      rootNodeId: "node-vocal-v07",
      nodeIds: ["node-vocal-v07"],
      survivorNodeId: null,
      color: "purple",
      riskIds: [
        "risk-lineage-manual-review",
        "risk-lineage-future-analyzer",
      ],
      readinessStatus: "needs-review",
    },
  ],
  lanes: [
    {
      id: "lane-lineage-survivors",
      label: "Survivors",
      detail: "Lineages with a strongest surviving idea.",
      color: "blue",
      branchIds: ["branch-main-hook-lineage"],
      readinessStatus: "ready",
    },
    {
      id: "lane-lineage-support",
      label: "Support Ideas",
      detail: "Ideas that support the main hook but need review.",
      color: "green",
      branchIds: ["branch-groove-support-lineage"],
      readinessStatus: "needs-review",
    },
    {
      id: "lane-lineage-review",
      label: "Review",
      detail: "Lineages waiting for user or analyzer confidence.",
      color: "yellow",
      branchIds: ["branch-vocal-memory-lineage"],
      readinessStatus: "needs-review",
    },
  ],
};