import type {
  MultiTrackComparisonFinding,
  MultiTrackComparisonGuardrail,
  MultiTrackComparisonMetric,
  MultiTrackComparisonWorkflowStep,
  MultiTrackComparisonWorkspaceState,
} from "./MultiTrackComparisonIntelligenceTypes";

export const multiTrackComparisonMetrics: MultiTrackComparisonMetric[] = [
  {
    id: "tempo-match-metric",
    lane: "tempo",
    label: "Tempo Match",
    sourceId: "both",
    status: "needs-review",
    confidence: "manual-required",
    currentMeaning: "Track A and Track B need manual BPM relationship approval.",
    futureMeaning: "Future analysis can calculate tempo drift, anchor BPM, and section tempo variance.",
  },
  {
    id: "key-relationship-metric",
    lane: "key",
    label: "Key Relationship",
    sourceId: "both",
    status: "needs-review",
    confidence: "manual-required",
    currentMeaning: "The user decides same key, relative key, pivot key, or contrast key.",
    futureMeaning: "Future analysis can detect pitch center and harmonic compatibility.",
  },
  {
    id: "structure-overlap-metric",
    lane: "structure",
    label: "Structure Overlap",
    sourceId: "both",
    status: "future",
    confidence: "low",
    currentMeaning: "Structure comparison is planning-only until section detection exists.",
    futureMeaning: "Future analyzer can compare intro, verse, hook, bridge, outro, and transition maps.",
  },
  {
    id: "hook-similarity-metric",
    lane: "hook",
    label: "Hook Similarity",
    sourceId: "both",
    status: "needs-review",
    confidence: "manual-required",
    currentMeaning: "The user identifies whether hooks feel related, copied, evolved, or unrelated.",
    futureMeaning: "Future analyzer can compare contour, rhythm, repetition, and phrase placement.",
  },
  {
    id: "melody-lineage-metric",
    lane: "lineage",
    label: "Melody Lineage",
    sourceId: "both",
    status: "needs-review",
    confidence: "manual-required",
    currentMeaning: "Original ad-lib ideas must be confirmed before lineage claims.",
    futureMeaning: "Future AI can score whether Track B appears derived from Track A.",
  },
  {
    id: "rhythm-drive-metric",
    lane: "rhythm",
    label: "Rhythm Drive",
    sourceId: "both",
    status: "future",
    confidence: "low",
    currentMeaning: "Groove similarity remains manual until transient and beat-grid analysis is wired.",
    futureMeaning: "Future analyzer can compare downbeats, swing, accents, and rhythmic density.",
  },
  {
    id: "energy-shape-metric",
    lane: "energy",
    label: "Energy Shape",
    sourceId: "both",
    status: "future",
    confidence: "low",
    currentMeaning: "Energy movement can be planned visually but not scored yet.",
    futureMeaning: "Future analyzer can compare build, drop, lift, breakdown, and final chorus intensity.",
  },
  {
    id: "stem-role-metric",
    lane: "stem",
    label: "Stem Role",
    sourceId: "both",
    status: "future",
    confidence: "low",
    currentMeaning: "Stem role comparison waits for reliable labels or future separation.",
    futureMeaning: "Future analyzer can compare drums, bass, vocal, melody, harmony, and texture roles.",
  },
];

export const multiTrackComparisonFindings: MultiTrackComparisonFinding[] = [
  {
    id: "finding-original-vs-produced",
    lane: "lineage",
    title: "Original Idea vs Produced Result",
    status: "needs-review",
    confidence: "manual-required",
    trackAObservation: "Track A may represent the raw phone/ad-lib/source idea.",
    trackBObservation: "Track B may represent the produced Suno/result version.",
    comparisonMeaning: "This comparison helps decide whether Track B kept, changed, or replaced the original idea.",
    requiredConfirmation: "User confirms that Track A is the original source and Track B is the produced result.",
  },
  {
    id: "finding-hook-placement",
    lane: "hook",
    title: "Hook Placement Comparison",
    status: "needs-review",
    confidence: "manual-required",
    trackAObservation: "Track A may contain the first hook, riff, or vocal phrase.",
    trackBObservation: "Track B may place the hook in a stronger chorus or repeated section.",
    comparisonMeaning: "This prepares future hook mapping without claiming automatic similarity.",
    requiredConfirmation: "User confirms which hook is the keeper.",
  },
  {
    id: "finding-section-balance",
    lane: "arrangement",
    title: "Section Balance Comparison",
    status: "future",
    confidence: "low",
    trackAObservation: "Track A may be shorter, looser, or idea-focused.",
    trackBObservation: "Track B may be longer, arranged, or finished.",
    comparisonMeaning: "Future arrangement tools can compare section balance and decide what to borrow.",
    requiredConfirmation: "Section boundaries must be confirmed or detected.",
  },
  {
    id: "finding-groove-compatibility",
    lane: "rhythm",
    title: "Groove Compatibility",
    status: "future",
    confidence: "low",
    trackAObservation: "Track A may have the original rhythmic feel.",
    trackBObservation: "Track B may have a generated groove or tighter production feel.",
    comparisonMeaning: "Future groove comparison can decide whether tracks can be blended or should remain separate.",
    requiredConfirmation: "Beat grid and transient ownership must be available first.",
  },
  {
    id: "finding-key-emotion",
    lane: "key",
    title: "Key and Emotional Fit",
    status: "needs-review",
    confidence: "manual-required",
    trackAObservation: "Track A key may carry the original emotional color.",
    trackBObservation: "Track B key may be shifted, polished, or more singable.",
    comparisonMeaning: "User decides whether emotional fit matters more than exact key match.",
    requiredConfirmation: "User confirms same-key, transpose, pivot, or contrast strategy.",
  },
];

export const multiTrackComparisonWorkflowSteps: MultiTrackComparisonWorkflowStep[] = [
  {
    id: "step-identify-source-role",
    label: "Identify Source Role",
    owner: "user",
    status: "needs-review",
    purpose: "Decide whether Track A is source, Track B is result, or both are equal references.",
    blockedUntil: "User confirms track roles.",
  },
  {
    id: "step-compare-tempo-key",
    label: "Compare Tempo / Key",
    owner: "manual-review",
    status: "needs-review",
    purpose: "Approve tempo and key relationship before any hybrid or confidence claim.",
    blockedUntil: "User confirms tempo/key relationship.",
  },
  {
    id: "step-map-hooks",
    label: "Map Hooks",
    owner: "user",
    status: "needs-review",
    purpose: "Mark which hook, riff, or melody idea matters most.",
    blockedUntil: "User confirms hook ownership.",
  },
  {
    id: "step-check-arrangement",
    label: "Check Arrangement",
    owner: "future-analyzer",
    status: "future",
    purpose: "Compare sections after structure analysis is available.",
    blockedUntil: "Section detection or manual section markers exist.",
  },
  {
    id: "step-score-lineage",
    label: "Score Lineage",
    owner: "future-ai",
    status: "future",
    purpose: "Estimate whether one song appears derived from another.",
    blockedUntil: "Melody, rhythm, structure, and phrase data exist.",
  },
];

export const multiTrackComparisonGuardrails: MultiTrackComparisonGuardrail[] = [
  {
    id: "guard-no-lineage-claims",
    label: "No Automatic Lineage Claims",
    rule: "Do not claim Track B came from Track A without user confirmation and future analysis.",
    status: "ready",
  },
  {
    id: "guard-no-audio-mutation",
    label: "No Audio Mutation",
    rule: "This workspace cannot process, render, save, merge, or alter audio.",
    status: "ready",
  },
  {
    id: "guard-no-duplicate-state",
    label: "No Duplicate Track State",
    rule: "This branch only displays seed planning data and does not own loaded track state.",
    status: "ready",
  },
  {
    id: "guard-user-first",
    label: "User First",
    rule: "All musical meaning decisions stay under user control until future tools are approved.",
    status: "ready",
  },
  {
    id: "guard-future-analyzer",
    label: "Future Analyzer Boundary",
    rule: "Analyzer ownership is described here but not implemented here.",
    status: "future",
  },
];

export const multiTrackComparisonWorkspaceState: MultiTrackComparisonWorkspaceState = {
  title: "Comparison Intelligence Workspace",
  description:
    "Read-only planning layer for comparing Track A and Track B across tempo, key, structure, hook, melody, rhythm, energy, stems, arrangement, and lineage.",
  metrics: multiTrackComparisonMetrics,
  findings: multiTrackComparisonFindings,
  workflowSteps: multiTrackComparisonWorkflowSteps,
  guardrails: multiTrackComparisonGuardrails,
};