
import type {
  MultiTrackKeeperComparisonPair,
  MultiTrackKeeperComparisonRank,
  MultiTrackKeeperComparisonVersion,
  MultiTrackKeeperComparisonWorkspaceState,
} from "./MultiTrackKeeperComparisonTypes";

export const multiTrackKeeperComparisonVersions: MultiTrackKeeperComparisonVersion[] = [
  {
    id: "keeper-comparison-original-phone",
    title: "Original phone riff",
    versionLabel: "Original",
    sourceKind: "original-phone-idea",
    role: "original",
    readinessStatus: "needs-review",
    decision: "hold",
    originalIdeaMatchScore: 100,
    hookPreservationScore: 100,
    mutationDistanceScore: 0,
    survivorScore: 80,
    arrangementScore: 66,
    extractionScore: 74,
    colorPath: "blue-original",
    signals: [
      {
        id: "signal-original-hook",
        kind: "hook-match",
        label: "Original Hook Anchor",
        score: 100,
        maxScore: 100,
        band: "excellent",
        detail: "This is the human anchor for comparing all Suno versions.",
      },
      {
        id: "signal-original-rhythm",
        kind: "rhythm-match",
        label: "Original Rhythm",
        score: 100,
        maxScore: 100,
        band: "excellent",
        detail: "Seed-safe baseline rhythm match.",
      },
      {
        id: "signal-original-extraction",
        kind: "survivor-strength",
        label: "Extraction Potential",
        score: 74,
        maxScore: 100,
        band: "strong",
        detail: "Useful for future extraction once real audio analysis is wired.",
      },
    ],
    strengths: [
      "Human source idea",
      "Best reference for lineage comparison",
      "Strong memory anchor",
    ],
    risks: [
      "Phone audio may be noisy",
      "Needs manual confirmation",
      "No real analyzer wired yet",
    ],
    notes: [
      "Original version stays held, not archived.",
      "All comparison math is seed-safe and isolated.",
    ],
  },
  {
    id: "keeper-comparison-suno-v03",
    title: "Suno V03 hook keeper",
    versionLabel: "Suno V03",
    sourceKind: "suno-version",
    role: "strongest-hook",
    readinessStatus: "ready",
    decision: "promote",
    originalIdeaMatchScore: 91,
    hookPreservationScore: 96,
    mutationDistanceScore: 24,
    survivorScore: 95,
    arrangementScore: 92,
    extractionScore: 90,
    colorPath: "gold-keeper",
    signals: [
      {
        id: "signal-v03-hook-match",
        kind: "hook-match",
        label: "Hook Match",
        score: 96,
        maxScore: 100,
        band: "excellent",
        detail: "Preserves the core hook while improving the generated performance.",
      },
      {
        id: "signal-v03-melody",
        kind: "melody-match",
        label: "Melody Match",
        score: 91,
        maxScore: 100,
        band: "excellent",
        detail: "Closest seed-safe generated version to the original melodic idea.",
      },
      {
        id: "signal-v03-survivor",
        kind: "survivor-strength",
        label: "Survivor Strength",
        score: 95,
        maxScore: 100,
        band: "excellent",
        detail: "Best overall keeper candidate for promotion.",
      },
    ],
    strengths: [
      "Best hook preservation",
      "Strong survivor score",
      "Ready for keeper promotion",
      "Good extraction candidate",
    ],
    risks: [
      "Needs future real waveform confirmation",
      "Seed math only for now",
    ],
    notes: [
      "Primary keeper comparison winner.",
      "Feeds naturally into Keeper Engine promotion queue later.",
    ],
  },
  {
    id: "keeper-comparison-suno-v07",
    title: "Suno V07 bridge mutation",
    versionLabel: "Suno V07",
    sourceKind: "suno-version",
    role: "best-mutation",
    readinessStatus: "needs-review",
    decision: "review",
    originalIdeaMatchScore: 76,
    hookPreservationScore: 72,
    mutationDistanceScore: 62,
    survivorScore: 81,
    arrangementScore: 88,
    extractionScore: 70,
    colorPath: "purple-mutation",
    signals: [
      {
        id: "signal-v07-mutation",
        kind: "mutation-distance",
        label: "Useful Mutation",
        score: 62,
        maxScore: 100,
        band: "medium",
        detail: "Farther from the original, but useful for bridge or alternate section.",
      },
      {
        id: "signal-v07-structure",
        kind: "structure-match",
        label: "Structure Use",
        score: 88,
        maxScore: 100,
        band: "strong",
        detail: "Strong arrangement candidate even though it is not the closest match.",
      },
      {
        id: "signal-v07-energy",
        kind: "energy-match",
        label: "Energy Match",
        score: 82,
        maxScore: 100,
        band: "strong",
        detail: "Keeps useful energy for future edit lanes.",
      },
    ],
    strengths: [
      "Good bridge candidate",
      "Interesting mutation",
      "Strong arrangement usefulness",
    ],
    risks: [
      "Less direct hook match",
      "Needs human review before promotion",
    ],
    notes: [
      "Not the main keeper.",
      "Good candidate for edit lane or arrangement section.",
    ],
  },
  {
    id: "keeper-comparison-suno-v10",
    title: "Suno V10 polished render",
    versionLabel: "Suno V10",
    sourceKind: "reference-bounce",
    role: "arrangement-candidate",
    readinessStatus: "future",
    decision: "hold",
    originalIdeaMatchScore: 68,
    hookPreservationScore: 70,
    mutationDistanceScore: 48,
    survivorScore: 78,
    arrangementScore: 86,
    extractionScore: 64,
    colorPath: "green-render",
    signals: [
      {
        id: "signal-v10-polish",
        kind: "energy-match",
        label: "Polished Energy",
        score: 86,
        maxScore: 100,
        band: "strong",
        detail: "Useful polished reference for a later render or arrangement queue.",
      },
      {
        id: "signal-v10-hook",
        kind: "hook-match",
        label: "Hook Carryover",
        score: 70,
        maxScore: 100,
        band: "medium",
        detail: "Still related to the original, but less direct than V03.",
      },
      {
        id: "signal-v10-structure",
        kind: "structure-match",
        label: "Structure Fit",
        score: 84,
        maxScore: 100,
        band: "strong",
        detail: "Useful for future arrangement reference.",
      },
    ],
    strengths: [
      "Polished reference",
      "Good arrangement score",
      "Useful future render candidate",
    ],
    risks: [
      "Not closest to original",
      "Future-only until real render queue exists",
    ],
    notes: [
      "Hold for future render comparison.",
      "Do not wire to render queue yet.",
    ],
  },
  {
    id: "keeper-comparison-suno-v02",
    title: "Suno V02 weak pass",
    versionLabel: "Suno V02",
    sourceKind: "suno-version",
    role: "archive-candidate",
    readinessStatus: "ready",
    decision: "archive",
    originalIdeaMatchScore: 42,
    hookPreservationScore: 38,
    mutationDistanceScore: 71,
    survivorScore: 32,
    arrangementScore: 28,
    extractionScore: 22,
    colorPath: "red-archive",
    signals: [
      {
        id: "signal-v02-hook",
        kind: "hook-match",
        label: "Hook Loss",
        score: 38,
        maxScore: 100,
        band: "weak",
        detail: "Seed placeholder for a generated pass that drifted away from the original idea.",
      },
      {
        id: "signal-v02-survivor",
        kind: "survivor-strength",
        label: "Low Survivor Strength",
        score: 32,
        maxScore: 100,
        band: "weak",
        detail: "Low candidate for keeper promotion.",
      },
      {
        id: "signal-v02-mutation",
        kind: "mutation-distance",
        label: "High Drift",
        score: 71,
        maxScore: 100,
        band: "medium",
        detail: "Mutated too far without becoming useful.",
      },
    ],
    strengths: [
      "Useful negative comparison",
      "Good archive example",
    ],
    risks: [
      "Weak hook",
      "Poor extraction candidate",
      "Not a keeper",
    ],
    notes: [
      "Archive candidate placeholder.",
      "Useful for teaching the future engine what not to promote.",
    ],
  },
];

export const multiTrackKeeperComparisonPairs: MultiTrackKeeperComparisonPair[] = [
  {
    id: "keeper-pair-original-v03",
    leftVersionId: "keeper-comparison-original-phone",
    rightVersionId: "keeper-comparison-suno-v03",
    label: "Original → Suno V03",
    sharedIdeaScore: 91,
    mutationDifferenceScore: 24,
    recommendation: "promote",
    detail: "Best direct keeper path from the original idea into a generated Suno version.",
  },
  {
    id: "keeper-pair-original-v07",
    leftVersionId: "keeper-comparison-original-phone",
    rightVersionId: "keeper-comparison-suno-v07",
    label: "Original → Suno V07",
    sharedIdeaScore: 76,
    mutationDifferenceScore: 62,
    recommendation: "review",
    detail: "Useful mutation, but should be reviewed before keeper promotion.",
  },
  {
    id: "keeper-pair-v03-v10",
    leftVersionId: "keeper-comparison-suno-v03",
    rightVersionId: "keeper-comparison-suno-v10",
    label: "Suno V03 → Suno V10",
    sharedIdeaScore: 73,
    mutationDifferenceScore: 48,
    recommendation: "hold",
    detail: "V10 may be useful as a polished arrangement reference, not the primary keeper.",
  },
  {
    id: "keeper-pair-original-v02",
    leftVersionId: "keeper-comparison-original-phone",
    rightVersionId: "keeper-comparison-suno-v02",
    label: "Original → Suno V02",
    sharedIdeaScore: 42,
    mutationDifferenceScore: 71,
    recommendation: "archive",
    detail: "Too much drift and not enough useful survivor strength.",
  },
];

export const multiTrackKeeperComparisonRanks: MultiTrackKeeperComparisonRank[] = [
  {
    id: "keeper-rank-v03",
    versionId: "keeper-comparison-suno-v03",
    rank: 1,
    label: "Best Keeper",
    score: 94,
    reason: "Best hook preservation, best survivor strength, strong extraction score.",
  },
  {
    id: "keeper-rank-original",
    versionId: "keeper-comparison-original-phone",
    rank: 2,
    label: "Best Anchor",
    score: 84,
    reason: "Original human idea remains the comparison anchor.",
  },
  {
    id: "keeper-rank-v07",
    versionId: "keeper-comparison-suno-v07",
    rank: 3,
    label: "Best Mutation",
    score: 78,
    reason: "Useful bridge mutation and arrangement candidate.",
  },
  {
    id: "keeper-rank-v10",
    versionId: "keeper-comparison-suno-v10",
    rank: 4,
    label: "Polished Reference",
    score: 73,
    reason: "Good render reference, but not the closest keeper.",
  },
  {
    id: "keeper-rank-v02",
    versionId: "keeper-comparison-suno-v02",
    rank: 5,
    label: "Archive",
    score: 32,
    reason: "Weak hook preservation and low survivor score.",
  },
];

export const multiTrackKeeperComparisonWorkspaceState: MultiTrackKeeperComparisonWorkspaceState = {
  id: "multi-track-keeper-comparison-workspace",
  title: "Keeper Comparison",
  description:
    "Seed-safe isolated comparison layer for checking which Suno version stayed closest to the original idea, which one mutated usefully, and which one should become the keeper.",
  readinessStatus: "ready",
  originalVersionId: "keeper-comparison-original-phone",
  versions: multiTrackKeeperComparisonVersions,
  pairs: multiTrackKeeperComparisonPairs,
  ranks: multiTrackKeeperComparisonRanks,
  notes: [
    "No controller wiring.",
    "No page wiring.",
    "No route wiring.",
    "No imports outside this 4-file comparison set.",
    "Designed to feed the Keeper Engine later without importing it now.",
  ],
};