import type {
  MultiTrackPatternGenomeWorkspaceState,
} from "./MultiTrackPatternGenomeTypes";

export const multiTrackPatternGenomeSeed: MultiTrackPatternGenomeWorkspaceState = {
  id: "pattern-genome-workspace",
  title: "Pattern Genome",
  description:
    "Seed workspace for finding the same musical idea across 10 Suno versions before color-code, extract, edit, duplicate, and render tools are wired.",
  readinessStatus: "ready",
  activeIdeaId: "idea-main-hook",
  guardrailNotes: [
    "No page wiring yet.",
    "No audio rendering yet.",
    "All analyzer items are seed-safe until real waveform/DSP evidence is connected.",
    "Use this as the planning layer for repeated musical ideas across versions.",
  ],
  sources: [
    {
      id: "source-version-01",
      versionId: "version-01",
      sourceKind: "suno-version",
      title: "Suno Version 01",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for first generated version."],
    },
    {
      id: "source-version-02",
      versionId: "version-02",
      sourceKind: "suno-version",
      title: "Suno Version 02",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for second generated version."],
    },
    {
      id: "source-version-03",
      versionId: "version-03",
      sourceKind: "suno-version",
      title: "Suno Version 03",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for third generated version."],
    },
    {
      id: "source-version-04",
      versionId: "version-04",
      sourceKind: "suno-version",
      title: "Suno Version 04",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for fourth generated version."],
    },
    {
      id: "source-version-05",
      versionId: "version-05",
      sourceKind: "suno-version",
      title: "Suno Version 05",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for fifth generated version."],
    },
    {
      id: "source-version-06",
      versionId: "version-06",
      sourceKind: "suno-version",
      title: "Suno Version 06",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for sixth generated version."],
    },
    {
      id: "source-version-07",
      versionId: "version-07",
      sourceKind: "suno-version",
      title: "Suno Version 07",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for seventh generated version."],
    },
    {
      id: "source-version-08",
      versionId: "version-08",
      sourceKind: "suno-version",
      title: "Suno Version 08",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for eighth generated version."],
    },
    {
      id: "source-version-09",
      versionId: "version-09",
      sourceKind: "suno-version",
      title: "Suno Version 09",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for ninth generated version."],
    },
    {
      id: "source-version-10",
      versionId: "version-10",
      sourceKind: "suno-version",
      title: "Suno Version 10",
      artistLabel: "User catalog",
      fileLabel: "Waiting for loaded audio",
      bpm: null,
      keyLabel: null,
      durationSeconds: null,
      readinessStatus: "needs-review",
      notes: ["Placeholder for tenth generated version."],
    },
  ],
  signals: [
    {
      id: "signal-main-hook-contour",
      signalKind: "melody-contour",
      label: "Main hook contour",
      detail:
        "Same up-down melodic shape appears across multiple generated versions.",
      weight: 95,
      confidenceBucket: "strong",
    },
    {
      id: "signal-main-hook-rhythm",
      signalKind: "rhythm-shape",
      label: "Main hook rhythm",
      detail:
        "Short-long-short rhythmic shape can be reused as a matching fingerprint.",
      weight: 88,
      confidenceBucket: "strong",
    },
    {
      id: "signal-main-hook-section",
      signalKind: "section-position",
      label: "Hook section position",
      detail:
        "Idea lands near chorus or post-chorus location in several versions.",
      weight: 74,
      confidenceBucket: "moderate",
    },
    {
      id: "signal-bass-motion",
      signalKind: "chord-anchor",
      label: "Bass/chord anchor",
      detail:
        "Low-end motion appears to support the same musical identity.",
      weight: 68,
      confidenceBucket: "moderate",
    },
    {
      id: "signal-vocal-phrase",
      signalKind: "lyric-phrase",
      label: "Vocal phrase memory",
      detail:
        "Lyric or syllable placement may preserve the user original idea.",
      weight: 63,
      confidenceBucket: "moderate",
    },
  ],
  evidence: [
    {
      id: "evidence-hook-v01",
      sourceId: "source-version-01",
      versionId: "version-01",
      timeRange: {
        startSeconds: 42,
        endSeconds: 50,
        label: "Approx hook region",
      },
      signalIds: [
        "signal-main-hook-contour",
        "signal-main-hook-rhythm",
        "signal-main-hook-section",
      ],
      summary: "Seed evidence for the main hook in version 01.",
      confidenceBucket: "strong",
      reviewerNote: "Manual review needed after waveform analyzer is connected.",
    },
    {
      id: "evidence-hook-v02",
      sourceId: "source-version-02",
      versionId: "version-02",
      timeRange: {
        startSeconds: 44,
        endSeconds: 52,
        label: "Approx hook region",
      },
      signalIds: [
        "signal-main-hook-contour",
        "signal-main-hook-rhythm",
        "signal-main-hook-section",
      ],
      summary: "Seed evidence for the main hook in version 02.",
      confidenceBucket: "strong",
      reviewerNote: "Manual review needed after waveform analyzer is connected.",
    },
    {
      id: "evidence-hook-v03",
      sourceId: "source-version-03",
      versionId: "version-03",
      timeRange: {
        startSeconds: 39,
        endSeconds: 48,
        label: "Approx hook region",
      },
      signalIds: ["signal-main-hook-contour", "signal-main-hook-rhythm"],
      summary: "Seed evidence for the main hook in version 03.",
      confidenceBucket: "moderate",
      reviewerNote: "Timing may drift until BPM/section map is real.",
    },
    {
      id: "evidence-bass-v05",
      sourceId: "source-version-05",
      versionId: "version-05",
      timeRange: {
        startSeconds: 16,
        endSeconds: 24,
        label: "Intro groove",
      },
      signalIds: ["signal-bass-motion"],
      summary: "Seed evidence for matching bass motion in version 05.",
      confidenceBucket: "moderate",
      reviewerNote: "Useful for future stem extraction comparison.",
    },
    {
      id: "evidence-vocal-v07",
      sourceId: "source-version-07",
      versionId: "version-07",
      timeRange: {
        startSeconds: 58,
        endSeconds: 66,
        label: "Vocal phrase",
      },
      signalIds: ["signal-vocal-phrase"],
      summary: "Seed evidence for a repeated vocal phrase in version 07.",
      confidenceBucket: "weak",
      reviewerNote: "Needs lyric/phonetic analyzer later.",
    },
  ],
  risks: [
    {
      id: "risk-no-real-audio",
      riskKind: "missing-audio",
      label: "No real audio connected",
      detail:
        "This layer is seed-safe only until actual uploaded Suno versions are attached.",
      severity: "medium",
      isBlocking: false,
    },
    {
      id: "risk-future-engine",
      riskKind: "future-engine-required",
      label: "Future DSP required",
      detail:
        "Real extraction, duplication, and render need waveform/DSP wiring later.",
      severity: "high",
      isBlocking: false,
    },
    {
      id: "risk-review-needed",
      riskKind: "manual-review-needed",
      label: "Manual review needed",
      detail:
        "Pattern Genome should never auto-claim a match without confidence evidence.",
      severity: "medium",
      isBlocking: false,
    },
  ],
  actions: [
    {
      id: "action-hook-color",
      actionKind: "color-code",
      label: "Color-code main hook",
      detail:
        "Mark all detected main hook regions blue for quick visual scanning.",
      readinessStatus: "ready",
      targetIdeaId: "idea-main-hook",
    },
    {
      id: "action-hook-extract",
      actionKind: "extract",
      label: "Extract hook candidates",
      detail:
        "Future action: cut all hook matches into editable clips.",
      readinessStatus: "future",
      targetIdeaId: "idea-main-hook",
    },
    {
      id: "action-hook-duplicate",
      actionKind: "duplicate",
      label: "Duplicate strongest hook",
      detail:
        "Future action: duplicate the best hook take into another arrangement lane.",
      readinessStatus: "future",
      targetIdeaId: "idea-main-hook",
    },
    {
      id: "action-bass-color",
      actionKind: "color-code",
      label: "Color-code bass motion",
      detail:
        "Mark bass/chord motion green for later stem comparison.",
      readinessStatus: "ready",
      targetIdeaId: "idea-bass-motion",
    },
    {
      id: "action-vocal-hold",
      actionKind: "hold",
      label: "Hold vocal phrase",
      detail:
        "Keep vocal phrase under review until lyric/phonetic analyzer exists.",
      readinessStatus: "needs-review",
      targetIdeaId: "idea-vocal-phrase",
    },
  ],
  ideas: [
    {
      id: "idea-main-hook",
      title: "Main Hook Genome",
      role: "hook",
      color: "blue",
      summary:
        "The main musical idea that should be detected across the 10 Suno versions.",
      primaryVersionId: "version-01",
      matchedVersionIds: ["version-01", "version-02", "version-03"],
      evidenceIds: ["evidence-hook-v01", "evidence-hook-v02", "evidence-hook-v03"],
      riskIds: ["risk-no-real-audio", "risk-future-engine"],
      actionIds: ["action-hook-color", "action-hook-extract", "action-hook-duplicate"],
      confidenceBucket: "strong",
      readinessStatus: "ready",
    },
    {
      id: "idea-bass-motion",
      title: "Bass Motion Genome",
      role: "bass-motion",
      color: "green",
      summary:
        "A repeated low-end or chord movement that may survive across versions.",
      primaryVersionId: "version-05",
      matchedVersionIds: ["version-05"],
      evidenceIds: ["evidence-bass-v05"],
      riskIds: ["risk-no-real-audio"],
      actionIds: ["action-bass-color"],
      confidenceBucket: "moderate",
      readinessStatus: "needs-review",
    },
    {
      id: "idea-vocal-phrase",
      title: "Vocal Phrase Genome",
      role: "vocal-phrase",
      color: "purple",
      summary:
        "A lyric, syllable, or melodic vocal phrase that may carry the user original idea.",
      primaryVersionId: "version-07",
      matchedVersionIds: ["version-07"],
      evidenceIds: ["evidence-vocal-v07"],
      riskIds: ["risk-review-needed"],
      actionIds: ["action-vocal-hold"],
      confidenceBucket: "weak",
      readinessStatus: "needs-review",
    },
  ],
  comparisons: [
    {
      id: "comparison-hook-v01-v02",
      ideaId: "idea-main-hook",
      fromVersionId: "version-01",
      toVersionId: "version-02",
      similarityPercent: 86,
      sharedSignals: ["melody-contour", "rhythm-shape", "section-position"],
      differenceSummary:
        "Version 02 appears to preserve the hook with a slight timing shift.",
      confidenceBucket: "strong",
    },
    {
      id: "comparison-hook-v01-v03",
      ideaId: "idea-main-hook",
      fromVersionId: "version-01",
      toVersionId: "version-03",
      similarityPercent: 74,
      sharedSignals: ["melody-contour", "rhythm-shape"],
      differenceSummary:
        "Version 03 appears related but needs stronger section mapping.",
      confidenceBucket: "moderate",
    },
    {
      id: "comparison-bass-v05-v01",
      ideaId: "idea-bass-motion",
      fromVersionId: "version-05",
      toVersionId: "version-01",
      similarityPercent: 51,
      sharedSignals: ["chord-anchor"],
      differenceSummary:
        "Possible harmonic relationship only; not enough for auto-promotion.",
      confidenceBucket: "weak",
    },
  ],
  renderTargets: [
    {
      id: "render-hook-wav",
      ideaId: "idea-main-hook",
      label: "Render main hook WAV",
      detail:
        "Future output target for the strongest hook clip after extraction.",
      sourceVersionIds: ["version-01", "version-02", "version-03"],
      targetFormat: "wav",
      readinessStatus: "future",
    },
    {
      id: "render-hook-stems",
      ideaId: "idea-main-hook",
      label: "Render hook stems",
      detail:
        "Future output target for stem-safe hook sections.",
      sourceVersionIds: ["version-01", "version-02", "version-03"],
      targetFormat: "stems",
      readinessStatus: "future",
    },
  ],
  lanes: [
    {
      id: "lane-hooks",
      label: "Hooks",
      detail: "Repeated top-line or chorus ideas.",
      ideaIds: ["idea-main-hook"],
      color: "blue",
      readinessStatus: "ready",
    },
    {
      id: "lane-groove",
      label: "Groove",
      detail: "Bass, drums, and pocket identity.",
      ideaIds: ["idea-bass-motion"],
      color: "green",
      readinessStatus: "needs-review",
    },
    {
      id: "lane-vocal",
      label: "Vocal",
      detail: "Vocal phrase and phonetic memory.",
      ideaIds: ["idea-vocal-phrase"],
      color: "purple",
      readinessStatus: "needs-review",
    },
  ],
};