import type {
  MultiTrackPromptExportChecklistItem,
  MultiTrackPromptExportGate,
  MultiTrackPromptExportPlan,
  MultiTrackPromptExportPreviewCard,
  MultiTrackPromptExportRiskItem,
  MultiTrackPromptExportWorkspaceState,
} from "./MultiTrackPromptExportIntelligenceTypes";

export const multiTrackPromptExportGates: MultiTrackPromptExportGate[] = [
  {
    id: "gate-track-a",
    label: "Track A Notes Gate",
    source: "track-a",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    requirement: "Track A notes must be confirmed before export text can describe source meaning.",
    missingBehavior: "Use a question instead of a fact claim.",
  },
  {
    id: "gate-track-b",
    label: "Track B Notes Gate",
    source: "track-b",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    requirement: "Track B notes must be confirmed before export text can describe result meaning.",
    missingBehavior: "Use a question instead of a fact claim.",
  },
  {
    id: "gate-comparison",
    label: "Comparison Gate",
    source: "comparison",
    status: "needs-review",
    confidence: "manual-required",
    owner: "manual-review",
    requirement: "Comparison language must stay separate from lineage claims.",
    missingBehavior: "Describe possible similarity only as review language.",
  },
  {
    id: "gate-confidence",
    label: "Confidence Gate",
    source: "confidence",
    status: "ready",
    confidence: "high",
    owner: "manual-review",
    requirement: "Export must respect confidence status and never inflate certainty.",
    missingBehavior: "Default to manual review and block automatic truth language.",
  },
  {
    id: "gate-ai-prompt",
    label: "AI Prompt Gate",
    source: "ai-prompt",
    status: "needs-review",
    confidence: "manual-required",
    owner: "manual-review",
    requirement: "AI prompt text must be reviewed before being copied into any generator.",
    missingBehavior: "Show draft-only language.",
  },
  {
    id: "gate-hybrid-plan",
    label: "Hybrid Plan Gate",
    source: "hybrid-plan",
    status: "future",
    confidence: "low",
    owner: "future-hybrid-builder",
    requirement: "Hybrid export requires confirmed merge direction and user approval.",
    missingBehavior: "Block builder instructions.",
  },
  {
    id: "gate-manual-note",
    label: "Manual Note Gate",
    source: "manual-note",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    requirement: "User notes are allowed, but still need clear fact/suggestion separation.",
    missingBehavior: "Ask the user what should be treated as confirmed.",
  },
  {
    id: "gate-future-analysis",
    label: "Future Analysis Gate",
    source: "future-analysis",
    status: "future",
    confidence: "low",
    owner: "future-analyzer",
    requirement: "Future analysis can support export only after analyzer data exists.",
    missingBehavior: "Do not mention analyzer results.",
  },
];

export const multiTrackPromptExportPlans: MultiTrackPromptExportPlan[] = [
  {
    id: "plan-suno-plain-text",
    label: "Suno Plain Text Export",
    target: "suno",
    format: "plain-text",
    status: "needs-review",
    confidence: "manual-required",
    owner: "user",
    purpose: "Prepare clean prompt text that the user can copy into Suno after review.",
    allowedSources: ["track-a", "track-b", "manual-note", "confidence", "ai-prompt"],
    exportRule: "Separate confirmed facts from creative suggestions.",
    blockedUntil: "User approves wording.",
  },
  {
    id: "plan-project-note",
    label: "Project Note Export",
    target: "project-note",
    format: "structured-note",
    status: "future",
    confidence: "low",
    owner: "future-exporter",
    purpose: "Send approved prompt context into a future project note.",
    allowedSources: ["track-a", "track-b", "comparison", "manual-note"],
    exportRule: "Do not write to project storage until export layer exists.",
    blockedUntil: "Project note export wiring exists.",
  },
  {
    id: "plan-library-note",
    label: "Library Note Export",
    target: "library-note",
    format: "structured-note",
    status: "future",
    confidence: "low",
    owner: "future-exporter",
    purpose: "Attach reviewed prompt context to future library metadata notes.",
    allowedSources: ["track-a", "track-b", "manual-note", "confidence"],
    exportRule: "No Supabase writes from this read-only panel.",
    blockedUntil: "Library note export wiring exists.",
  },
  {
    id: "plan-hybrid-builder",
    label: "Hybrid Builder Instruction Export",
    target: "hybrid-builder",
    format: "builder-instruction",
    status: "future",
    confidence: "low",
    owner: "future-hybrid-builder",
    purpose: "Prepare future instructions for combining confirmed parts of Track A and Track B.",
    allowedSources: ["hybrid-plan", "comparison", "confidence", "manual-note"],
    exportRule: "No builder command until user confirms merge direction.",
    blockedUntil: "Hybrid builder exists and user approves direction.",
  },
  {
    id: "plan-training-log",
    label: "Training Feedback Export",
    target: "training-log",
    format: "training-feedback",
    status: "future",
    confidence: "low",
    owner: "future-ai",
    purpose: "Capture why a user-approved prompt or hybrid direction worked.",
    allowedSources: ["manual-note", "confidence", "ai-prompt"],
    exportRule: "Training feedback cannot override future user choices.",
    blockedUntil: "Training log system exists.",
  },
  {
    id: "plan-manual-copy",
    label: "Manual Copy Export",
    target: "manual-copy",
    format: "plain-text",
    status: "ready",
    confidence: "high",
    owner: "user",
    purpose: "Allow safe read-only display for user copy and paste.",
    allowedSources: ["manual-note", "confidence", "ai-prompt"],
    exportRule: "User manually decides what leaves the app.",
    blockedUntil: "Nothing; read-only copy is allowed.",
  },
  {
    id: "plan-future-export-api",
    label: "Future Export API",
    target: "future-export-api",
    format: "structured-note",
    status: "future",
    confidence: "low",
    owner: "future-exporter",
    purpose: "Reserve a future API export target without wiring it yet.",
    allowedSources: ["confidence", "ai-prompt", "future-analysis"],
    exportRule: "API export must be blocked until permissions and review rules exist.",
    blockedUntil: "Future export API is designed.",
  },
];

export const multiTrackPromptExportRisks: MultiTrackPromptExportRiskItem[] = [
  {
    id: "risk-user-approval",
    risk: "missing-user-approval",
    label: "Missing User Approval",
    status: "needs-review",
    owner: "user",
    detail: "Export text cannot be treated as final until the user approves it.",
    preventionRule: "Keep export preview read-only and label draft content clearly.",
  },
  {
    id: "risk-confidence",
    risk: "missing-confidence",
    label: "Missing Confidence Context",
    status: "needs-review",
    owner: "manual-review",
    detail: "Export text must not hide low confidence or missing evidence.",
    preventionRule: "Always include confidence safety language for review/future items.",
  },
  {
    id: "risk-invented-bpm",
    risk: "invented-bpm",
    label: "Invented BPM",
    status: "ready",
    owner: "manual-review",
    detail: "Prompt export must not invent tempo, BPM lock, or sync claims.",
    preventionRule: "Use BPM only when confirmed by user or future analyzer.",
  },
  {
    id: "risk-invented-key",
    risk: "invented-key",
    label: "Invented Key",
    status: "ready",
    owner: "manual-review",
    detail: "Prompt export must not invent key center or harmonic compatibility.",
    preventionRule: "Use key only when confirmed or mark as unknown.",
  },
  {
    id: "risk-false-lineage",
    risk: "false-lineage",
    label: "False Lineage",
    status: "ready",
    owner: "user",
    detail: "Export must not claim Track B came from Track A without confirmation.",
    preventionRule: "Use comparison questions, not lineage assertions.",
  },
  {
    id: "risk-false-stem-label",
    risk: "false-stem-label",
    label: "False Stem Label",
    status: "future",
    owner: "future-analyzer",
    detail: "Future stem export cannot label stems without evidence.",
    preventionRule: "Block stem claims until labels or DSP evidence exist.",
  },
  {
    id: "risk-builder-command",
    risk: "unsafe-builder-command",
    label: "Unsafe Builder Command",
    status: "future",
    owner: "future-hybrid-builder",
    detail: "The future builder cannot receive commands until confidence gates pass.",
    preventionRule: "Keep builder instructions blocked until user approval.",
  },
  {
    id: "risk-unreviewed-ai",
    risk: "unreviewed-ai-output",
    label: "Unreviewed AI Output",
    status: "needs-review",
    owner: "manual-review",
    detail: "AI text should be treated as draft language until reviewed.",
    preventionRule: "Show draft labels and require review for export.",
  },
];

export const multiTrackPromptExportChecklist: MultiTrackPromptExportChecklistItem[] = [
  {
    id: "check-family-types",
    label: "Types Match Export Family",
    status: "ready",
    owner: "manual-review",
    detail: "Seed, Helpers, and Panel import only MultiTrackPromptExportIntelligenceTypes.",
  },
  {
    id: "check-no-audio",
    label: "No Audio Processing",
    status: "ready",
    owner: "manual-review",
    detail: "Prompt export planning does not touch audio, DSP, transport, or runtime state.",
  },
  {
    id: "check-no-supabase",
    label: "No Supabase Writes",
    status: "ready",
    owner: "manual-review",
    detail: "This workspace is display-only and does not save exports.",
  },
  {
    id: "check-user-approval",
    label: "User Approval Required",
    status: "needs-review",
    owner: "user",
    detail: "Actual export wording must be approved by the user.",
  },
  {
    id: "check-future-api",
    label: "Future API Blocked",
    status: "future",
    owner: "future-exporter",
    detail: "API export is reserved but intentionally not wired.",
  },
];

export const multiTrackPromptExportPreviewCards: MultiTrackPromptExportPreviewCard[] = [
  {
    id: "preview-suno",
    label: "Suno Draft Preview",
    target: "suno",
    format: "plain-text",
    status: "needs-review",
    summary: "A copy-ready prompt draft can be displayed after user review.",
    safeOutputExample:
      "Use only confirmed notes. Describe the mood, groove, hook direction, and arrangement goal. Mark unknown BPM or key as unknown.",
  },
  {
    id: "preview-project-note",
    label: "Project Note Preview",
    target: "project-note",
    format: "structured-note",
    status: "future",
    summary: "Future project notes can store approved prompt decisions.",
    safeOutputExample:
      "Confirmed facts, suggestions, unanswered questions, and safety notes remain separated.",
  },
  {
    id: "preview-hybrid-builder",
    label: "Hybrid Builder Preview",
    target: "hybrid-builder",
    format: "builder-instruction",
    status: "future",
    summary: "Future builder instructions remain blocked until merge direction is approved.",
    safeOutputExample:
      "Do not merge automatically. Wait for user-approved hook, tempo/key, and section strategy.",
  },
  {
    id: "preview-training",
    label: "Training Feedback Preview",
    target: "training-log",
    format: "training-feedback",
    status: "future",
    summary: "Future training feedback captures why a decision worked.",
    safeOutputExample:
      "User approved this because the hook, groove, and chorus lift matched the intended song direction.",
  },
];

export const multiTrackPromptExportWorkspaceState: MultiTrackPromptExportWorkspaceState = {
  title: "Prompt Export Intelligence Workspace",
  description:
    "Read-only export planning layer for moving approved prompt language toward Suno, project notes, library notes, hybrid builder instructions, manual copy, and future export APIs without inventing musical facts.",
  gates: multiTrackPromptExportGates,
  plans: multiTrackPromptExportPlans,
  risks: multiTrackPromptExportRisks,
  checklist: multiTrackPromptExportChecklist,
  previewCards: multiTrackPromptExportPreviewCards,
};