"use client";
import { useEffect, useState } from "react";
import { loadDawPrivateClipRepair, saveDawPrivateClipRepair, type DawPrivateAudioLane, type DawPrivateClipRepair } from "@/app/workspace/projects/[id]/projectDawApi";

const button = "rounded-lg border border-white/20 bg-white px-2 py-1 font-black text-black disabled:opacity-40";
export default function TimelineDawPrivateClipRepairEditor({ sessionId, lane, onChange }: { sessionId: string; lane: DawPrivateAudioLane; onChange?: (repair: DawPrivateClipRepair) => void }) {
  const [repair, setRepair] = useState<DawPrivateClipRepair>(), [frame, setFrame] = useState(0), [gainDb, setGainDb] = useState(0), [startFrame, setStartFrame] = useState(0), [endFrame, setEndFrame] = useState(Math.min(lane.audio.frameCount, lane.audio.sampleRate)), [lowHz, setLowHz] = useState(100), [highHz, setHighHz] = useState(8000), [attenuationDb, setAttenuationDb] = useState(-12), [busy, setBusy] = useState(false), [error, setError] = useState<string>();
  useEffect(() => { let active = true; void loadDawPrivateClipRepair(sessionId, lane.id).then(({ repair: stored }) => { if (active) { setRepair(stored); onChange?.(stored); } }).catch((cause) => { if (active) setError(cause instanceof Error ? cause.message : "Clip repair could not be loaded."); }); return () => { active = false; }; }, [lane.id, sessionId]); // A parent notification must not retrigger persistence loading.
  const run = async (next: DawPrivateClipRepair, action: "save" | "undo" | "redo" = "save") => { setBusy(true); setError(undefined); try { const { repair: saved } = await saveDawPrivateClipRepair(sessionId, next, action); setRepair(saved); onChange?.(saved); } catch (cause) { setError(cause instanceof Error ? cause.message : "Clip repair could not be saved."); } finally { setBusy(false); } };
  if (!repair) return <div className="mt-3 text-xs text-white/45">{error ?? "Loading clip repair…"}</div>;
  const maxFrame = Math.round((lane.sourceOutSeconds - lane.sourceInSeconds) * lane.audio.sampleRate), addGain = () => void run({ ...repair, gainPoints: [...repair.gainPoints.filter((point) => point.frame !== frame), { frame, gainDb }].sort((a, b) => a.frame - b.frame) }), addRepair = () => void run({ ...repair, spectralRepairs: [...repair.spectralRepairs, { id: crypto.randomUUID(), startFrame, endFrame, lowHz, highHz, attenuationDb, bypassed: false, provenance: "manual spectral selection" }] });
  return <div className="mt-3 rounded-xl border border-cyan-300/20 bg-cyan-300/[.04] p-3 text-xs"><div className="flex flex-wrap items-center gap-2"><strong>Clip Gain & Spectral Repair</strong><span>rev {repair.revision} · {repair.checksum.slice(0, 18)}…</span><button className={button} disabled={busy} onClick={() => void run({ ...repair, bypassed: !repair.bypassed })}>{repair.bypassed ? "Enable" : "Bypass"}</button><button className={button} disabled={busy} onClick={() => void run(repair, "undo")}>Undo</button><button className={button} disabled={busy} onClick={() => void run(repair, "redo")}>Redo</button>{error ? <span className="text-red-200">{error}</span> : null}</div><div className="mt-2 flex flex-wrap items-end gap-2"><label>Frame<input className="ml-1 w-24 bg-black" type="number" min={0} max={maxFrame} value={frame} onChange={(event) => setFrame(Number(event.target.value))} /></label><label>Gain dB<input className="ml-1 w-20 bg-black" type="number" min={-96} max={24} step={0.1} value={gainDb} onChange={(event) => setGainDb(Number(event.target.value))} /></label><button className={button} disabled={busy} onClick={addGain}>Add Point</button>{repair.gainPoints.map((point) => <button className="rounded bg-white/10 px-2 py-1" key={point.frame} onClick={() => void run({ ...repair, gainPoints: repair.gainPoints.filter((item) => item.frame !== point.frame) })}>{point.frame}: {point.gainDb} dB ×</button>)}</div><div className="mt-2 flex flex-wrap items-end gap-2"><label>Start<input className="ml-1 w-24 bg-black" type="number" min={0} max={maxFrame} value={startFrame} onChange={(event) => setStartFrame(Number(event.target.value))} /></label><label>End<input className="ml-1 w-24 bg-black" type="number" min={1} max={maxFrame} value={endFrame} onChange={(event) => setEndFrame(Number(event.target.value))} /></label><label>Low Hz<input className="ml-1 w-20 bg-black" type="number" min={20} value={lowHz} onChange={(event) => setLowHz(Number(event.target.value))} /></label><label>High Hz<input className="ml-1 w-20 bg-black" type="number" max={lane.audio.sampleRate / 2} value={highHz} onChange={(event) => setHighHz(Number(event.target.value))} /></label><label>Atten dB<input className="ml-1 w-20 bg-black" type="number" min={-96} max={0} value={attenuationDb} onChange={(event) => setAttenuationDb(Number(event.target.value))} /></label><button className={button} disabled={busy} onClick={addRepair}>Add Repair</button>{repair.spectralRepairs.map((item) => <button title={`${item.lowHz}-${item.highHz} Hz · ${item.provenance}`} className="rounded bg-white/10 px-2 py-1" key={item.id} onClick={() => void run({ ...repair, spectralRepairs: repair.spectralRepairs.map((candidate) => candidate.id === item.id ? { ...candidate, bypassed: !candidate.bypassed } : candidate) })}>{item.startFrame}-{item.endFrame} · {item.attenuationDb} dB {item.bypassed ? "(off)" : ""}</button>)}</div></div>;
}
