"use client";

import { useMemo, useState } from "react";
import { assessTimelineDawChromeRecoveryQa, normalizeTimelineDawChromeRecoveryQaEvidence, TIMELINE_DAW_CHROME_RECOVERY_QA_CHECKS, TIMELINE_DAW_CHROME_RECOVERY_QA_LABELS, timelineDawChromeRecoveryQaStorageKey, type TimelineDawChromeRecoveryQaCheck, type TimelineDawChromeRecoveryQaEvidence } from "@/lib/timeline/TimelineDawChromeRecoveryQaPolicy";

export default function TimelineDawChromeRecoveryQaWorkspace({ sessionId }: { sessionId: string }) {
  const [userAgent] = useState(() => typeof navigator === "undefined" ? "" : navigator.userAgent);
  const [evidence, setEvidence] = useState<Partial<Record<TimelineDawChromeRecoveryQaCheck, TimelineDawChromeRecoveryQaEvidence>>>(() => { try { return typeof window === "undefined" ? {} : normalizeTimelineDawChromeRecoveryQaEvidence(JSON.parse(window.localStorage.getItem(timelineDawChromeRecoveryQaStorageKey(sessionId)) ?? "{}")); } catch { return {}; } });
  const report = useMemo(() => assessTimelineDawChromeRecoveryQa({ userAgent, evidence }), [evidence, userAgent]);
  const update = (check: TimelineDawChromeRecoveryQaCheck, result: TimelineDawChromeRecoveryQaEvidence) => { const next = { ...evidence, [check]: result }; setEvidence(next); try { window.localStorage.setItem(timelineDawChromeRecoveryQaStorageKey(sessionId), JSON.stringify(normalizeTimelineDawChromeRecoveryQaEvidence(next))); } catch {} };
  const clear = () => { setEvidence({}); try { window.localStorage.removeItem(timelineDawChromeRecoveryQaStorageKey(sessionId)); } catch {} };
  const status = report.status === "passed" ? "CHROME RECOVERY PRODUCTION EVIDENCE COMPLETE" : report.status === "chrome-required" ? "GOOGLE CHROME REQUIRED—EDGE IS NOT ACCEPTED" : report.status === "needs-review" ? "HELD—ISSUES MUST BE RETESTED" : "REAL CHROME RECOVERY TRIALS IN PROGRESS";
  return <section className="mt-4 rounded-2xl border border-sky-300/25 bg-sky-300/[0.05] p-4">
    <p className="text-xs font-black uppercase tracking-wider text-sky-200">Long-session Chrome recovery QA</p><h3 className="mt-1 text-lg font-black">Complete ten real recovery trials</h3><p className="mt-1 text-sm text-white/60">Run these trials in Google Chrome on the real production site. Edge and automated simulations cannot qualify this leaf.</p>
    <div className="mt-3 rounded-lg border border-white/15 p-3"><p className="font-black">Detected browser</p><p className={report.chrome ? "mt-1 text-emerald-200" : "mt-1 text-amber-200"}>{report.chrome ? `${report.chrome.browser} ${report.chrome.version}` : "Not Google Chrome or browser identity unavailable"}</p></div>
    <div className="mt-3 space-y-2">{TIMELINE_DAW_CHROME_RECOVERY_QA_CHECKS.map((check, index) => <div className="grid gap-2 rounded-lg border border-white/10 p-3 sm:grid-cols-[1fr_auto_auto]" key={check}><p className="text-sm"><b>{index + 1}.</b> {TIMELINE_DAW_CHROME_RECOVERY_QA_LABELS[check]}</p><button type="button" className={`rounded-lg border px-3 py-1 font-black ${evidence[check] === "pass" ? "border-emerald-300 bg-emerald-300 text-black" : "border-white/25"}`} onClick={() => update(check, "pass")}>REAL TEST PASSED</button><button type="button" className={`rounded-lg border px-3 py-1 font-black ${evidence[check] === "issue" ? "border-rose-300 bg-rose-300 text-black" : "border-white/25"}`} onClick={() => update(check, "issue")}>ISSUE FOUND</button></div>)}</div>
    <div className={`mt-3 rounded-lg border p-3 ${report.status === "passed" ? "border-emerald-300/40 text-emerald-100" : report.status === "needs-review" ? "border-rose-300/40 text-rose-100" : "border-amber-300/40 text-amber-100"}`}><p className="font-black">{status}</p><p className="mt-1 text-sm">{report.passedChecks.length}/10 passed · {report.remainingChecks.length} remaining · {report.issues.length} issues</p>{report.status === "passed" ? <p className="mt-1 text-sm">This exact Google Chrome version passed every required long-session recovery trial.</p> : null}<p className="mt-2 text-xs font-bold">Only pass/issue markers are remembered for this session so reload trials can be completed. No audio, names, paths, checkpoints, history, or private content are stored by this QA panel.</p><button type="button" className="mt-3 rounded-lg border border-white/25 px-3 py-1 font-black" onClick={clear}>Clear QA Evidence</button></div>
  </section>;
}
