"use client";

import { useMemo, useState } from "react";
import { assessTimelineDawChromeMidiProductionQa, identifyTimelineDawGoogleChrome, TIMELINE_DAW_CHROME_MIDI_QA_CHECKS, TIMELINE_DAW_CHROME_MIDI_QA_LABELS, type TimelineDawChromeMidiQaCheck } from "@/lib/timeline/TimelineDawChromeMidiProductionQaPolicy";

export default function TimelineDawChromeMidiProductionQaWorkspace() {
  const [userAgent] = useState(() => typeof navigator === "undefined" ? "" : navigator.userAgent);
  const [deviceName, setDeviceName] = useState("");
  const [evidence, setEvidence] = useState<Partial<Record<TimelineDawChromeMidiQaCheck, "pass" | "issue">>>({});
  const chrome = identifyTimelineDawGoogleChrome(userAgent);
  const report = useMemo(() => assessTimelineDawChromeMidiProductionQa({ userAgent, deviceName, evidence }), [userAgent, deviceName, evidence]);
  const status = report.status === "passed" ? "CHROME MIDI PRODUCTION EVIDENCE COMPLETE" : report.status === "chrome-required" ? "GOOGLE CHROME REQUIRED" : report.status === "hardware-required" ? "PHYSICAL MIDI CONTROLLER REQUIRED" : report.status === "needs-review" ? "HELD FOR REVIEW" : "REAL-WORLD QUALIFICATION IN PROGRESS";
  return <div className="mt-3 rounded-xl border border-sky-200/20 bg-black/25 p-3">
    <p className="text-[11px] font-black uppercase tracking-wider text-sky-200">Chrome MIDI production QA</p><p className="mt-1 text-base font-black">Complete twelve real browser and hardware trials</p><p className="mt-1 text-sm text-white/60">Evidence remains only in this tab. Browser capability or automated tests cannot substitute for musician-confirmed physical-controller trials.</p>
    <div className="mt-3 grid gap-2 md:grid-cols-2"><div className="rounded-lg border border-white/15 p-3"><p className="font-black">Detected browser</p><p className={chrome ? "mt-1 text-emerald-200" : "mt-1 text-amber-200"}>{chrome ? `${chrome.browser} ${chrome.version}` : "Not Google Chrome or browser identity unavailable"}</p></div><label className="font-black">Physical MIDI controller name<input className="mt-1 block w-full rounded-lg border border-white/20 bg-black px-3 py-2 text-white" value={deviceName} maxLength={160} onChange={(event) => setDeviceName(event.target.value)} placeholder="Required real device" /></label></div>
    <div className="mt-3 space-y-2">{TIMELINE_DAW_CHROME_MIDI_QA_CHECKS.map((check, index) => <div className="grid gap-2 rounded-lg border border-white/10 p-3 sm:grid-cols-[1fr_auto_auto]" key={check}><p className="text-sm"><b>{index + 1}.</b> {TIMELINE_DAW_CHROME_MIDI_QA_LABELS[check]}</p><button type="button" className={`rounded-lg border px-3 py-1 font-black ${evidence[check] === "pass" ? "border-emerald-300 bg-emerald-300 text-black" : "border-white/25"}`} onClick={() => setEvidence((current) => ({ ...current, [check]: "pass" }))}>REAL TEST PASSED</button><button type="button" className={`rounded-lg border px-3 py-1 font-black ${evidence[check] === "issue" ? "border-rose-300 bg-rose-300 text-black" : "border-white/25"}`} onClick={() => setEvidence((current) => ({ ...current, [check]: "issue" }))}>ISSUE FOUND</button></div>)}</div>
    <div className={`mt-3 rounded-lg border p-3 ${report.status === "passed" ? "border-emerald-300/40 text-emerald-100" : report.status === "needs-review" ? "border-rose-300/40 text-rose-100" : "border-amber-300/40 text-amber-100"}`}><p className="font-black">{status}</p><p className="mt-1 text-sm">{report.passedChecks.length}/12 passed · {report.remainingChecks.length} remaining · {report.issues.length} issues</p>{report.status === "needs-review" ? <p className="mt-1 text-sm">Resolve every issue and repeat that physical trial before qualification.</p> : null}{report.status === "passed" ? <p className="mt-1 text-sm">The named controller and this exact Google Chrome version passed every required MIDI production trial.</p> : null}<p className="mt-2 text-xs font-bold">Private MIDI sources remain preserved. This report does not store MIDI, device data, or session content.</p></div>
  </div>;
}
