"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";
import TimelineDawMidiBabyStepHelp from "./TimelineDawMidiBabyStepHelp";
import TimelineDawThirdPartyInstrumentCompatibilityWorkspace from "./TimelineDawThirdPartyInstrumentCompatibilityWorkspace";
import TimelineDawChromeMidiProductionQaWorkspace from "./TimelineDawChromeMidiProductionQaWorkspace";

type TempoPoint={tick:number;bpm:number};
type Note={id:string;pitch:number;velocity:number;startTick:number;durationTicks:number;channel:number};
type Controller={id:string;controller:number;value:number;tick:number;channel:number};
type PitchBend={id:string;tick:number;value:number;channel:number};
type ProgramChange={id:string;tick:number;program:number;channel:number};
type RackLayer={id:string;waveform:OscillatorType;octave:number;detuneCents:number;gain:number;pan:number;attack:number;release:number;filterHz:number};type Rack={id:string;name:string;version:number;layers:RackLayer[]};type ControllerTemplate={id:string;name:string;controller:number;channel:number;defaultValue:number};type MidiAutomation={id:string;parameter:"expression"|"modulation"|"pitchBend"|"filter"|"gain";channel:number;points:Array<{id:string;tick:number;value:number}>};type Artifact={checksum:string;renderedRevision:number;stale:boolean};
type Clip={id:string;name:string;revision:number;ppq:number;lengthTicks:number;startTick:number;instrument:{waveform:OscillatorType;attack:number;release:number;gain:number;maxVoices:number;busId:string|null};notes:Note[];controllers:Controller[];pitchBends:PitchBend[];programChanges:ProgramChange[];rackPresetId:string|null;rackPresetVersion:number|null;midiAutomation:MidiAutomation[];programMap:Array<{channel:number;program:number;rackPresetId:string}>;frozen:boolean;frozenRecipeChecksum:string|null;checksum:string;provenance:string|null;artifact:Artifact|null};
type Bus={id:string;name:string;mix:{gain:number;pan:number;muted:boolean}};
const field="rounded-lg border border-white/20 bg-black px-2 py-1";
const button="rounded-lg border border-white/25 bg-white px-2 py-1 font-black text-black disabled:opacity-40";
const tickSeconds=(tick:number,ppq:number,map:TempoPoint[])=>{let seconds=0,prior=map[0]??{tick:0,bpm:120};for(const point of map.slice(1).sort((a,b)=>a.tick-b.tick)){if(tick<=point.tick)break;seconds+=(point.tick-prior.tick)*60/(prior.bpm*ppq);prior=point}return seconds+(tick-prior.tick)*60/(prior.bpm*ppq)};
const latest=<T extends {tick:number}>(events:T[],tick:number)=>events.filter(event=>event.tick<=tick).sort((a,b)=>b.tick-a.tick)[0];

export default function TimelineDawPrivateMidiSequencer({sessionId}:{sessionId:string}){
  const[clips,setClips]=useState<Clip[]>([]);
  const[buses,setBuses]=useState<Bus[]>([]);const[racks,setRacks]=useState<Rack[]>([]),[templates,setTemplates]=useState<ControllerTemplate[]>([]);
  const[selected,setSelected]=useState("");
  const[tempoMap,setTempoMap]=useState<TempoPoint[]>([{tick:0,bpm:120}]);
  const[pitch,setPitch]=useState(60),[velocity,setVelocity]=useState(100),[tick,setTick]=useState(0),[duration,setDuration]=useState(480);
  const[controller,setController]=useState(64),[controllerValue,setControllerValue]=useState(127);
  const[bend,setBend]=useState(0),[program,setProgram]=useState(0),[automationParameter,setAutomationParameter]=useState<MidiAutomation["parameter"]>("expression"),[automationValue,setAutomationValue]=useState(1);
  const[error,setError]=useState<string>(),[message,setMessage]=useState<string>();
  const voices=useRef<Array<{osc:OscillatorNode;gain:GainNode;context:AudioContext}>>([]);

  const token=async()=>{const{data}=await requireProjectSupabase().auth.getSession();return data.session?.access_token??""};
  const request=useCallback(async(body?:Record<string,unknown>)=>{const response=await fetch("/api/timeline/daw-private-midi"+(body?"":"?sessionId="+encodeURIComponent(sessionId)),{method:body?"POST":"GET",headers:{Authorization:"Bearer "+await token(),...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify({sessionId,...body}):undefined}),json=await response.json();if(!response.ok)throw Error(json.error);if(json.clips)setClips(json.clips);if(json.clip)setClips(current=>[...current.filter(item=>item.id!==json.clip.id),json.clip].sort((a,b)=>a.startTick-b.startTick));return json},[sessionId]);
  useEffect(()=>{void request().catch(cause=>setError(cause.message))},[request]);
  useEffect(()=>{void token().then(access=>fetch("/api/timeline/daw-midi-racks?sessionId="+encodeURIComponent(sessionId),{headers:{Authorization:"Bearer "+access}})).then(response=>response.json()).then(json=>{setRacks(json.presets??[]);setTemplates(json.templates??[])}).catch(cause=>setError(cause.message))},[sessionId]);useEffect(()=>{void token().then(access=>fetch("/api/timeline/daw-private-buses?sessionId="+encodeURIComponent(sessionId),{headers:{Authorization:"Bearer "+access}})).then(response=>response.json()).then(json=>setBuses(json.buses??[])).catch(cause=>setError(cause.message))},[sessionId]);
  const clip=clips.find(item=>item.id===selected)??clips[0];
  const save=(patch:Partial<Clip>,action="save")=>clip?request({action,clipId:clip.id,expectedRevision:clip.revision,...clip,...patch}).catch(cause=>setError(cause.message)):Promise.resolve();

  function stop(){for(const voice of voices.current){try{voice.osc.stop()}catch{}voice.osc.disconnect();voice.gain.disconnect();void voice.context.close()}voices.current=[]}
  const audition=useCallback((playheadSeconds=0)=>{if(!clip)return;stop();const context=new AudioContext(),now=context.currentTime+.03,bus=buses.find(item=>item.id===clip.instrument.busId),busGain=bus?.mix.muted?0:bus?.mix.gain??1,busPan=bus?.mix.pan??0,clipOrigin=tickSeconds(clip.startTick,clip.ppq,tempoMap),clipEnd=tickSeconds(clip.startTick+clip.lengthTicks,clip.ppq,tempoMap);if(playheadSeconds>=clipEnd)return;for(const note of clip.notes.slice().sort((a,b)=>a.startTick-b.startTick).slice(0,clip.instrument.maxVoices)){const noteStart=tickSeconds(clip.startTick+note.startTick,clip.ppq,tempoMap),rawEnd=note.startTick+note.durationTicks,sustainDown=clip.controllers.some(event=>event.channel===note.channel&&event.controller===64&&event.value>=64&&event.tick<=rawEnd),sustainUp=clip.controllers.filter(event=>event.channel===note.channel&&event.controller===64&&event.value<64&&event.tick>rawEnd).sort((a,b)=>a.tick-b.tick)[0],noteEnd=tickSeconds(clip.startTick+(sustainDown?sustainUp?.tick??clip.lengthTicks:rawEnd),clip.ppq,tempoMap);if(noteEnd<=playheadSeconds)continue;const osc=context.createOscillator(),gain=context.createGain(),panner=context.createStereoPanner(),start=now+Math.max(0,noteStart-playheadSeconds),end=now+Math.max(0,noteEnd-playheadSeconds),volume=(latest(clip.controllers.filter(event=>event.channel===note.channel&&event.controller===7),note.startTick)?.value??127)/127,pan=(latest(clip.controllers.filter(event=>event.channel===note.channel&&event.controller===10),note.startTick)?.value??64)/63.5-1,bendValue=latest(clip.pitchBends.filter(event=>event.channel===note.channel),note.startTick)?.value??0;osc.type=clip.instrument.waveform;osc.frequency.value=440*2**((note.pitch-69+(bendValue/8192)*2)/12);panner.pan.value=Math.max(-1,Math.min(1,pan+busPan));const level=clip.instrument.gain*note.velocity/127*volume*busGain;gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(level,start+clip.instrument.attack);gain.gain.setValueAtTime(level,end);gain.gain.linearRampToValueAtTime(0,end+clip.instrument.release);osc.connect(gain).connect(panner).connect(context.destination);osc.start(start);osc.stop(end+clip.instrument.release);voices.current.push({osc,gain,context})}},[buses,clip,tempoMap]);
  useEffect(()=>{const receive=(event:Event)=>{const detail=(event as CustomEvent<{sessionId?:string;state?:string;elapsed?:number;tempoMap?:TempoPoint[]}>).detail;if(detail?.sessionId!==sessionId)return;if(detail.tempoMap?.length)setTempoMap(detail.tempoMap);if(detail.state==="playing")audition(detail.elapsed??0);else stop()};window.addEventListener("muzes:daw-transport-state",receive);return()=>{window.removeEventListener("muzes:daw-transport-state",receive);stop()}},[audition,sessionId]);

  async function download(){if(!clip)return;try{const result=await request({action:"export",clipId:clip.id,expectedRevision:clip.revision}),anchor=document.createElement("a");anchor.href="data:audio/midi;base64,"+result.base64;anchor.download=result.fileName;anchor.click()}catch(cause){setError(cause instanceof Error?cause.message:"MIDI export failed.")}}
  async function saveRack(){const rack={name:clip?.name+" Rack",version:1,layers:[{id:"body",waveform:clip?.instrument.waveform??"triangle",octave:0,detuneCents:0,gain:clip?.instrument.gain??.25,pan:0,attack:clip?.instrument.attack??.005,release:clip?.instrument.release??.08,filterHz:12000}]};const response=await fetch("/api/timeline/daw-midi-racks",{method:"POST",headers:{Authorization:"Bearer "+await token(),"Content-Type":"application/json"},body:JSON.stringify({sessionId,rack})}),json=await response.json();if(!response.ok)throw Error(json.error);setRacks(current=>[json.preset,...current.filter(item=>item.id!==json.preset.id)]);if(clip)await save({rackPresetId:json.preset.id,rackPresetVersion:json.preset.version})}async function saveControllerTemplate(){const response=await fetch("/api/timeline/daw-midi-racks",{method:"POST",headers:{Authorization:"Bearer "+await token(),"Content-Type":"application/json"},body:JSON.stringify({sessionId,action:"save-template",name:"CC "+controller,controller,channel:1,defaultValue:controllerValue})}),json=await response.json();if(!response.ok)throw Error(json.error);setTemplates(current=>[...current.filter(item=>item.id!==json.template.id),json.template])}async function artifactAction(action:"render"|"audition"|"promote"|"freeze"|"unfreeze"){if(!clip)return;try{setError(undefined);const result=await request({action,clipId:clip.id,expectedRevision:clip.revision,tempoMap});if(action==="audition"){const audio=new Audio(result.auditionUrl);await audio.play()}setMessage(action==="render"?"Bounce is current.":action==="promote"?"Bounce promoted into a private audio lane.":action==="freeze"?"MIDI instrument frozen; source clip preserved.":action==="unfreeze"?"MIDI instrument unfrozen and editable.":"Playing private bounce.")}catch(cause){setError(cause instanceof Error?cause.message:"MIDI artifact action failed.")}}

  return <section className="mt-4 rounded-xl border border-fuchsia-300/20 bg-fuchsia-300/[.04] p-3 text-xs">
    <TimelineDawMidiBabyStepHelp sessionId={sessionId}/>
    <TimelineDawThirdPartyInstrumentCompatibilityWorkspace/>
    <TimelineDawChromeMidiProductionQaWorkspace/>
    <div className="flex flex-wrap gap-2"><strong>MIDI Sequencer & Instrument</strong>
      <label className={button}>Import MIDI<input className="hidden" type="file" accept=".mid,.midi,audio/midi" onChange={event=>{const file=event.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>void request({action:"import",name:file.name.replace(/\.(mid|midi)$/i,""),base64:String(reader.result).split(",")[1]??""}).then(result=>setSelected(result.clip.id)).catch(cause=>setError(cause.message));reader.readAsDataURL(file)}}/></label>
      <button className={button} onClick={()=>void request({action:"create",name:"MIDI Clip",ppq:480,lengthTicks:7680,startTick:0,instrument:{waveform:"triangle",attack:.005,release:.08,gain:.25,maxVoices:16,busId:null},notes:[],controllers:[],pitchBends:[],programChanges:[]}).then(result=>setSelected(result.clip.id)).catch(cause=>setError(cause.message))}>New Clip</button>
      {clips.length?<select className={field} value={clip?.id} onChange={event=>setSelected(event.target.value)}>{clips.map(item=><option key={item.id} value={item.id}>{item.name+" · rev "+item.revision}</option>)}</select>:null}
      {clip?<><button className={button} onClick={()=>audition(0)}>Audition Live</button><button className={button} onClick={stop}>Stop</button><button className={button} onClick={()=>void request({action:"quantize",clipId:clip.id,expectedRevision:clip.revision,gridTicks:clip.ppq/4,strength:1})}>Quantize 1/16</button><button className={button} onClick={()=>void request({action:"undo",clipId:clip.id,expectedRevision:clip.revision})}>Undo</button><button className={button} onClick={()=>void request({action:"redo",clipId:clip.id,expectedRevision:clip.revision})}>Redo</button><button className={button} onClick={()=>void artifactAction("render")}>Bounce WAV</button><button className={button} disabled={!clip.artifact||clip.artifact.stale} onClick={()=>void artifactAction("audition")}>Audition Bounce</button><button className={button} disabled={!clip.artifact||clip.artifact.stale} onClick={()=>void artifactAction("promote")}>Promote to Lane</button><button className={button} onClick={()=>void artifactAction(clip.frozen?"unfreeze":"freeze")}>{clip.frozen?"Unfreeze MIDI":"Freeze MIDI"}</button><button className={button} onClick={()=>void download()}>Export MIDI</button></>:null}
      {error?<span className="text-red-200">{error}</span>:message?<span className="text-emerald-200">{message}</span>:null}
    </div>
    {clip?<><div className="mt-2 flex flex-wrap items-end gap-2">
      <label>Pitch<input className={"ml-1 w-16 "+field} type="number" min={0} max={127} value={pitch} onChange={event=>setPitch(Number(event.target.value))}/></label>
      <label>Velocity<input className={"ml-1 w-16 "+field} type="number" min={1} max={127} value={velocity} onChange={event=>setVelocity(Number(event.target.value))}/></label>
      <label>Tick<input className={"ml-1 w-24 "+field} type="number" min={0} max={clip.lengthTicks-1} value={tick} onChange={event=>setTick(Number(event.target.value))}/></label>
      <label>Length<input className={"ml-1 w-20 "+field} type="number" min={1} value={duration} onChange={event=>setDuration(Number(event.target.value))}/></label>
      <button className={button} onClick={()=>void save({notes:[...clip.notes,{id:crypto.randomUUID(),pitch,velocity,startTick:tick,durationTicks:duration,channel:1}]})}>Add Note</button>
      <select className={field} value={clip.instrument.waveform} onChange={event=>void save({instrument:{...clip.instrument,waveform:event.target.value as OscillatorType}})}><option>sine</option><option>triangle</option><option>sawtooth</option><option>square</option></select>
      <select aria-label="Instrument rack" className={field} value={clip.rackPresetId??""} onChange={event=>{const rack=racks.find(item=>item.id===event.target.value);void save({rackPresetId:rack?.id??null,rackPresetVersion:rack?.version??null})}}><option value="">Single oscillator</option>{racks.map(rack=><option key={rack.id} value={rack.id}>{rack.name+" v"+rack.version}</option>)}</select><button className={button} onClick={()=>void saveRack().catch(cause=>setError(cause.message))}>Save Rack Preset</button><select aria-label="MIDI output bus" className={field} value={clip.instrument.busId??""} onChange={event=>void save({instrument:{...clip.instrument,busId:event.target.value||null}})}><option value="">Master</option>{buses.map(bus=><option key={bus.id} value={bus.id}>{bus.name}</option>)}</select>
    </div>
    <div className="mt-3 flex flex-wrap items-end gap-2 border-t border-white/10 pt-3">
      <label>Controller<input className={"ml-1 w-16 "+field} type="number" min={0} max={127} value={controller} onChange={event=>setController(Number(event.target.value))}/></label>
      <label>Value<input className={"ml-1 w-16 "+field} type="number" min={0} max={127} value={controllerValue} onChange={event=>setControllerValue(Number(event.target.value))}/></label>
      <button className={button} onClick={()=>void saveControllerTemplate().catch(cause=>setError(cause.message))}>Save CC Template</button><select aria-label="Controller template" className={field} value="" onChange={event=>{const template=templates.find(item=>item.id===event.target.value);if(template){setController(template.controller);setControllerValue(template.defaultValue)}}}><option value="">CC templates</option>{templates.map(template=><option key={template.id} value={template.id}>{template.name}</option>)}</select><button className={button} onClick={()=>void save({controllers:[...clip.controllers,{id:crypto.randomUUID(),controller,value:controllerValue,tick,channel:1}]})}>Add Controller</button>
      <label>Pitch bend<input className={"ml-1 w-24 "+field} type="number" min={-8192} max={8191} value={bend} onChange={event=>setBend(Number(event.target.value))}/></label>
      <button className={button} onClick={()=>void save({pitchBends:[...clip.pitchBends,{id:crypto.randomUUID(),tick,value:bend,channel:1}]})}>Add Bend</button>
      <label>Program<input className={"ml-1 w-16 "+field} type="number" min={0} max={127} value={program} onChange={event=>setProgram(Number(event.target.value))}/></label>
      <button className={button} onClick={()=>void save({programChanges:[...clip.programChanges,{id:crypto.randomUUID(),tick,program,channel:1}]})}>Add Program</button><select className={field} value={automationParameter} onChange={event=>setAutomationParameter(event.target.value as MidiAutomation["parameter"])}><option>expression</option><option>modulation</option><option>pitchBend</option><option>filter</option><option>gain</option></select><input aria-label="Automation value" className={"w-20 "+field} type="number" min={-1} max={1} step={.05} value={automationValue} onChange={event=>setAutomationValue(Number(event.target.value))}/><button className={button} onClick={()=>{const lane=clip.midiAutomation.find(item=>item.parameter===automationParameter&&item.channel===1),next:MidiAutomation={id:lane?.id??crypto.randomUUID(),parameter:automationParameter,channel:1,points:[...(lane?.points??[]).filter(point=>point.tick!==tick),{id:crypto.randomUUID(),tick,value:automationValue}].sort((a,b)=>a.tick-b.tick)};void save({midiAutomation:[...clip.midiAutomation.filter(item=>item.id!==next.id),next]})}}>Add Automation Point</button><button className={button} disabled={!clip.rackPresetId} onClick={()=>void save({programMap:[...clip.programMap.filter(item=>item.channel!==1||item.program!==program),{channel:1,program,rackPresetId:clip.rackPresetId!}]})}>Map Program to Rack</button>
    </div>
    <div className="mt-3 grid grid-cols-8 gap-1 rounded bg-black/40 p-2">{clip.notes.map(note=><button key={note.id} title={"MIDI "+note.pitch+", velocity "+note.velocity+", tick "+note.startTick} className="rounded bg-fuchsia-300/30 px-1 py-2" style={{gridColumnStart:Math.min(8,Math.floor(note.startTick/Math.max(1,clip.lengthTicks/8))+1)}} onClick={()=>void save({notes:clip.notes.filter(item=>item.id!==note.id)})}>{note.pitch}<br/><span className="opacity-60">{"v"+note.velocity}</span></button>)}</div>
    <div className="mt-2 flex flex-wrap gap-1">{clip.controllers.map(event=><button className={button} key={event.id} onClick={()=>void save({controllers:clip.controllers.filter(item=>item.id!==event.id)})}>{"CC"+event.controller+" "+event.value+" @"+event.tick}</button>)}{clip.pitchBends.map(event=><button className={button} key={event.id} onClick={()=>void save({pitchBends:clip.pitchBends.filter(item=>item.id!==event.id)})}>{"Bend "+event.value+" @"+event.tick}</button>)}{clip.programChanges.map(event=><button className={button} key={event.id} onClick={()=>void save({programChanges:clip.programChanges.filter(item=>item.id!==event.id)})}>{"Program "+event.program+" @"+event.tick}</button>)}</div>
    {clip.artifact?<p className={clip.artifact.stale?"mt-2 text-amber-200":"mt-2 text-emerald-200"}>{clip.artifact.stale?"Bounce is stale; render again.":"Bounce verified and current."}</p>:null}</>:<p className="mt-2 text-white/45">Create a MIDI clip to open the piano roll.</p>}
  </section>
}
