"use client";
import { useState } from "react";
import { saveDawPrivateAutomation, type DawPrivateAutomationEnvelope } from "./timelineDawPrivateAutomationApi";
const field="rounded-lg border border-white/20 bg-black px-2 py-1 text-white";
export default function TimelineDawPrivateAutomationEditor({sessionId,sources,envelopes,onChange}:{sessionId:string;sources:Array<{id:string;kind:"lane"|"bus";name:string;sampleRate:number}>;envelopes:DawPrivateAutomationEnvelope[];onChange:(items:DawPrivateAutomationEnvelope[])=>void}){
 const[sourceKey,setSourceKey]=useState(sources[0]?`${sources[0].kind}:${sources[0].id}`:"");const[parameter,setParameter]=useState<"gain"|"pan">("gain");const[busy,setBusy]=useState(false);const source=sources.find((item)=>`${item.kind}:${item.id}`===sourceKey)??sources[0];const current=source?envelopes.find((item)=>item.sourceKind===source.kind&&item.sourceId===source.id&&item.parameter===parameter):undefined;const draft=current??(source?{id:"",sourceKind:source.kind,sourceId:source.id,parameter,bypassed:false,points:[]}:undefined);
 async function persist(next:DawPrivateAutomationEnvelope){setBusy(true);try{const{envelope}=await saveDawPrivateAutomation(sessionId,{...next,id:next.id||undefined});onChange([...envelopes.filter((item)=>item.id!==envelope.id&&!(item.sourceKind===envelope.sourceKind&&item.sourceId===envelope.sourceId&&item.parameter===envelope.parameter)),envelope]);}finally{setBusy(false);}}
 function updatePoint(index:number,patch:Partial<DawPrivateAutomationEnvelope["points"][number]>){if(!draft)return;const points=draft.points.map((point,itemIndex)=>itemIndex===index?{...point,...patch}:point).sort((a,b)=>a.samplePosition-b.samplePosition);void persist({...draft,points});}
 if(!sources.length)return null;return <div className="mt-4 rounded-xl border border-cyan-300/20 bg-cyan-300/[0.06] p-3"><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-black text-white/60">Automation source<select className={`mt-1 block ${field}`} value={sourceKey||`${source?.kind}:${source?.id}`} onChange={(event)=>setSourceKey(event.target.value)}>{sources.map((item)=><option key={`${item.kind}:${item.id}`} value={`${item.kind}:${item.id}`}>{item.name}</option>)}</select></label><label className="text-xs font-black text-white/60">Parameter<select className={`mt-1 block ${field}`} value={parameter} onChange={(event)=>setParameter(event.target.value as "gain"|"pan")}><option value="gain">Gain</option><option value="pan">Pan</option></select></label><button disabled={busy||!draft} className="rounded-lg bg-cyan-200 px-3 py-2 text-xs font-black text-black disabled:opacity-40" onClick={()=>draft&&void persist({...draft,bypassed:!draft.bypassed})}>{draft?.bypassed?"Enable":"Bypass"}</button><button disabled={busy||!draft} className="rounded-lg bg-white px-3 py-2 text-xs font-black text-black disabled:opacity-40" onClick={()=>draft&&void persist({...draft,points:[...draft.points,{id:`point-${crypto.randomUUID()}`,samplePosition:(draft.points.at(-1)?.samplePosition??-source!.sampleRate)+source!.sampleRate,value:parameter==="gain"?1:0,interpolation:"linear"}]})}>Add Point (+1s)</button></div><div className="mt-2 grid gap-2">{draft?.points.map((point,index)=><div key={point.id} className="grid grid-cols-[1fr_1fr_auto_auto] gap-2"><input aria-label="Sample position" className={field} type="number" min={0} step={1} value={point.samplePosition} onChange={(event)=>updatePoint(index,{samplePosition:Number(event.target.value)})}/><input aria-label="Automation value" className={field} type="number" min={parameter==="gain"?0:-1} max={parameter==="gain"?2:1} step="0.01" value={point.value} onChange={(event)=>updatePoint(index,{value:Number(event.target.value)})}/><select aria-label="Interpolation" className={field} value={point.interpolation} onChange={(event)=>updatePoint(index,{interpolation:event.target.value as "linear"|"hold"})}><option value="linear">Linear</option><option value="hold">Hold</option></select><button className="text-xs font-black text-red-200" disabled={busy} onClick={()=>draft&&void persist({...draft,points:draft.points.filter((_,itemIndex)=>itemIndex!==index)})}>Delete</button></div>)}</div></div>;
}
