"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";
import { createTimelineDawMusicianInvitationHandoff } from "@/lib/timeline/TimelineDawMusicianInvitationHandoff";
type Invite={id:string;label:string;state:string;expires_at:string|null}; type Enrollment={id:string;state:string;acknowledgement_version:string|null;environment:Record<string,boolean>|null;tester_id:string};
type Data={invitations:Invite[];enrollments:Enrollment[];workflow:{percent:number;exportReady:boolean};integrityBlockers:number;releaseReceipts:Array<{id:string;ready:boolean}>;release?:{ready:boolean;blockers:string[];warnings:string[]}};
const field="rounded-lg border border-white/15 bg-black px-3 py-2",button="rounded-lg border border-white/20 px-3 py-2 font-black disabled:opacity-40";
export default function TimelineDawBetaOnboardingOwner({sessionId}:{sessionId:string}){
 const[data,setData]=useState<Data|null>(null),[label,setLabel]=useState(""),[invitedLabel,setInvitedLabel]=useState(""),[code,setCode]=useState(""),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 const request=useCallback(async(body?:Record<string,unknown>)=>{const token=(await requireProjectSupabase().auth.getSession()).data.session?.access_token??"",response=await fetch(body?"/api/timeline/daw-beta-onboarding":`/api/timeline/daw-beta-onboarding?sessionId=${encodeURIComponent(sessionId)}`,{method:body?"POST":"GET",headers:{Authorization:`Bearer ${token}`,...(body?{"Content-Type":"application/json"}:{})},body:body?JSON.stringify({sessionId,...body}):undefined,cache:"no-store"}),result=await response.json();if(!response.ok)throw Error(result.error);if(result.invitations)setData(result);return result},[sessionId]);
 useEffect(()=>{let active=true;queueMicrotask(()=>void request().catch(cause=>{if(active)setError(cause.message)}));return()=>{active=false}},[request]);
 const handoff=useMemo(()=>code&&typeof window!=="undefined"?createTimelineDawMusicianInvitationHandoff({label:invitedLabel,code,origin:window.location.origin}):null,[code,invitedLabel]);
 async function act(body:Record<string,unknown>){setBusy(true);setError("");setMessage("");try{return await request(body)}catch(cause){setError(cause instanceof Error?cause.message:"Beta access request failed.")}finally{setBusy(false)}}
 async function invite(){const next=label.trim(),result=await act({action:"invite",label:next});if(result?.code){setCode(result.code);setInvitedLabel(next);setLabel("");await request()}}
 async function copy(text:string,success:string){try{await navigator.clipboard.writeText(text);setMessage(success)}catch{setError("Copy was blocked. Select the message and copy it manually.")}}
 return <section className="rounded-3xl border border-sky-300/25 bg-sky-300/[.04] p-5"><p className="text-xs font-black uppercase tracking-[.22em] text-sky-200">First musician guest pass</p><h2 className="mt-1 text-2xl font-black">Create, copy, enroll, release</h2><ol className="mt-3 grid gap-2 text-sm text-white/75 sm:grid-cols-4"><li><b>1.</b> Create guest pass</li><li><b>2.</b> Send full message</li><li><b>3.</b> Musician completes setup</li><li><b>4.</b> Run release gate</li></ol><div className="mt-3 flex flex-wrap gap-2"><input className={field} value={label} onChange={event=>setLabel(event.target.value)} placeholder="Musician first name or private label"/><button className={button} disabled={busy||label.trim().length<2} onClick={()=>void invite()}>Create Non-Expiring Guest Pass</button></div>
 {handoff?<div className="mt-4 rounded-xl border border-amber-300/30 bg-black/30 p-4"><b>Send this complete message now</b><p className="mt-1 text-xs text-amber-200">The non-expiring guest pass is shown only during this handoff. Copy the full message before leaving.</p><textarea className="mt-3 min-h-96 w-full rounded-lg border border-white/15 bg-black p-3 text-sm" readOnly value={`Subject: ${handoff.subject}\n\n${handoff.message}`}/><div className="mt-2 flex flex-wrap gap-2"><button className={button} onClick={()=>void copy(`Subject: ${handoff.subject}\n\n${handoff.message}`,"Full musician invitation copied.")}>Copy Full Invitation</button><button className={button} onClick={()=>void copy(code,"Guest pass copied.")}>Copy Guest Pass Only</button><a className={button} href={handoff.enrollmentUrl}>Preview Guest Page</a></div></div>:null}
 <div className="mt-4 grid gap-2 md:grid-cols-2">{data?.invitations.map(item=><article className="rounded-xl border border-white/10 p-3" key={item.id}><b>{item.label}</b><p>{item.state} · {item.expires_at?`expires ${new Date(item.expires_at).toLocaleString()}`:"does not expire"}</p>{item.state!=="revoked"?<button className={button} disabled={busy} onClick={()=>void act({action:"revoke",invitationId:item.id})}>Revoke invitation</button>:null}</article>)}</div>
 {data?.enrollments.map(enrollment=><article className="mt-3 rounded-xl border border-white/10 p-3" key={enrollment.id}><b>Musician {enrollment.tester_id.slice(0,8)}</b><p>{enrollment.state} · acknowledgement {enrollment.acknowledgement_version?"complete":"waiting"} · setup check {enrollment.environment?"complete":"waiting"}</p><button className={button} disabled={busy||!enrollment.environment} onClick={()=>void act({action:"release",enrollmentId:enrollment.id})}>Run Release Gate</button>{data?.release?<div className={data.release.ready?"text-emerald-200":"text-amber-200"}><b>{data.release.ready?"Musician may open the trial":"Release held"}</b>{data.release.blockers.map(item=><p key={item}>{item}</p>)}{data.release.warnings.map(item=><p key={item}>{item}</p>)}</div>:null}</article>)}
 {data?<p className="mt-3 text-xs text-white/45">Workflow {data.workflow.percent}% · export {data.workflow.exportReady?"ready":"not ready"} · integrity blockers {data.integrityBlockers} · {data.releaseReceipts.length} release receipt(s)</p>:null}{message?<p className="mt-3 text-emerald-200">{message}</p>:null}{error?<p role="alert" className="mt-3 text-red-200">{error}</p>:null}</section>
}
