"use client";
import { useState } from "react";
import type { TimelineTransportSynchronization } from "@/lib/timeline/TimelineTransportAndSynchronizationEngine";
type Action="add-tempo"|"update-tempo"|"remove-tempo"|"add-signature"|"update-signature"|"remove-signature";
type Extras={pointId?:string;tick?:number;bpm?:number;numerator?:number;denominator?:1|2|4|8|16|32};
const input="rounded-lg border border-white/20 bg-black px-2 py-1 text-white",button="rounded-lg border border-white/25 px-3 py-2 text-xs font-black disabled:opacity-40";
function TempoRow({point,origin,onCommand}:{point:TimelineTransportSynchronization["tempoMap"][number];origin:boolean;onCommand:(action:Action,extras:Extras)=>Promise<unknown>}){const[tick,setTick]=useState(point.tick),[bpm,setBpm]=useState(point.bpm);return <div className="grid grid-cols-[1fr_1fr_auto_auto] gap-2"><input aria-label="Tempo tick" className={input} type="number" min={0} step={1} disabled={origin} value={tick} onChange={(event)=>setTick(Number(event.target.value))}/><input aria-label="Tempo BPM" className={input} type="number" min={20} max={400} step={0.01} value={bpm} onChange={(event)=>setBpm(Number(event.target.value))}/><button className={button} onClick={()=>void onCommand("update-tempo",{pointId:point.id,tick,bpm})}>Save</button><button className={button} disabled={origin} onClick={()=>void onCommand("remove-tempo",{pointId:point.id})}>Delete</button></div>}
function SignatureRow({point,origin,onCommand}:{point:TimelineTransportSynchronization["timeSignatureMap"][number];origin:boolean;onCommand:(action:Action,extras:Extras)=>Promise<unknown>}){const[tick,setTick]=useState(point.tick),[numerator,setNumerator]=useState(point.numerator),[denominator,setDenominator]=useState<1|2|4|8|16|32>(point.denominator);return <div className="grid grid-cols-[1fr_1fr_1fr_auto_auto] gap-2"><input aria-label="Signature tick" className={input} type="number" min={0} step={1} disabled={origin} value={tick} onChange={(event)=>setTick(Number(event.target.value))}/><input aria-label="Signature numerator" className={input} type="number" min={1} max={32} step={1} value={numerator} onChange={(event)=>setNumerator(Number(event.target.value))}/><select aria-label="Signature denominator" className={input} value={denominator} onChange={(event)=>setDenominator(Number(event.target.value) as typeof denominator)}>{[1,2,4,8,16,32].map((value)=><option key={value}>{value}</option>)}</select><button className={button} onClick={()=>void onCommand("update-signature",{pointId:point.id,tick,numerator,denominator})}>Save</button><button className={button} disabled={origin} onClick={()=>void onCommand("remove-signature",{pointId:point.id})}>Delete</button></div>}
export default function TimelineDawTempoMapEditor({transport,onCommand}:{transport:TimelineTransportSynchronization;onCommand:(action:Action,extras:Extras)=>Promise<unknown>}){const[tick,setTick]=useState(transport.tick),[bpm,setBpm]=useState(120),[numerator,setNumerator]=useState(4),[denominator,setDenominator]=useState<1|2|4|8|16|32>(4);return <section className="mt-4 rounded-xl border border-emerald-300/20 bg-emerald-300/[0.05] p-3"><p className="text-xs font-black uppercase tracking-[.18em] text-emerald-200">Tempo map and musical grid</p><div className="mt-3 grid gap-4 lg:grid-cols-2"><div><p className="mb-2 text-xs font-black text-white/55">Tempo events</p><div className="grid gap-2">{transport.tempoMap.map((point)=><TempoRow key={point.id} point={point} origin={point.tick===0} onCommand={onCommand}/>)}</div><div className="mt-2 flex gap-2"><input className={`w-28 ${input}`} type="number" min={0} step={1} value={tick} onChange={(event)=>setTick(Number(event.target.value))}/><input className={`w-24 ${input}`} type="number" min={20} max={400} step={0.01} value={bpm} onChange={(event)=>setBpm(Number(event.target.value))}/><button className={button} onClick={()=>void onCommand("add-tempo",{tick,bpm})}>Add Tempo</button></div></div><div><p className="mb-2 text-xs font-black text-white/55">Time signatures</p><div className="grid gap-2">{transport.timeSignatureMap.map((point)=><SignatureRow key={point.id} point={point} origin={point.tick===0} onCommand={onCommand}/>)}</div><div className="mt-2 flex gap-2"><input className={`w-24 ${input}`} type="number" min={1} max={32} step={1} value={numerator} onChange={(event)=>setNumerator(Number(event.target.value))}/><select className={input} value={denominator} onChange={(event)=>setDenominator(Number(event.target.value) as typeof denominator)}>{[1,2,4,8,16,32].map((value)=><option key={value}>{value}</option>)}</select><button className={button} onClick={()=>void onCommand("add-signature",{tick,numerator,denominator})}>Add Signature</button></div></div></div></section>}
