"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";
type Workflow = { receipt_checksum: string; evaluation: { checkpoints: Array<{ stage: string; completed: boolean; title: string; detail: string; action: string }>; percent: number; blockers: string[]; next: { stage: string } | null } };
type Feedback = { id: string; stage: string; severity: string; summary: string; state: string; created_at: string };
type Data = { workflow: Workflow | null; feedback: Feedback[] };
const input = "w-full rounded-lg border border-white/15 bg-black px-3 py-2", button = "rounded-lg bg-white px-3 py-2 font-black text-black disabled:opacity-40";
export default function TimelineDawBetaCollaboratorPanel({ sessionId }: { sessionId: string }) {
  const [data, setData] = useState<Data | null>(null), [stage, setStage] = useState("setup"), [severity, setSeverity] = useState("minor"), [reproducibility, setReproducibility] = useState("sometimes"), [summary, setSummary] = useState(""), [expectedBehavior, setExpectedBehavior] = useState(""), [reproductionNotes, setReproductionNotes] = useState(""), [error, setError] = useState(""), [message, setMessage] = useState(""), [busy, setBusy] = useState(false);
  const call = useCallback(async (body?: Record<string, unknown>) => { const token = (await requireProjectSupabase().auth.getSession()).data.session?.access_token ?? "", response = await fetch(body ? "/api/timeline/daw-beta-collaboration" : `/api/timeline/daw-beta-collaboration?sessionId=${encodeURIComponent(sessionId)}`, { method: body ? "POST" : "GET", headers: { Authorization: `Bearer ${token}`, ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify({ sessionId, ...body }) : undefined, cache: "no-store" }), result = await response.json(); if (!response.ok) throw new Error(result.error); return result; }, [sessionId]);
  const load = useCallback(async () => { try { const result = await call(); setData(result); const next = result.workflow?.evaluation?.next?.stage; if (next) setStage(next); } catch (reason) { setError(reason instanceof Error ? reason.message : "Beta workflow could not be loaded."); } }, [call]);
  useEffect(() => { queueMicrotask(() => void load()); }, [load]);
  const canSubmit = useMemo(() => Boolean(data?.workflow?.receipt_checksum && summary.trim().length >= 5 && expectedBehavior.trim().length >= 5 && reproductionNotes.trim().length >= 5), [data, summary, expectedBehavior, reproductionNotes]);
  async function submit() { if (!data?.workflow) return; setBusy(true); setError(""); setMessage(""); try { await call({ checkpointChecksum: data.workflow.receipt_checksum, stage, severity, reproducibility, summary, expectedBehavior, reproductionNotes }); setSummary(""); setExpectedBehavior(""); setReproductionNotes(""); setMessage("Feedback saved with your identity and the current workflow checkpoint."); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Feedback could not be saved."); } finally { setBusy(false); } }
  return <><section className="rounded-2xl border border-white/15 p-4"><h2 className="text-2xl font-black">Guided beta workflow</h2>{data?.workflow?<><p className="text-white/55">{data.workflow.evaluation.percent}% complete · checkpoint {data.workflow.receipt_checksum.slice(0,18)}…</p><div className="mt-3 grid gap-2 md:grid-cols-2">{data.workflow.evaluation.checkpoints.map(item=><article className="rounded-xl border border-white/10 p-3" key={item.stage}><b>{item.completed?"✓":"○"} {item.title}</b><p className="text-sm text-white/55">{item.detail}</p>{!item.completed?<p className="text-sm text-sky-200">Next: {item.action}</p>:null}</article>)}</div>{data.workflow.evaluation.blockers.map(item=><p className="text-amber-200" key={item}>{item}</p>)}</>:<p>The owner must save a workflow checkpoint before feedback can be attached.</p>}</section><section className="rounded-2xl border border-white/15 p-4"><h2 className="text-2xl font-black">Report what happened</h2><div className="mt-3 grid gap-2 md:grid-cols-3"><select className={input} value={stage} onChange={event=>setStage(event.target.value)}>{["setup","capture","edit","mix","protect","export"].map(value=><option key={value}>{value}</option>)}</select><select className={input} value={severity} onChange={event=>setSeverity(event.target.value)}>{["suggestion","minor","major","blocking"].map(value=><option key={value}>{value}</option>)}</select><select className={input} value={reproducibility} onChange={event=>setReproducibility(event.target.value)}>{["once","sometimes","always","not-tested"].map(value=><option key={value}>{value}</option>)}</select></div><input className={`${input} mt-2`} value={summary} onChange={event=>setSummary(event.target.value)} placeholder="Short summary"/><textarea className={`${input} mt-2`} value={expectedBehavior} onChange={event=>setExpectedBehavior(event.target.value)} placeholder="What did you expect?"/><textarea className={`${input} mt-2`} value={reproductionNotes} onChange={event=>setReproductionNotes(event.target.value)} placeholder="Exact steps to make it happen again"/><button className={`${button} mt-2`} disabled={busy||!canSubmit} onClick={()=>void submit()}>Submit checkpoint-linked feedback</button>{message?<p className="text-emerald-200">{message}</p>:null}{error?<p role="alert" className="text-red-200">{error}</p>:null}</section><section className="rounded-2xl border border-white/15 p-4"><h2 className="font-black">Your reports</h2>{data?.feedback.length?data.feedback.map(item=><p key={item.id}>{item.state} · {item.severity} · {item.stage} · {item.summary}</p>):<p className="text-white/55">No reports submitted by this tester yet.</p>}</section></>;
}
