"use client";
import { useCallback, useEffect, useState } from "react";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";
type Tester = { enrollmentId: string; testerId: string; state: string };
type Certification = { ready: boolean; checks: Array<{ key: string; passed: boolean; detail: string }>; receiptChecksum: string };
const button = "rounded-lg border border-white/20 bg-white px-3 py-2 font-black text-black disabled:opacity-40";
export default function TimelineDawBetaReadinessCertification({ sessionId }: { sessionId: string }) {
  const [testers, setTesters] = useState<Tester[]>([]), [results, setResults] = useState<Record<string, Certification>>({}), [busy, setBusy] = useState(""), [error, setError] = useState("");
  const token = async () => ((await requireProjectSupabase().auth.getSession()).data.session?.access_token ?? "");
  const load = useCallback(async () => { const response = await fetch(`/api/timeline/daw-beta-release-package?sessionId=${encodeURIComponent(sessionId)}`, { headers: { Authorization: `Bearer ${await token()}` }, cache: "no-store" }), data = await response.json(); if (!response.ok) throw Error(data.error); setTesters(data.testers); }, [sessionId]);
  useEffect(() => { queueMicrotask(() => void load().catch(cause => setError(cause.message))); }, [load]);
  async function certify(tester: Tester) { setBusy(tester.enrollmentId); setError(""); try { const response = await fetch("/api/timeline/daw-beta-tester-portal", { method: "POST", headers: { Authorization: `Bearer ${await token()}`, "Content-Type": "application/json" }, body: JSON.stringify({ sessionId, enrollmentId: tester.enrollmentId }) }), result = await response.json(); if (!response.ok) throw Error(result.error); setResults(current => ({ ...current, [tester.enrollmentId]: result })); } catch (cause) { setError(cause instanceof Error ? cause.message : "Certification failed."); } finally { setBusy(""); } }
  return <section className="rounded-3xl border border-fuchsia-300/25 bg-fuchsia-300/[.04] p-5"><p className="text-xs font-black uppercase tracking-[.22em] text-fuchsia-200">End-to-end beta certification</p><h2 className="mt-1 text-2xl font-black">Prove each musician path before handoff</h2><p className="mt-2 text-sm text-white/55">This audit reads seven independent durable evidence chains and saves a checksum receipt. It does not expose audio, storage paths, or another tester&apos;s information.</p>{testers.map(tester => { const result = results[tester.enrollmentId]; return <article className="mt-3 rounded-xl border border-white/10 p-3" key={tester.enrollmentId}><div className="flex flex-wrap items-center justify-between gap-2"><b>Tester {tester.testerId.slice(0, 8)} · {tester.state}</b><button className={button} disabled={Boolean(busy)} onClick={() => void certify(tester)}>{busy === tester.enrollmentId ? "Auditing…" : "Run readiness certification"}</button></div>{result ? <><p className={`mt-2 font-black ${result.ready ? "text-emerald-200" : "text-amber-200"}`}>{result.ready ? "CERTIFIED FOR EXTERNAL BETA" : "CERTIFICATION HELD"}</p>{result.checks.map(check => <p className={check.passed ? "text-emerald-200" : "text-amber-200"} key={check.key}>{check.passed ? "PASS" : "HOLD"} · {check.detail}</p>)}<p className="mt-2 break-all font-mono text-xs text-white/45">{result.receiptChecksum}</p></> : null}</article>; })}{error ? <p role="alert" className="mt-3 text-red-200">{error}</p> : null}</section>;
}
