"use client";
import { useState } from "react";
import type { DawPrivateBus } from "@/app/workspace/projects/[id]/projectDawApi";
import type { TimelineDawPrivateLaneMeter } from "@/lib/timeline/TimelineDawPrivateLaneMonitorGraph";
const button = "rounded-xl border border-white/25 bg-white px-3 py-2 text-sm font-black text-black disabled:opacity-40";
export default function TimelineDawPrivateBusMixer({ buses, meters, busy, onSave, onDelete }: { buses: DawPrivateBus[]; meters: Record<string, TimelineDawPrivateLaneMeter>; busy: boolean; onSave: (bus: { busId?: string; name: string; muted: boolean; soloed: boolean; gain: number; pan: number }) => void; onDelete: (bus: DawPrivateBus) => void }) {
  const [name, setName] = useState("");
  return <div className="mt-4 rounded-xl border border-fuchsia-300/20 bg-fuchsia-300/[0.06] p-3"><div className="flex flex-wrap gap-2"><input aria-label="New bus name" className="rounded-lg border border-white/20 bg-black px-2 py-1 text-white" value={name} maxLength={80} onChange={(e) => setName(e.target.value)} placeholder="New bus name" /><button className={button} disabled={busy || !name.trim()} onClick={() => { onSave({ name, muted: false, soloed: false, gain: 1, pan: 0 }); setName(""); }}>Create Bus</button></div>{buses.length ? <div className="mt-3 grid gap-2">{buses.map((bus) => { const meter = meters[bus.id] ?? { peakDbfs: -96, peakAmplitude: 0, clipped: false }; return <div key={bus.id} className="grid gap-2 rounded-lg border border-white/10 p-2 md:grid-cols-[1fr_auto_auto_1fr_1fr_auto]"><span className="font-black">{bus.name}<small className="block text-white/45">{meter.clipped ? "CLIP" : `${meter.peakDbfs.toFixed(1)} dBFS`}</small></span><button className={button} onClick={() => onSave({ busId: bus.id, name: bus.name, ...bus.mix, muted: !bus.mix.muted })}>{bus.mix.muted ? "Muted" : "Mute"}</button><button className={button} onClick={() => onSave({ busId: bus.id, name: bus.name, ...bus.mix, soloed: !bus.mix.soloed })}>{bus.mix.soloed ? "Soloed" : "Solo"}</button><label className="text-xs">Gain<input className="block w-full" type="range" min={0} max={2} step={0.01} value={bus.mix.gain} onChange={(e) => onSave({ busId: bus.id, name: bus.name, ...bus.mix, gain: Number(e.target.value) })} /></label><label className="text-xs">Pan<input className="block w-full" type="range" min={-1} max={1} step={0.01} value={bus.mix.pan} onChange={(e) => onSave({ busId: bus.id, name: bus.name, ...bus.mix, pan: Number(e.target.value) })} /></label><button className={button} disabled={busy} onClick={() => onDelete(bus)}>Delete</button></div>; })}</div> : <p className="mt-2 text-xs text-white/45">No buses yet; lanes route directly to master.</p>}</div>;
}
