import crypto from "node:crypto";
import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { createTimelineDawBetaWorkflowReceipt, type TimelineDawBetaEvidence } from "@/lib/timeline/TimelineDawBetaWorkflowPolicy";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";
export const runtime = "nodejs", dynamic = "force-dynamic";
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw Error(`${name} is not configured.`);return value};
async function authorize(request:NextRequest){const header=request.headers.get("authorization")??"";if(!header.toLowerCase().startsWith("bearer "))throw Error("Authentication is required.");const token=header.slice(7).trim(),client=createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}}),{data,error}=await client.auth.getUser(token);if(error||!data.user)throw Error("Supabase session is invalid or expired.");return{id:data.user.id,token,client}}
async function count(client:SupabaseClient,table:string,ownerId:string,sessionId:string,filters:Record<string,string|boolean>={}){let query=client.from(table).select("id",{count:"exact",head:true}).eq("owner_id",ownerId).eq("session_id",sessionId);for(const[column,value]of Object.entries(filters))query=query.eq(column,value);const{count:total,error}=await query;if(error)throw Error(`${table} could not be inspected: ${error.message}`);return total??0}
async function inspect(client:SupabaseClient,ownerId:string,sessionId:string):Promise<TimelineDawBetaEvidence>{const v=await Promise.all([count(client,"timeline_daw_recording_takes",ownerId,sessionId),count(client,"timeline_daw_private_audio_lanes",ownerId,sessionId),count(client,"timeline_daw_private_lane_edit_history",ownerId,sessionId),count(client,"timeline_daw_arrangement_item_edits",ownerId,sessionId),count(client,"timeline_daw_private_buses",ownerId,sessionId),count(client,"timeline_daw_private_inserts",ownerId,sessionId),count(client,"timeline_daw_private_automation_edits",ownerId,sessionId),count(client,"timeline_daw_private_session_snapshots",ownerId,sessionId),count(client,"timeline_daw_private_bounce_jobs",ownerId,sessionId,{state:"completed"}),count(client,"timeline_daw_private_bounce_jobs",ownerId,sessionId,{state:"failed"}),count(client,"timeline_daw_normalization_evidence_incidents",ownerId,sessionId,{state:"manual-review"})]);return{sessionExists:true,audioSourceCount:v[0]+v[1],editCount:v[2]+v[3],mixControlCount:v[4]+v[5]+v[6],snapshotCount:v[7],completedExportCount:v[8],failedJobCount:v[9],unresolvedIntegrityCount:v[10]}}
async function context(request:NextRequest,sessionId:string){if(!sessionId)throw Error("sessionId is required.");const user=await authorize(request),session=await createTimelineDawWorkspaceServer(user.id,user.token).get(user.id,sessionId);if(!session)throw Error("DAW session was not found.");return user}
async function build(request:NextRequest,sessionId:string,persist:boolean){const user=await context(request,sessionId),receipt=createTimelineDawBetaWorkflowReceipt({sessionId,evidence:await inspect(user.client,user.id,sessionId)});if(persist){const stage=receipt.evaluation.complete?"complete":(receipt.evaluation.next?.stage??"complete"),{error}=await user.client.from("timeline_daw_beta_workflow_receipts").upsert({id:`timeline-daw-beta-${crypto.randomUUID()}`,owner_id:user.id,session_id:sessionId,stage,completed:receipt.evaluation.completed,required:receipt.evaluation.required,evidence:receipt.evidence,evaluation:receipt.evaluation,receipt_checksum:receipt.checksum,observed_at:receipt.observedAt},{onConflict:"owner_id,session_id,receipt_checksum",ignoreDuplicates:true});if(error)throw Error(`Workflow checkpoint could not be saved: ${error.message}`)}const{data,error}=await user.client.from("timeline_daw_beta_workflow_receipts").select("id,stage,completed,required,receipt_checksum,observed_at").eq("owner_id",user.id).eq("session_id",sessionId).order("observed_at",{ascending:false}).limit(12);if(error)throw Error(`Workflow history could not be loaded: ${error.message}`);return NextResponse.json({receipt,history:data??[]},{headers:{"Cache-Control":"no-store"}})}
const failure=(error:unknown)=>NextResponse.json({error:error instanceof Error?error.message:"Beta workflow request failed."},{status:400});
export async function GET(request:NextRequest){try{return await build(request,request.nextUrl.searchParams.get("sessionId")?.trim()??"",false)}catch(error){return failure(error)}}
export async function POST(request:NextRequest){try{const body=await request.json();return await build(request,String(body.sessionId??"").trim(),true)}catch(error){return failure(error)}}
