import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";
import { assertTimelineDawPrivateBusSendAcyclic, parseTimelineDawPrivateInsert, parseTimelineDawPrivateSend } from "@/lib/timeline/TimelineDawPrivateBusProcessingPolicy";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
class ApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw new ApiError(`${name} is not configured.`,503);return value;};
async function auth(request:NextRequest){const header=request.headers.get("authorization")?.trim()??"";if(!header.toLowerCase().startsWith("bearer "))throw new ApiError("Authentication is required.",401);const token=header.slice(7).trim();const client=createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const {data,error}=await client.auth.getUser(token);if(error||!data.user?.id)throw new ApiError("Supabase session is invalid or expired.",401);return{id:data.user.id,token,client};}
async function session(user:Awaited<ReturnType<typeof auth>>,id:string){if(!id||!await createTimelineDawWorkspaceServer(user.id,user.token).get(user.id,id))throw new ApiError("DAW session was not found.",404);}
const sendMap=(r:Record<string,unknown>)=>({id:String(r.id),sourceKind:r.source_kind as "lane"|"bus",sourceId:String(r.source_id),destinationBusId:String(r.destination_bus_id),level:Number(r.level),preFader:Boolean(r.pre_fader),muted:Boolean(r.muted)});
const insertMap=(r:Record<string,unknown>)=>({id:String(r.id),sourceKind:r.source_kind as "lane"|"bus",sourceId:String(r.source_id),slot:Number(r.slot),effect:r.effect as "gain"|"filter"|"compressor",bypassed:Boolean(r.bypassed),parameters:(r.parameters??{}) as Record<string,number>});
const fail=(error:unknown)=>NextResponse.json({error:error instanceof Error?error.message:"Private processing request failed."},{status:error instanceof ApiError?error.status:400,headers:{"Cache-Control":"no-store"}});
export async function GET(request:NextRequest){try{const user=await auth(request);const sessionId=request.nextUrl.searchParams.get("sessionId")?.trim()??"";await session(user,sessionId);const [sends,inserts]=await Promise.all([user.client.from("timeline_daw_private_sends").select("*").eq("owner_id",user.id).eq("session_id",sessionId).order("created_at"),user.client.from("timeline_daw_private_inserts").select("*").eq("owner_id",user.id).eq("session_id",sessionId).order("slot")]);if(sends.error||inserts.error)throw new ApiError(sends.error?.message??inserts.error?.message??"Processing could not be loaded.",500);return NextResponse.json({sends:(sends.data??[]).map(sendMap),inserts:(inserts.data??[]).map(insertMap)},{headers:{"Cache-Control":"no-store"}});}catch(error){return fail(error);}}
export async function POST(request:NextRequest){try{const user=await auth(request);const body=await request.json() as Record<string,unknown>;const sessionId=typeof body.sessionId==="string"?body.sessionId.trim():"";await session(user,sessionId);if(body.action==="delete"){const table=body.kind==="insert"?"timeline_daw_private_inserts":"timeline_daw_private_sends";const id=typeof body.id==="string"?body.id.trim():"";const {data,error}=await user.client.from(table).delete().eq("id",id).eq("owner_id",user.id).eq("session_id",sessionId).select("id").single();if(error||!data)throw new ApiError("Private processing item was not found.",404);return NextResponse.json({deletedId:id});}
if(body.kind==="send"){const value=parseTimelineDawPrivateSend(body);const bus=await user.client.from("timeline_daw_private_buses").select("id").eq("id",value.destinationBusId).eq("owner_id",user.id).eq("session_id",sessionId).maybeSingle();if(!bus.data)throw new ApiError("Send destination bus was not found.",404);const sourceTable=value.sourceKind==="bus"?"timeline_daw_private_buses":"timeline_daw_private_audio_lanes";const source=await user.client.from(sourceTable).select("id").eq("id",value.sourceId).eq("owner_id",user.id).eq("session_id",sessionId).maybeSingle();if(!source.data)throw new ApiError("Send source was not found.",404);const existing=await user.client.from("timeline_daw_private_sends").select("source_kind,source_id,destination_bus_id,muted").eq("owner_id",user.id).eq("session_id",sessionId);assertTimelineDawPrivateBusSendAcyclic([...(existing.data??[]).map((r)=>({sourceKind:r.source_kind as "lane"|"bus",sourceId:String(r.source_id),destinationBusId:String(r.destination_bus_id),muted:Boolean(r.muted)})).filter((r)=>!(r.sourceKind===value.sourceKind&&r.sourceId===value.sourceId&&r.destinationBusId===value.destinationBusId)),value]);const id=typeof body.id==="string"&&body.id.trim()?body.id.trim():`timeline-daw-private-send-${crypto.randomUUID()}`;const {data,error}=await user.client.from("timeline_daw_private_sends").upsert({id,owner_id:user.id,session_id:sessionId,source_kind:value.sourceKind,source_id:value.sourceId,destination_bus_id:value.destinationBusId,level:value.level,pre_fader:value.preFader,muted:value.muted,updated_at:new Date().toISOString()},{onConflict:"owner_id,session_id,source_kind,source_id,destination_bus_id"}).select("*").single();if(error||!data)throw new ApiError(error?.message??"Send could not be saved.",500);return NextResponse.json({send:sendMap(data)});}
const value=parseTimelineDawPrivateInsert(body);const sourceTable=value.sourceKind==="bus"?"timeline_daw_private_buses":"timeline_daw_private_audio_lanes";const source=await user.client.from(sourceTable).select("id").eq("id",value.sourceId).eq("owner_id",user.id).eq("session_id",sessionId).maybeSingle();if(!source.data)throw new ApiError("Insert source was not found.",404);const id=typeof body.id==="string"&&body.id.trim()?body.id.trim():`timeline-daw-private-insert-${crypto.randomUUID()}`;const {data,error}=await user.client.from("timeline_daw_private_inserts").upsert({id,owner_id:user.id,session_id:sessionId,source_kind:value.sourceKind,source_id:value.sourceId,slot:value.slot,effect:value.effect,bypassed:value.bypassed,parameters:value.parameters,updated_at:new Date().toISOString()},{onConflict:"owner_id,session_id,source_kind,source_id,slot"}).select("*").single();if(error||!data)throw new ApiError(error?.message??"Insert could not be saved.",500);return NextResponse.json({insert:insertMap(data)});}catch(error){return fail(error);}}
