import type {
  MultiTrackEngineAnalysisState,
  MultiTrackEngineComparisonState,
  MultiTrackEngineDecisionState,
  MultiTrackEngineState,
  MultiTrackEngineTimelineState,
  MultiTrackEngineTrackState,
} from "./multiTrackEngineTypes";

export const DEFAULT_MULTI_TRACK_ENGINE_TRACK_A: MultiTrackEngineTrackState = {
  trackSlotId: "track-a",
  label: "Track A",
  shortLabel: "A",
  sourceLabel: "Waiting for Track A",
  sourceKind: "empty",
  sourceId: "",
  title: "No track loaded",
  artist: "Unknown artist",
  album: "Unknown album",
  durationSeconds: 0,
  bpm: null,
  keyLabel: "Unknown key",
  sampleRate: null,
  channelCount: null,
  gainDb: 0,
  pan: -0.15,
  muted: false,
  solo: false,
  armed: false,
  locked: false,
  loaded: false,
  waveformReady: false,
  analysisReady: false,
  syncReady: false,
  transientReady: false,
  metadataReady: false,
  readiness: "empty",
  colorToken: "cyan",
  notes: [
    "Track A is reserved for the first loaded song, stem, upload, Library track, Finder result, or project source.",
    "Track A does not own audio playback yet.",
    "Track A engine state is separated from controller navigation and session health.",
    "Future Track A upgrades can safely add waveform, transient, key, BPM, and DSP readiness here.",
  ],
};

export const DEFAULT_MULTI_TRACK_ENGINE_TRACK_B: MultiTrackEngineTrackState = {
  trackSlotId: "track-b",
  label: "Track B",
  shortLabel: "B",
  sourceLabel: "Waiting for Track B",
  sourceKind: "empty",
  sourceId: "",
  title: "No track loaded",
  artist: "Unknown artist",
  album: "Unknown album",
  durationSeconds: 0,
  bpm: null,
  keyLabel: "Unknown key",
  sampleRate: null,
  channelCount: null,
  gainDb: 0,
  pan: 0.15,
  muted: false,
  solo: false,
  armed: false,
  locked: false,
  loaded: false,
  waveformReady: false,
  analysisReady: false,
  syncReady: false,
  transientReady: false,
  metadataReady: false,
  readiness: "empty",
  colorToken: "violet",
  notes: [
    "Track B is reserved for the second loaded song, stem, upload, Library track, Finder result, or project source.",
    "Track B comparison ownership belongs in engine, not session.",
    "Track B does not own audio playback yet.",
    "Future Track B upgrades can safely mirror Track A without controller growth.",
  ],
};

export const DEFAULT_MULTI_TRACK_ENGINE_COMPARISON: MultiTrackEngineComparisonState = {
  status: "not-started",
  readiness: "draft",
  averageScore: 0,
  weightedScore: 0,
  strongestMatchLabel: "No comparison yet",
  weakestMatchLabel: "No comparison yet",
  summary: "Load Track A and Track B to begin engine comparison.",
  signals: [
    {
      id: "tempo-placeholder",
      label: "Tempo relationship",
      detail: "Waiting for BPM values from Track A and Track B.",
      polarity: "neutral",
      score: 0,
      weight: 1.2,
      ready: false,
    },
    {
      id: "key-placeholder",
      label: "Key relationship",
      detail: "Waiting for key analysis from both tracks.",
      polarity: "neutral",
      score: 0,
      weight: 1,
      ready: false,
    },
    {
      id: "structure-placeholder",
      label: "Structure relationship",
      detail: "Waiting for timeline markers and section detection.",
      polarity: "neutral",
      score: 0,
      weight: 1.1,
      ready: false,
    },
    {
      id: "readiness-placeholder",
      label: "Engine readiness",
      detail: "Waiting for loaded tracks, waveform readiness, analysis readiness, and sync readiness.",
      polarity: "neutral",
      score: 0,
      weight: 1.4,
      ready: false,
    },
  ],
};

export const DEFAULT_MULTI_TRACK_ENGINE_TIMELINE: MultiTrackEngineTimelineState = {
  status: "waiting",
  transportStatus: "stopped",
  zoomLevel: 1,
  playheadSeconds: 0,
  loopEnabled: false,
  loopStartSeconds: 0,
  loopEndSeconds: 0,
  snapToMarkers: true,
  markers: [
    {
      id: "timeline-start",
      trackSlotId: "both",
      kind: "intro",
      label: "Start placeholder",
      startSeconds: 0,
      endSeconds: 8,
      confidence: 0.25,
      locked: true,
    },
    {
      id: "timeline-first-checkpoint",
      trackSlotId: "both",
      kind: "custom",
      label: "First comparison checkpoint",
      startSeconds: 8,
      endSeconds: 16,
      confidence: 0.15,
      locked: false,
    },
  ],
  cues: [
    {
      id: "cue-engine-entry",
      trackSlotId: "both",
      kind: "entry",
      label: "Engine entry cue",
      seconds: 0,
      confidence: 0.2,
      note: "Placeholder cue for future downbeat, vocal, instrument, and transition detection.",
    },
  ],
};

export const DEFAULT_MULTI_TRACK_ENGINE_ANALYSIS: MultiTrackEngineAnalysisState = {
  readiness: "draft",
  summary:
    "Engine foundation is ready. Real waveform, DSP, comparison, sync, and analysis ownership can be attached later.",
  nextStepLabel: "Load tracks",
  findingCount: 4,
  warningCount: 0,
  blockedCount: 0,
  laneReadiness: [
    {
      laneId: "overview",
      label: "Overview",
      readiness: "draft",
      score: 20,
      detail: "Engine overview exists and is waiting for loaded tracks.",
    },
    {
      laneId: "waveform",
      label: "Waveform",
      readiness: "empty",
      score: 0,
      detail: "Waveform ownership is not connected yet.",
    },
    {
      laneId: "tempo",
      label: "Tempo",
      readiness: "empty",
      score: 0,
      detail: "Tempo comparison is waiting for BPM values.",
    },
    {
      laneId: "key",
      label: "Key",
      readiness: "empty",
      score: 0,
      detail: "Key comparison is waiting for key labels.",
    },
    {
      laneId: "structure",
      label: "Structure",
      readiness: "draft",
      score: 15,
      detail: "Timeline markers exist as placeholders.",
    },
    {
      laneId: "sync",
      label: "Sync",
      readiness: "empty",
      score: 0,
      detail: "Sync ownership is not active yet.",
    },
    {
      laneId: "decision",
      label: "Decision",
      readiness: "draft",
      score: 10,
      detail: "Decision routing exists and is waiting for real readiness.",
    },
  ],
  findings: [
    {
      id: "engine-foundation-ready",
      trackSlotId: "both",
      label: "Engine folder is active",
      detail:
        "Track, comparison, timeline, analysis, decision, and snapshot contracts are separated from session.",
      severity: "good",
      actionLabel: "Keep engine ownership here",
    },
    {
      id: "controller-kept-clean",
      trackSlotId: "both",
      label: "Controller stays split",
      detail:
        "Controller can keep owning views, panels, track slots, and navigation while engine owns track comparison state.",
      severity: "good",
      actionLabel: "Avoid controller regrowth",
    },
    {
      id: "session-kept-clean",
      trackSlotId: "both",
      label: "Session stays health-focused",
      detail:
        "Session remains responsible for health, notes, routes, and selections without taking audio-runtime ownership.",
      severity: "good",
      actionLabel: "Do not move engine state into session",
    },
    {
      id: "audio-not-owned-yet",
      trackSlotId: "both",
      label: "Audio ownership is not active",
      detail:
        "No real audio graph, waveform, DSP, sync calculation, or comparison calculation is connected yet.",
      severity: "info",
      actionLabel: "Connect later through safe adapters",
    },
  ],
};

export const DEFAULT_MULTI_TRACK_ENGINE_DECISION: MultiTrackEngineDecisionState = {
  route: "hold",
  readiness: "draft",
  primaryActionLabel: "Load tracks",
  secondaryActionLabel: "Inspect engine foundation",
  reason: "The engine is ready for richer state, but no real tracks are loaded yet.",
  canSave: false,
  canExport: false,
};

export const DEFAULT_MULTI_TRACK_ENGINE_STATE: MultiTrackEngineState = {
  engineId: "multi-track-engine-foundation",
  versionLabel: "engine-foundation-003",
  editedAtLabel: "Not edited yet",
  trackA: DEFAULT_MULTI_TRACK_ENGINE_TRACK_A,
  trackB: DEFAULT_MULTI_TRACK_ENGINE_TRACK_B,
  comparison: DEFAULT_MULTI_TRACK_ENGINE_COMPARISON,
  timeline: DEFAULT_MULTI_TRACK_ENGINE_TIMELINE,
  analysis: DEFAULT_MULTI_TRACK_ENGINE_ANALYSIS,
  decision: DEFAULT_MULTI_TRACK_ENGINE_DECISION,
  snapshots: [],
};