import type { MultiTrackEngineRelationshipState } from "./multiTrackEngineRelationshipTypes";

export const DEFAULT_MULTI_TRACK_ENGINE_RELATIONSHIP_STATE: MultiTrackEngineRelationshipState = {
  readiness: "draft",
  summary: "Relationship intelligence is waiting for real Track A and Track B analysis data.",
  strongestRelationshipLabel: "No strongest relationship yet",
  weakestRelationshipLabel: "No weakest relationship yet",
  averageScore: 0,
  averageConfidence: 0,
  relationships: [
    {
      id: "relationship-tempo",
      kind: "tempo",
      label: "Tempo relationship",
      trackALabel: "Track A BPM unknown",
      trackBLabel: "Track B BPM unknown",
      detail: "Waiting for BPM values before tempo relationship can be scored.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-key",
      kind: "key",
      label: "Key relationship",
      trackALabel: "Track A key unknown",
      trackBLabel: "Track B key unknown",
      detail: "Waiting for key labels before harmonic relationship can be scored.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-energy",
      kind: "energy",
      label: "Energy relationship",
      trackALabel: "Track A energy unknown",
      trackBLabel: "Track B energy unknown",
      detail: "Future analyzer can compare loudness, density, movement, and intensity here.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-genre",
      kind: "genre",
      label: "Genre relationship",
      trackALabel: "Track A genre unknown",
      trackBLabel: "Track B genre unknown",
      detail: "Future metadata adapter can compare genre, style, era, and production family here.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-instrument",
      kind: "instrument",
      label: "Instrument relationship",
      trackALabel: "Track A instruments unknown",
      trackBLabel: "Track B instruments unknown",
      detail: "Future stem or metadata analysis can compare drums, bass, vocals, keys, guitars, and featured instruments.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-vocal",
      kind: "vocal",
      label: "Vocal relationship",
      trackALabel: "Track A vocal unknown",
      trackBLabel: "Track B vocal unknown",
      detail: "Future vocal analysis can compare lead vocal presence, backing vocals, phrasing, and overlap risk.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-section",
      kind: "section",
      label: "Section relationship",
      trackALabel: "Track A sections unknown",
      trackBLabel: "Track B sections unknown",
      detail: "Future timeline intelligence can compare intro, verse, chorus, bridge, drop, break, and outro structure.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
    {
      id: "relationship-confidence",
      kind: "confidence",
      label: "Overall confidence",
      trackALabel: "Track A readiness unknown",
      trackBLabel: "Track B readiness unknown",
      detail: "Overall confidence will rise as tempo, key, waveform, metadata, analysis, transient, and sync readiness improve.",
      score: 0,
      confidence: 0,
      strength: "unknown",
      polarity: "neutral",
      ready: false,
    },
  ],
  focusItems: [
    {
      id: "focus-load-tracks",
      label: "Load both tracks",
      detail: "Relationship intelligence needs Track A and Track B before scoring can begin.",
      trackSlotId: "both",
      priority: 1,
    },
    {
      id: "focus-add-tempo-key",
      label: "Add tempo and key data",
      detail: "Tempo and key are the first safe relationship signals before DSP ownership exists.",
      trackSlotId: "both",
      priority: 2,
    },
  ],
};