import { describe,expect,it } from "vitest";
import { TimelineTransportAndSynchronizationEngine } from "../../lib/timeline/TimelineTransportAndSynchronizationEngine";
import { parseTimelineDawTransportCommand } from "../../lib/timeline/TimelineDawTransportApiPolicy";

function active(){const engine=new TimelineTransportAndSynchronizationEngine();let transport=engine.createTransport({projectId:"project",sessionId:"session",audioGraphId:"graph",name:"Tempo",sampleRate:48000,ppq:960,bpm:120,createdBy:"owner"});transport=engine.validate({transportId:transport.id,expectedHead:transport.head,validatedBy:"owner"});transport=engine.activate({transportId:transport.id,expectedHead:transport.head,activatedBy:"owner"});return{engine,transport};}
describe("durable tempo map editing",()=>{
 it("adds, moves, edits, and removes ordered tempo points",()=>{const{engine,transport:initial}=active();let transport=engine.addTempoPoint({transportId:initial.id,expectedHead:initial.head,tick:1920,bpm:90,editedBy:"owner"});const point=transport.tempoMap[1];transport=engine.updateTempoPoint({transportId:transport.id,expectedHead:transport.head,pointId:point.id,tick:960,bpm:100,editedBy:"owner"});expect(transport.tempoMap.map((item)=>[item.tick,item.bpm])).toEqual([[0,120],[960,100]]);transport=engine.removeTempoPoint({transportId:transport.id,expectedHead:transport.head,pointId:point.id,editedBy:"owner"});expect(transport.tempoMap).toHaveLength(1);expect(()=>engine.removeTempoPoint({transportId:transport.id,expectedHead:transport.head,pointId:transport.tempoMap[0].id,editedBy:"owner"})).toThrow(/origin/);});
 it("edits signatures while preserving the required origin",()=>{const{engine,transport:initial}=active();let transport=engine.addTimeSignaturePoint({transportId:initial.id,expectedHead:initial.head,tick:3840,numerator:3,denominator:4,editedBy:"owner"});const point=transport.timeSignatureMap[1];transport=engine.updateTimeSignaturePoint({transportId:transport.id,expectedHead:transport.head,pointId:point.id,tick:7680,numerator:7,denominator:8,editedBy:"owner"});expect(transport.timeSignatureMap[1]).toMatchObject({tick:7680,numerator:7,denominator:8});});
 it("parses bounded authenticated map commands",()=>{expect(parseTimelineDawTransportCommand({action:"add-tempo",sessionId:"session",expectedWorkspaceRevision:2,expectedTransportHead:4,tick:960,bpm:128})).toMatchObject({action:"add-tempo",bpm:128});expect(()=>parseTimelineDawTransportCommand({action:"add-tempo",sessionId:"session",expectedWorkspaceRevision:2,expectedTransportHead:4,tick:960,bpm:900})).toThrow(/20-400/);});
});
