import { describe, expect, it } from "vitest";
import { createTimelineDawBetaInviteCode, createTimelineDawBetaOnboardingReceipt, evaluateTimelineDawBetaRelease, hashTimelineDawBetaInviteCode } from "../../lib/timeline/TimelineDawBetaOnboardingPolicy";
const environment={secureContext:true,supportedBrowser:true,audioInput:true,audioOutput:true,localStorage:true,fileApi:true,supportedAudioTypes:true};
describe("DAW beta onboarding policy",()=>{
 it("creates non-stored invitation secrets",()=>{const code=createTimelineDawBetaInviteCode();expect(code.length).toBeGreaterThan(20);expect(hashTimelineDawBetaInviteCode(code)).toMatch(/^sha256:[a-f0-9]{64}$/)});
 it("opens the release gate only when every musician access control passes",()=>{expect(evaluateTimelineDawBetaRelease({enrolled:true,acknowledged:true,environment,workflowPercent:100,workflowComplete:true,exportReady:true,blockingFeedback:0,unresolvedFeedback:2,integrityBlockers:0})).toMatchObject({ready:true,warnings:["2 non-blocking report(s) remain open."]});expect(evaluateTimelineDawBetaRelease({enrolled:true,acknowledged:false,environment,workflowPercent:100,workflowComplete:true,exportReady:true,blockingFeedback:0,unresolvedFeedback:0,integrityBlockers:0}).ready).toBe(false)});
 it("bypasses older workflow requirements only with explicit isolated-trial readiness",()=>{const base={enrolled:true,acknowledged:true,environment,workflowPercent:0,workflowComplete:false,exportReady:false,blockingFeedback:0,unresolvedFeedback:0,integrityBlockers:0};expect(evaluateTimelineDawBetaRelease(base).ready).toBe(false);expect(evaluateTimelineDawBetaRelease({...base,isolatedTrialReady:true})).toMatchObject({ready:true,warnings:["The older owner workflow record is incomplete; it does not block the isolated seven-action musician trial."]})});
 it("still holds an isolated trial for failed setup, blocking feedback, or integrity issues",()=>{const failed={...environment,audioInput:false};expect(evaluateTimelineDawBetaRelease({enrolled:true,acknowledged:true,environment:failed,workflowPercent:0,workflowComplete:false,exportReady:false,isolatedTrialReady:true,blockingFeedback:1,unresolvedFeedback:1,integrityBlockers:1})).toMatchObject({ready:false,blockers:["Environment check failed: audioInput.","1 blocking feedback report(s) remain unresolved.","1 integrity blocker(s) require review."]})});
 it("creates checksum-protected onboarding receipts",()=>expect(createTimelineDawBetaOnboardingReceipt({sessionId:"s",testerId:"t"}).checksum).toMatch(/^sha256:/));
});
