import{describe,it,expect}from"vitest";import{TimelineOfflineRenderAndExportEngine as E}from"../../lib/timeline/TimelineOfflineRenderAndExportEngine";
const create=(e:E,o:Record<string,unknown>={})=>e.createJob({projectId:"p",name:"Mix",target:"mix",sourceIds:["master"],startSample:0,endSample:48000,sampleRate:48000,bitDepth:24,channels:2,format:"wav",createdBy:"steve",...o});
describe("TimelineOfflineRenderAndExportEngine",()=>{
it("validates, renders every frame, and fingerprints output",()=>{const e=new E();let j=create(e);j=e.validate({jobId:j.id,expectedHead:j.head,validatedBy:"steve"});j=e.queue({jobId:j.id,expectedHead:j.head,queuedBy:"steve"});j=e.start({jobId:j.id,expectedHead:j.head,workerId:"w"});j=e.reportProgress({jobId:j.id,expectedHead:j.head,renderedFrames:48000,workerId:"w"});j=e.complete({jobId:j.id,expectedHead:j.head,outputUri:"mix.wav",checksum:"sha256:x",workerId:"w"});expect(j).toMatchObject({state:"completed",renderedFrames:48000,checksum:"sha256:x"})});
it("holds unsafe formats, ranges, and missing sources",()=>{const e=new E();let j=create(e,{sourceIds:[],endSample:0,format:"mp3",bitDepth:24,channels:6});j=e.validate({jobId:j.id,expectedHead:j.head,validatedBy:"steve"});expect(j.state).toBe("held");expect(j.issues.length).toBeGreaterThanOrEqual(3)});
it("prevents premature completion and invalid progress",()=>{const e=new E();let j=create(e);j=e.validate({jobId:j.id,expectedHead:j.head,validatedBy:"s"});j=e.queue({jobId:j.id,expectedHead:j.head,queuedBy:"s"});j=e.start({jobId:j.id,expectedHead:j.head,workerId:"w"});expect(()=>e.complete({jobId:j.id,expectedHead:j.head,outputUri:"x",checksum:"x",workerId:"w"})).toThrow(/every frame/);expect(()=>e.reportProgress({jobId:j.id,expectedHead:j.head,renderedFrames:50000,workerId:"w"})).toThrow(/progress/)});
it("records failures with evidence",()=>{const e=new E();let j=create(e);j=e.validate({jobId:j.id,expectedHead:j.head,validatedBy:"s"});j=e.queue({jobId:j.id,expectedHead:j.head,queuedBy:"s"});j=e.start({jobId:j.id,expectedHead:j.head,workerId:"w"});j=e.fail({jobId:j.id,expectedHead:j.head,message:"disk full",workerId:"w"});expect(e.listReceipts(j.id).at(-1)?.message).toBe("disk full")});
it("restores stable job and receipt identities",()=>{const source=new E();create(source);const a=source.exportArchive(),e=new E();e.restoreArchive(a);expect(e.getJob(a.jobs[0].id)).toEqual(a.jobs[0]);expect(create(e).id).not.toBe(a.jobs[0].id);expect(()=>e.restoreArchive({jobs:[...a.jobs,a.jobs[0]],receipts:a.receipts})).toThrow(/duplicate/)});
});
