import { describe, expect, it } from "vitest";
import { evaluateTimelineDawOwnerTest, isTimelineDawOwnerTestReturnVerified, parseTimelineDawOwnerTestReturnStep, TIMELINE_DAW_OWNER_TEST_DEFINITIONS, timelineDawOwnerTestAwayStorageKey, timelineDawOwnerTestReturnConfirmedStorageKey, timelineDawOwnerTestReturnStorageKey, validateTimelineDawOwnerTestResult, type TimelineDawOwnerTestEvidence } from "../../lib/timeline/TimelineDawOwnerMusicianTestPolicy";
const empty: TimelineDawOwnerTestEvidence={audioSourceCount:0,editCount:0,mixControlCount:0,snapshotCount:0,completedExportCount:0};
describe("TimelineDawOwnerMusicianTestPolicy",()=>{
  it("reveals exactly the first unfinished step",()=>{expect(evaluateTimelineDawOwnerTest([],empty).current?.step).toBe("protect");expect(evaluateTimelineDawOwnerTest([{step:"protect",outcome:"pass"}],empty).current?.step).toBe("import")});
  it("does not accept a pass without durable DAW proof",()=>{expect(()=>validateTimelineDawOwnerTestResult({step:"import",outcome:"pass",evidence:empty})).toThrow(/required proof/);expect(validateTimelineDawOwnerTestResult({step:"import",outcome:"pass",evidence:{...empty,audioSourceCount:1}}).step).toBe("import")});
  it("retains failures while keeping that step current",()=>{const result=evaluateTimelineDawOwnerTest([{step:"protect",outcome:"pass"},{step:"import",outcome:"fail"}],empty);expect(result.completed).toBe(1);expect(result.current?.step).toBe("import")});
  it("requires an actual local download match before export can pass",()=>{const evidence={...empty,completedExportCount:1};expect(()=>validateTimelineDawOwnerTestResult({step:"export",outcome:"pass",evidence})).toThrow(/verify the downloaded/i);expect(validateTimelineDawOwnerTestResult({step:"export",outcome:"pass",evidence,downloadVerified:true}).step).toBe("export")});
  it("remembers only a validated current return step for one session",()=>{expect(parseTimelineDawOwnerTestReturnStep("mix")).toBe("mix");expect(parseTimelineDawOwnerTestReturnStep("private-note")).toBeNull();expect(timelineDawOwnerTestReturnStorageKey("session-14")).toBe("muzes:daw-owner-test-return:session-14");expect(()=>timelineDawOwnerTestReturnStorageKey("bad/session")).toThrow(/valid DAW session/i)});
  it("sends the reversible edit step to the real arrangement workspace",()=>{expect(TIMELINE_DAW_OWNER_TEST_DEFINITIONS.find((item)=>item.step==="edit")?.destination).toBe("#timeline-daw-arrange")});
  it("accepts the owner's reversible current-session clip-edit attestation",()=>{expect(validateTimelineDawOwnerTestResult({step:"edit",outcome:"pass",evidence:empty}).step).toBe("edit")});
  it("accepts the owner's audible current-session Quick Mix attestation",()=>{expect(validateTimelineDawOwnerTestResult({step:"mix",outcome:"pass",evidence:empty}).step).toBe("mix")});
  it("requires a real leave-and-return round trip before the return step can pass",()=>{expect(TIMELINE_DAW_OWNER_TEST_DEFINITIONS.find((item)=>item.step==="return")?.instruction).toMatch(/Codex chat/i);expect(()=>validateTimelineDawOwnerTestResult({step:"return",outcome:"pass",evidence:empty,returnVerified:false})).toThrow(/leave the app/i);expect(validateTimelineDawOwnerTestResult({step:"return",outcome:"pass",evidence:empty,returnVerified:true}).step).toBe("return")});
  it("rejects an instant focus flicker and verifies a one-second app round trip",()=>{expect(isTimelineDawOwnerTestReturnVerified(null,2_000)).toBe(false);expect(isTimelineDawOwnerTestReturnVerified(1_000,1_999)).toBe(false);expect(isTimelineDawOwnerTestReturnVerified(1_000,2_000)).toBe(true)});
  it("scopes durable leave timing to the active DAW session",()=>{expect(timelineDawOwnerTestAwayStorageKey("session-14")).toBe("muzes:daw-owner-test-away:session-14");expect(()=>timelineDawOwnerTestAwayStorageKey("bad/session")).toThrow(/valid DAW session/i)});
  it("scopes return confirmation to the active DAW session",()=>{expect(timelineDawOwnerTestReturnConfirmedStorageKey("session-14")).toBe("muzes:daw-owner-test-return-confirmed:session-14");expect(()=>timelineDawOwnerTestReturnConfirmedStorageKey("bad/session")).toThrow(/valid DAW session/i)});
});
