import { describe, expect, it } from "vitest";
import { assessTimelineDawThirdPartyInstrumentCompatibility } from "../../lib/timeline/TimelineDawThirdPartyInstrumentCompatibilityPolicy";

const passed = { fingerprintVerified: true, vendorVerified: true, sampleRateSupported: true, channelLayoutSupported: true, latencyMeasured: true, stateRecallPassed: true, bypassRecoveryPassed: true, renderedAudioVerified: false, midiNoteResponsePassed: true, velocityAndChannelPassed: true, presetAndProgramRecallPassed: true, automationPassed: true, polyphonyPassed: true };

describe("timeline DAW third-party instrument compatibility", () => {
  it("qualifies a fully verified browser-native WASM instrument", () => expect(assessTimelineDawThirdPartyInstrumentCompatibility({ format: "wasm", executionPath: "browser-native", ...passed })).toMatchObject({ status: "qualified", capability: "live-browser-processing", activationAllowed: true, directBinaryLoadAllowed: true, sourceMidiPreserved: true }));
  it("never claims Chrome directly loads a desktop instrument binary", () => expect(assessTimelineDawThirdPartyInstrumentCompatibility({ format: "vst3", executionPath: "browser-native", ...passed })).toMatchObject({ status: "held", capability: "unsupported", activationAllowed: false, directBinaryLoadAllowed: false, safeMode: "silent-placeholder" }));
  it("requires instrument-specific MIDI evidence for live bridges", () => expect(assessTimelineDawThirdPartyInstrumentCompatibility({ format: "au", executionPath: "desktop-bridge", ...passed, midiNoteResponsePassed: false, automationPassed: false, polyphonyPassed: false }).requirements.join(" ")).toMatch(/note-on.*automation.*polyphony/i));
  it("permits a verified rendered fallback without calling it live", () => expect(assessTimelineDawThirdPartyInstrumentCompatibility({ format: "aax", executionPath: "rendered-exchange", ...passed, renderedAudioVerified: true, midiNoteResponsePassed: false, velocityAndChannelPassed: false, presetAndProgramRecallPassed: false, automationPassed: false, polyphonyPassed: false })).toMatchObject({ status: "qualified", capability: "offline-rendered-audio", activationAllowed: false, safeMode: "verified-render", sourceMidiPreserved: true }));
  it("holds incomplete vendor, recall, and recovery evidence safely", () => expect(assessTimelineDawThirdPartyInstrumentCompatibility({ format: "clap", executionPath: "desktop-bridge", ...passed, vendorVerified: false, stateRecallPassed: false, bypassRecoveryPassed: false })).toMatchObject({ status: "held", activationAllowed: false, sourceAudioPreserved: true }));
});
