import { createClient, type SupabaseClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { evaluateTimelineDawOwnerTest, TIMELINE_DAW_OWNER_TEST_STEPS, validateTimelineDawOwnerTestResult, type TimelineDawOwnerTestEvidence, type TimelineDawOwnerTestOutcome, type TimelineDawOwnerTestStep } from "@/lib/timeline/TimelineDawOwnerMusicianTestPolicy";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";
export const runtime="nodejs",dynamic="force-dynamic";
const env=(name:string)=>{const value=process.env[name]?.trim();if(!value)throw Error(`${name} is not configured.`);return value};
async function authorize(request:NextRequest){const header=request.headers.get("authorization")??"";if(!header.toLowerCase().startsWith("bearer "))throw Error("Authentication is required.");const token=header.slice(7).trim(),client=createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}}),{data,error}=await client.auth.getUser(token);if(error||!data.user)throw Error("Supabase session is invalid or expired.");return{id:data.user.id,token,client}}
async function count(client:SupabaseClient,table:string,ownerId:string,sessionId:string,filters:Record<string,string>={}){let query=client.from(table).select("id",{count:"exact",head:true}).eq("owner_id",ownerId).eq("session_id",sessionId);for(const[column,value]of Object.entries(filters))query=query.eq(column,value);const{count:total,error}=await query;if(error)throw Error(`${table} could not be inspected: ${error.message}`);return total??0}
async function evidence(client:SupabaseClient,ownerId:string,sessionId:string):Promise<TimelineDawOwnerTestEvidence>{const values=await Promise.all([count(client,"timeline_daw_recording_takes",ownerId,sessionId),count(client,"timeline_daw_private_audio_lanes",ownerId,sessionId),count(client,"timeline_daw_private_lane_edit_history",ownerId,sessionId),count(client,"timeline_daw_arrangement_item_edits",ownerId,sessionId),count(client,"timeline_daw_private_buses",ownerId,sessionId),count(client,"timeline_daw_private_inserts",ownerId,sessionId),count(client,"timeline_daw_private_automation_edits",ownerId,sessionId),count(client,"timeline_daw_private_session_snapshots",ownerId,sessionId),count(client,"timeline_daw_private_bounce_jobs",ownerId,sessionId,{state:"completed"})]);return{audioSourceCount:values[0]+values[1],editCount:values[2]+values[3],mixControlCount:values[4]+values[5]+values[6],snapshotCount:values[7],completedExportCount:values[8]}}
async function context(request:NextRequest,sessionId:string){if(!sessionId)throw Error("sessionId is required.");const user=await authorize(request),session=await createTimelineDawWorkspaceServer(user.id,user.token).get(user.id,sessionId);if(!session)throw Error("DAW session was not found.");return user}
async function load(client:SupabaseClient,ownerId:string,sessionId:string){const{data:session,error:sessionError}=await client.from("timeline_daw_owner_test_sessions").select("id,status,created_at,updated_at").eq("owner_id",ownerId).eq("session_id",sessionId).order("created_at",{ascending:false}).limit(1).maybeSingle();if(sessionError)throw Error(`Guided test could not be loaded: ${sessionError.message}`);let observations:Record<string,unknown>[]=[];if(session){const{data,error}=await client.from("timeline_daw_owner_test_observations").select("id,step,outcome,notes,click_count,excessive_steps,screenshot_data_url,failure_context,created_at").eq("test_session_id",session.id).order("created_at",{ascending:true});if(error)throw Error(`Guided observations could not be loaded: ${error.message}`);observations=data??[]}const proof=await evidence(client,ownerId,sessionId);return{session,observations,evaluation:evaluateTimelineDawOwnerTest(observations.map(item=>({step:String(item.step) as TimelineDawOwnerTestStep,outcome:String(item.outcome) as TimelineDawOwnerTestOutcome})),proof)}}
const failure=(error:unknown)=>NextResponse.json({error:error instanceof Error?error.message:"Guided test request failed."},{status:400});
export async function GET(request:NextRequest){try{const sessionId=request.nextUrl.searchParams.get("sessionId")?.trim()??"",user=await context(request,sessionId);return NextResponse.json(await load(user.client,user.id,sessionId),{headers:{"Cache-Control":"no-store"}})}catch(error){return failure(error)}}
export async function POST(request:NextRequest){try{const body=await request.json(),sessionId=String(body.sessionId??"").trim(),user=await context(request,sessionId);let loaded=await load(user.client,user.id,sessionId);if(body.action==="start"){if(loaded.session?.status==="active")return NextResponse.json(loaded);const{error}=await user.client.from("timeline_daw_owner_test_sessions").insert({owner_id:user.id,session_id:sessionId});if(error)throw Error(`Guided test could not be started: ${error.message}`);return NextResponse.json(await load(user.client,user.id,sessionId))}if(body.action!=="result"||!loaded.session||loaded.session.status!=="active")throw Error("Start the guided test before recording a result.");const testSessionId=loaded.session.id;const step=String(body.step??"") as TimelineDawOwnerTestStep,outcome=String(body.outcome??"") as TimelineDawOwnerTestOutcome;if(!TIMELINE_DAW_OWNER_TEST_STEPS.includes(step)||!["pass","fail","confusing","blocked"].includes(outcome))throw Error("Choose a valid step result.");if(loaded.evaluation.current?.step!==step)throw Error(`Finish “${loaded.evaluation.current?.title??"the current step"}” first.`);validateTimelineDawOwnerTestResult({step,outcome,evidence:loaded.evaluation.evidence});const notes=String(body.notes??"").trim().slice(0,4000),screenshot=typeof body.screenshotDataUrl==="string"?body.screenshotDataUrl:"";if(outcome!=="pass"&&!notes)throw Error("Add a short note explaining what failed, was confusing, or blocked you.");if(screenshot&&(!screenshot.startsWith("data:image/")||screenshot.length>1_000_000))throw Error("The screenshot is not a supported image or is too large.");const clickCount=body.clickCount===""||body.clickCount==null?null:Number(body.clickCount);if(clickCount!==null&&(!Number.isInteger(clickCount)||clickCount<0||clickCount>10000))throw Error("Click count must be a whole number from 0 to 10000.");const{error}=await user.client.from("timeline_daw_owner_test_observations").insert({test_session_id:testSessionId,owner_id:user.id,session_id:sessionId,step,outcome,notes,click_count:clickCount,excessive_steps:Boolean(body.excessiveSteps),screenshot_data_url:screenshot||null,failure_context:body.failureContext&&typeof body.failureContext==="object"?body.failureContext:{}});if(error)throw Error(`Your test result could not be saved: ${error.message}`);loaded=await load(user.client,user.id,sessionId);if(loaded.evaluation.complete){const{error:updateError}=await user.client.from("timeline_daw_owner_test_sessions").update({status:"completed",updated_at:new Date().toISOString()}).eq("id",testSessionId).eq("owner_id",user.id);if(updateError)throw Error(`Test completion could not be saved: ${updateError.message}`);loaded=await load(user.client,user.id,sessionId)}return NextResponse.json(loaded)}catch(error){return failure(error)}}
