import type { MultiTrackSourceWorkspaceItem } from "./MultiTrackSourceTypes";

export const MULTI_TRACK_SOURCE_WORKSPACE_ITEMS: MultiTrackSourceWorkspaceItem[] = [
  {
    id: "library-source",
    label: "Library",
    sourceKind: "library",
    status: "recommended",
    description: "Use a saved Library track as a stable engine source.",
    recommendedFor: "Known songs, catalog testing, and repeatable comparison work.",
    demoPatch: {
      sourceLabel: "Library source",
      sourceKind: "library",
      sourceId: "library-demo-source",
      title: "Library Demo Source",
      artist: "The Muzes Garden",
      album: "Library Workspace",
      durationSeconds: 214,
      bpm: 96,
      keyLabel: "A minor",
      sampleRate: 44100,
      channelCount: 2,
      waveformReady: true,
      analysisReady: true,
      transientReady: true,
      metadataReady: true,
      syncReady: false,
      readiness: "draft",
      notes: [
        "Loaded from the source workspace Library lane.",
        "This is state-only until the real Library adapter is connected.",
        "Use this to test comparison and readiness flow safely.",
      ],
    },
  },
  {
    id: "finder-source",
    label: "Finder",
    sourceKind: "finder",
    status: "available",
    description: "Use a Finder result as a comparison candidate.",
    recommendedFor: "Match testing, related songs, and search-driven comparison.",
    demoPatch: {
      sourceLabel: "Finder source",
      sourceKind: "finder",
      sourceId: "finder-demo-source",
      title: "Finder Demo Match",
      artist: "The Muzes Garden",
      album: "Finder Workspace",
      durationSeconds: 208,
      bpm: 98,
      keyLabel: "C major",
      sampleRate: 44100,
      channelCount: 2,
      waveformReady: true,
      analysisReady: true,
      transientReady: true,
      metadataReady: true,
      syncReady: false,
      readiness: "draft",
      notes: [
        "Loaded from the source workspace Finder lane.",
        "This is state-only until Finder selection is wired in.",
        "Use this to test track-to-track matching without controller growth.",
      ],
    },
  },
  {
    id: "upload-source",
    label: "Upload",
    sourceKind: "upload",
    status: "coming-soon",
    description: "Prepare the lane for future uploaded audio files.",
    recommendedFor: "New audio, stems, test files, and user-provided tracks.",
    demoPatch: {
      sourceLabel: "Upload source",
      sourceKind: "upload",
      sourceId: "upload-demo-source",
      title: "Upload Demo Stem",
      artist: "User Upload",
      album: "Upload Workspace",
      durationSeconds: 176,
      bpm: 88,
      keyLabel: "D minor",
      sampleRate: 48000,
      channelCount: 2,
      waveformReady: true,
      analysisReady: false,
      transientReady: false,
      metadataReady: true,
      syncReady: false,
      readiness: "draft",
      notes: [
        "Loaded from the source workspace Upload lane.",
        "This is state-only until real upload wiring is connected.",
        "Use this to test future stem and uploaded-track workflows.",
      ],
    },
  },
  {
    id: "project-source",
    label: "Project",
    sourceKind: "project",
    status: "available",
    description: "Use a project-owned track as a workstation lane source.",
    recommendedFor: "Project pages, saved work sessions, and future project libraries.",
    demoPatch: {
      sourceLabel: "Project source",
      sourceKind: "project",
      sourceId: "project-demo-source",
      title: "Project Demo Track",
      artist: "Project Workspace",
      album: "Project Source Tests",
      durationSeconds: 240,
      bpm: 104,
      keyLabel: "G minor",
      sampleRate: 44100,
      channelCount: 2,
      waveformReady: true,
      analysisReady: true,
      transientReady: false,
      metadataReady: true,
      syncReady: false,
      readiness: "draft",
      notes: [
        "Loaded from the source workspace Project lane.",
        "This is state-only until project track selection is wired.",
        "Use this to test project-to-project source comparison.",
      ],
    },
  },
  {
    id: "seed-source",
    label: "Seed",
    sourceKind: "seed",
    status: "connected",
    description: "Use safe seeded source data for repeatable dashboard testing.",
    recommendedFor: "Build checks, UI testing, and green-state verification.",
    demoPatch: {
      sourceLabel: "Seed source",
      sourceKind: "seed",
      sourceId: "seed-demo-source",
      title: "Seed Demo Track",
      artist: "The Muzes Garden",
      album: "Seed Workspace",
      durationSeconds: 192,
      bpm: 92,
      keyLabel: "E minor",
      sampleRate: 44100,
      channelCount: 2,
      waveformReady: true,
      analysisReady: true,
      transientReady: true,
      metadataReady: true,
      syncReady: true,
      readiness: "ready",
      notes: [
        "Loaded from the source workspace Seed lane.",
        "This is the safest repeatable testing source.",
        "Use this to verify ready-state behavior without external data.",
      ],
    },
  },
];