import type { Track } from "../types/track";

export const TRACKS_SEED: Track[] = [
  {
    id: "demo-1",
    title: "Out of Tune 2 (Soft)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune2%20soft%202%2039%20.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-2",
    title: "Out of Tune 4 (Soft)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune4%20soft%20.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-3",
    title: "Out of Tune 3 (Soft)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune3%20soft%20(1).mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-4",
    title: "Out of Tune 2 (Hard)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune2%20hard.mp3%202%2003.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-5",
    title: "Out of Tune 1 (Soft)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune1%20soft%20(1).mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-6",
    title: "Out of Tune 1 (Hard)",
    artist: "The Muzes Garden",
    url: "https://buanleyzigiglewmedmr.supabase.co/storage/v1/object/public/mp3s%20for%20muzes%20garden/out%20of%20tune1%20hard%20.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
   {
    id: "demo-7",
    title: "Break da Hold",
    artist: "The Muzes Garden",
    url: "https://ohjvqopxmmfrvgliolcr.supabase.co/storage/v1/object/public/audio/Break_Da_Hold%20HARD%20ROCK1%20FUNKY%204%2006.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
   {
    id: "demo-8",
    title: "Back to the Sea",
    artist: "The Muzes Garden",
    url: "https://ohjvqopxmmfrvgliolcr.supabase.co/storage/v1/object/public/audio/back%20to%20the%20sea1%20r&b%20KEEPER.mp3",
    tags: ["demo"],
    createdAt: new Date().toISOString(),
  },
];