import{createHash}from"node:crypto";
export type TimelineDawVersionAlignment={versionId:string;sourceChecksum:string;offsetSeconds:number;confidence:number;method:"onset-correlation"|"manual";confirmed:boolean;revision:number};
export type TimelineDawVersionMarker={id:string;seconds:number;label:string;note:string;decision:"unreviewed"|"keeper"|"alternate"|"reject"};
const finite=(value:unknown,min:number,max:number,label:string)=>{const number=Number(value);if(!Number.isFinite(number)||number<min||number>max)throw Error(label+" must be from "+min+" to "+max+".");return number};
export function suggestTimelineDawVersionAlignment(reference:number[],candidate:number[],stepSeconds:number,maxOffsetSeconds=30){if(reference.length<4||candidate.length<4||stepSeconds<=0)throw Error("Alignment envelopes are insufficient.");const limit=Math.min(Math.floor(maxOffsetSeconds/stepSeconds),Math.max(reference.length,candidate.length)-1);let best={shift:0,score:-Infinity};for(let shift=-limit;shift<=limit;shift++){let dot=0,a2=0,b2=0,count=0;for(let i=0;i<reference.length;i++){const j=i+shift;if(j<0||j>=candidate.length)continue;const a=reference[i],b=candidate[j];dot+=a*b;a2+=a*a;b2+=b*b;count++}const score=count>=4&&a2&&b2?dot/Math.sqrt(a2*b2):-Infinity;if(score>best.score)best={shift,score}}return{offsetSeconds:-best.shift*stepSeconds,confidence:Math.max(0,Math.min(1,best.score)),method:"onset-correlation" as const}}
export function parseTimelineDawVersionAlignment(value:unknown):TimelineDawVersionAlignment{if(!value||typeof value!=="object")throw Error("Version alignment is required.");const input=value as Record<string,unknown>,versionId=String(input.versionId??"").trim(),sourceChecksum=String(input.sourceChecksum??"").toLowerCase();if(!versionId||!/^sha256:[a-f0-9]{64}$/.test(sourceChecksum))throw Error("Alignment version and checksum are required.");if(input.method!=="onset-correlation"&&input.method!=="manual")throw Error("Alignment method is invalid.");return{versionId,sourceChecksum,offsetSeconds:finite(input.offsetSeconds,-86400,86400,"Alignment offset"),confidence:finite(input.confidence,0,1,"Alignment confidence"),method:input.method,confirmed:Boolean(input.confirmed),revision:Math.floor(finite(input.revision??0,0,Number.MAX_SAFE_INTEGER,"Alignment revision"))}}
export function parseTimelineDawVersionMarker(value:unknown):TimelineDawVersionMarker{if(!value||typeof value!=="object")throw Error("Version marker is required.");const input=value as Record<string,unknown>,decision=String(input.decision??"unreviewed") as TimelineDawVersionMarker["decision"];if(!["unreviewed","keeper","alternate","reject"].includes(decision))throw Error("Marker decision is invalid.");const label=String(input.label??"").trim();if(!label||label.length>120)throw Error("Marker label is invalid.");return{id:String(input.id??"marker-"+crypto.randomUUID()),seconds:finite(input.seconds,0,86400,"Marker position"),label,note:String(input.note??"").trim().slice(0,1000),decision}}
export function timelineDawAlignmentReceiptChecksum(input:unknown){return"sha256:"+createHash("sha256").update(JSON.stringify(input)).digest("hex")}
export function isTimelineDawVersionAlignmentStale(alignment:TimelineDawVersionAlignment,currentChecksum:string){return alignment.sourceChecksum!==currentChecksum}
export function applyTimelineDawVersionOffset(baseSeconds:number,alignment:TimelineDawVersionAlignment){return Math.max(0,baseSeconds+alignment.offsetSeconds)}