import type { TimelineDawOwnerTestEvidence } from "./TimelineDawOwnerMusicianTestPolicy";

export const TIMELINE_DAW_VISUAL_LESSON_IDS = ["open-studio","protect-copy","import-audio","audition","edit","quick-mix","recover","export"] as const;
export type TimelineDawVisualLessonId=(typeof TIMELINE_DAW_VISUAL_LESSON_IDS)[number];
export type TimelineDawVisualLesson={id:TimelineDawVisualLessonId;screen:string;title:string;targetLabel:string;action:string;expected:string;why:string;anchor:string;proof:keyof TimelineDawOwnerTestEvidence|null;humanJudgment:boolean};

export const TIMELINE_DAW_VISUAL_LESSONS:TimelineDawVisualLesson[]=[
  {id:"open-studio",screen:"Project page",title:"Open the song workspace",targetLabel:"Studio",action:"Click the Studio tab inside the song project, then Enter Workspace on an existing session.",expected:"The DAW Session Workspace opens and shows the protected song session.",why:"A project can contain several safe DAW sessions without changing the original song.",anchor:"#owner-test-workspace",proof:null,humanJudgment:false},
  {id:"protect-copy",screen:"Guided test",title:"Protect the original",targetLabel:"Protected copy",action:"Confirm that this session is a working copy and not the only original recording.",expected:"The guide unlocks Import Audio as the next step.",why:"Experiments stay reversible and the original song remains recoverable.",anchor:"#owner-test-workspace",proof:null,humanJudgment:false},
  {id:"import-audio",screen:"Musician Audio Import",title:"Bring in the music",targetLabel:"Import Into Arrangement",action:"Choose Full Song, Stems, or Alternate Versions; select WAV/MP3 files; then import them.",expected:"Protected source copies appear as editable arrangement lanes.",why:"The DAW edits lane instructions while preserving source audio.",anchor:"#musician-audio-import",proof:"audioSourceCount",humanJudgment:false},
  {id:"audition",screen:"Transport",title:"Listen before changing anything",targetLabel:"Play",action:"Press Play and listen long enough to confirm that the correct song and versions loaded.",expected:"The playhead moves and the expected audio is heard.",why:"A quick identity check prevents editing the wrong song or version.",anchor:"#timeline-daw-transport",proof:null,humanJudgment:true},
  {id:"edit",screen:"Arrangement",title:"Make one reversible edit",targetLabel:"Split / Move / Trim",action:"Select one region and make one small arrangement change, then audition it.",expected:"The waveform region changes while edit history keeps the earlier state available.",why:"Non-destructive history lets musicians explore without losing work.",anchor:"#beta-workflow-edit",proof:"editCount",humanJudgment:true},
  {id:"quick-mix",screen:"Quick Mix",title:"Make one mix decision",targetLabel:"Gain / Pan / Mute / Solo",action:"Change one clearly audible mix control or apply one native starting sound.",expected:"The channel updates, meters remain visible, and the source recording is unchanged.",why:"A small intentional decision is easier to evaluate than changing everything at once.",anchor:"#musician-quick-mix",proof:"mixControlCount",humanJudgment:true},
  {id:"recover",screen:"Recovery",title:"Save a recovery point",targetLabel:"Create Snapshot",action:"Give the current state a recognizable name and save a session snapshot.",expected:"A dated recovery point appears and can restore the earlier session state.",why:"Recovery points turn experimentation into a safe process.",anchor:"#beta-workflow-protect",proof:"snapshotCount",humanJudgment:false},
  {id:"export",screen:"Export",title:"Create a verified listening file",targetLabel:"Render / Download",action:"Render the mix, wait for completion, and download the checksum-protected result.",expected:"A completed export appears with a downloadable verified artifact.",why:"Verification proves the delivered file matches the render the DAW completed.",anchor:"#beta-workflow-export",proof:"completedExportCount",humanJudgment:true},
];

export function evaluateTimelineDawVisualGuide(evidence:TimelineDawOwnerTestEvidence){return TIMELINE_DAW_VISUAL_LESSONS.map((lesson,index)=>({...lesson,number:index+1,automatedStatus:lesson.proof===null?"human-or-navigation":evidence[lesson.proof]>0?"verified":"not-yet-verified" as const}))}

export function normalizeTimelineDawVisualLessonIndex(value:number){if(!Number.isFinite(value))return 0;return Math.min(TIMELINE_DAW_VISUAL_LESSONS.length-1,Math.max(0,Math.trunc(value)))}
