export type TimelineDawNavigationDestination = { id: string; label: string; purpose: string; href: string; actionLabel: string; steps: string[] };

export const TIMELINE_DAW_NAVIGATION_DESTINATIONS: TimelineDawNavigationDestination[] = [
  { id: "start-song", label: "Start a new song", purpose: "Create the Studio session that holds your tracks and recordings.", href: "/workspace/projects", actionLabel: "Choose a Project", steps: ["Open Projects.", "Choose the project that should hold the song.", "Open the Studio tab.", "Under Start a song, choose linked music and name the session.", "Choose Start in Studio."] },
  { id: "open-session", label: "Continue an existing song", purpose: "Return to a Studio session you already started.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Find My Sessions", steps: ["Open the DAW Control Center.", "Use Search open sessions if the list is long.", "Choose the main action shown for the session until it says Enter Studio.", "Choose Enter Studio."] },
  { id: "add-audio", label: "Add an MP3, WAV, or audio track", purpose: "Bring an existing recording into the song.", href: "/upload", actionLabel: "Upload Audio", steps: ["Upload the audio file.", "Link it to the project that holds your song.", "Open that project’s Studio session.", "Use the private audio/source lanes area to place it in the timeline."] },
  { id: "record-audio", label: "Record vocals or instruments", purpose: "Record microphone or audio-interface performances into saved takes.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Enter the song’s Studio session.", "Find Recording — Live PCM capture.", "Choose the input and use Test Input Level.", "Choose Start Recording, perform, then Stop & Save.", "Audition the saved take and choose Use as Preferred when ready."] },
  { id: "midi", label: "Create or edit MIDI", purpose: "Work with MIDI notes, timing, instruments, and controller information.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Enter the song’s Studio session.", "Find the Private MIDI workspace.", "Create or import a MIDI clip.", "Edit notes and timing, then save the clip revision."] },
  { id: "edit-tracks", label: "Move, trim, or organize tracks", purpose: "Arrange audio lanes and clips along the song timeline.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Enter the song’s Studio session.", "Find Recorded and promoted audio or the arrangement workspace.", "Select the lane or clip you want to change.", "Adjust its timeline position, source range, grouping, or order.", "Audition the change before continuing."] },
  { id: "mix", label: "Mix tracks and add effects", purpose: "Set volume, pan, mute, solo, buses, effects, and automation.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Enter the song’s Studio session.", "Find the private lanes, buses, master, and automation sections.", "Set lane volume and pan first.", "Add buses or effects only where needed.", "Play the song and compare the result."] },
  { id: "export", label: "Export or bounce the song", purpose: "Create a listening or delivery file from the Studio session.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Enter the song’s Studio session.", "Find Export and render.", "Choose the source, format, and range.", "Validate and save the render.", "Download the completed file."] },
  { id: "recover", label: "Find a recording or recover lost work", purpose: "Reload saved takes or recover a recording that did not finish saving.", href: "/workspace/daw#daw-open-sessions", actionLabel: "Open a Studio Session", steps: ["Return to the correct Studio session.", "In Recording, check Local recording recovery and Saved takes.", "Choose Retry Private Save for protected unsaved audio.", "Choose Reload Saved Takes if the saved list could not be confirmed."] },
];
