import type { TimelineDawPrivateAutomationInterpolation, TimelineDawPrivateAutomationParameter, TimelineDawPrivateAutomationPoint } from "./TimelineDawPrivateAutomationPolicy";

export type TimelineDawPrivateAutomationRecordingMode="touch"|"latch"|"write";
export type TimelineDawPrivateAutomationCapture={samplePosition:number;value:number};
const bounds={gain:[0,2],pan:[-1,1]} as const;
const clamp=(value:number,parameter:TimelineDawPrivateAutomationParameter)=>Math.max(bounds[parameter][0],Math.min(bounds[parameter][1],value));

function distance(point:TimelineDawPrivateAutomationCapture,start:TimelineDawPrivateAutomationCapture,end:TimelineDawPrivateAutomationCapture):number{if(end.samplePosition===start.samplePosition)return Math.abs(point.value-start.value);const projected=start.value+(end.value-start.value)*(point.samplePosition-start.samplePosition)/(end.samplePosition-start.samplePosition);return Math.abs(point.value-projected);}
export function reduceTimelineDawPrivateAutomationCaptures(captures:TimelineDawPrivateAutomationCapture[],tolerance:number):TimelineDawPrivateAutomationCapture[]{if(!Number.isFinite(tolerance)||tolerance<0)throw new Error("Automation reduction tolerance must be non-negative.");const ordered=[...captures].sort((a,b)=>a.samplePosition-b.samplePosition).filter((item,index,all)=>index===all.length-1||item.samplePosition!==all[index+1].samplePosition);if(ordered.length<3)return ordered;let farthest=0,index=-1;for(let current=1;current<ordered.length-1;current+=1){const next=distance(ordered[current],ordered[0],ordered[ordered.length-1]);if(next>farthest){farthest=next;index=current;}}if(farthest<=tolerance)return[ordered[0],ordered[ordered.length-1]];return[...reduceTimelineDawPrivateAutomationCaptures(ordered.slice(0,index+1),tolerance).slice(0,-1),...reduceTimelineDawPrivateAutomationCaptures(ordered.slice(index),tolerance)];}
export function mergeTimelineDawPrivateAutomationRecording(input:{existing:TimelineDawPrivateAutomationPoint[];captures:TimelineDawPrivateAutomationCapture[];parameter:TimelineDawPrivateAutomationParameter;mode:TimelineDawPrivateAutomationRecordingMode;tolerance:number;interpolation?:TimelineDawPrivateAutomationInterpolation}):TimelineDawPrivateAutomationPoint[]{const reduced=reduceTimelineDawPrivateAutomationCaptures(input.captures,input.tolerance);if(!reduced.length)return input.existing;const start=reduced[0].samplePosition,end=reduced[reduced.length-1].samplePosition,kept=input.mode==="write"?input.existing.filter((point)=>point.samplePosition<start||point.samplePosition>end):input.existing.filter((point)=>point.samplePosition<start||point.samplePosition>end);const captured=reduced.map((item)=>({id:`point-${crypto.randomUUID()}`,samplePosition:item.samplePosition,value:clamp(item.value,input.parameter),interpolation:input.interpolation??"linear" as const}));return[...kept,...captured].sort((a,b)=>a.samplePosition-b.samplePosition);}
export function transformTimelineDawPrivateAutomationPoints(input:{points:TimelineDawPrivateAutomationPoint[];selectedIds:Set<string>;deltaSamples:number;valueScale:number;parameter:TimelineDawPrivateAutomationParameter;interpolation?:TimelineDawPrivateAutomationInterpolation}):TimelineDawPrivateAutomationPoint[]{const transformed=input.points.map((point)=>input.selectedIds.has(point.id)?{...point,samplePosition:Math.max(0,Math.round(point.samplePosition+input.deltaSamples)),value:clamp(point.value*input.valueScale,input.parameter),interpolation:input.interpolation??point.interpolation}:point).sort((a,b)=>a.samplePosition-b.samplePosition);for(let index=1;index<transformed.length;index+=1)if(transformed[index].samplePosition<=transformed[index-1].samplePosition)throw new Error("Curve movement would overlap automation sample positions.");return transformed;}
