import { createHash } from"node:crypto";
export type TimelineDawNormalizationReview={songId:string;decision:"pending"|"confirmed"|"corrected";key:string;mode:"major"|"minor";bpm:number;note:string};
export function parseTimelineDawNormalizationReviews(value:unknown,knownIds:ReadonlySet<string>):TimelineDawNormalizationReview[]{if(!Array.isArray(value))throw Error("Normalization reviews are required.");const seen=new Set<string>();return value.map((raw,index)=>{if(!raw||typeof raw!=="object")throw Error(`Review ${index+1} is invalid.`);const x=raw as Record<string,unknown>,songId=String(x.songId??"").trim(),decision=String(x.decision??"pending") as TimelineDawNormalizationReview["decision"],key=String(x.key??"").trim().toUpperCase(),mode=x.mode,bpm=Number(x.bpm),note=String(x.note??"").trim();if(!knownIds.has(songId)||seen.has(songId))throw Error(`Review ${index+1} source is invalid.`);seen.add(songId);if(!["pending","confirmed","corrected"].includes(decision))throw Error(`Review ${index+1} decision is invalid.`);if(!/^[A-G](#)?$/.test(key)||(mode!=="major"&&mode!=="minor"))throw Error(`Review ${index+1} key is invalid.`);if(!Number.isFinite(bpm)||bpm<40||bpm>240)throw Error(`Review ${index+1} tempo is invalid.`);if(note.length>500)throw Error(`Review ${index+1} note is too long.`);return{songId,decision,key,mode,bpm:Math.round(bpm*10)/10,note}})}
export function timelineDawNormalizationRevisionChecksum(input:{targetBpm:number;targetKey:string;targetMode:string;reviews:TimelineDawNormalizationReview[]}){return`sha256:${createHash("sha256").update(JSON.stringify(input)).digest("hex")}`}
export function assertTimelineDawNormalizationPromotion(reviews:TimelineDawNormalizationReview[]){const pending=reviews.filter(x=>x.decision==="pending");if(pending.length)throw Error(`Confirm or correct ${pending.length} normalization review${pending.length===1?"":"s"} before promotion.`)}
const NOTES=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
export type TimelineDawNormalizationTransform={songId:string;bpm:number;targetBpm:number;stretchRatio:number;pitchSemitones:number};
export function createTimelineDawNormalizationTransforms(reviews:TimelineDawNormalizationReview[],targetBpm:number,targetKey:string):TimelineDawNormalizationTransform[]{if(!Number.isFinite(targetBpm)||targetBpm<40||targetBpm>240)throw Error("Normalization target tempo is invalid.");const target=NOTES.indexOf(targetKey.toUpperCase());if(target<0)throw Error("Normalization target key is invalid.");return reviews.map(review=>{const source=NOTES.indexOf(review.key);if(source<0)throw Error(`Normalization source key ${review.key} is invalid.`);let semitones=target-source;while(semitones>6)semitones-=12;while(semitones< -6)semitones+=12;return{songId:review.songId,bpm:review.bpm,targetBpm,stretchRatio:Math.round(targetBpm/review.bpm*1e6)/1e6,pitchSemitones:semitones}})}
export function assertTimelineDawNormalizationRevision(expected:number,current:number){if(!Number.isInteger(expected)||expected!==current)throw Error(`Normalization proof changed from revision ${expected} to ${current}; reload before saving.`)}
export function diffTimelineDawNormalizationRevisions(left:{target_bpm:number;target_key:string;target_mode:string;reviews:TimelineDawNormalizationReview[]},right:typeof left){const changed=new Set<string>();if(left.target_bpm!==right.target_bpm)changed.add("target tempo");if(left.target_key!==right.target_key||left.target_mode!==right.target_mode)changed.add("target key");const before=new Map(left.reviews.map(x=>[x.songId,x]));for(const review of right.reviews)if(JSON.stringify(before.get(review.songId))!==JSON.stringify(review))changed.add(review.songId);return[...changed]}
