import type { TimelineId, TimelineUserId } from "./TimelineTypes";
export type AutomationPoint={id:TimelineId;sample:number;value:number;curve:"step"|"linear"|"smooth"};
export type ExecutionLane={id:TimelineId;targetId:TimelineId;parameter:string;minimum:number;maximum:number;defaultValue:number;mode:"read"|"touch"|"latch"|"write";points:AutomationPoint[];status:"draft"|"held"|"validated"|"active";issues:string[];head:number;updatedBy:TimelineUserId};
const clone=<T>(v:T):T=>structuredClone(v);
export class TimelineAutomationExecutionEngine{
 private lanes=new Map<TimelineId,ExecutionLane>();private sequence=0;private pointSequence=0;
 createLane(i:{targetId:TimelineId;parameter:string;minimum:number;maximum:number;defaultValue:number;mode?:ExecutionLane["mode"];createdBy:TimelineUserId}){
  if(!i.targetId.trim()||!i.parameter.trim()||i.minimum>=i.maximum||i.defaultValue<i.minimum||i.defaultValue>i.maximum)throw new Error("Invalid automation lane.");
  const lane:ExecutionLane={id:`timeline-automation-execution-${++this.sequence}`,targetId:i.targetId,parameter:i.parameter,minimum:i.minimum,maximum:i.maximum,defaultValue:i.defaultValue,mode:i.mode??"read",points:[],status:"draft",issues:[],head:0,updatedBy:i.createdBy};this.lanes.set(lane.id,clone(lane));return clone(lane);
 }
 addPoint(i:{laneId:TimelineId;expectedHead:number;sample:number;value:number;curve?:AutomationPoint["curve"];editedBy:TimelineUserId}){const lane=this.editable(i.laneId,i.expectedHead);if(!Number.isInteger(i.sample)||i.sample<0||i.value<lane.minimum||i.value>lane.maximum)throw new Error("Invalid automation point.");if(lane.points.some(p=>p.sample===i.sample))throw new Error("Duplicate automation sample.");lane.points.push({id:`timeline-automation-point-${++this.pointSequence}`,sample:i.sample,value:i.value,curve:i.curve??"linear"});lane.points.sort((a,b)=>a.sample-b.sample);return this.save(lane,i.editedBy)}
 validate(i:{laneId:TimelineId;expectedHead:number;validatedBy:TimelineUserId}){const lane=this.editable(i.laneId,i.expectedHead);lane.issues=lane.points.length?[]:["Automation requires a point."];lane.status=lane.issues.length?"held":"validated";return this.save(lane,i.validatedBy)}
 activate(i:{laneId:TimelineId;expectedHead:number;activatedBy:TimelineUserId}){const lane=this.required(i.laneId);this.head(lane,i.expectedHead);if(lane.status!=="validated")throw new Error("Only validated automation can execute.");lane.status="active";return this.save(lane,i.activatedBy)}
 valueAt(id:TimelineId,sample:number){const lane=this.required(id);if(lane.status!=="active")return lane.defaultValue;const before=[...lane.points].reverse().find(p=>p.sample<=sample),after=lane.points.find(p=>p.sample>sample);if(!before)return lane.points[0]?.value??lane.defaultValue;if(!after||before.curve==="step")return before.value;const x=(sample-before.sample)/(after.sample-before.sample),t=before.curve==="smooth"?x*x*(3-2*x):x;return before.value+(after.value-before.value)*t}
 exportArchive(){return{lanes:[...this.lanes.values()].map(clone)}}
 restoreArchive(a:{lanes:ExecutionLane[]}){const ids=new Set<string>();a.lanes.forEach(l=>{if(ids.has(l.id))throw new Error("Duplicate automation identity.");ids.add(l.id);l.points.forEach(p=>{if(ids.has(p.id))throw new Error("Duplicate automation identity.");ids.add(p.id)})});this.lanes.clear();this.sequence=this.pointSequence=0;a.lanes.forEach(l=>{this.lanes.set(l.id,clone(l));this.sequence=Math.max(this.sequence,Number(l.id.match(/(\d+)$/)?.[1]??0));l.points.forEach(p=>this.pointSequence=Math.max(this.pointSequence,Number(p.id.match(/(\d+)$/)?.[1]??0)))})}
 getLane(id:TimelineId){return this.required(id)}private required(id:TimelineId){const lane=this.lanes.get(id);if(!lane)throw new Error("Automation lane not found.");return clone(lane)}private head(l:ExecutionLane,h:number){if(l.head!==h)throw new Error("Automation head conflict.")}private editable(id:TimelineId,h:number){const l=this.required(id);this.head(l,h);if(!["draft","held"].includes(l.status))throw new Error("Automation is not editable.");return l}private save(l:ExecutionLane,by:TimelineUserId){const n={...clone(l),head:l.head+1,updatedBy:by};this.lanes.set(n.id,clone(n));return clone(n)}
}
export const timelineAutomationExecutionEngine=new TimelineAutomationExecutionEngine();
