import type{TimelineId,TimelineUserId}from"./TimelineTypes";
export type SessionPerformanceSample={id:TimelineId;sessionId:TimelineId;cpuPercent:number;memoryMb:number;latencyMs:number;xruns:number;recordedAt:string};
export type SessionCheckpoint={id:TimelineId;sessionId:TimelineId;label:string;sessionHead:number;state:unknown;checksum:string;createdAt:string;createdBy:TimelineUserId};
export type SessionHealth={status:"healthy"|"warning"|"critical";issues:string[];actions:string[]};
export type SessionRecoveryArchive={samples:SessionPerformanceSample[];checkpoints:SessionCheckpoint[]};
const clone=<T>(v:T):T=>structuredClone(v);const hash=(v:unknown)=>{let h=2166136261;for(const c of JSON.stringify(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return`session-${(h>>>0).toString(16)}`};
export class TimelineSessionRecoveryAndPerformanceEngine{
 private samples:SessionPerformanceSample[]=[];private checkpoints:SessionCheckpoint[]=[];private sampleSequence=0;private checkpointSequence=0;
 constructor(private now:()=>Date=()=>new Date()){}
 recordPerformance(i:{sessionId:TimelineId;cpuPercent:number;memoryMb:number;latencyMs:number;xruns:number}){if(!i.sessionId.trim()||![i.cpuPercent,i.memoryMb,i.latencyMs,i.xruns].every(Number.isFinite)||i.cpuPercent<0||i.cpuPercent>100||i.memoryMb<0||i.latencyMs<0||!Number.isInteger(i.xruns)||i.xruns<0)throw new Error("Invalid session performance sample.");const s:SessionPerformanceSample={id:`timeline-session-performance-${++this.sampleSequence}`,...i,recordedAt:this.now().toISOString()};this.samples.push(clone(s));return clone(s)}
 assess(sessionId:TimelineId):SessionHealth{const recent=this.samples.filter(s=>s.sessionId===sessionId).slice(-20),issues:string[]=[],actions:string[]=[];if(!recent.length)return{status:"warning",issues:["No performance evidence is available."],actions:["Collect a performance sample."]};const last=recent.at(-1)!;if(last.cpuPercent>=90){issues.push("CPU is critically overloaded.");actions.push("Freeze device-heavy tracks.")}else if(last.cpuPercent>=75){issues.push("CPU load is high.");actions.push("Increase the audio buffer.")}if(last.memoryMb>=8192){issues.push("Memory use is critically high.");actions.push("Unload unused samples.")}if(last.xruns>0){issues.push(`${last.xruns} audio dropout(s) detected.`);actions.push("Enable safe playback mode.")}if(last.latencyMs>25){issues.push("Monitoring latency is high.");actions.push("Disable look-ahead devices while recording.")}return{status:issues.some(x=>/critically/.test(x))?"critical":issues.length?"warning":"healthy",issues,actions:[...new Set(actions)]}}
 createCheckpoint(i:{sessionId:TimelineId;label:string;sessionHead:number;state:unknown;createdBy:TimelineUserId}){if(!i.sessionId.trim()||!i.label.trim()||!Number.isInteger(i.sessionHead)||i.sessionHead<0)throw new Error("Invalid recovery checkpoint.");const unsigned={id:`timeline-session-checkpoint-${++this.checkpointSequence}`,sessionId:i.sessionId,label:i.label.trim(),sessionHead:i.sessionHead,state:clone(i.state),createdAt:this.now().toISOString(),createdBy:i.createdBy};const c:SessionCheckpoint={...unsigned,checksum:hash(unsigned)};this.checkpoints.push(clone(c));return clone(c)}
 validateCheckpoint(c:SessionCheckpoint){const{checksum,...unsigned}=c;return checksum===hash(unsigned)}
 restoreCheckpoint(id:TimelineId){const c=this.checkpoints.find(v=>v.id===id);if(!c)throw new Error("Recovery checkpoint not found.");if(!this.validateCheckpoint(c))throw new Error("Recovery checkpoint checksum mismatch.");return{sessionId:c.sessionId,sessionHead:c.sessionHead,state:clone(c.state)}}
 latestCheckpoint(sessionId:TimelineId){return clone(this.checkpoints.filter(c=>c.sessionId===sessionId).at(-1)??null)}
 exportArchive():SessionRecoveryArchive{return{samples:this.samples.map(clone),checkpoints:this.checkpoints.map(clone)}}
 restoreArchive(a:SessionRecoveryArchive){const ids=new Set<string>();[...a.samples,...a.checkpoints].forEach(v=>{if(ids.has(v.id))throw new Error("Recovery archive contains duplicate identities.");ids.add(v.id)});if(a.checkpoints.some(c=>!this.validateCheckpoint(c)))throw new Error("Recovery archive contains a checksum mismatch.");this.samples=a.samples.map(clone);this.checkpoints=a.checkpoints.map(clone);this.sampleSequence=Math.max(0,...a.samples.map(s=>this.seq(s.id)));this.checkpointSequence=Math.max(0,...a.checkpoints.map(c=>this.seq(c.id)))}
 private seq(id:string){return Number(id.match(/(\d+)$/)?.[1]??0)}
}
export const timelineSessionRecoveryAndPerformanceEngine=new TimelineSessionRecoveryAndPerformanceEngine();
