import type { TimelineId, TimelineUserId } from "./TimelineTypes";

export type TimelineRenderTarget = "mix" | "stem" | "selection";
export type TimelineRenderFormat = "wav" | "flac" | "mp3";
export type TimelineOfflineRenderJob = {
  id: TimelineId; projectId: TimelineId; name: string; target: TimelineRenderTarget; sourceIds: TimelineId[];
  startSample: number; endSample: number; sampleRate: number; bitDepth: 16 | 24 | 32; channels: number;
  format: TimelineRenderFormat; normalizePeakDb: number | null; dither: boolean;
  state: "draft" | "held" | "validated" | "queued" | "rendering" | "completed" | "failed" | "archived";
  issues: string[]; renderedFrames: number; totalFrames: number; checksum: string | null;
  outputUri: string | null; head: number; createdBy: TimelineUserId; updatedBy: TimelineUserId;
};
export type TimelineRenderReceipt = { id: TimelineId; jobId: TimelineId; action: string; message: string; recordedAt: string; recordedBy: TimelineUserId };
export type TimelineOfflineRenderArchive = { jobs: TimelineOfflineRenderJob[]; receipts: TimelineRenderReceipt[] };
const clone=<T>(v:T):T=>structuredClone(v);
const text=(v:string,l:string)=>{const n=v.trim();if(!n)throw new Error(`${l} is required.`);return n};
export class TimelineOfflineRenderAndExportEngine{
 private jobs=new Map<TimelineId,TimelineOfflineRenderJob>();private receipts:TimelineRenderReceipt[]=[];private sequence=0;private receiptSequence=0;
 constructor(private now:()=>Date=()=>new Date()){}
 createJob(i:{projectId:TimelineId;name:string;target:TimelineRenderTarget;sourceIds:TimelineId[];startSample:number;endSample:number;sampleRate:number;bitDepth:16|24|32;channels:number;format:TimelineRenderFormat;normalizePeakDb?:number|null;dither?:boolean;createdBy:TimelineUserId}){
  const job:TimelineOfflineRenderJob={id:`timeline-offline-render-${++this.sequence}`,projectId:text(i.projectId,"Project"),name:text(i.name,"Render name"),target:i.target,sourceIds:[...new Set(i.sourceIds.map(v=>text(v,"Source")))],startSample:i.startSample,endSample:i.endSample,sampleRate:i.sampleRate,bitDepth:i.bitDepth,channels:i.channels,format:i.format,normalizePeakDb:i.normalizePeakDb??null,dither:i.dither??false,state:"draft",issues:[],renderedFrames:0,totalFrames:Math.max(0,i.endSample-i.startSample),checksum:null,outputUri:null,head:0,createdBy:i.createdBy,updatedBy:i.createdBy};this.jobs.set(job.id,clone(job));this.record(job,"created","Render draft created.",i.createdBy);return clone(job)}
 validate(i:{jobId:TimelineId;expectedHead:number;validatedBy:TimelineUserId}){const j=this.editable(i.jobId,i.expectedHead);j.issues=[];if(!j.sourceIds.length)j.issues.push("At least one source is required.");if(!Number.isInteger(j.startSample)||!Number.isInteger(j.endSample)||j.startSample<0||j.endSample<=j.startSample)j.issues.push("Render range is invalid.");if(!Number.isInteger(j.sampleRate)||j.sampleRate<8000||j.sampleRate>384000)j.issues.push("Sample rate is invalid.");if(!Number.isInteger(j.channels)||j.channels<1||j.channels>64)j.issues.push("Channel count is invalid.");if(j.format==="mp3"&&(j.bitDepth!==16||j.channels>2))j.issues.push("MP3 requires 16-bit mono or stereo output.");if(j.normalizePeakDb!==null&&(j.normalizePeakDb>0||j.normalizePeakDb< -24))j.issues.push("Normalization peak must be between -24 and 0 dB.");j.state=j.issues.length?"held":"validated";const saved=this.save(j,i.validatedBy);this.record(saved,saved.state,saved.issues.length?`Held with ${saved.issues.length} issue(s).`:"Render validated.",i.validatedBy);return saved}
 queue(i:{jobId:TimelineId;expectedHead:number;queuedBy:TimelineUserId}){const j=this.required(i.jobId);this.head(j,i.expectedHead);if(j.state!=="validated")throw new Error("Only validated renders can be queued.");j.state="queued";return this.save(j,i.queuedBy)}
 start(i:{jobId:TimelineId;expectedHead:number;workerId:string}){const j=this.required(i.jobId);this.head(j,i.expectedHead);if(j.state!=="queued")throw new Error("Only queued renders can start.");j.state="rendering";const saved=this.save(j,text(i.workerId,"Worker"));this.record(saved,"started","Offline rendering started.",i.workerId);return saved}
 reportProgress(i:{jobId:TimelineId;expectedHead:number;renderedFrames:number;workerId:string}){const j=this.required(i.jobId);this.head(j,i.expectedHead);if(j.state!=="rendering")throw new Error("Render is not running.");if(!Number.isInteger(i.renderedFrames)||i.renderedFrames<j.renderedFrames||i.renderedFrames>j.totalFrames)throw new Error("Render progress is invalid.");j.renderedFrames=i.renderedFrames;return this.save(j,i.workerId)}
 complete(i:{jobId:TimelineId;expectedHead:number;outputUri:string;checksum:string;workerId:string}){const j=this.required(i.jobId);this.head(j,i.expectedHead);if(j.state!=="rendering"||j.renderedFrames!==j.totalFrames)throw new Error("Render must finish every frame before completion.");j.outputUri=text(i.outputUri,"Output URI");j.checksum=text(i.checksum,"Checksum");j.state="completed";const saved=this.save(j,i.workerId);this.record(saved,"completed","Offline render completed and fingerprinted.",i.workerId);return saved}
 fail(i:{jobId:TimelineId;expectedHead:number;message:string;workerId:string}){const j=this.required(i.jobId);this.head(j,i.expectedHead);if(j.state!=="rendering")throw new Error("Only a running render can fail.");j.state="failed";const saved=this.save(j,i.workerId);this.record(saved,"failed",text(i.message,"Failure message"),i.workerId);return saved}
 getJob(id:TimelineId){return this.required(id)}listReceipts(id:TimelineId){return this.receipts.filter(r=>r.jobId===id).map(clone)}exportArchive():TimelineOfflineRenderArchive{return{jobs:[...this.jobs.values()].map(clone),receipts:this.receipts.map(clone)}}
 restoreArchive(a:TimelineOfflineRenderArchive){const ids=new Set<string>();const use=(id:string)=>{if(ids.has(id))throw new Error("Render archive contains duplicate identities.");ids.add(id)};a.jobs.forEach(j=>use(j.id));a.receipts.forEach(r=>{use(r.id);if(!a.jobs.some(j=>j.id===r.jobId))throw new Error("Receipt refers to a missing render.");});this.jobs.clear();this.receipts=[];this.sequence=this.receiptSequence=0;a.jobs.forEach(j=>{this.jobs.set(j.id,clone(j));this.sequence=Math.max(this.sequence,this.seq(j.id))});a.receipts.forEach(r=>{this.receipts.push(clone(r));this.receiptSequence=Math.max(this.receiptSequence,this.seq(r.id))})}
 private required(id:TimelineId){const j=this.jobs.get(id);if(!j)throw new Error("Render job not found.");return clone(j)}private editable(id:TimelineId,h:number){const j=this.required(id);this.head(j,h);if(!["draft","held"].includes(j.state))throw new Error("Render job is not editable.");return j}private head(j:TimelineOfflineRenderJob,h:number){if(j.head!==h)throw new Error("Render head conflict.")}private save(j:TimelineOfflineRenderJob,by:TimelineUserId){const n={...clone(j),head:j.head+1,updatedBy:by};this.jobs.set(n.id,clone(n));return clone(n)}private record(j:TimelineOfflineRenderJob,action:string,message:string,by:TimelineUserId){this.receipts.push({id:`timeline-render-receipt-${++this.receiptSequence}`,jobId:j.id,action,message,recordedAt:this.now().toISOString(),recordedBy:by})}private seq(id:string){return Number(id.match(/(\d+)$/)?.[1]??0)}
}
export const timelineOfflineRenderAndExportEngine=new TimelineOfflineRenderAndExportEngine();
