export type TimelineDawTempoAnalysis={bpm:number;confidence:number};
export type TimelineDawKeyAnalysis={key:string;mode:"major"|"minor";confidence:number};
export type TimelineDawNormalizationSource={id:string;name:string;bpm:number;key:string;mode:"major"|"minor"};
export type TimelineDawNormalizationPlan={targetBpm:number;targetKey:string;targetMode:"major"|"minor";sources:Array<TimelineDawNormalizationSource&{stretchRatio:number;pitchSemitones:number}>};
const NOTES=["C","C#","D","D#","E","F","F#","G","G#","A","A#","B"];
const MAJOR=[6.35,2.23,3.48,2.33,4.38,4.09,2.52,5.19,2.39,3.66,2.29,2.88],MINOR=[6.33,2.68,3.52,5.38,2.6,3.53,2.54,4.75,3.98,2.69,3.34,3.17];
const clamp=(value:number,min=0,max=1)=>Math.max(min,Math.min(max,value));
export function analyzeTimelineDawTempo(channel:Float32Array,sampleRate:number):TimelineDawTempoAnalysis{if(channel.length<sampleRate*4)throw Error("Tempo analysis requires at least four seconds.");const hop=1024,energy:number[]=[];for(let offset=0;offset+hop<=channel.length;offset+=hop){let sum=0;for(let i=0;i<hop;i++)sum+=channel[offset+i]*channel[offset+i];energy.push(Math.sqrt(sum/hop))}const onset=energy.map((value,index)=>Math.max(0,value-(energy[index-1]??value))),mean=onset.reduce((a,b)=>a+b,0)/onset.length;for(let i=0;i<onset.length;i++)onset[i]=Math.max(0,onset[i]-mean*.5);const minBpm=60,maxBpm=190,minLag=Math.floor(60*sampleRate/(maxBpm*hop)),maxLag=Math.ceil(60*sampleRate/(minBpm*hop));let bestLag=minLag,best=-Infinity,total=0;for(let lag=minLag;lag<=maxLag;lag++){let score=0,normA=0,normB=0;for(let i=lag;i<onset.length;i++){score+=onset[i]*onset[i-lag];normA+=onset[i]*onset[i];normB+=onset[i-lag]*onset[i-lag]}score/=Math.sqrt(normA*normB)||1;total+=Math.max(0,score);if(score>best){best=score;bestLag=lag}}const bpm=Math.round(60*sampleRate/(bestLag*hop)*10)/10;return{bpm,confidence:Math.round(clamp(best/(total/Math.max(1,maxLag-minLag+1)+1e-9)/8)*1000)/1000}}
function fft(re:Float64Array,im:Float64Array){const n=re.length;for(let i=1,j=0;i<n;i++){let bit=n>>1;for(;j&bit;bit>>=1)j^=bit;j^=bit;if(i<j){[re[i],re[j]]=[re[j],re[i]];[im[i],im[j]]=[im[j],im[i]]}}for(let len=2;len<=n;len<<=1){const angle=-2*Math.PI/len;for(let start=0;start<n;start+=len)for(let j=0;j<len/2;j++){const c=Math.cos(angle*j),s=Math.sin(angle*j),even=start+j,odd=even+len/2,tr=re[odd]*c-im[odd]*s,ti=re[odd]*s+im[odd]*c;re[odd]=re[even]-tr;im[odd]=im[even]-ti;re[even]+=tr;im[even]+=ti}}}
function correlation(a:number[],b:number[]){const am=a.reduce((x,y)=>x+y,0)/a.length,bm=b.reduce((x,y)=>x+y,0)/b.length;let top=0,aa=0,bb=0;for(let i=0;i<a.length;i++){const x=a[i]-am,y=b[i]-bm;top+=x*y;aa+=x*x;bb+=y*y}return top/(Math.sqrt(aa*bb)||1)}
export function analyzeTimelineDawKey(channel:Float32Array,sampleRate:number):TimelineDawKeyAnalysis{if(channel.length<sampleRate*2)throw Error("Key analysis requires at least two seconds.");const size=4096,step=8192,chroma=Array(12).fill(0);for(let offset=0;offset+size<=channel.length;offset+=step){const re=new Float64Array(size),im=new Float64Array(size);for(let i=0;i<size;i++)re[i]=channel[offset+i]*(.5-.5*Math.cos(2*Math.PI*i/(size-1)));fft(re,im);for(let bin=Math.ceil(55*size/sampleRate);bin<Math.min(size/2,Math.floor(3520*size/sampleRate));bin++){const frequency=bin*sampleRate/size,midi=Math.round(69+12*Math.log2(frequency/440)),pitch=((midi%12)+12)%12,magnitude=re[bin]*re[bin]+im[bin]*im[bin];chroma[pitch]+=magnitude}}const total=chroma.reduce((a,b)=>a+b,0);if(!total)throw Error("Key analysis found no tonal energy.");for(let i=0;i<12;i++)chroma[i]/=total;const candidates:Array<{key:string;mode:"major"|"minor";score:number}>=[];for(let root=0;root<12;root++)for(const [mode,profile] of [["major",MAJOR],["minor",MINOR]] as const)candidates.push({key:NOTES[root],mode,score:correlation(chroma,profile.map((_,i)=>profile[(i-root+12)%12]))});candidates.sort((a,b)=>b.score-a.score);const best=candidates[0],next=candidates[1];return{key:best.key,mode:best.mode,confidence:Math.round(clamp((best.score-next.score+.15)/.45)*1000)/1000}}
function pitchClass(key:string){const index=NOTES.indexOf(key);if(index<0)throw Error(`Key ${key} is invalid.`);return index}
export function createTimelineDawNormalizationPlan(sources:TimelineDawNormalizationSource[]):TimelineDawNormalizationPlan{if(sources.length<2||sources.length>16)throw Error("Normalization requires 2 to 16 sources.");const sorted=sources.map(x=>x.bpm).sort((a,b)=>a-b),targetBpm=Math.round(sorted[Math.floor(sorted.length/2)]*10)/10;let best:{key:string;mode:"major"|"minor";cost:number}={key:"C",mode:"major",cost:Infinity};for(const mode of ["major","minor"] as const)for(const key of NOTES){let cost=0;for(const source of sources){const raw=pitchClass(key)-pitchClass(source.key),shift=((raw+18)%12)-6;cost+=Math.abs(shift)+(source.mode===mode?0:1.5)}if(cost<best.cost)best={key,mode,cost}}return{targetBpm,targetKey:best.key,targetMode:best.mode,sources:sources.map(source=>{const raw=pitchClass(best.key)-pitchClass(source.key),pitchSemitones=((raw+18)%12)-6,tempoCandidates=[source.bpm/2,source.bpm,source.bpm*2].filter(bpm=>bpm>=50&&bpm<=220),effectiveBpm=tempoCandidates.sort((a,b)=>Math.abs(Math.log(a/targetBpm))-Math.abs(Math.log(b/targetBpm)))[0];return{...source,bpm:Math.round(effectiveBpm*10)/10,stretchRatio:Math.round(effectiveBpm/targetBpm*10000)/10000,pitchSemitones}})}}