import { createHash } from "node:crypto";
import { renderTimelineDawPrivateMidiClip, type TimelineDawPrivateMidiClip } from "./TimelineDawPrivateMidiPolicy";

export type TimelineDawMidiRackLayer={id:string;waveform:"sine"|"triangle"|"sawtooth"|"square";octave:number;detuneCents:number;gain:number;pan:number;attack:number;release:number;filterHz:number};
export type TimelineDawMidiRack={id:string;name:string;version:number;layers:TimelineDawMidiRackLayer[]};
export type TimelineDawMidiAutomationPoint={id:string;tick:number;value:number};
export type TimelineDawMidiAutomationLane={id:string;parameter:"expression"|"modulation"|"pitchBend"|"filter"|"gain";channel:number;points:TimelineDawMidiAutomationPoint[]};
export type TimelineDawMidiProgramMap={channel:number;program:number;rackPresetId:string};
export type TimelineDawMidiControllerTemplate={id:string;name:string;controller:number;channel:number;defaultValue:number};

const number=(value:unknown,min:number,max:number,label:string)=>{const parsed=Number(value);if(!Number.isFinite(parsed)||parsed<min||parsed>max)throw Error(label+" must be from "+min+" to "+max+".");return parsed};
export function parseTimelineDawMidiRack(value:unknown,id="rack"):TimelineDawMidiRack{if(!value||typeof value!=="object")throw Error("Instrument rack is required.");const input=value as Record<string,unknown>,layers=(Array.isArray(input.layers)?input.layers:[]).map((raw,index)=>{const layer=raw as Record<string,unknown>,waveform=String(layer.waveform);if(!["sine","triangle","sawtooth","square"].includes(waveform))throw Error("Rack waveform is invalid.");return{id:typeof layer.id==="string"&&layer.id.trim()?layer.id.trim():"layer-"+index,waveform:waveform as TimelineDawMidiRackLayer["waveform"],octave:number(layer.octave??0,-4,4,"Layer octave"),detuneCents:number(layer.detuneCents??0,-1200,1200,"Layer detune"),gain:number(layer.gain??.25,0,1,"Layer gain"),pan:number(layer.pan??0,-1,1,"Layer pan"),attack:number(layer.attack??.005,0,5,"Layer attack"),release:number(layer.release??.08,0,10,"Layer release"),filterHz:number(layer.filterHz??12000,20,24000,"Layer filter")}});if(!layers.length||layers.length>8||new Set(layers.map(layer=>layer.id)).size!==layers.length)throw Error("Instrument rack requires 1 to 8 unique layers.");return{id,name:typeof input.name==="string"&&input.name.trim()?input.name.trim().slice(0,120):"Instrument Rack",version:Math.max(1,Math.floor(number(input.version??1,1,Number.MAX_SAFE_INTEGER,"Rack version"))),layers}}
export function parseTimelineDawMidiAutomation(value:unknown,lengthTicks:number){return(Array.isArray(value)?value:[]).map((raw,index)=>{const lane=raw as Record<string,unknown>,parameter=String(lane.parameter);if(!["expression","modulation","pitchBend","filter","gain"].includes(parameter))throw Error("MIDI automation parameter is invalid.");const points=(Array.isArray(lane.points)?lane.points:[]).map((item,pointIndex)=>{const point=item as Record<string,unknown>;return{id:typeof point.id==="string"?point.id:"point-"+pointIndex,tick:Math.floor(number(point.tick,0,lengthTicks-1,"Automation tick")),value:number(point.value,-1,1,"Automation value")}}).sort((a,b)=>a.tick-b.tick);if(points.some((point,i)=>i>0&&point.tick===points[i-1].tick))throw Error("Automation points must use unique ticks.");return{id:typeof lane.id==="string"?lane.id:"automation-"+index,parameter:parameter as TimelineDawMidiAutomationLane["parameter"],channel:Math.floor(number(lane.channel??1,1,16,"Automation channel")),points}})}
export function timelineDawMidiAutomationValue(lane:TimelineDawMidiAutomationLane|undefined,tick:number,fallback:number){if(!lane?.points.length)return fallback;if(tick<=lane.points[0].tick)return lane.points[0].value;const right=lane.points.findIndex(point=>point.tick>=tick);if(right<0)return lane.points[lane.points.length-1].value;const a=lane.points[right-1],b=lane.points[right];return a.value+(b.value-a.value)*(tick-a.tick)/(b.tick-a.tick)}
export function renderTimelineDawMidiRack(clip:TimelineDawPrivateMidiClip,rack:TimelineDawMidiRack,automation:TimelineDawMidiAutomationLane[],sampleRate:number,tempoMap:Array<{tick:number;bpm:number}>){let output:Float32Array[]|undefined;for(const layer of rack.layers){const expression=timelineDawMidiAutomationValue(automation.find(lane=>lane.parameter==="expression"),0,1),gainAutomation=(timelineDawMidiAutomationValue(automation.find(lane=>lane.parameter==="gain"),0,0)+1)/2,notes=clip.notes.map(note=>({...note,pitch:Math.max(0,Math.min(127,note.pitch+layer.octave*12))})),rendered=renderTimelineDawPrivateMidiClip({...clip,notes,instrument:{...clip.instrument,waveform:layer.waveform,gain:layer.gain*expression*gainAutomation,attack:layer.attack,release:layer.release}},sampleRate,tempoMap);if(!output)output=rendered.channels.map(channel=>new Float32Array(channel.length));const left=Math.cos((layer.pan+1)*Math.PI/4),right=Math.sin((layer.pan+1)*Math.PI/4),alpha=1-Math.exp(-2*Math.PI*layer.filterHz/sampleRate);let pl=0,pr=0;for(let frame=0;frame<rendered.frameCount;frame++){pl+=alpha*(rendered.channels[0][frame]-pl);pr+=alpha*(rendered.channels[1][frame]-pr);output[0][frame]+=pl*left;output[1][frame]+=pr*right}}if(!output)throw Error("Instrument rack rendered no layers.");for(const channel of output)for(let i=0;i<channel.length;i++)channel[i]=Math.max(-1,Math.min(1,channel[i]));return{channels:output,sampleRate,frameCount:output[0].length}}
export function timelineDawMidiRackRecipeChecksum(input:unknown){return"sha256:"+createHash("sha256").update(JSON.stringify(input)).digest("hex")}