import crypto from "node:crypto";
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";
import { persistTimelineDawNormalizationEvidenceMonitoring } from "@/lib/timeline/TimelineDawNormalizationEvidenceMonitorServer";
import { assertTimelineDawNormalizationRecoveryPlan, createTimelineDawNormalizationRecoveryPlan, createTimelineDawNormalizationRecoveryReceipt } from "@/lib/timeline/TimelineDawNormalizationEvidenceMonitorPolicy";
export const runtime = "nodejs", dynamic = "force-dynamic";
const env = (name: string) => process.env[name]?.trim() ?? "";
async function auth(request: NextRequest, sessionId: string) { const token = (request.headers.get("authorization") ?? "").slice(7).trim(), client = createClient(env("NEXT_PUBLIC_SUPABASE_URL"), env("NEXT_PUBLIC_SUPABASE_ANON_KEY"), { global: { headers: { Authorization: `Bearer ${token}` } } }), { data } = await client.auth.getUser(token); if (!data.user || !await createTimelineDawWorkspaceServer(data.user.id, token).get(data.user.id, sessionId)) throw new Error("DAW session access is required."); return { id: data.user.id, client }; }
const fail = (error: unknown) => NextResponse.json({ error: error instanceof Error ? error.message : "Evidence monitoring request failed." }, { status: 400 });
async function response(client: any, ownerId: string, sessionId: string, scan = false) { const current = scan ? await persistTimelineDawNormalizationEvidenceMonitoring(client, ownerId, sessionId) : null, [{ data: checkpoints }, { data: incidents }, { data: receipts }] = await Promise.all([client.from("timeline_daw_normalization_evidence_checkpoints").select("*").eq("owner_id", ownerId).eq("session_id", sessionId).order("observed_at", { ascending: false }).limit(20), client.from("timeline_daw_normalization_evidence_incidents").select("*").eq("owner_id", ownerId).eq("session_id", sessionId).order("created_at", { ascending: false }).limit(20), client.from("timeline_daw_normalization_evidence_recovery_receipts").select("*").eq("owner_id", ownerId).eq("session_id", sessionId).order("created_at", { ascending: false }).limit(20)]), latest = current ?? (checkpoints?.[0] ? { checkpoint: { checksum: checkpoints[0].checkpoint_checksum }, issue: checkpoints[0].issue, coveragePlan: null } : null), recoveryPlan = latest ? createTimelineDawNormalizationRecoveryPlan({ checkpointChecksum: latest.checkpoint.checksum, issue: latest.issue, coveragePlanChecksum: latest.coveragePlan?.planChecksum }) : null; return { current, checkpoints: checkpoints ?? [], incidents: incidents ?? [], receipts: receipts ?? [], recoveryPlan }; }
export async function GET(request: NextRequest) { try { const sessionId = request.nextUrl.searchParams.get("sessionId") ?? "", user = await auth(request, sessionId); return NextResponse.json(await response(user.client, user.id, sessionId)); } catch (error) { return fail(error); } }
export async function POST(request: NextRequest) { try { const body = await request.json(), sessionId = String(body.sessionId ?? ""), user = await auth(request, sessionId), action = String(body.action ?? "scan"); if (action === "scan") return NextResponse.json(await response(user.client, user.id, sessionId, true)); if (action === "acknowledge") { await user.client.from("timeline_daw_normalization_evidence_incidents").update({ state: "acknowledged", acknowledged_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", String(body.incidentId)).eq("owner_id", user.id).eq("state", "open"); return NextResponse.json(await response(user.client, user.id, sessionId)); } if (action === "record-recovery") { const plan = body.plan; assertTimelineDawNormalizationRecoveryPlan(plan, String(plan.checkpointChecksum)); const { data: before } = await user.client.from("timeline_daw_normalization_evidence_checkpoints").select("id,checkpoint_checksum").eq("owner_id", user.id).eq("session_id", sessionId).eq("checkpoint_checksum", plan.checkpointChecksum).single(); if (!before) throw new Error("Recovery checkpoint was not found."); const after = await persistTimelineDawNormalizationEvidenceMonitoring(user.client, user.id, sessionId); if (after.issue !== "healthy") throw new Error("Recovery did not produce a healthy evidence chain."); const incidentId = String(body.incidentId), receipt = createTimelineDawNormalizationRecoveryReceipt({ incidentId, sessionId, planChecksum: plan.planChecksum, beforeCheckpointChecksum: before.checkpoint_checksum, afterCheckpointChecksum: after.checkpoint.checksum, actions: plan.actions, completedAt: new Date().toISOString() }), id = `timeline-daw-normalization-evidence-recovery-${crypto.randomUUID()}`; const { error } = await user.client.from("timeline_daw_normalization_evidence_recovery_receipts").insert({ id, owner_id: user.id, session_id: sessionId, incident_id: incidentId, checkpoint_id: after.checkpointId, plan_checksum: plan.planChecksum, before_checkpoint_checksum: before.checkpoint_checksum, after_checkpoint_checksum: after.checkpoint.checksum, actions: plan.actions, receipt, receipt_checksum: receipt.checksum }); if (error) throw new Error(error.message); await user.client.from("timeline_daw_normalization_evidence_incidents").update({ state: "recovered", recovered_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", incidentId).eq("owner_id", user.id); return NextResponse.json(await response(user.client, user.id, sessionId)); } throw new Error("Evidence monitoring action is unsupported."); } catch (error) { return fail(error); } }
