import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { assertTimelineDawBetaAuditionSource, createTimelineDawBetaAuditionChecksum, parseTimelineDawBetaAuditionEvent } from "@/lib/timeline/TimelineDawBetaAuditionPolicy";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";

export const runtime = "nodejs"; export const dynamic = "force-dynamic";
const value = (name: string) => { const result = process.env[name]?.trim(); if (!result) throw new Error(`${name} is not configured.`); return result; };
async function auth(request: NextRequest) { const header = request.headers.get("authorization") ?? ""; if (!header.toLowerCase().startsWith("bearer ")) throw new Error("Authentication is required."); const token = header.slice(7).trim(), database = createClient(value("NEXT_PUBLIC_SUPABASE_URL"), value("NEXT_PUBLIC_SUPABASE_ANON_KEY"), { auth: { persistSession: false, autoRefreshToken: false }, global: { headers: { Authorization: `Bearer ${token}` } } }); const { data, error } = await database.auth.getUser(token); if (error || !data.user) throw new Error("Supabase session is invalid or expired."); return { id: data.user.id, token, database }; }
async function owner(request: NextRequest, sessionId: string) { const user = await auth(request); if (!await createTimelineDawWorkspaceServer(user.id, user.token).get(user.id, sessionId)) throw new Error("Only the verified session owner can publish an audition master."); return user; }
const fail = (error: unknown) => NextResponse.json({ error: error instanceof Error ? error.message : "Beta audition request failed." }, { status: 400 });

async function ownerData(user: Awaited<ReturnType<typeof owner>>, sessionId: string) {
  const [{ data: masters, error: masterError }, { data: active, error: activeError }, { data: receipts, error: receiptError }] = await Promise.all([
    user.database.from("timeline_daw_normalization_master_proofs").select("id,revision,source_uri,source_checksum,created_at").eq("owner_id", user.id).eq("session_id", sessionId).order("revision", { ascending: false }),
    user.database.from("timeline_daw_beta_audition_sources").select("id,master_proof_id,revision,label,source_checksum,state,selected_at").eq("owner_id", user.id).eq("session_id", sessionId).eq("state", "active").maybeSingle(),
    user.database.from("timeline_daw_beta_audition_receipts").select("id,actor_id,event,position_seconds,detail,receipt_checksum,observed_at").eq("owner_id", user.id).eq("session_id", sessionId).order("observed_at", { ascending: false }).limit(30),
  ]);
  const error = masterError || activeError || receiptError; if (error) throw new Error(error.message);
  const eligible = [];
  for (const master of masters ?? []) { const { data: approval } = await user.database.from("timeline_daw_normalization_approvals").select("decision,master_checksum,created_at").eq("owner_id", user.id).eq("session_id", sessionId).eq("revision", master.revision).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (approval?.decision === "approved" && approval.master_checksum === master.source_checksum) eligible.push({ id: master.id, revision: master.revision, checksum: master.source_checksum, createdAt: master.created_at }); }
  return { eligible, active, receipts: receipts ?? [] };
}

async function record(database: Awaited<ReturnType<typeof auth>>["database"], sessionId: string, sourceId: string, event: ReturnType<typeof parseTimelineDawBetaAuditionEvent>) {
  const observedAt = new Date().toISOString(), checksum = createTimelineDawBetaAuditionChecksum({ sessionId, sourceId, ...event, observedAt });
  const { data, error } = await database.rpc("record_timeline_daw_beta_audition", { p_session_id: sessionId, p_source_id: sourceId, p_event: event.action, p_position_seconds: event.positionSeconds, p_detail: event.detail, p_receipt_checksum: checksum, p_observed_at: observedAt });
  if (error) throw new Error(error.message); return { id: data, checksum, observedAt };
}

export async function GET(request: NextRequest) { try { const sessionId = request.nextUrl.searchParams.get("sessionId")?.trim() ?? ""; if (request.nextUrl.searchParams.get("mode") === "owner") { const user = await owner(request, sessionId); return NextResponse.json(await ownerData(user, sessionId), { headers: { "Cache-Control": "no-store" } }); } const user = await auth(request), { data, error } = await user.database.rpc("get_timeline_daw_beta_audition", { p_session_id: sessionId }); if (error || !data?.source) throw new Error(error?.message ?? "Beta audition source was not found."); const source = data.source as { id: string; label: string; revision: number; sourceUri: string; sourceChecksum: string; selectedAt: string }, confinement = assertTimelineDawBetaAuditionSource({ sourceUri: source.sourceUri, sourceChecksum: source.sourceChecksum, ownerId: data.access.ownerId, sessionId }); const signed = await user.database.storage.from("timeline-daw-render-sources").createSignedUrl(confinement.storagePath, confinement.expiresInSeconds); if (signed.error || !signed.data?.signedUrl) throw new Error(signed.error?.message ?? "Audition playback URL could not be issued."); const opened = await record(user.database, sessionId, source.id, { action: "audition-opened", positionSeconds: 0, detail: "Short-lived playback access issued." }); return NextResponse.json({ source: { id: source.id, label: source.label, revision: source.revision, checksum: source.sourceChecksum, selectedAt: source.selectedAt }, auditionUrl: signed.data.signedUrl, expiresInSeconds: confinement.expiresInSeconds, receipt: opened }, { headers: { "Cache-Control": "no-store" } }); } catch (error) { return fail(error); } }

export async function POST(request: NextRequest) { try { const body = await request.json() as Record<string, unknown>, sessionId = String(body.sessionId ?? "").trim(); if (body.action === "publish") { const user = await owner(request, sessionId), masterId = String(body.masterId ?? ""), label = String(body.label ?? "Beta audition master").trim(); if (label.length < 2 || label.length > 120) throw new Error("Audition label must contain 2-120 characters."); const { data: master } = await user.database.from("timeline_daw_normalization_master_proofs").select("id,revision,source_uri,source_checksum").eq("id", masterId).eq("owner_id", user.id).eq("session_id", sessionId).single(); if (!master) throw new Error("Verified master proof was not found."); const { data: approval } = await user.database.from("timeline_daw_normalization_approvals").select("decision,master_checksum").eq("owner_id", user.id).eq("session_id", sessionId).eq("revision", master.revision).order("created_at", { ascending: false }).limit(1).maybeSingle(); if (approval?.decision !== "approved" || approval.master_checksum !== master.source_checksum) throw new Error("The selected master does not have a current checksum-matching approval."); assertTimelineDawBetaAuditionSource({ sourceUri: master.source_uri, sourceChecksum: master.source_checksum, ownerId: user.id, sessionId }); await user.database.from("timeline_daw_beta_audition_sources").update({ state: "revoked" }).eq("owner_id", user.id).eq("session_id", sessionId).eq("state", "active"); const selectedAt = new Date().toISOString(), { error } = await user.database.from("timeline_daw_beta_audition_sources").insert({ id: `timeline-daw-beta-audition-${crypto.randomUUID()}`, owner_id: user.id, session_id: sessionId, master_proof_id: master.id, revision: master.revision, label, source_uri: master.source_uri, source_checksum: master.source_checksum, state: "active", selected_at: selectedAt }); if (error) throw new Error(error.message); return NextResponse.json(await ownerData(user, sessionId), { status: 201 }); } const user = await auth(request), sourceId = String(body.sourceId ?? ""), event = parseTimelineDawBetaAuditionEvent(body); return NextResponse.json({ receipt: await record(user.database, sessionId, sourceId, event) }, { status: 201 }); } catch (error) { return fail(error); } }
