"use client";

import { useEffect, useState } from "react";
import type { AiDriftReport } from "@/lib/developer-workspace/aiDriftReport";

export default function AiDriftHoldingReport() {
  const [report, setReport] = useState<AiDriftReport | null>(null);
  const [error, setError] = useState("");
  useEffect(() => { void fetch("/api/developer-workspace/prevented-errors?limit=250", { cache: "no-store" }).then(async (response) => { const body = await response.json() as { driftReport?: AiDriftReport; error?: string }; if (!response.ok || !body.driftReport) throw new Error(body.error ?? "AI drift report failed."); setReport(body.driftReport); }).catch((cause) => setError(cause instanceof Error ? cause.message : "AI drift report failed.")); }, []);
  if (error) return <div className="mt-4 rounded border border-red-300/30 bg-red-300/10 p-3 text-sm text-red-100">{error}</div>;
  return <section className="mt-4 rounded-xl border border-violet-300/25 bg-[#0b1720] p-5"><div className="text-xs font-black uppercase tracking-[0.28em] text-violet-300">AI Drift / Unrealized Type Holding Cell</div><h2 className="mt-1 text-2xl font-black">Proof of incomplete code stopped before use</h2><p className="mt-2 text-sm text-white/60">A candidate remains unrealized until its declaration, required pieces, imports, compiler validity, architecture, and real activation all pass.</p>{report ? <><div className="mt-4 grid gap-2 sm:grid-cols-5">{[["Held attempts",report.totalHeldAttempts],["Still unrealized",report.stillUnrealized],["Corrected",report.corrected],["Activated",report.activated],["Abandoned",report.abandoned]].map(([label,value]) => <div key={label} className="rounded-lg border border-white/10 bg-black/20 p-3"><div className="text-[10px] font-bold uppercase text-white/40">{label}</div><div className="mt-1 text-2xl font-black">{value}</div></div>)}</div><div className="mt-4 space-y-3">{report.incidents.map((incident) => <details key={incident.attemptId} className="rounded-lg border border-white/10 bg-black/20 p-4" open={incident.unrealized}><summary className="cursor-pointer font-black"><span className={incident.unrealized ? "text-amber-200" : "text-emerald-200"}>{incident.unrealized ? "HELD" : incident.latestOutcome.toUpperCase()}</span> · {incident.title} · {incident.file}</summary><div className="mt-3 grid gap-2 md:grid-cols-2 xl:grid-cols-5">{incident.validationSteps.map((step) => <div key={step.name} className={`rounded border p-2 text-xs ${step.passed ? "border-emerald-300/25 bg-emerald-300/5" : "border-red-300/30 bg-red-300/10"}`}><div className="font-black">{step.passed ? "PASS" : "MISSING"} · {step.name}</div><div className="mt-1 text-white/55">{step.evidence}</div></div>)}</div><div className="mt-3 text-xs text-white/40">First held: {new Date(incident.firstHeldAt).toLocaleString()} · Attempt {incident.attemptId}</div></details>)}</div></> : <div className="mt-4 text-sm text-white/40">Loading holding evidence…</div>}</section>;
}
