"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useAuth } from "@/app/components/AuthProvider";
import { requireProjectSupabase } from "@/app/workspace/projects/[id]/projectSupabase";

type Enrollment = { enrollmentId:string; sessionId:string; projectId:string; state:string; acknowledged?:boolean; environment?:Record<string,boolean>|null };
const button="rounded-lg border border-white/20 px-3 py-2 font-black disabled:opacity-40",field="min-w-0 flex-1 rounded-lg border border-white/15 bg-black px-3 py-2";

export default function DawBetaEnrollmentPage(){
 const{user,loading}=useAuth(),[code,setCode]=useState(""),[enrollment,setEnrollment]=useState<Enrollment|null>(null),[acknowledged,setAcknowledged]=useState(false),[environment,setEnvironment]=useState<Record<string,boolean>|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[resuming,setResuming]=useState(false);
 const token=useCallback(async()=>((await requireProjectSupabase().auth.getSession()).data.session?.access_token??""),[]);
 const post=useCallback(async(body:Record<string,unknown>)=>{setBusy(true);setError("");try{const response=await fetch("/api/timeline/daw-beta-onboarding",{method:"POST",headers:{Authorization:`Bearer ${await token()}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok)throw Error(result.error);return result}catch(cause){setError(cause instanceof Error?cause.message:"Onboarding request failed.");throw cause}finally{setBusy(false)}},[token]);
 useEffect(()=>{if(loading||!user)return;let active=true;queueMicrotask(()=>{if(!active)return;setResuming(true);void token().then(async accessToken=>{const response=await fetch("/api/timeline/daw-beta-onboarding/resume",{headers:{Authorization:`Bearer ${accessToken}`},cache:"no-store"}),result=await response.json();if(!response.ok)throw Error(result.error);if(active&&result.enrollment){setEnrollment(result.enrollment);setAcknowledged(Boolean(result.enrollment.acknowledged));setEnvironment(result.enrollment.environment??null)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Enrollment could not be resumed.")}).finally(()=>{if(active)setResuming(false)})});return()=>{active=false}},[loading,token,user]);
 async function redeem(){const result=await post({action:"redeem",code});setEnrollment(result);setAcknowledged(false);setEnvironment(null);setCode("")}
 async function enterWithGuestPass(){setBusy(true);setError("");try{const client=requireProjectSupabase(),{data,error:guestError}=await client.auth.signInAnonymously();if(guestError||!data.session)throw Error(guestError?.message??"Guest access could not start.");const response=await fetch("/api/timeline/daw-beta-onboarding",{method:"POST",headers:{Authorization:`Bearer ${data.session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify({action:"redeem",code})}),result=await response.json();if(!response.ok)throw Error(result.error);setEnrollment(result);setAcknowledged(false);setEnvironment(null);setCode("")}catch(cause){setError(cause instanceof Error?cause.message:"Guest pass could not be opened.")}finally{setBusy(false)}}
 async function acknowledge(){if(!enrollment)return;await post({action:"acknowledge",enrollmentId:enrollment.enrollmentId,sessionId:enrollment.sessionId});setAcknowledged(true);setEnrollment(current=>current?{...current,acknowledged:true}:current)}
 async function check(){if(!enrollment)return;let audioInput=false;try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});audioInput=stream.getAudioTracks().length>0;stream.getTracks().forEach(track=>track.stop())}catch{audioInput=false}let localStorageReady=false;try{localStorage.setItem("muzes-beta-check","1");localStorage.removeItem("muzes-beta-check");localStorageReady=true}catch{localStorageReady=false}const result={secureContext:window.isSecureContext,supportedBrowser:Boolean(window.AudioContext&&window.MediaRecorder),audioInput,audioOutput:Boolean(window.HTMLAudioElement),localStorage:localStorageReady,fileApi:Boolean(window.File&&window.FileReader),supportedAudioTypes:Boolean(document.createElement("audio").canPlayType("audio/wav")||document.createElement("audio").canPlayType("audio/mpeg"))};await post({action:"environment",enrollmentId:enrollment.enrollmentId,sessionId:enrollment.sessionId,environment:result});setEnvironment(result)}
 if(loading)return <main className="p-8 text-white">Checking membership…</main>;
 if(!user)return <main className="mx-auto max-w-3xl space-y-5 p-6 text-white"><h1 className="text-4xl font-black">Musician Guest Pass</h1><p>No member account or sign-in is required for this private test. Enter the pass Steve sent you.</p><div className="flex flex-wrap gap-2"><input className={field} value={code} onChange={event=>setCode(event.target.value)} placeholder="Private guest pass"/><button className={button} disabled={busy||code.length<20} onClick={()=>void enterWithGuestPass()}>{busy?"Opening…":"Open Guest Test"}</button></div><p className="text-sm text-white/55">The pass does not expire, but the owner can revoke it. Do not share it.</p><Link className={`${button} inline-block`} href="/members?next=/workspace/daw/beta">Member sign-in for later</Link>{error?<p role="alert" className="text-red-200">{error}</p>:null}</main>;
 return <main className="mx-auto max-w-3xl space-y-5 p-6 text-white"><h1 className="text-4xl font-black">Musician Beta Enrollment</h1><p className="text-white/60">This is experimental software. Keep your original audio backups. Private audio is not attached to feedback reports.</p><Link className={`${button} inline-block`} href="/workspace/daw/beta/portal">Open My Beta Sessions</Link>{resuming?<p>Checking for an invitation you already redeemed…</p>:null}{!resuming&&!enrollment?<div className="flex flex-wrap gap-2"><input className={field} value={code} onChange={event=>setCode(event.target.value)} placeholder="Invitation code"/><button className={button} disabled={busy||code.length<20} onClick={()=>void redeem()}>Redeem invitation</button></div>:null}{enrollment?<><p className="rounded-xl border border-emerald-300/25 p-3 text-emerald-200">Invitation found. This setup will return after a refresh or browser restart.</p><section className="rounded-2xl border border-white/15 p-4"><h2 className="font-black">1. Privacy and beta-risk acknowledgement</h2><label className="mt-2 block"><input type="checkbox" checked={acknowledged} disabled={Boolean(enrollment.acknowledged)} onChange={event=>setAcknowledged(event.target.checked)}/> I understand this is beta software, I will keep backups, and feedback excludes my audio and protected diagnostics.</label><button className={`${button} mt-2`} disabled={busy||!acknowledged||Boolean(enrollment.acknowledged)} onClick={()=>void acknowledge()}>{enrollment.acknowledged?"Acknowledgement saved":"Save acknowledgement"}</button></section><section className="rounded-2xl border border-white/15 p-4"><h2 className="font-black">2. Browser and audio setup check</h2><p className="text-white/55">Your browser may ask for microphone permission. The test stops the microphone immediately after confirming an input exists.</p><button className={`${button} mt-2`} disabled={busy} onClick={()=>void check()}>{environment?"Run setup check again":"Run setup check"}</button>{environment?Object.entries(environment).map(([name,ready])=><p className={ready?"text-emerald-200":"text-red-200"} key={name}>{ready?"Pass":"Needs attention"} · {name}</p>):null}</section><section className="rounded-2xl border border-amber-300/30 p-4"><b>Enrollment active</b><p>The owner must run the release gate before this session opens. You can safely leave and return while you wait.</p><Link className={`${button} mt-3 inline-block`} href={`/workspace/daw/beta/session/${encodeURIComponent(enrollment.sessionId)}`}>Check access and open session</Link></section></>:null}{error?<p role="alert" className="text-red-200">{error}</p>:null}</main>
}
