import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { parseTimelineDawPrivateAutomationEnvelope, type TimelineDawPrivateAutomationEnvelope } from "@/lib/timeline/TimelineDawPrivateAutomationPolicy";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
class ApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
const env = (name: string) => { const value = process.env[name]?.trim(); if (!value) throw new ApiError(`${name} is not configured.`, 503); return value; };
async function auth(request: NextRequest) { const header=request.headers.get("authorization")?.trim()??"";if(!header.toLowerCase().startsWith("bearer "))throw new ApiError("Authentication is required.",401);const token=header.slice(7).trim(),client=createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}});const{data,error}=await client.auth.getUser(token);if(error||!data.user?.id)throw new ApiError("Supabase session is invalid or expired.",401);return{id:data.user.id,token,client}; }
async function requireSession(user:Awaited<ReturnType<typeof auth>>,id:string){if(!id||!await createTimelineDawWorkspaceServer(user.id,user.token).get(user.id,id))throw new ApiError("DAW session was not found.",404);}
const fail=(error:unknown)=>NextResponse.json({error:error instanceof Error?error.message:"Private automation request failed."},{status:error instanceof ApiError?error.status:400,headers:{"Cache-Control":"no-store"}});

async function list(user:Awaited<ReturnType<typeof auth>>,sessionId:string):Promise<TimelineDawPrivateAutomationEnvelope[]>{const{data:rows,error}=await user.client.from("timeline_daw_private_automation_envelopes").select("*").eq("owner_id",user.id).eq("session_id",sessionId).order("created_at");if(error)throw new ApiError(error.message,500);const ids=(rows??[]).map((row)=>row.id);const{data:points,error:pointError}=ids.length?await user.client.from("timeline_daw_private_automation_points").select("*").eq("owner_id",user.id).in("envelope_id",ids).order("sample_position"):{data:[],error:null};if(pointError)throw new ApiError(pointError.message,500);return(rows??[]).map((row)=>({id:String(row.id),sourceKind:row.source_kind,sourceId:String(row.source_id),parameter:row.parameter,bypassed:Boolean(row.bypassed),points:(points??[]).filter((point)=>point.envelope_id===row.id).map((point)=>({id:String(point.id),samplePosition:Number(point.sample_position),value:Number(point.value),interpolation:point.interpolation}))})) as TimelineDawPrivateAutomationEnvelope[];}
async function history(user:Awaited<ReturnType<typeof auth>>,sessionId:string){const{data,error}=await user.client.from("timeline_daw_private_automation_edits").select("id,envelope_id,state,created_at,changed_at").eq("owner_id",user.id).eq("session_id",sessionId).order("created_at",{ascending:false}).limit(50);if(error)throw new ApiError(error.message,500);return(data??[]).map((row)=>({id:String(row.id),envelopeId:String(row.envelope_id),state:row.state,createdAt:String(row.created_at),changedAt:String(row.changed_at)}));}
async function write(user:Awaited<ReturnType<typeof auth>>,sessionId:string,envelope:TimelineDawPrivateAutomationEnvelope|null,envelopeId:string){if(!envelope){const{error}=await user.client.from("timeline_daw_private_automation_envelopes").delete().eq("owner_id",user.id).eq("session_id",sessionId).eq("id",envelopeId);if(error)throw new ApiError(error.message,500);return;}const{error}=await user.client.from("timeline_daw_private_automation_envelopes").upsert({id:envelopeId,owner_id:user.id,session_id:sessionId,source_kind:envelope.sourceKind,source_id:envelope.sourceId,parameter:envelope.parameter,bypassed:envelope.bypassed,updated_at:new Date().toISOString()},{onConflict:"owner_id,session_id,source_kind,source_id,parameter"});if(error)throw new ApiError(error.message,500);const{error:deleteError}=await user.client.from("timeline_daw_private_automation_points").delete().eq("owner_id",user.id).eq("envelope_id",envelopeId);if(deleteError)throw new ApiError(deleteError.message,500);if(envelope.points.length){const{error:pointError}=await user.client.from("timeline_daw_private_automation_points").insert(envelope.points.map((point)=>({id:point.id.startsWith("point-")?`timeline-daw-private-automation-point-${crypto.randomUUID()}`:point.id,envelope_id:envelopeId,owner_id:user.id,sample_position:point.samplePosition,value:point.value,interpolation:point.interpolation})));if(pointError)throw new ApiError(pointError.message,500);}}

export async function GET(request:NextRequest){try{const user=await auth(request),sessionId=request.nextUrl.searchParams.get("sessionId")?.trim()??"";await requireSession(user,sessionId);return NextResponse.json({envelopes:await list(user,sessionId),history:await history(user,sessionId)},{headers:{"Cache-Control":"no-store"}});}catch(error){return fail(error);}}
export async function POST(request:NextRequest){try{const user=await auth(request),body=await request.json() as Record<string,unknown>,sessionId=typeof body.sessionId==="string"?body.sessionId.trim():"";await requireSession(user,sessionId);if(body.action==="undo"||body.action==="redo"){const desired=body.action==="undo"?"applied":"undone",next=body.action==="undo"?"undone":"applied";const{data:edit,error}=await user.client.from("timeline_daw_private_automation_edits").select("*").eq("owner_id",user.id).eq("session_id",sessionId).eq("state",desired).order("changed_at",{ascending:false}).limit(1).maybeSingle();if(error)throw new ApiError(error.message,500);if(!edit)throw new ApiError(`No automation edit is available to ${body.action}.`,409);await write(user,sessionId,(body.action==="undo"?edit.before_state:edit.after_state) as TimelineDawPrivateAutomationEnvelope|null,String(edit.envelope_id));const{error:updateError}=await user.client.from("timeline_daw_private_automation_edits").update({state:next,changed_at:new Date().toISOString()}).eq("owner_id",user.id).eq("id",edit.id).eq("state",desired);if(updateError)throw new ApiError(updateError.message,409);return NextResponse.json({envelopes:await list(user,sessionId),history:await history(user,sessionId)});}const parsed=parseTimelineDawPrivateAutomationEnvelope(body);const{error:branchError}=await user.client.from("timeline_daw_private_automation_edits").delete().eq("owner_id",user.id).eq("session_id",sessionId).eq("state","undone");if(branchError)throw new ApiError(branchError.message,500);const existing=(await list(user,sessionId)).find((item)=>item.sourceKind===parsed.sourceKind&&item.sourceId===parsed.sourceId&&item.parameter===parsed.parameter),envelopeId=existing?.id??parsed.id??`timeline-daw-private-automation-${crypto.randomUUID()}`,after={...parsed,id:envelopeId} as TimelineDawPrivateAutomationEnvelope;await write(user,sessionId,after,envelopeId);const{error:historyError}=await user.client.from("timeline_daw_private_automation_edits").insert({id:`timeline-daw-private-automation-edit-${crypto.randomUUID()}`,owner_id:user.id,session_id:sessionId,envelope_id:envelopeId,before_state:existing??null,after_state:after});if(historyError)throw new ApiError(historyError.message,500);return NextResponse.json({envelope:(await list(user,sessionId)).find((item)=>item.id===envelopeId),history:await history(user,sessionId)},{status:201});}catch(error){return fail(error);}}
