import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { parseTimelineDawPrivateAutomationEnvelope } from "@/lib/timeline/TimelineDawPrivateAutomationPolicy";
import { createTimelineDawWorkspaceServer } from "@/lib/timeline/TimelineDawWorkspaceServer";
export const runtime = "nodejs"; export const dynamic = "force-dynamic";
class ApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
const env = (name: string) => { const value = process.env[name]?.trim(); if (!value) throw new ApiError(`${name} is not configured.`, 503); return value; };
async function auth(request: NextRequest) { const header=request.headers.get("authorization")?.trim()??""; if(!header.toLowerCase().startsWith("bearer "))throw new ApiError("Authentication is required.",401); const token=header.slice(7).trim(),client=createClient(env("NEXT_PUBLIC_SUPABASE_URL"),env("NEXT_PUBLIC_SUPABASE_ANON_KEY"),{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:`Bearer ${token}`}}}); const{data,error}=await client.auth.getUser(token);if(error||!data.user?.id)throw new ApiError("Supabase session is invalid or expired.",401);return{id:data.user.id,token,client}; }
async function session(user:Awaited<ReturnType<typeof auth>>,id:string){if(!id||!await createTimelineDawWorkspaceServer(user.id,user.token).get(user.id,id))throw new ApiError("DAW session was not found.",404);}
const fail=(error:unknown)=>NextResponse.json({error:error instanceof Error?error.message:"Private automation request failed."},{status:error instanceof ApiError?error.status:400,headers:{"Cache-Control":"no-store"}});
async function list(user:Awaited<ReturnType<typeof auth>>,sessionId:string){const{data:rows,error}=await user.client.from("timeline_daw_private_automation_envelopes").select("*").eq("owner_id",user.id).eq("session_id",sessionId).order("created_at");if(error)throw new ApiError(error.message,500);const ids=(rows??[]).map((row)=>row.id);const{data:points,error:pointError}=ids.length?await user.client.from("timeline_daw_private_automation_points").select("*").eq("owner_id",user.id).in("envelope_id",ids).order("sample_position"):{data:[],error:null};if(pointError)throw new ApiError(pointError.message,500);return(rows??[]).map((row)=>({id:String(row.id),sourceKind:row.source_kind,sourceId:String(row.source_id),parameter:row.parameter,bypassed:Boolean(row.bypassed),points:(points??[]).filter((point)=>point.envelope_id===row.id).map((point)=>({id:String(point.id),samplePosition:Number(point.sample_position),value:Number(point.value),interpolation:point.interpolation}))}));}
export async function GET(request:NextRequest){try{const user=await auth(request),sessionId=request.nextUrl.searchParams.get("sessionId")?.trim()??"";await session(user,sessionId);return NextResponse.json({envelopes:await list(user,sessionId)},{headers:{"Cache-Control":"no-store"}});}catch(error){return fail(error);}}
export async function POST(request:NextRequest){try{const user=await auth(request),body=await request.json() as Record<string,unknown>,sessionId=typeof body.sessionId==="string"?body.sessionId.trim():"";await session(user,sessionId);const parsed=parseTimelineDawPrivateAutomationEnvelope(body),id=parsed.id??`timeline-daw-private-automation-${crypto.randomUUID()}`;const{data:existing}=await user.client.from("timeline_daw_private_automation_envelopes").select("*").eq("owner_id",user.id).eq("session_id",sessionId).eq("source_kind",parsed.sourceKind).eq("source_id",parsed.sourceId).eq("parameter",parsed.parameter).maybeSingle();const envelopeId=existing?.id??id;const before=existing?(await list(user,sessionId)).find((item)=>item.id===envelopeId)??null:null;const{error}=await user.client.from("timeline_daw_private_automation_envelopes").upsert({id:envelopeId,owner_id:user.id,session_id:sessionId,source_kind:parsed.sourceKind,source_id:parsed.sourceId,parameter:parsed.parameter,bypassed:parsed.bypassed,updated_at:new Date().toISOString()},{onConflict:"owner_id,session_id,source_kind,source_id,parameter"});if(error)throw new ApiError(error.message,500);const{error:deleteError}=await user.client.from("timeline_daw_private_automation_points").delete().eq("owner_id",user.id).eq("envelope_id",envelopeId);if(deleteError)throw new ApiError(deleteError.message,500);if(parsed.points.length){const{error:pointError}=await user.client.from("timeline_daw_private_automation_points").insert(parsed.points.map((point)=>({id:point.id.startsWith("point-")?`timeline-daw-private-automation-point-${crypto.randomUUID()}`:point.id,envelope_id:envelopeId,owner_id:user.id,sample_position:point.samplePosition,value:point.value,interpolation:point.interpolation})));if(pointError)throw new ApiError(pointError.message,500);}const after=(await list(user,sessionId)).find((item)=>item.id===envelopeId)??null;await user.client.from("timeline_daw_private_automation_edits").insert({id:`timeline-daw-private-automation-edit-${crypto.randomUUID()}`,owner_id:user.id,session_id:sessionId,envelope_id:envelopeId,before_state:before,after_state:after});return NextResponse.json({envelope:after},{status:201});}catch(error){return fail(error);}}
