create table if not exists public.timeline_daw_normalization_evidence_checkpoints(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,head_hash text,link_count integer not null,coverage jsonb not null,verification jsonb not null,issue text not null check(issue in('healthy','coverage-gap','previous-hash','chain-hash','subject-checksum','chronology','unknown-integrity')),checkpoint_checksum text not null,observed_at timestamptz not null,created_at timestamptz not null default now(),unique(owner_id,session_id,checkpoint_checksum));
create table if not exists public.timeline_daw_normalization_evidence_incidents(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,checkpoint_id text not null references public.timeline_daw_normalization_evidence_checkpoints(id),issue text not null,state text not null default 'open' check(state in('open','acknowledged','recovered','manual-review')),message text not null,acknowledged_at timestamptz,recovered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index if not exists timeline_daw_normalization_open_evidence_incident on public.timeline_daw_normalization_evidence_incidents(owner_id,session_id,issue) where state in('open','acknowledged','manual-review');
create table if not exists public.timeline_daw_normalization_evidence_recovery_receipts(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,incident_id text not null references public.timeline_daw_normalization_evidence_incidents(id),checkpoint_id text not null references public.timeline_daw_normalization_evidence_checkpoints(id),plan_checksum text not null,before_checkpoint_checksum text not null,after_checkpoint_checksum text not null,actions jsonb not null,receipt jsonb not null,receipt_checksum text not null,created_at timestamptz not null default now());
create table if not exists public.timeline_daw_normalization_evidence_monitor_runs(id text primary key,started_at timestamptz not null,finished_at timestamptz not null,scanned integer not null,healthy integer not null,incidents integer not null,failures jsonb not null default '[]'::jsonb);
alter table public.timeline_daw_normalization_evidence_checkpoints enable row level security;alter table public.timeline_daw_normalization_evidence_incidents enable row level security;alter table public.timeline_daw_normalization_evidence_recovery_receipts enable row level security;alter table public.timeline_daw_normalization_evidence_monitor_runs enable row level security;
create policy timeline_daw_normalization_evidence_checkpoints_owner on public.timeline_daw_normalization_evidence_checkpoints for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy timeline_daw_normalization_evidence_incidents_owner on public.timeline_daw_normalization_evidence_incidents for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy timeline_daw_normalization_evidence_receipts_owner on public.timeline_daw_normalization_evidence_recovery_receipts for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
