create table if not exists public.timeline_daw_private_collaborators(owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null,role text not null check(role in('editor','mixer','viewer')),created_at timestamptz not null default now(),primary key(owner_id,session_id,user_id));
create table if not exists public.timeline_daw_private_presence(owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,user_id uuid not null references auth.users(id) on delete cascade,display_name text not null,last_seen_at timestamptz not null default now(),primary key(owner_id,session_id,user_id));
create table if not exists public.timeline_daw_private_edit_leases(owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,resource_kind text not null check(resource_kind in('lane','bus')),resource_id text not null,holder_id uuid not null references auth.users(id) on delete cascade,holder_name text not null,expires_at timestamptz not null,updated_at timestamptz not null default now(),primary key(owner_id,session_id,resource_kind,resource_id));
create table if not exists public.timeline_daw_private_collaboration_audit(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,actor_id uuid not null,action text not null,details jsonb not null default '{}'::jsonb,created_at timestamptz not null default now());
alter table public.timeline_daw_private_collaborators enable row level security;alter table public.timeline_daw_private_presence enable row level security;alter table public.timeline_daw_private_edit_leases enable row level security;alter table public.timeline_daw_private_collaboration_audit enable row level security;
drop policy if exists timeline_daw_private_collaborators_owner on public.timeline_daw_private_collaborators;create policy timeline_daw_private_collaborators_owner on public.timeline_daw_private_collaborators using(auth.uid()=owner_id or auth.uid()=user_id) with check(auth.uid()=owner_id);
drop policy if exists timeline_daw_private_presence_member on public.timeline_daw_private_presence;create policy timeline_daw_private_presence_member on public.timeline_daw_private_presence using(auth.uid()=owner_id or auth.uid()=user_id) with check(auth.uid()=owner_id or auth.uid()=user_id);
drop policy if exists timeline_daw_private_edit_leases_member on public.timeline_daw_private_edit_leases;create policy timeline_daw_private_edit_leases_member on public.timeline_daw_private_edit_leases using(auth.uid()=owner_id or auth.uid()=holder_id) with check(auth.uid()=owner_id or auth.uid()=holder_id);
drop policy if exists timeline_daw_private_collaboration_audit_owner on public.timeline_daw_private_collaboration_audit;create policy timeline_daw_private_collaboration_audit_owner on public.timeline_daw_private_collaboration_audit using(auth.uid()=owner_id) with check(auth.uid()=owner_id);
