create table if not exists public.timeline_daw_beta_invitations(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,session_id text not null,label text not null,invite_code_hash text not null unique check(invite_code_hash~'^sha256:[a-f0-9]{64}$'),state text not null default 'active' check(state in('active','redeemed','revoked','expired')),expires_at timestamptz not null,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.timeline_daw_beta_enrollments(id text primary key,invitation_id text not null references public.timeline_daw_beta_invitations(id) on delete cascade,owner_id uuid not null references auth.users(id) on delete cascade,project_id uuid not null references public.projects(id) on delete cascade,session_id text not null,tester_id uuid not null references auth.users(id) on delete cascade,state text not null default 'active' check(state in('active','revoked','completed')),acknowledgement_version text,acknowledged_at timestamptz,environment jsonb,environment_checked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(invitation_id,tester_id));
create table if not exists public.timeline_daw_beta_release_receipts(id text primary key,owner_id uuid not null references auth.users(id) on delete cascade,session_id text not null,enrollment_id text references public.timeline_daw_beta_enrollments(id) on delete set null,ready boolean not null,evaluation jsonb not null,receipt_checksum text not null check(receipt_checksum~'^sha256:[a-f0-9]{64}$'),observed_at timestamptz not null,created_at timestamptz not null default now());
alter table public.timeline_daw_beta_invitations enable row level security;alter table public.timeline_daw_beta_enrollments enable row level security;alter table public.timeline_daw_beta_release_receipts enable row level security;
create policy timeline_daw_beta_invitation_owner on public.timeline_daw_beta_invitations for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy timeline_daw_beta_enrollment_participant on public.timeline_daw_beta_enrollments for select to authenticated using(owner_id=auth.uid() or tester_id=auth.uid());
create policy timeline_daw_beta_enrollment_owner_update on public.timeline_daw_beta_enrollments for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy timeline_daw_beta_release_owner on public.timeline_daw_beta_release_receipts for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create or replace function public.redeem_timeline_daw_beta_invitation(p_code_hash text) returns text language plpgsql security definer set search_path=public as $$ declare v_inv public.timeline_daw_beta_invitations;v_id text;begin if auth.uid() is null then raise exception 'Authentication is required';end if;select * into v_inv from public.timeline_daw_beta_invitations where invite_code_hash=p_code_hash and state='active' and expires_at>now() for update;if v_inv.id is null then raise exception 'Invitation is invalid, expired, or unavailable';end if;v_id='timeline-daw-beta-enrollment-'||gen_random_uuid()::text;insert into public.timeline_daw_beta_enrollments(id,invitation_id,owner_id,project_id,session_id,tester_id)values(v_id,v_inv.id,v_inv.owner_id,v_inv.project_id,v_inv.session_id,auth.uid())on conflict(invitation_id,tester_id)do update set state='active',updated_at=now() returning id into v_id;update public.timeline_daw_beta_invitations set state='redeemed',updated_at=now() where id=v_inv.id;return v_id;end$$;
revoke all on function public.redeem_timeline_daw_beta_invitation(text) from public,anon;grant execute on function public.redeem_timeline_daw_beta_invitation(text) to authenticated;

create or replace function public.save_timeline_daw_beta_tester_onboarding(p_enrollment_id text,p_action text,p_acknowledgement_version text,p_environment jsonb) returns boolean language plpgsql security definer set search_path=public as $$ declare v_count integer;begin if auth.uid() is null then raise exception 'Authentication is required';end if;if p_action='acknowledge' then update public.timeline_daw_beta_enrollments set acknowledgement_version=p_acknowledgement_version,acknowledged_at=now(),updated_at=now() where id=p_enrollment_id and tester_id=auth.uid() and state='active';elsif p_action='environment' then update public.timeline_daw_beta_enrollments set environment=p_environment,environment_checked_at=now(),updated_at=now() where id=p_enrollment_id and tester_id=auth.uid() and state='active';else raise exception 'Onboarding action is invalid';end if;get diagnostics v_count=row_count;return v_count=1;end$$;
revoke all on function public.save_timeline_daw_beta_tester_onboarding(text,text,text,jsonb) from public,anon;grant execute on function public.save_timeline_daw_beta_tester_onboarding(text,text,text,jsonb) to authenticated;