import type { TrackMatcherFinderTrackResult } from "./trackMatcherFinderTypes";

export const TRACK_MATCHER_FINDER_MOCK_TRACKS: TrackMatcherFinderTrackResult[] =
  [
    {
      id: "mock-14-days-full",
      title: "14DaysMjac suno rock funk keeper1",
      artist: "Supabase",
      source: "supabase",
      tags: ["suno", "rock", "funk", "keeper"],
      description: "Full song reference candidate from Supabase.",
      score: 0,
      isStem: false,
      isInstrumental: false,
      isReferenceSong: true,
      isHybridCandidate: false,
      destinationHints: ["track-a", "track-b", "reference-song"],
    },
    {
      id: "mock-14-days-stem",
      title: "14DaysMjacMaster funk stemsInstrumental",
      artist: "Supabase",
      source: "supabase",
      tags: ["funk", "stem", "instrumental", "keeper"],
      description: "Instrumental stem candidate for lane loading.",
      score: 0,
      isStem: true,
      isInstrumental: true,
      isReferenceSong: false,
      isHybridCandidate: false,
      destinationHints: ["track-a", "track-b", "stem", "instrument"],
    },
    {
      id: "mock-bass-stem",
      title: "Rock Funk Bass Stem",
      artist: "Library",
      source: "library",
      tags: ["rock", "funk", "bass", "stem"],
      description: "Bass stem for low-end matching.",
      score: 0,
      isStem: true,
      isInstrumental: true,
      isReferenceSong: false,
      isHybridCandidate: false,
      destinationHints: ["track-a", "track-b", "bass", "stem"],
    },
    {
      id: "mock-drum-stem",
      title: "Keeper Drum Stem",
      artist: "Library",
      source: "library",
      tags: ["keeper", "drums", "stem"],
      description: "Drum stem for rhythm comparison.",
      score: 0,
      isStem: true,
      isInstrumental: true,
      isReferenceSong: false,
      isHybridCandidate: false,
      destinationHints: ["track-a", "track-b", "drums", "stem"],
    },
    {
      id: "mock-hybrid",
      title: "Hybrid Rock Funk Candidate",
      artist: "Project",
      source: "project",
      tags: ["hybrid", "rock", "funk"],
      description: "Blend candidate for hybrid lane testing.",
      score: 0,
      isStem: false,
      isInstrumental: false,
      isReferenceSong: false,
      isHybridCandidate: true,
      destinationHints: ["track-a", "track-b", "hybrid"],
    },
  ];