import type {
  TrackMatcherFinderSavedSearch,
  TrackMatcherFinderSavedSearchGroup,
} from "./trackMatcherFinderSavedSearchTypes";
import { DEFAULT_TRACK_MATCHER_FINDER_QUERY } from "./trackMatcherFinderTypes";

function savedSearch(
  args: Omit<TrackMatcherFinderSavedSearch, "query"> & {
    searchText: string;
    includeStemTracks?: boolean;
    includeInstrumentals?: boolean;
    includeReferenceSongs?: boolean;
    includeHybridCandidates?: boolean;
  },
): TrackMatcherFinderSavedSearch {
  return {
    id: args.id,
    label: args.label,
    description: args.description,
    scope: args.scope,
    status: args.status,
    keywords: args.keywords,
    query: {
      ...DEFAULT_TRACK_MATCHER_FINDER_QUERY,
      searchText: args.searchText,
      includeStemTracks: args.includeStemTracks ?? true,
      includeInstrumentals: args.includeInstrumentals ?? true,
      includeReferenceSongs: args.includeReferenceSongs ?? true,
      includeHybridCandidates: args.includeHybridCandidates ?? true,
    },
  };
}

export const TRACK_MATCHER_FINDER_SAVED_SEARCHES: TrackMatcherFinderSavedSearch[] =
  [
    savedSearch({
      id: "rock-funk-keepers",
      label: "Rock Funk Keepers",
      description: "Find rock/funk tracks marked like keeper candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "rock funk keeper",
      keywords: ["rock", "funk", "keeper"],
    }),
    savedSearch({
      id: "instrumental-stems",
      label: "Instrumental Stems",
      description: "Find instrumental stem material for lane loading.",
      scope: "track-matcher",
      status: "starter",
      searchText: "instrumental stem",
      keywords: ["instrumental", "stem"],
    }),
    savedSearch({
      id: "bass-lane-candidates",
      label: "Bass Lane Candidates",
      description: "Find bass stems and low-end candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "bass stem",
      keywords: ["bass", "stem"],
    }),
    savedSearch({
      id: "drum-lane-candidates",
      label: "Drum Lane Candidates",
      description: "Find drum stems, beats, and rhythm candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "drums stem",
      keywords: ["drums", "stem", "beat"],
    }),
    savedSearch({
      id: "vocal-lane-candidates",
      label: "Vocal Lane Candidates",
      description: "Find vocal stems and sung ideas.",
      scope: "track-matcher",
      status: "starter",
      searchText: "vocal stem",
      keywords: ["vocal", "stem"],
      includeInstrumentals: false,
    }),
    savedSearch({
      id: "reference-songs",
      label: "Reference Songs",
      description: "Find reference songs and sounds-like material.",
      scope: "track-matcher",
      status: "starter",
      searchText: "reference",
      keywords: ["reference", "sounds-like"],
    }),
    savedSearch({
      id: "hybrid-candidates",
      label: "Hybrid Candidates",
      description: "Find hybrid blend candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "hybrid candidate",
      keywords: ["hybrid", "candidate"],
    }),
    savedSearch({
      id: "track-a-load-ready",
      label: "Track A Ready",
      description: "Find playable deck candidates that can be loaded into Track A first.",
      scope: "track-matcher",
      status: "starter",
      searchText: "track a load ready",
      keywords: ["track", "a", "load", "ready"],
    }),
    savedSearch({
      id: "track-b-load-ready",
      label: "Track B Ready",
      description: "Find playable comparison candidates that can be loaded into Track B.",
      scope: "track-matcher",
      status: "starter",
      searchText: "track b load ready",
      keywords: ["track", "b", "load", "ready"],
    }),
    savedSearch({
      id: "deck-comparison-candidates",
      label: "Deck Comparison",
      description: "Find full-track material for direct Track A / Track B comparison.",
      scope: "track-matcher",
      status: "starter",
      searchText: "comparison reference keeper",
      keywords: ["comparison", "reference", "keeper"],
    }),
    savedSearch({
      id: "tempo-match-candidates",
      label: "Tempo Match",
      description: "Find tracks likely useful for BPM and tempo matching tests.",
      scope: "track-matcher",
      status: "starter",
      searchText: "tempo bpm groove beat",
      keywords: ["tempo", "bpm", "groove", "beat"],
    }),
    savedSearch({
      id: "key-match-candidates",
      label: "Key Match",
      description: "Find harmonic material for key matching and pitch comparison.",
      scope: "track-matcher",
      status: "starter",
      searchText: "key harmony chord melody",
      keywords: ["key", "harmony", "chord", "melody"],
    }),
    savedSearch({
      id: "melody-lane-candidates",
      label: "Melody Lane",
      description: "Find hook, lead, top-line, and melody lane candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "melody hook lead topline",
      keywords: ["melody", "hook", "lead", "topline"],
    }),
    savedSearch({
      id: "harmony-lane-candidates",
      label: "Harmony Lane",
      description: "Find harmony, chord, pad, stacked vocal, and harmonic map candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "harmony chord pad stack",
      keywords: ["harmony", "chord", "pad", "stack"],
    }),
    savedSearch({
      id: "instrument-lane-candidates",
      label: "Instrument Lane",
      description: "Find guitars, keys, synths, riffs, and other instrument-part candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "instrument guitar keys synth riff",
      keywords: ["instrument", "guitar", "keys", "synth", "riff"],
    }),
    savedSearch({
      id: "stem-lane-candidates",
      label: "Stem Lane",
      description: "Find general stem material when the exact lane role is not known yet.",
      scope: "track-matcher",
      status: "starter",
      searchText: "stem isolated part",
      keywords: ["stem", "isolated", "part"],
    }),
    savedSearch({
      id: "analysis-lane-candidates",
      label: "Analysis Lane",
      description: "Find tracks for future analysis-only loading, diagnostics, and scoring.",
      scope: "track-matcher",
      status: "starter",
      searchText: "analysis diagnostic score",
      keywords: ["analysis", "diagnostic", "score"],
    }),
    savedSearch({
      id: "full-song-references",
      label: "Full Song References",
      description: "Find full-song references for style, energy, and arrangement comparison.",
      scope: "track-matcher",
      status: "starter",
      searchText: "full song reference arrangement",
      keywords: ["full", "song", "reference", "arrangement"],
      includeStemTracks: false,
    }),
    savedSearch({
      id: "sounds-like-references",
      label: "Sounds-Like Refs",
      description: "Find sounds-like references and inspiration tracks for comparison.",
      scope: "track-matcher",
      status: "starter",
      searchText: "sounds like reference inspiration",
      keywords: ["sounds-like", "reference", "inspiration"],
    }),
    savedSearch({
      id: "keeper-references",
      label: "Keeper References",
      description: "Find references that are also marked or described as keepers.",
      scope: "track-matcher",
      status: "starter",
      searchText: "keeper reference",
      keywords: ["keeper", "reference"],
    }),
    savedSearch({
      id: "drum-groove-candidates",
      label: "Drum Grooves",
      description: "Find drum grooves, beats, loops, rhythm beds, and percussion ideas.",
      scope: "track-matcher",
      status: "starter",
      searchText: "drum groove beat loop rhythm percussion",
      keywords: ["drum", "groove", "beat", "loop", "rhythm", "percussion"],
    }),
    savedSearch({
      id: "bass-groove-candidates",
      label: "Bass Grooves",
      description: "Find bass grooves, basslines, low-end loops, and pocket ideas.",
      scope: "track-matcher",
      status: "starter",
      searchText: "bass groove bassline low end pocket",
      keywords: ["bass", "groove", "bassline", "low-end", "pocket"],
    }),
    savedSearch({
      id: "vocal-hook-candidates",
      label: "Vocal Hooks",
      description: "Find vocal hook, phrase, chant, sung idea, and pronunciation candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "vocal hook phrase chant sung pronunciation",
      keywords: ["vocal", "hook", "phrase", "chant", "sung", "pronunciation"],
      includeInstrumentals: false,
    }),
    savedSearch({
      id: "lead-line-candidates",
      label: "Lead Lines",
      description: "Find lead lines, riffs, hooks, motifs, and top-line pieces.",
      scope: "track-matcher",
      status: "starter",
      searchText: "lead line riff hook motif",
      keywords: ["lead", "line", "riff", "hook", "motif"],
    }),
    savedSearch({
      id: "chord-pad-candidates",
      label: "Chord Pads",
      description: "Find chord pads, harmonic beds, synth layers, and atmosphere parts.",
      scope: "track-matcher",
      status: "starter",
      searchText: "chord pad harmonic synth atmosphere",
      keywords: ["chord", "pad", "harmonic", "synth", "atmosphere"],
    }),
    savedSearch({
      id: "guitar-part-candidates",
      label: "Guitar Parts",
      description: "Find guitar riffs, rhythm guitars, lead guitars, and string ideas.",
      scope: "track-matcher",
      status: "starter",
      searchText: "guitar riff rhythm lead strings",
      keywords: ["guitar", "riff", "rhythm", "lead", "strings"],
    }),
    savedSearch({
      id: "keys-synth-candidates",
      label: "Keys + Synths",
      description: "Find keyboard, piano, synth, pad, and electronic instrument parts.",
      scope: "track-matcher",
      status: "starter",
      searchText: "keys keyboard piano synth pad",
      keywords: ["keys", "keyboard", "piano", "synth", "pad"],
    }),
    savedSearch({
      id: "suno-result-candidates",
      label: "Suno Results",
      description: "Find generated or Suno-related results for comparison and routing.",
      scope: "track-matcher",
      status: "starter",
      searchText: "suno generated result",
      keywords: ["suno", "generated", "result"],
    }),
    savedSearch({
      id: "original-idea-candidates",
      label: "Original Ideas",
      description: "Find original idea material, sketches, seeds, and rough song starts.",
      scope: "track-matcher",
      status: "starter",
      searchText: "original idea sketch seed rough",
      keywords: ["original", "idea", "sketch", "seed", "rough"],
    }),
    savedSearch({
      id: "upload-candidates",
      label: "Uploads",
      description: "Find uploaded tracks and user-added material.",
      scope: "track-matcher",
      status: "starter",
      searchText: "upload uploaded user added",
      keywords: ["upload", "uploaded", "user", "added"],
    }),
    savedSearch({
      id: "supabase-candidates",
      label: "Supabase Tracks",
      description: "Find Supabase-backed tracks when Library storage is available.",
      scope: "track-matcher",
      status: "starter",
      searchText: "supabase storage library",
      keywords: ["supabase", "storage", "library"],
    }),
    savedSearch({
      id: "seed-track-candidates",
      label: "Seed Tracks",
      description: "Find seed tracks and built-in example material.",
      scope: "track-matcher",
      status: "starter",
      searchText: "seed demo example built in",
      keywords: ["seed", "demo", "example", "built-in"],
    }),
    savedSearch({
      id: "project-track-candidates",
      label: "Project Tracks",
      description: "Find project-attached tracks and workspace material.",
      scope: "track-matcher",
      status: "starter",
      searchText: "project workspace track",
      keywords: ["project", "workspace", "track"],
    }),
    savedSearch({
      id: "rough-mix-candidates",
      label: "Rough Mixes",
      description: "Find rough mixes, draft mixes, and work-in-progress candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "rough mix draft wip",
      keywords: ["rough", "mix", "draft", "wip"],
    }),
    savedSearch({
      id: "final-mix-candidates",
      label: "Final Mixes",
      description: "Find final, mastered, bounced, or finished mix candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "final mastered bounce finished",
      keywords: ["final", "mastered", "bounce", "finished"],
    }),
    savedSearch({
      id: "energy-match-candidates",
      label: "Energy Match",
      description: "Find high-energy, low-energy, lift, drop, and dynamic contrast material.",
      scope: "track-matcher",
      status: "starter",
      searchText: "energy lift drop dynamic",
      keywords: ["energy", "lift", "drop", "dynamic"],
    }),
    savedSearch({
      id: "vibe-match-candidates",
      label: "Vibe Match",
      description: "Find vibe, mood, color, attitude, and feel-based candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "vibe mood feel attitude",
      keywords: ["vibe", "mood", "feel", "attitude"],
    }),
    savedSearch({
      id: "arrangement-match-candidates",
      label: "Arrangement Match",
      description: "Find intro, verse, chorus, bridge, breakdown, and arrangement references.",
      scope: "track-matcher",
      status: "starter",
      searchText: "intro verse chorus bridge breakdown arrangement",
      keywords: ["intro", "verse", "chorus", "bridge", "breakdown", "arrangement"],
    }),
    savedSearch({
      id: "production-reference-candidates",
      label: "Production Refs",
      description: "Find production, mix, texture, polish, and sonic reference tracks.",
      scope: "track-matcher",
      status: "starter",
      searchText: "production mix texture polish sonic",
      keywords: ["production", "mix", "texture", "polish", "sonic"],
    }),
    savedSearch({
      id: "keeper-stem-candidates",
      label: "Keeper Stems",
      description: "Find stems that are likely worth keeping for later lane work.",
      scope: "track-matcher",
      status: "starter",
      searchText: "keeper stem useful lane",
      keywords: ["keeper", "stem", "useful", "lane"],
    }),
    savedSearch({
      id: "problem-track-candidates",
      label: "Problem Tracks",
      description: "Find tracks marked for review, issues, mismatch, cleanup, or repair.",
      scope: "track-matcher",
      status: "starter",
      searchText: "review issue mismatch cleanup repair",
      keywords: ["review", "issue", "mismatch", "cleanup", "repair"],
    }),
    savedSearch({
      id: "favorite-candidates",
      label: "Favorites",
      description: "Find favorite, liked, best, strong, and high-value candidates.",
      scope: "track-matcher",
      status: "starter",
      searchText: "favorite liked best strong",
      keywords: ["favorite", "liked", "best", "strong"],
    }),
  ];

export const TRACK_MATCHER_FINDER_SAVED_SEARCH_GROUPS: TrackMatcherFinderSavedSearchGroup[] =
  [
    {
      id: "deck-loading",
      label: "Deck Loading",
      description: "Saved searches for Track A / Track B comparison loading.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "track-a-load-ready",
          "track-b-load-ready",
          "deck-comparison-candidates",
          "tempo-match-candidates",
          "key-match-candidates",
          "rock-funk-keepers",
        ].includes(search.id),
      ),
    },
    {
      id: "lane-candidates",
      label: "Lane Candidates",
      description: "Saved searches for Track Matcher lane routing.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "melody-lane-candidates",
          "harmony-lane-candidates",
          "drum-lane-candidates",
          "bass-lane-candidates",
          "vocal-lane-candidates",
          "instrument-lane-candidates",
          "stem-lane-candidates",
          "analysis-lane-candidates",
          "instrumental-stems",
          "keeper-stem-candidates",
        ].includes(search.id),
      ),
    },
    {
      id: "reference-workflows",
      label: "Reference Workflows",
      description: "Saved searches for references, sounds-like tracks, and production matching.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "reference-songs",
          "full-song-references",
          "sounds-like-references",
          "keeper-references",
          "production-reference-candidates",
          "arrangement-match-candidates",
        ].includes(search.id),
      ),
    },
    {
      id: "instrument-workflows",
      label: "Instrument Workflows",
      description: "Saved searches for drums, bass, vocals, hooks, guitars, keys, and pads.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "drum-groove-candidates",
          "bass-groove-candidates",
          "vocal-hook-candidates",
          "lead-line-candidates",
          "chord-pad-candidates",
          "guitar-part-candidates",
          "keys-synth-candidates",
        ].includes(search.id),
      ),
    },
    {
      id: "source-workflows",
      label: "Source Workflows",
      description: "Saved searches for uploads, Supabase, seed, project, and generated sources.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "upload-candidates",
          "supabase-candidates",
          "seed-track-candidates",
          "project-track-candidates",
          "suno-result-candidates",
          "original-idea-candidates",
        ].includes(search.id),
      ),
    },
    {
      id: "workflow-searches",
      label: "Workflow Searches",
      description: "Saved searches for hybrids, mixes, energy, vibe, favorites, and review.",
      searches: TRACK_MATCHER_FINDER_SAVED_SEARCHES.filter((search) =>
        [
          "hybrid-candidates",
          "rough-mix-candidates",
          "final-mix-candidates",
          "energy-match-candidates",
          "vibe-match-candidates",
          "problem-track-candidates",
          "favorite-candidates",
        ].includes(search.id),
      ),
    },
  ];
