import type { TrackMatcherFinderPreset } from "./trackMatcherFinderMetadataTypes";

export const TRACK_MATCHER_FINDER_PRESETS: TrackMatcherFinderPreset[] = [
  {
    id: "rock-keepers",
    label: "Rock Keepers",
    description: "Rock songs marked as keeper candidates.",
    requiredTokens: ["rock", "keeper"],
    excludedTokens: [],
  },
  {
    id: "funk-keepers",
    label: "Funk Keepers",
    description: "Funk keeper candidates.",
    requiredTokens: ["funk", "keeper"],
    excludedTokens: [],
  },
  {
    id: "jazz-keepers",
    label: "Jazz Keepers",
    description: "Jazz tracks that may be worth keeping for comparison or routing.",
    requiredTokens: ["jazz", "keeper"],
    excludedTokens: [],
  },
  {
    id: "blues-keepers",
    label: "Blues Keepers",
    description: "Blues tracks marked or described as strong keeper candidates.",
    requiredTokens: ["blues", "keeper"],
    excludedTokens: [],
  },
  {
    id: "country-keepers",
    label: "Country Keepers",
    description: "Country or country-rock keeper candidates.",
    requiredTokens: ["country", "keeper"],
    excludedTokens: [],
  },
  {
    id: "metal-keepers",
    label: "Metal Keepers",
    description: "Metal or heavy rock keeper candidates.",
    requiredTokens: ["metal", "keeper"],
    excludedTokens: [],
  },
  {
    id: "edm-keepers",
    label: "EDM Keepers",
    description: "Electronic dance tracks worth keeping for matching or routing.",
    requiredTokens: ["edm", "keeper"],
    excludedTokens: [],
  },
  {
    id: "ambient-tracks",
    label: "Ambient Tracks",
    description: "Ambient, atmospheric, and dreamy material.",
    requiredTokens: ["ambient"],
    excludedTokens: [],
  },
  {
    id: "orchestral-tracks",
    label: "Orchestral Tracks",
    description: "Orchestral, cinematic, or score-like material.",
    requiredTokens: ["orchestral"],
    excludedTokens: [],
  },
  {
    id: "hiphop-tracks",
    label: "Hip Hop Tracks",
    description: "Hip hop, rap, and beat-driven material.",
    requiredTokens: ["hiphop"],
    excludedTokens: [],
  },
  {
    id: "trap-tracks",
    label: "Trap Tracks",
    description: "Trap beats, trap grooves, and trap-leaning candidates.",
    requiredTokens: ["trap"],
    excludedTokens: [],
  },
  {
    id: "pop-tracks",
    label: "Pop Tracks",
    description: "Pop, pop-rock, and hook-forward material.",
    requiredTokens: ["pop"],
    excludedTokens: [],
  },
  {
    id: "soul-tracks",
    label: "Soul Tracks",
    description: "Soul, R&B, and soulful groove material.",
    requiredTokens: ["soul"],
    excludedTokens: [],
  },
  {
    id: "folk-tracks",
    label: "Folk Tracks",
    description: "Folk, acoustic, and singer-songwriter leaning material.",
    requiredTokens: ["folk"],
    excludedTokens: [],
  },
  {
    id: "instrumentals",
    label: "Instrumentals",
    description: "Instrumental-only tracks.",
    requiredTokens: ["instrumental"],
    excludedTokens: [],
  },
  {
    id: "vocal-stems",
    label: "Vocal Stems",
    description: "Vocal stem material.",
    requiredTokens: ["vocal", "stem"],
    excludedTokens: [],
  },
  {
    id: "drum-stems",
    label: "Drum Stems",
    description: "Drum-only stem material.",
    requiredTokens: ["drums", "stem"],
    excludedTokens: [],
  },
  {
    id: "bass-stems",
    label: "Bass Stems",
    description: "Bass stem material.",
    requiredTokens: ["bass", "stem"],
    excludedTokens: [],
  },
  {
    id: "melody-stems",
    label: "Melody Stems",
    description: "Melody, hook, lead, and top-line stem material.",
    requiredTokens: ["melody", "stem"],
    excludedTokens: [],
  },
  {
    id: "harmony-stems",
    label: "Harmony Stems",
    description: "Harmony, chord, pad, and stacked vocal stem material.",
    requiredTokens: ["harmony", "stem"],
    excludedTokens: [],
  },
  {
    id: "instrument-stems",
    label: "Instrument Stems",
    description: "Guitar, keys, synth, riff, and instrument-part stems.",
    requiredTokens: ["instrument", "stem"],
    excludedTokens: [],
  },
  {
    id: "acapella-stems",
    label: "Acapella Stems",
    description: "A cappella, isolated vocal, and voice-only material.",
    requiredTokens: ["acapella", "vocal"],
    excludedTokens: [],
  },
  {
    id: "drum-grooves",
    label: "Drum Grooves",
    description: "Drum grooves, beats, rhythm beds, and percussion loops.",
    requiredTokens: ["drums", "groove"],
    excludedTokens: [],
  },
  {
    id: "bass-grooves",
    label: "Bass Grooves",
    description: "Bass grooves, basslines, pockets, and low-end ideas.",
    requiredTokens: ["bass", "groove"],
    excludedTokens: [],
  },
  {
    id: "vocal-hooks",
    label: "Vocal Hooks",
    description: "Vocal hooks, phrases, chants, sung ideas, and top-line vocal parts.",
    requiredTokens: ["vocal", "hook"],
    excludedTokens: [],
  },
  {
    id: "lead-lines",
    label: "Lead Lines",
    description: "Lead lines, riffs, motifs, melodic hooks, and top-line ideas.",
    requiredTokens: ["lead"],
    excludedTokens: [],
  },
  {
    id: "chord-pads",
    label: "Chord Pads",
    description: "Chord pads, harmonic beds, synth layers, and atmosphere parts.",
    requiredTokens: ["chord", "pad"],
    excludedTokens: [],
  },
  {
    id: "guitar-parts",
    label: "Guitar Parts",
    description: "Guitar riffs, rhythm guitars, lead guitars, and string ideas.",
    requiredTokens: ["guitar"],
    excludedTokens: [],
  },
  {
    id: "keys-synths",
    label: "Keys + Synths",
    description: "Keyboard, piano, synth, pad, and electronic instrument parts.",
    requiredTokens: ["synth"],
    excludedTokens: [],
  },
  {
    id: "dark-tracks",
    label: "Dark Tracks",
    description: "Dark, moody, shadowy, and tense material.",
    requiredTokens: ["dark"],
    excludedTokens: [],
  },
  {
    id: "bright-tracks",
    label: "Bright Tracks",
    description: "Bright, upbeat, uplift, and high-energy material.",
    requiredTokens: ["bright"],
    excludedTokens: [],
  },
  {
    id: "sad-tracks",
    label: "Sad Tracks",
    description: "Sad, melancholy, blue, and emotional material.",
    requiredTokens: ["sad"],
    excludedTokens: [],
  },
  {
    id: "happy-tracks",
    label: "Happy Tracks",
    description: "Happy, joyful, playful, and fun material.",
    requiredTokens: ["happy"],
    excludedTokens: [],
  },
  {
    id: "dreamy-tracks",
    label: "Dreamy Tracks",
    description: "Dreamy, floaty, ethereal, and atmospheric tracks.",
    requiredTokens: ["dreamy"],
    excludedTokens: [],
  },
  {
    id: "epic-tracks",
    label: "Epic Tracks",
    description: "Epic, big, massive, cinematic, and high-impact material.",
    requiredTokens: ["epic"],
    excludedTokens: [],
  },
  {
    id: "gritty-tracks",
    label: "Gritty Tracks",
    description: "Gritty, dirty, raw, aggressive, and rough-edged material.",
    requiredTokens: ["gritty"],
    excludedTokens: [],
  },
  {
    id: "smooth-tracks",
    label: "Smooth Tracks",
    description: "Smooth, polished, silky, and laid-back material.",
    requiredTokens: ["smooth"],
    excludedTokens: [],
  },
  {
    id: "romantic-tracks",
    label: "Romantic Tracks",
    description: "Romantic, tender, love-song, and intimate material.",
    requiredTokens: ["romantic"],
    excludedTokens: [],
  },
  {
    id: "haunting-tracks",
    label: "Haunting Tracks",
    description: "Haunting, eerie, ghostly, and suspenseful material.",
    requiredTokens: ["haunting"],
    excludedTokens: [],
  },
  {
    id: "reference-songs",
    label: "Reference Songs",
    description: "Reference and sounds-like material.",
    requiredTokens: ["reference"],
    excludedTokens: [],
  },
  {
    id: "hybrid-candidates",
    label: "Hybrid Candidates",
    description: "Potential hybrid lane material.",
    requiredTokens: ["hybrid"],
    excludedTokens: [],
  },
  {
    id: "master-files",
    label: "Master Files",
    description: "Mastered and final exports.",
    requiredTokens: ["master"],
    excludedTokens: [],
  },
  {
    id: "final-mixes",
    label: "Final Mixes",
    description: "Final, finished, mastered, or bounced mix candidates.",
    requiredTokens: ["final"],
    excludedTokens: [],
  },
  {
    id: "rough-mixes",
    label: "Rough Mixes",
    description: "Rough mixes, drafts, work-in-progress tracks, and sketch mixes.",
    requiredTokens: ["rough"],
    excludedTokens: [],
  },
  {
    id: "keeper-candidates",
    label: "Keeper Candidates",
    description: "Tracks marked as strong, favorite, useful, or keeper material.",
    requiredTokens: ["keeper"],
    excludedTokens: [],
  },
  {
    id: "approved-tracks",
    label: "Approved Tracks",
    description: "Tracks marked as approved or accepted.",
    requiredTokens: ["approved"],
    excludedTokens: [],
  },
  {
    id: "analysis-ready",
    label: "Analysis Ready",
    description: "Tracks suitable for future analysis lanes.",
    requiredTokens: ["analysis"],
    excludedTokens: [],
  },
  {
    id: "comparison-ready",
    label: "Comparison Ready",
    description: "Tracks ready for Track A / Track B matching and comparison.",
    requiredTokens: ["compare"],
    excludedTokens: [],
  },
  {
    id: "tempo-match",
    label: "Tempo Match",
    description: "Tracks useful for BPM, speed, groove, and tempo matching.",
    requiredTokens: ["tempo"],
    excludedTokens: [],
  },
  {
    id: "key-match",
    label: "Key Match",
    description: "Tracks useful for pitch, key, chord, and harmony matching.",
    requiredTokens: ["key"],
    excludedTokens: [],
  },
  {
    id: "route-to-melody",
    label: "Route Melody",
    description: "Material likely useful for the future Melody lane.",
    requiredTokens: ["melody"],
    excludedTokens: [],
  },
  {
    id: "route-to-drums",
    label: "Route Drums",
    description: "Material likely useful for the future Drum lane.",
    requiredTokens: ["drums"],
    excludedTokens: [],
  },
  {
    id: "route-to-bass",
    label: "Route Bass",
    description: "Material likely useful for the future Bass lane.",
    requiredTokens: ["bass"],
    excludedTokens: [],
  },
  {
    id: "route-to-vocal",
    label: "Route Vocal",
    description: "Material likely useful for the future Vocal lane.",
    requiredTokens: ["vocal"],
    excludedTokens: [],
  },
  {
    id: "route-to-harmony",
    label: "Route Harmony",
    description: "Material likely useful for the future Harmony lane.",
    requiredTokens: ["harmony"],
    excludedTokens: [],
  },
  {
    id: "library-tracks",
    label: "Library Tracks",
    description: "Library-sourced tracks and catalog material.",
    requiredTokens: ["library"],
    excludedTokens: [],
  },
  {
    id: "project-tracks",
    label: "Project Tracks",
    description: "Project or workspace-attached tracks.",
    requiredTokens: ["project"],
    excludedTokens: [],
  },
  {
    id: "uploaded-tracks",
    label: "Uploaded Tracks",
    description: "Uploaded tracks and user-added material.",
    requiredTokens: ["upload"],
    excludedTokens: [],
  },
  {
    id: "supabase-tracks",
    label: "Supabase Tracks",
    description: "Supabase-backed Library storage tracks.",
    requiredTokens: ["supabase"],
    excludedTokens: [],
  },
  {
    id: "seed-tracks",
    label: "Seed Tracks",
    description: "Seed, demo, example, or starter tracks.",
    requiredTokens: ["seed"],
    excludedTokens: [],
  },
  {
    id: "suno-results",
    label: "Suno Results",
    description: "Generated or Suno-related results for matching and routing.",
    requiredTokens: ["suno"],
    excludedTokens: [],
  },
  {
    id: "original-ideas",
    label: "Original Ideas",
    description: "Original idea material, song seeds, sketches, and rough starts.",
    requiredTokens: ["original"],
    excludedTokens: [],
  },
  {
    id: "problem-tracks",
    label: "Problem Tracks",
    description: "Tracks marked for review, issues, cleanup, mismatch, or repair.",
    requiredTokens: ["problem"],
    excludedTokens: [],
  },
  {
    id: "production-refs",
    label: "Production Refs",
    description: "Production, mix, texture, polish, and sonic reference tracks.",
    requiredTokens: ["production"],
    excludedTokens: [],
  },
];
