import type { TrackMatcherFinderRoute } from "./trackMatcherFinderRoutingTypes";

export const TRACK_MATCHER_FINDER_ROUTES: TrackMatcherFinderRoute[] = [
  {
    destination: "track-a",
    label: "Load To Track A",
    shortLabel: "Track A",
    detail: "Load this result into the primary comparison deck.",
    intent: "deck-load",
    status: "ready",
    priority: "primary",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: true,
    acceptsHybrid: true,
    acceptsFullSong: true,
  },
  {
    destination: "track-b",
    label: "Load To Track B",
    shortLabel: "Track B",
    detail: "Load this result into the secondary comparison deck.",
    intent: "deck-load",
    status: "ready",
    priority: "primary",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: true,
    acceptsHybrid: true,
    acceptsFullSong: true,
  },
  {
    destination: "melody",
    label: "Load To Melody Lane",
    shortLabel: "Melody",
    detail: "Use for hooks, lead lines, top-line ideas, or melodic stems.",
    intent: "lane-load",
    status: "future",
    priority: "recommended",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: false,
  },
  {
    destination: "drums",
    label: "Load To Drum Lane",
    shortLabel: "Drums",
    detail: "Use for drum stems, beats, rhythm references, and groove matching.",
    intent: "lane-load",
    status: "future",
    priority: "recommended",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: false,
    acceptsFullSong: false,
  },
  {
    destination: "bass",
    label: "Load To Bass Lane",
    shortLabel: "Bass",
    detail: "Use for bass stems, low-end references, and bassline matching.",
    intent: "lane-load",
    status: "future",
    priority: "recommended",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: false,
    acceptsFullSong: false,
  },
  {
    destination: "vocal",
    label: "Load To Vocal Lane",
    shortLabel: "Vocal",
    detail: "Use for vocal stems, sung ideas, and pronunciation checking later.",
    intent: "lane-load",
    status: "future",
    priority: "recommended",
    acceptsStem: true,
    acceptsInstrumental: false,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: false,
  },
  {
    destination: "harmony",
    label: "Load To Harmony Lane",
    shortLabel: "Harmony",
    detail: "Use for harmony, chords, stacked vocals, pads, and harmonic maps.",
    intent: "lane-load",
    status: "future",
    priority: "optional",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: false,
  },
  {
    destination: "instrument",
    label: "Load To Instrument Lane",
    shortLabel: "Instrument",
    detail: "Use for guitars, keys, synths, riffs, and other instrument parts.",
    intent: "lane-load",
    status: "future",
    priority: "optional",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: false,
  },
  {
    destination: "stem",
    label: "Load To Stem Lane",
    shortLabel: "Stem",
    detail: "Generic stem destination when the exact role is not known yet.",
    intent: "lane-load",
    status: "future",
    priority: "optional",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: false,
  },
  {
    destination: "reference-song",
    label: "Load To Reference Lane",
    shortLabel: "Reference",
    detail: "Use for full songs or inspiration tracks that guide the comparison.",
    intent: "reference-load",
    status: "future",
    priority: "recommended",
    acceptsStem: false,
    acceptsInstrumental: true,
    acceptsReference: true,
    acceptsHybrid: false,
    acceptsFullSong: true,
  },
  {
    destination: "hybrid",
    label: "Load To Hybrid Lane",
    shortLabel: "Hybrid",
    detail: "Use for blended ideas, candidates, experiments, and mixed sources.",
    intent: "hybrid-load",
    status: "future",
    priority: "recommended",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: false,
    acceptsHybrid: true,
    acceptsFullSong: true,
  },
  {
    destination: "analysis",
    label: "Load To Analysis Lane",
    shortLabel: "Analysis",
    detail: "Use for analysis-only loading, future scoring, and diagnostics.",
    intent: "analysis-load",
    status: "future",
    priority: "optional",
    acceptsStem: true,
    acceptsInstrumental: true,
    acceptsReference: true,
    acceptsHybrid: true,
    acceptsFullSong: true,
  },
];

export const TRACK_MATCHER_FINDER_ROUTE_GROUPS = [
  {
    id: "decks",
    label: "Decks",
    detail: "Immediate Track A / Track B comparison loading.",
    destinations: ["track-a", "track-b"],
  },
  {
    id: "core-lanes",
    label: "Core Lanes",
    detail: "Main musical lane destinations.",
    destinations: ["melody", "drums", "bass", "vocal", "harmony"],
  },
  {
    id: "support-lanes",
    label: "Support Lanes",
    detail: "Stem, instrument, reference, hybrid, and analysis destinations.",
    destinations: ["instrument", "stem", "reference-song", "hybrid", "analysis"],
  },
] as const;