import { aiAnalysisPlaceholders, aiAnalysisRoutes, markerLaneRoutes, stemRoutingPlaceholders, timelineGroups, timelineLanes, waveformCards, waveformPrepItems } from "../multiTrackData";
import { InfoCard, MiniMarkerList, RouteCard, SectionHeader, StatusPill, cardClass, labelClass, panelClass, statusLabel } from "./MultiTrackShared";
export function TimelineMarkerWorkspace(){return <section className={panelClass}><SectionHeader title="Timeline / Marker Workspace" body="Future place for Track A markers, Track B markers, shared comparison markers, hooks, transitions, problems, and blend opportunities." pill="Markers"/><div className="mt-4 grid gap-3 lg:grid-cols-3">{timelineGroups.map((group)=><article key={group.label} className={cardClass}><p className={labelClass}>{group.label}</p><p className="mt-2 text-sm font-black text-white/80">{group.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{group.detail}</p><MiniMarkerList title="Starter markers" markers={group.markers}/></article>)}</div></section>}
export function TimelineLaneSystemWorkspace(){return <section className={panelClass}><SectionHeader title="Timeline Lane System" body="Separates structure markers, comparison markers, sync problems, and manual review notes." pill="Lane System"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{timelineLanes.map((lane)=><article key={lane.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{lane.label}</p><StatusPill label={statusLabel(lane.status)}/></div><p className="mt-2 text-sm font-black text-white/80">{lane.purpose}</p><p className="mt-2 text-xs leading-5 text-white/55">{lane.detail}</p><MiniMarkerList title="Lane markers" markers={lane.markers}/></article>)}</div></section>}
export function MarkerLaneRoutingWorkspace(){return <section className={panelClass}><SectionHeader title="Marker Lane Routing" body="Routes markers into metadata, save records, and future AI analysis without runtime state." pill="Marker Routes"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{markerLaneRoutes.map((route)=><RouteCard key={route.label} label={route.label} route={`${route.fromLane} → ${route.toDestination}`} detail={route.detail} status={route.status}/>)}</div></section>}
export function FutureWaveformWorkspace(){return <section className={panelClass}><SectionHeader title="Future Waveform Workspace" body="Reserved area for waveform inspection, stem overlays, AI moment detection, zoom regions, marker overlays, and sync preview." pill="Waveform"/><div className="mt-4 grid gap-3 md:grid-cols-4">{waveformCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function WaveformPrepWorkspace(){return <section className={panelClass}><SectionHeader title="Waveform Prep Workspace" body="Future waveform inputs as planned data contracts, not active runtime code." pill="Waveform Prep"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{waveformPrepItems.map((item)=><article key={item.label} className={cardClass}><p className={labelClass}>{item.label}</p><p className="mt-2 text-sm font-black text-white/80">{item.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{item.detail}</p><p className="mt-3 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-[0.65rem] font-black uppercase tracking-[0.12em] text-white/45">{item.futureInput}</p></article>)}</div></section>}
export function StemRoutingWorkspace(){return <section className={panelClass}><SectionHeader title="Future Stem Routing" body="Visible stem routing shell for later extraction, playback, comparison, and AI suggestions." pill="Stems"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{stemRoutingPlaceholders.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function AiAnalysisPlaceholderWorkspace(){return <section className={panelClass}><SectionHeader title="Future AI Analysis Placeholders" body="Reserved UI slots for future match summaries, problem finding, prompt building, and stem suggestions." pill="AI Prep"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{aiAnalysisPlaceholders.map((item)=><article key={item.label} className={cardClass}><p className={labelClass}>{item.label}</p><p className="mt-2 text-sm font-black text-white/80">{item.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{item.detail}</p><p className="mt-3 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-[0.65rem] font-black uppercase tracking-[0.12em] text-white/45">{item.nextSignal}</p></article>)}</div></section>}
export function AiRoutingWorkspace(){return <section className={panelClass}><SectionHeader title="AI Routing Workspace" body="Shows how saved analysis, marker lanes, decision notes, and stem lanes can later feed AI helpers." pill="AI Routes"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{aiAnalysisRoutes.map((route)=><article key={route.label} className={cardClass}><p className={labelClass}>{route.label}</p><p className="mt-2 text-sm font-black text-white/80">{route.route}</p><p className="mt-2 text-xs leading-5 text-white/55">{route.detail}</p></article>)}</div></section>}
