import type { InfoCardProps, MultiTrackMetricBand, MultiTrackStatus, StatusPillProps } from "../multiTrackTypes";
import { trackChecklist } from "../multiTrackData";
export const panelClass = "rounded-3xl border border-white/10 bg-white/[0.04] p-5 text-white shadow-2xl";
export const cardClass = "rounded-2xl border border-white/10 bg-black/40 p-4 text-white";
export const softTextClass = "text-sm leading-6 text-white/70";
export const labelClass = "text-[0.65rem] font-black uppercase tracking-[0.18em] text-white/45";
export const valueClass = "mt-1 text-sm font-black text-white/80";
export function statusLabel(status: MultiTrackStatus) { if (status === "ready") return "Ready"; if (status === "foundation") return "Foundation"; return "Planned"; }
export function metricBandLabel(band: MultiTrackMetricBand) { if (band === "high") return "High"; if (band === "medium") return "Medium"; if (band === "low") return "Low"; return "Unknown"; }
export function StatusPill({ label }: StatusPillProps) { return <span className="rounded-full border border-white/10 bg-white/[0.07] px-3 py-1 text-xs font-black uppercase tracking-[0.16em] text-white/65">{label}</span>; }
export function InfoCard({ label, value, detail }: InfoCardProps) { return <article className={cardClass}><p className={labelClass}>{label}</p><p className={valueClass}>{value}</p><p className="mt-2 text-xs leading-5 text-white/55">{detail}</p></article>; }
export function ChecklistCard({ title }: { title: string }) { return <article className={cardClass}><p className={labelClass}>{title}</p><div className="mt-3 grid gap-2">{trackChecklist.map((item) => <div key={`${title}-${item.label}`} className="flex items-center justify-between gap-3 rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2"><span className="text-xs font-black text-white/70">{item.label}</span><span className="text-[0.65rem] font-black uppercase tracking-[0.16em] text-white/45">{item.status === "ready" ? "Ready" : "Planned"}</span></div>)}</div></article>; }
export function ListPanel({ title, items }: { title: string; items: string[] }) { return <article className={cardClass}><p className={labelClass}>{title}</p><div className="mt-3 grid gap-2">{items.map((item) => <div key={item} className="rounded-xl border border-white/10 bg-white/[0.04] px-3 py-2 text-xs font-black leading-5 text-white/65">{item}</div>)}</div></article>; }
export function SectionHeader({ title, body, pill }: { title: string; body: string; pill?: string }) { return <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black text-white">{title}</h2><p className={`mt-2 ${softTextClass}`}>{body}</p></div>{pill ? <StatusPill label={pill} /> : null}</div>; }
export function MetricCard({ label, value, detail, band }: { label: string; value: string; detail: string; band: MultiTrackMetricBand }) { return <article className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{label}</p><StatusPill label={metricBandLabel(band)} /></div><p className={valueClass}>{value}</p><p className="mt-2 text-xs leading-5 text-white/55">{detail}</p></article>; }
export function RouteCard({ label, route, detail, status }: { label: string; route: string; detail: string; status: MultiTrackStatus }) { return <article className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{label}</p><StatusPill label={statusLabel(status)} /></div><p className="mt-2 text-sm font-black text-white/80">{route}</p><p className="mt-2 text-xs leading-5 text-white/55">{detail}</p></article>; }
export function MiniMarkerList({ title, markers }: { title: string; markers: string[] }) { return <div className="rounded-2xl border border-white/10 bg-white/[0.04] p-3"><p className={labelClass}>{title}</p><div className="mt-3 flex flex-wrap gap-2">{markers.map((marker) => <span key={`${title}-${marker}`} className="rounded-full border border-white/10 bg-black/40 px-3 py-1 text-[0.65rem] font-black uppercase tracking-[0.12em] text-white/55">{marker}</span>)}</div></div>; }
export function EmptyFutureSlot({ title, body }: { title: string; body: string }) { return <article className="rounded-2xl border border-dashed border-white/15 bg-black/20 p-4 text-white"><p className={labelClass}>{title}</p><p className="mt-2 text-xs font-black leading-5 text-white/55">{body}</p></article>; }
