import { metadataGraphNodes, relationshipRouteGroups, trackMetadataGroups, trackRelationshipGroups } from "../multiTrackData";
import type { TrackWorkspaceKind } from "../multiTrackTypes";
import { InfoCard, ListPanel, SectionHeader, StatusPill, cardClass, labelClass, panelClass } from "./MultiTrackShared";
function TrackMetadataWorkspace({ track }: { track: TrackWorkspaceKind }){return <section className={panelClass}><SectionHeader title={`${track} Metadata Workspace`} body={`Phase 4 separates ${track} metadata into its own workspace.`} pill="Metadata"/><div className="mt-4 grid gap-3 lg:grid-cols-3">{trackMetadataGroups[track].map((group)=><ListPanel key={group.title} title={group.title} items={group.items}/>)}</div></section>}
function TrackRelationshipWorkspace({ track }: { track: TrackWorkspaceKind }){return <section className={panelClass}><SectionHeader title={`${track} Relationships`} body={`Phase 4 gives ${track} its own relationship area.`} pill="Relationships"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{trackRelationshipGroups[track].map((card)=><article key={card.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{card.label}</p><StatusPill label="Route"/></div><p className="mt-2 text-sm font-black text-white/80">{card.value}</p><p className="mt-2 text-xs font-black uppercase tracking-[0.14em] text-white/45">{card.route}</p><p className="mt-2 text-xs leading-5 text-white/55">{card.detail}</p></article>)}</div></section>}
export function TrackMetadataReadinessWorkspace(){return <section className={panelClass}><SectionHeader title="Metadata Routing Readiness" body="Keeps metadata foundation visible for Library, Finder, project, and relationship graph pages." pill="Graph Prep"/><div className="mt-4 grid gap-3 md:grid-cols-3"><InfoCard label="Library Metadata" value="Prepared" detail="Track identity and musical facts have their own data panels."/><InfoCard label="Relationship Metadata" value="Prepared" detail="Track-to-track links can become graph records later."/><InfoCard label="Moment Metadata" value="Prepared" detail="Hook, transition, problem, and AI notes have a future home."/></div></section>}
export function RelationshipRouteExpansionWorkspace(){return <section className={panelClass}><SectionHeader title="Relationship Route Expansion" body="Groups future metadata routes created by saved analysis." pill="Route Groups"/><div className="mt-4 grid gap-3 lg:grid-cols-2">{relationshipRouteGroups.map((group)=><article key={group.title} className={cardClass}><p className={labelClass}>{group.title}</p><div className="mt-3 grid gap-3">{group.routes.map((route)=><div key={route.label} className="rounded-xl border border-white/10 bg-white/[0.04] p-3"><p className="text-xs font-black text-white/80">{route.label}</p><p className="mt-1 text-[0.65rem] font-black uppercase tracking-[0.12em] text-white/45">{route.route}</p><p className="mt-2 text-xs leading-5 text-white/55">{route.detail}</p></div>)}</div></article>)}</div></section>}
export function MetadataGraphPrepWorkspace(){return <section className={panelClass}><SectionHeader title="Metadata Graph Prep" body="Future graph nodes for Track A, Track B, saved analysis, and prompt routes." pill="Graph Nodes"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{metadataGraphNodes.map((node)=><article key={node.label} className={cardClass}><p className={labelClass}>{node.label}</p><p className="mt-2 text-sm font-black text-white/80">{node.nodeType}</p><p className="mt-2 text-xs leading-5 text-white/55">{node.detail}</p></article>)}</div></section>}
export function TrackAMetadataWorkspace(){return <TrackMetadataWorkspace track="Track A"/>}
export function TrackBMetadataWorkspace(){return <TrackMetadataWorkspace track="Track B"/>}
export function TrackARelationshipWorkspace(){return <TrackRelationshipWorkspace track="Track A"/>}
export function TrackBRelationshipWorkspace(){return <TrackRelationshipWorkspace track="Track B"/>}
