import { analysisHistoryItems, controllerAdapterSteps, comparisonNoteGroups, futureWiringCards, saveAnalysisCards, saveFieldChecklist, saveRecordShape, saveWorkspaceGroups, workflowSteps } from "../multiTrackData";
import { InfoCard, ListPanel, RouteCard, SectionHeader, StatusPill, cardClass, labelClass, panelClass, softTextClass, statusLabel } from "./MultiTrackShared";
export function SaveAnalysisPlaceholder(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Save Analysis Placeholder</h2><p className={`mt-2 ${softTextClass}`}>Later this area can save selected tracks, match decision, metadata, relationships, prompts, notes, confidence, markers, and stem routing.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{saveAnalysisCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function SaveFieldChecklistWorkspace(){return <section className={panelClass}><SectionHeader title="Save Field Checklist" body="Makes the future save record explicit before database wiring." pill="Save Shape"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{saveFieldChecklist.map((field)=><article key={field.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{field.label}</p><StatusPill label={field.required?"Required":"Optional"}/></div><p className="mt-2 text-xs leading-5 text-white/55">{field.detail}</p></article>)}</div></section>}
export function SaveRecordShapeWorkspace(){return <section className={panelClass}><SectionHeader title="Save Record Shape" body="Future saved analysis shape without runtime code or database writes." pill="Record Shape"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{saveRecordShape.map((field)=><article key={field.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{field.label}</p><StatusPill label={statusLabel(field.status)}/></div><p className="mt-2 text-sm font-black text-white/80">{field.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{field.detail}</p></article>)}</div></section>}
export function WorkflowWorkspace(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Workflow Steps</h2><p className={`mt-2 ${softTextClass}`}>Clear working order before deeper audio tools are connected.</p><div className="mt-4 grid gap-3 md:grid-cols-2">{workflowSteps.map((step,index)=><div key={step} className="rounded-2xl border border-white/10 bg-black/40 p-4"><p className={labelClass}>Step {index+1}</p><p className="mt-1 text-sm font-black text-white/80">{step}</p></div>)}</div></section>}
export function FutureWiringWorkspace(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Future Wiring Notes</h2><p className={`mt-2 ${softTextClass}`}>Later this page can receive Track A/B state, Finder actions, Library metadata, project routing, saved records, waveform data, stem routes, and AI summaries.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{futureWiringCards.map((card)=><div key={card} className={cardClass}>{card}</div>)}</div></section>}
export function ComparisonNotesWorkspace(){return <section className={panelClass}><SectionHeader title="Comparison Notes Workspace" body="Human listening notes explaining why two tracks fit, clash, reference each other, or become a hybrid." pill="Phase 4"/><div className="mt-4 grid gap-3 lg:grid-cols-3">{comparisonNoteGroups.map((group)=><ListPanel key={group.title} title={group.title} items={group.items}/>)}</div></section>}
export function AnalysisHistoryWorkspace(){return <section className={panelClass}><SectionHeader title="Analysis History Workspace" body="Future history for saved changes, decision changes, marker edits, confidence changes, and exports." pill="History"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{analysisHistoryItems.map((item)=><article key={item.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{item.label}</p><StatusPill label={statusLabel(item.status)}/></div><p className="mt-2 text-sm font-black text-white/80">{item.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{item.detail}</p></article>)}</div></section>}
export function SaveAnalysisWorkspace(){return <section className={panelClass}><SectionHeader title="Save Analysis Workspace" body="Clear shape before database wiring: what gets saved, where it can go, and why it exists." pill="Save Ready"/><div className="mt-4 grid gap-3 lg:grid-cols-2">{saveWorkspaceGroups.map((group)=><ListPanel key={group.title} title={group.title} items={group.items}/>)}</div></section>}
export function ControllerAdapterPrepWorkspace(){return <section className={panelClass}><SectionHeader title="Controller Adapter Prep" body="Future adapter contracts without touching the existing controller or runtime files." pill="Adapter Prep"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{controllerAdapterSteps.map((step)=><RouteCard key={step.label} label={step.label} route={step.contract} detail={step.detail} status={step.status}/>)}</div></section>}
