import { comparisonCards, comparisonScoreMetrics, comparisonScoreSignals, confidenceSystems, decisionCards, promptReferenceCards, relationshipCards, relationshipRoutingSteps, syncPrepItems } from "../multiTrackData";
import { InfoCard, MetricCard, RouteCard, SectionHeader, StatusPill, cardClass, labelClass, panelClass, softTextClass, statusLabel } from "./MultiTrackShared";
export function ComparisonWorkspace(){return <section className={panelClass}><SectionHeader title="Comparison Workspace" body="Compare Track A and Track B by tempo, key, structure, energy, mood, arrangement, instrumentation, and future match quality." pill="Comparison"/><div className="mt-4 grid gap-3 md:grid-cols-3">{comparisonCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function ComparisonScoringWorkspace(){return <section className={panelClass}><SectionHeader title="Comparison Scoring Shell" body="Visible scoring structure before real BPM, key, waveform, and AI analysis are wired." pill="Scoring"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{comparisonScoreMetrics.map((m)=><MetricCard key={m.label} {...m}/>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-5">{comparisonScoreSignals.map((s)=><article key={s.label} className={cardClass}><p className={labelClass}>{s.label}</p><p className="mt-2 text-sm font-black text-white/80">{s.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{s.detail}</p></article>)}</div></section>}
export function ConfidenceSystemWorkspace(){return <section className={panelClass}><SectionHeader title="Confidence System Workspace" body="Separates detected facts, manual confirmation, and future AI summaries." pill="Confidence"/><div className="mt-4 grid gap-3 lg:grid-cols-2">{confidenceSystems.map((system)=><article key={system.title} className={cardClass}><p className={labelClass}>{system.title}</p><p className="mt-2 text-xs leading-5 text-white/55">{system.summary}</p><div className="mt-4 grid gap-3 md:grid-cols-2">{system.metrics.map((m)=><MetricCard key={m.label} {...m}/>)}</div></article>)}</div></section>}
export function SyncPrepWorkspace(){return <section className={panelClass}><SectionHeader title="Sync Prep Workspace" body="Prepares tempo, key, marker, and playback alignment without touching runtime." pill="Sync Prep"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{syncPrepItems.map((item)=><article key={item.label} className={cardClass}><div className="flex items-start justify-between gap-3"><p className={labelClass}>{item.label}</p><StatusPill label={statusLabel(item.status)}/></div><p className="mt-2 text-sm font-black text-white/80">{item.value}</p><p className="mt-2 text-xs leading-5 text-white/55">{item.detail}</p></article>)}</div></section>}
export function RelationshipWorkspace(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Relationship Workspace</h2><p className={`mt-2 ${softTextClass}`}>Decide whether tracks are similar, reference material, hybrid candidates, or prompt-related ideas.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{relationshipCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function RelationshipRoutingWorkspace(){return <section className={panelClass}><SectionHeader title="Relationship Routing System" body="Routing shell for Finder, Library, Projects, metadata, and AI." pill="Routing"/><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-4">{relationshipRoutingSteps.map((step)=><RouteCard key={step.label} label={step.label} route={step.route} detail={step.detail} status={step.status}/>)}</div></section>}
export function PromptReferenceWorkspace(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Prompt Reference Workspace</h2><p className={`mt-2 ${softTextClass}`}>Keeps prompt thinking connected to the track pair.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{promptReferenceCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
export function DecisionCenterWorkspace(){return <section className={panelClass}><h2 className="text-xl font-black text-white">Decision Center</h2><p className={`mt-2 ${softTextClass}`}>Future save point for deciding what Track A and Track B mean together.</p><div className="mt-4 grid gap-3 md:grid-cols-4">{decisionCards.map((card)=><InfoCard key={card.label} {...card}/>)}</div></section>}
